Main Project: npi::win Namespace Reference
npi::win Namespace Reference
Windows related utilities.
Functions
void abortMsgBox (const QString &title, const QString &msg, const HWND h=nullptr) noexcept
Show a fatal error box and terminate the process.
void errorMsgBox (const QString &title, const QString &msg, const HWND h=nullptr) noexcept
Show an error message box (OK + error icon).
void infoMsgBox (const QString &title, const QString &msg, const HWND h=nullptr) noexcept
Show an informational message box (OK + information icon).
void msgBox (const QString &title, const QString &msg, const HWND h, const UINT flags) noexcept
Show a Windows message box with custom flags.
void warnMsgBox (const QString &title, const QString &msg, const HWND h=nullptr) noexcept
Show a warning message box (OK + warning icon).
Detailed Description
Windows related utilities.
This namespace contains Windows-specific variables and functions.
Function Documentation
abortMsgBox()
void npi::win::abortMsgBox (const QString & title, const QString & msg, const HWND h = nullptr) inline noexcept
Show a fatal error box and terminate the process.
Displays an error dialog (OK + error icon). Adds MB_TOPMOST for better visibility in critical situations, then calls std::abort(). Intended for unrecoverable failures where continuing execution is unsafe.
Parameters
title Caption text.
msg Body text.
h Optional owner HWND. Defaults to nullptr.
Postcondition
The function does not return; the process is aborted.
Warning
If you pass an HWND that belongs to a QWidget, ensure you did not obtain it on a worker thread. Do not call QWidget APIs off the GUI thread.
Use only for fatal conditions. Consider logging to persistent storage before calling this function if possible.
Definition at line 142 of file WinMsgBox.hpp.
  {
    msgBox(title, msg, h, MB_OK | MB_ICONERROR | MB_TOPMOST);
    std::abort();
  }
References msgBox().
Referenced by npi::app::appProgramDataDir(), npi::app::appPublicDocumentsDir(), npi::app::orgProgramDataDir(), and npi::app::orgPublicDocumentsDir().
errorMsgBox()
void npi::win::errorMsgBox (const QString & title, const QString & msg, const HWND h = nullptr) inline noexcept
Show an error message box (OK + error icon).
Convenience wrapper over msgBox(...) with MB_OK | MB_ICONERROR.
Parameters
title Caption text.
msg Body text.
h Optional owner HWND. Defaults to nullptr.
Warning
If you pass an HWND that belongs to a QWidget, ensure you did not obtain it on a worker thread. Do not call QWidget APIs off the GUI thread.
Definition at line 121 of file WinMsgBox.hpp.
  {
    msgBox(title, msg, h, MB_OK | MB_ICONERROR);
  }
References msgBox().
infoMsgBox()
void npi::win::infoMsgBox (const QString & title, const QString & msg, const HWND h = nullptr) inline noexcept
Show an informational message box (OK + information icon).
Convenience wrapper over msgBox(...) with MB_OK | MB_ICONINFORMATION.
Parameters
title Caption text.
msg Body text.
h Optional owner HWND. Defaults to nullptr.
Warning
If you pass an HWND that belongs to a QWidget, ensure you did not obtain it on a worker thread. Do not call QWidget APIs off the GUI thread.
Definition at line 93 of file WinMsgBox.hpp.
  {
    msgBox(title, msg, h, MB_OK | MB_ICONINFORMATION);
  }
References msgBox().
msgBox()
void npi::win::msgBox (const QString & title, const QString & msg, const HWND h, const UINT flags) inline noexcept
Show a Windows message box with custom flags.
This is the base helper around MessageBoxW. It adds sane defaults: if no modality flag is supplied, it uses MB_APPLMODAL when an owner is present and MB_TASKMODAL when there is no owner. When there is no owner, MB_SETFOREGROUND is added to reduce z-order issues.
Parameters
title Caption text (UTF-16 via QString conversion).
msg Body text (UTF-16 via QString conversion).
h Owner window handle. May be nullptr. If obtained from QWidget, it must have been retrieved on the GUI thread.
flags Standard MessageBox flags (buttons, icon, modality, etc.).
Note
Callable from any thread. Does not interact with QWidget.
Warning
If you pass an HWND that belongs to a QWidget, ensure you did not obtain it on a worker thread. Do not call QWidget APIs off the GUI thread.
See also
MessageBoxW
Definition at line 73 of file WinMsgBox.hpp.
  {
    const std::wstring wTitle = title.toStdWString();                                  // UTF-16 caption for MessageBoxW.
    const std::wstring wMsg = msg.toStdWString();                                      // UTF-16 body for MessageBoxW.
    constexpr UINT kModalityMask = MB_SYSTEMMODAL | MB_TASKMODAL | MB_APPLMODAL;       // Bit mask of all modality flags.
    UINT effFlags = flags;                                                             // Effective flags passed to MessageBoxW.
    if((effFlags & kModalityMask) == 0) effFlags |= (h ? MB_APPLMODAL : MB_TASKMODAL); // Auto-modality when unspecified.
    if(!h) effFlags |= MB_SETFOREGROUND;                                               // Reduce Z-order issues without owner.
    ::MessageBoxW(h, wMsg.c_str(), wTitle.c_str(), effFlags);                          // Show the message box, ignore return value.
  }
Referenced by abortMsgBox(), errorMsgBox(), infoMsgBox(), and warnMsgBox().
warnMsgBox()
void npi::win::warnMsgBox (const QString & title, const QString & msg, const HWND h = nullptr) inline noexcept
Show a warning message box (OK + warning icon).
Convenience wrapper over msgBox(...) with MB_OK | MB_ICONWARNING.
Parameters
title Caption text.
msg Body text.
h Optional owner HWND. Defaults to nullptr.
Warning
If you pass an HWND that belongs to a QWidget, ensure you did not obtain it on a worker thread. Do not call QWidget APIs off the GUI thread.
Definition at line 107 of file WinMsgBox.hpp.
  {
    msgBox(title, msg, h, MB_OK | MB_ICONWARNING);
  }
References msgBox().