Main Project: npi::RefPtrFromThis< T > Class Template Reference
npi::RefPtrFromThis< T > Class Template Reference
Enables objects that inherits from this class to produce a RefPtr object referencing themselves if the object is wrapped in a RefPtrHost.
#include <RefPtrClasses.hpp>
Public Member Functions
RefPtrFromThis () noexcept=default
Default constructor.
RefPtrFromThis (const RefPtrFromThis &other) noexcept=default
Default copy constructor.
RefPtrFromThis (RefPtrFromThis &&other) noexcept=default
Default move constructor.
~RefPtrFromThis () noexcept=default
Default destructor.
bool isRefPtrFromThisAvailable_ () const noexcept
Check whether a RefPtr can be obtained from this object i.e. if the object is wrapped in a RefPtrHost.
RefPtrFromThis & operator= (const RefPtrFromThis &other) noexcept=default
Default copy assignment operator.
RefPtrFromThis & operator= (RefPtrFromThis &&other) noexcept=default
Default move assignment operator.
RefPtr< T > refPtrFromThis_ () const noexcept
Create a RefPtr to this object if still alive and is wrapped in a RefPtrHost.
void swap_ (RefPtrFromThis &other) noexcept
Member swap function.
Private Attributes
std::weak_ptr< typename RefPtrHost< T >::Obs > weakUni_
Weak pointer to the uni_ in RefPtrHost.
Friends
template<typename U>
class RefPtrHost
Friend declarations of RefPtrHost class.
void swap (RefPtrFromThis &a, RefPtrFromThis &b) noexcept
Friend swap to exchange two RefPtrFromThis instances.
Detailed Description
template<typename T>
class npi::RefPtrFromThis< T >
Enables objects that inherits from this class to produce a RefPtr object referencing themselves if the object is wrapped in a RefPtrHost.
Behaves like a std::enable_shared_from_this but for RefPtrHost.
Stores a weak reference to the universal observer in the RefPtrHost.
Provides a way to obtain a RefPtr object to itself using the universal observer if the RefPtrHost object is still alive.
Template Parameters
T The type of the object being wrapped in RefPtrHost and supporting enable-from-this semantics.
Note
This class only holds a weak reference to the universal observer in the RefPtrHost. This means that as long as any RefPtrHost object is alive, the RefPtrFromThis object will be able to create a RefPtr object to itself and that RefPtr object will be valid as long as the RefPtrHost object is alive.
Example of using LinkFromThis:
struct MyClass : RefPtrFromThis<MyClass> {
  void hello() {}
};
auto host = RefPtrHost<MyClass>(new MyClass());
auto refPtr = host.universal_()->refPtrFromThis_();
if(refPtr) refPtr->hello();
Definition at line 1123 of file RefPtrClasses.hpp.
Constructor & Destructor Documentation
RefPtrFromThis() [1/3]
template<typename T> npi::RefPtrFromThis< T >::RefPtrFromThis () default noexcept
Default constructor.
Referenced by RefPtrFromThis(), RefPtrFromThis(), ~RefPtrFromThis(), operator=(), operator=(), swap, and swap_().
RefPtrFromThis() [2/3]
template<typename T> npi::RefPtrFromThis< T >::RefPtrFromThis (const RefPtrFromThis< T > & other) default noexcept
Default copy constructor.
References RefPtrFromThis().
RefPtrFromThis() [3/3]
template<typename T> npi::RefPtrFromThis< T >::RefPtrFromThis (RefPtrFromThis< T > && other) default noexcept
Default move constructor.
References RefPtrFromThis().
~RefPtrFromThis()
template<typename T> npi::RefPtrFromThis< T >::~RefPtrFromThis () default noexcept
Default destructor.
References RefPtrFromThis().
Member Function Documentation
isRefPtrFromThisAvailable_()
template<typename T> bool npi::RefPtrFromThis< T >::isRefPtrFromThisAvailable_ () const inline noexcept
Check whether a RefPtr can be obtained from this object i.e. if the object is wrapped in a RefPtrHost.
Returns
true if the universal observer has not expired and the object is wrapped in a RefPtrHost.
Definition at line 1155 of file RefPtrClasses.hpp.
{ return weakUni_.expired() == false; }
References weakUni_.
operator=() [1/2]
template<typename T> RefPtrFromThis & npi::RefPtrFromThis< T >::operator= (const RefPtrFromThis< T > & other) default noexcept
Default copy assignment operator.
References RefPtrFromThis().
operator=() [2/2]
template<typename T> RefPtrFromThis & npi::RefPtrFromThis< T >::operator= (RefPtrFromThis< T > && other) default noexcept
Default move assignment operator.
References RefPtrFromThis().
refPtrFromThis_()
template<typename T> RefPtr< T > npi::RefPtrFromThis< T >::refPtrFromThis_ () const inline noexcept
Create a RefPtr to this object if still alive and is wrapped in a RefPtrHost.
Returns
A valid RefPtr if the universal observer exists, otherwise an empty RefPtr.
Attempts to lock the weak universal observer and returns a RefPtr pointing to the stored ptr.
Definition at line 1146 of file RefPtrClasses.hpp.
    {
      if(auto uni = weakUni_.lock())
        return RefPtr<T>{uni->ptr_};
      return RefPtr<T>{nullptr};
    }
References refPtrFromThis_(), and weakUni_.
Referenced by refPtrFromThis_().
swap_()
template<typename T> void npi::RefPtrFromThis< T >::swap_ (RefPtrFromThis< T > & other) inline noexcept
Member swap function.
Parameters
other The RefPtrFromThis object to swap with.
Definition at line 1168 of file RefPtrClasses.hpp.
    {
      using std::swap;
      swap(*this, other);
    }
References RefPtrFromThis(), and swap.
Friends And Related Symbol Documentation
RefPtrHost
template<typename T> template<typename U> friend class RefPtrHost friend
Friend declarations of RefPtrHost class.
Definition at line 1176 of file RefPtrClasses.hpp.
References RefPtrHost.
Referenced by RefPtrHost.
swap
template<typename T> void swap (RefPtrFromThis< T > & a, RefPtrFromThis< T > & b) friend
Friend swap to exchange two RefPtrFromThis instances.
Parameters
a First RefPtrFromThis object.
b Second RefPtrFromThis object.
Definition at line 1160 of file RefPtrClasses.hpp.
    {
      using std::swap;
      swap(a.weakUni_, b.weakUni_);
    }
References RefPtrFromThis(), and swap.
Referenced by swap, and swap_().
Member Data Documentation
weakUni_
template<typename T> std::weak_ptr<typename RefPtrHost<T>::Obs> npi::RefPtrFromThis< T >::weakUni_ mutable private
Weak pointer to the uni_ in RefPtrHost.
Definition at line 1179 of file RefPtrClasses.hpp.
Referenced by isRefPtrFromThisAvailable_(), and refPtrFromThis_().
The documentation for this class was generated from the following file:
RefPtrClasses.hpp