Main Project: npi::log Namespace Reference
npi::log Namespace Reference
Classes
struct DirResult
Functions
const QStringList & availableFieldNames ()
QStringList categories ()
void clearFilterRules (const bool temp=false)
void closeConsole ()
QString dir ()
QString futureDir ()
QStringList getFilterBaseRules ()
QStringList getFilterRules ()
bool getFilterRulesTempState ()
QStringList getLogFields ()
bool getLogFieldsTempState ()
qint64 getMaxFolderSizeMb ()
QStringList getMsgFields ()
bool getMsgFieldsTempState ()
bool isConsoleColored ()
bool isConsoleOpen ()
bool isConsolePermanent ()
bool isDisplayMuted ()
bool isWarnImpLog ()
bool openConsole ()
DirResult restoreDefaultDir ()
qint64 restoreDefaultMaxFolderSizeMb ()
void setColoredConsole (const bool state)
QStringList setDefaultLogFields (const bool temp=false)
QStringList setDefaultMsgFields (const bool temp=false)
DirResult setDir (const QString &path)
QStringList setFilterRules (const QStringList &rules={}, const bool temp=false)
QStringList setLogFields (const QStringList &fieldList={}, const bool temp=false)
qint64 setMaxFolderSizeMb (const qint64 size)
QStringList setMsgFields (const QStringList &fieldList={}, const bool temp=false)
void setMuteDisplay (const bool state)
void setWarnAsImpLog (bool state, bool temp=false)
Class Documentation
npi::log::DirResult
struct npi::log::DirResult
Definition at line 13 of file Log.h.
Class Members
bool error_ {false}
QString message_
QString newPath_
Function Documentation
availableFieldNames()
const QStringList & npi::log::availableFieldNames ()
Definition at line 3009 of file Log.cpp.
{ return ::LogCore::Inst_()->getAvailableFieldNames_(); }
categories()
QStringList npi::log::categories ()
Definition at line 3023 of file Log.cpp.
{ return ::LogCore::Inst_()->getLogCategories_(); }
clearFilterRules()
void npi::log::clearFilterRules (const bool temp = false)
Definition at line 3021 of file Log.cpp.
{ ::LogCore::Inst_()->setFilterRules_(temp); }
References anonymous_namespace{Log.cpp}::LogCore::Inst_(), and anonymous_namespace{Log.cpp}::LogCore::setFilterRules_().
closeConsole()
void npi::log::closeConsole ()
Definition at line 3031 of file Log.cpp.
{ ::LogCore::Inst_()->closeConsole_(); }
References anonymous_namespace{Log.cpp}::LogCore::closeConsole_(), and anonymous_namespace{Log.cpp}::LogCore::Inst_().
dir()
QString npi::log::dir ()
Definition at line 3002 of file Log.cpp.
{ return ::LogCore::Inst_()->getDir_(); }
futureDir()
QString npi::log::futureDir ()
Definition at line 3005 of file Log.cpp.
{ return ::LogCore::Inst_()->getFutureDir_(); }
getFilterBaseRules()
QStringList npi::log::getFilterBaseRules ()
Definition at line 3018 of file Log.cpp.
{ return ::LogCore::GetFilterBaseRules_(); }
getFilterRules()
QStringList npi::log::getFilterRules ()
Definition at line 3019 of file Log.cpp.
{ return ::LogCore::Inst_()->getFilterRules_(); }
getFilterRulesTempState()
bool npi::log::getFilterRulesTempState ()
Definition at line 3020 of file Log.cpp.
{ return ::LogCore::Inst_()->getFilterRulesTempState_(); }
getLogFields()
QStringList npi::log::getLogFields ()
Definition at line 3010 of file Log.cpp.
{ return ::LogCore::Inst_()->getFields_(true); }
getLogFieldsTempState()
bool npi::log::getLogFieldsTempState ()
Definition at line 3012 of file Log.cpp.
{ return ::LogCore::Inst_()->getFieldTempState_(true); }
getMaxFolderSizeMb()
qint64 npi::log::getMaxFolderSizeMb ()
Definition at line 3006 of file Log.cpp.
{ return ::LogCore::Inst_()->getMaxFolderSizeMb_(); }
getMsgFields()
QStringList npi::log::getMsgFields ()
Definition at line 3011 of file Log.cpp.
{ return ::LogCore::Inst_()->getFields_(false); }
getMsgFieldsTempState()
bool npi::log::getMsgFieldsTempState ()
Definition at line 3013 of file Log.cpp.
{ return ::LogCore::Inst_()->getFieldTempState_(false); }
isConsoleColored()
bool npi::log::isConsoleColored ()
Definition at line 3026 of file Log.cpp.
{ return ::LogCore::Inst_()->isConsoleColored_(); }
isConsoleOpen()
bool npi::log::isConsoleOpen ()
Definition at line 3029 of file Log.cpp.
{ return ::LogCore::Inst_()->isConsoleOpen_(); }
isConsolePermanent()
bool npi::log::isConsolePermanent ()
Definition at line 3028 of file Log.cpp.
{ return ::LogCore::Inst_()->isPermanentConsole_(); }
isDisplayMuted()
bool npi::log::isDisplayMuted ()
Definition at line 3024 of file Log.cpp.
{ return ::LogCore::Inst_()->isDisplayMuted_(); }
isWarnImpLog()
bool npi::log::isWarnImpLog ()
Definition at line 3032 of file Log.cpp.
{ return ::LogCore::Inst_()->isWarnImp_(); }
openConsole()
bool npi::log::openConsole ()
Definition at line 3030 of file Log.cpp.
{ return ::LogCore::Inst_()->openConsole_(); }
restoreDefaultDir()
npi::log::DirResult npi::log::restoreDefaultDir ()
Definition at line 3003 of file Log.cpp.
{ return ::LogCore::Inst_()->setDir_(); }
restoreDefaultMaxFolderSizeMb()
qint64 npi::log::restoreDefaultMaxFolderSizeMb ()
Definition at line 3007 of file Log.cpp.
{ return ::LogCore::Inst_()->setMaxFolderSizeMb_(); }
setColoredConsole()
void npi::log::setColoredConsole (const bool state)
Definition at line 3027 of file Log.cpp.
{ ::LogCore::Inst_()->setColoredConsole_(state); }
References anonymous_namespace{Log.cpp}::LogCore::Inst_(), and anonymous_namespace{Log.cpp}::LogCore::setColoredConsole_().
setDefaultLogFields()
QStringList npi::log::setDefaultLogFields (const bool temp = false)
Definition at line 3014 of file Log.cpp.
{ return ::LogCore::Inst_()->setFields_(true, temp); }
setDefaultMsgFields()
QStringList npi::log::setDefaultMsgFields (const bool temp = false)
Definition at line 3015 of file Log.cpp.
{ return ::LogCore::Inst_()->setFields_(false, temp); }
setDir()
npi::log::DirResult npi::log::setDir (const QString & path)
Definition at line 3004 of file Log.cpp.
{ return ::LogCore::Inst_()->setDir_(path); }
setFilterRules()
QStringList npi::log::setFilterRules (const QStringList & rules = {}, const bool temp = false)
Definition at line 3022 of file Log.cpp.
{ return ::LogCore::Inst_()->setFilterRules_(temp, rules); }
setLogFields()
QStringList npi::log::setLogFields (const QStringList & fieldList = {}, const bool temp = false)
Definition at line 3016 of file Log.cpp.
{ return ::LogCore::Inst_()->setFields_(true, temp, fieldList); }
setMaxFolderSizeMb()
qint64 npi::log::setMaxFolderSizeMb (const qint64 size)
Definition at line 3008 of file Log.cpp.
{ return ::LogCore::Inst_()->setMaxFolderSizeMb_(size); }
setMsgFields()
QStringList npi::log::setMsgFields (const QStringList & fieldList = {}, const bool temp = false)
Definition at line 3017 of file Log.cpp.
{ return ::LogCore::Inst_()->setFields_(false, temp, fieldList); }
setMuteDisplay()
void npi::log::setMuteDisplay (const bool state)
Definition at line 3025 of file Log.cpp.
{ ::LogCore::Inst_()->setMuteDisplay_(state); }
References anonymous_namespace{Log.cpp}::LogCore::Inst_(), and anonymous_namespace{Log.cpp}::LogCore::setMuteDisplay_().
setWarnAsImpLog()
void npi::log::setWarnAsImpLog (bool state, bool temp = false)
Definition at line 3033 of file Log.cpp.
{ ::LogCore::Inst_()->setWarnIsImp_(state, temp); }
References anonymous_namespace{Log.cpp}::LogCore::Inst_(), and anonymous_namespace{Log.cpp}::LogCore::setWarnIsImp_().