Main Project: anonymous_namespace{MetaPaths.cpp} Namespace Reference
anonymous_namespace{MetaPaths.cpp} Namespace Reference
Anonymous namespace for internal usage.
Functions
QString basePath (const KNOWNFOLDERID &folderId, const char *envVar, const QString &envSuffix, const QString &pathNameForErrors) noexcept
Resolve base path using Known Folder ID or environment variable fallback.
QString createSubDir (const QString &base, const QString &dirName) noexcept
Create subdirectory under base path.
Detailed Description
Anonymous namespace for internal usage.
This namespace contains helper functions used for meta path resolution and creation. These functions are used internally within this translation unit by
npi::app::orgProgramDataDir()
npi::app::orgPublicDocumentsDir()
npi::app::appProgramDataDir()
npi::app::appPublicDocumentsDir()
Note
This namespace is anonymous to limit the scope of the function it contains to this translation unit only. Since these functions terminate the process on failure, they should not be called from outside this translation unit.
Function Documentation
basePath()
QString anonymous_namespace{MetaPaths.cpp}::basePath (const KNOWNFOLDERID & folderId, const char * envVar, const QString & envSuffix, const QString & pathNameForErrors) noexcept
Resolve base path using Known Folder ID or environment variable fallback.
This functions attempts to resolve the base path for the given folder ID by first querying the Windows API and falling back to an environment variable if necessary.
Parameters
folderId The Known Folder ID to query via SHGetKnownFolderPath.
envVar The environment variable to check if the API call fails.
envSuffix The suffix to append to the environment variable path.
pathNameForErrors The name of the path for error messages.
Warning
On unrecoverable failure (cannot locate or validate the directory), a native dialog is shown and the process is terminated (no return).
Definition at line 59 of file MetaPaths.cpp.
  {
    // String to hold the resolved base path.
    QString base;
    // Windows API attempt.
    PWSTR p = nullptr;
    const HRESULT hr = SHGetKnownFolderPath(folderId, KF_FLAG_DEFAULT, nullptr, &p);
    if(SUCCEEDED(hr) && p) {
      base = QString::fromWCharArray(p);
      CoTaskMemFree(p);
    }
    // Environment variable fallback.
    if(base.isEmpty()) {
      if(const QString envPath = qEnvironmentVariable(envVar); !envPath.isEmpty()) {
        base = envSuffix.isEmpty() ? envPath : QDir(envPath).filePath(envSuffix);
      }
    }
    // Abort on failure to locate.
    if(base.isEmpty()) {
      npi::app::startupFatalMessage(
        QString("%1 Not Found").arg(pathNameForErrors),
        QString("Could not locate the system's %1 directory. This folder is "
          "required for application settings.")
       .arg(pathNameForErrors));
    }
    // Abort if the path is missing or not a directory.
    if(const QFileInfo info(base); !info.exists() || !info.isDir()) {
      npi::app::startupFatalMessage(
        QString("%1 Invalid").arg(pathNameForErrors),
        QString("The system's %1 path '%2' is missing or is not a "
          "directory. Please ensure this folder exists.")
       .arg(pathNameForErrors, QDir::fromNativeSeparators(base)));
    }
    return base;
  }
References npi::app::startupFatalMessage().
Referenced by npi::app::orgProgramDataDir(), and npi::app::orgPublicDocumentsDir().
createSubDir()
QString anonymous_namespace{MetaPaths.cpp}::createSubDir (const QString & base, const QString & dirName) noexcept
Create subdirectory under base path.
This function attempts to create a subdirectory under the specified base path. On failure, a fatal error message is displayed and the process is terminated.
Parameters
base The base directory under which to create the subdirectory.
dirName The name of the subdirectory to create.
Warning
On unrecoverable failure to create the directory, a native dialog is shown and the process is terminated (no return).
Definition at line 108 of file MetaPaths.cpp.
  {
    QDir root{base};
    const QString target = root.filePath(dirName);
    if(!root.mkpath(dirName)) {
      npi::app::startupFatalMessage(
        "Cannot Create Directory",
        QString("The required settings directory could not be created:\n%1\n\n"
          "This may be due to a permissions issue or because a file "
          "with the same name already exists.")
       .arg(QDir::fromNativeSeparators(target)));
    }
    return QDir::cleanPath(target);
  }
References npi::app::startupFatalMessage().
Referenced by npi::app::appProgramDataDir(), npi::app::appPublicDocumentsDir(), npi::app::orgProgramDataDir(), and npi::app::orgPublicDocumentsDir().