Main Project: anonymous_namespace{Log.cpp}::ALogger Class Reference
anonymous_namespace{Log.cpp}::ALogger Class Reference
Public Member Functions
ALogger (const QString &logDir)
~ALogger () override
Private Member Functions
QString fileNamePrefix_ ()
Private Attributes
const QString dir_
QFile file_
const QString mainThreadId_
QTextStream stream_
Detailed Description
Definition at line 248 of file Log.cpp.
Constructor & Destructor Documentation
ALogger()
anonymous_namespace{Log.cpp}::ALogger::ALogger (const QString & logDir) inline
Definition at line 252 of file Log.cpp.
                                   : dir_{logDir}
    {
      qDebug() << "4: ALogger CTOR: " << QThread::currentThreadId();
      QObject::connect(qApp, &QApplication::aboutToQuit, this, [this] {
        qDebug() << "4: ALogger qApp: " << QThread::currentThreadId();
        this->moveToThread(qApp->thread());
      }, Qt::BlockingQueuedConnection);
      QObject::connect(qApp, &QObject::destroyed, this, [this] { delete this; });
      file_.setFileName(QString(fileNamePrefix_()).append(".run.log"));
      file_.open(QIODevice::WriteOnly | QIODevice::Unbuffered);
      stream_.setDevice(&file_);
      stream_.setEncoding(QStringConverter::Utf8);
    }
References dir_, file_, fileNamePrefix_(), and stream_.
Referenced by anonymous_namespace{Log.cpp}::aScheduleInit().
~ALogger()
anonymous_namespace{Log.cpp}::ALogger::~ALogger () inline override
Definition at line 266 of file Log.cpp.
    {
      qDebug() << "4: ALogger DTOR: " << QThread::currentThreadId();
      if(file_.isOpen()) {
        stream_.flush();
        stream_.setDevice(nullptr);
        file_.flush();
        file_.close();
      }
      file_.rename(QString(fileNamePrefix_()).append(".log"));
      qDebug() << "5: ALogger Destroyed";
      aLogger = nullptr;
    }
References anonymous_namespace{Log.cpp}::aLogger, file_, fileNamePrefix_(), and stream_.
Member Function Documentation
fileNamePrefix_()
QString anonymous_namespace{Log.cpp}::ALogger::fileNamePrefix_ () inline private
Definition at line 286 of file Log.cpp.
    {
      static const QString namePrefix = [dir = dir_]() -> QString {
        QString sPid = QString::number(QCoreApplication::applicationPid());
        if(sPid.size() < 10) sPid = QString(10 - sPid.size(), QLatin1Char('0')) + sPid;
        return QDir(dir).filePath(
          QString(QDateTime::currentDateTime().toString("yyyyMMdd_HHmmsszzz"))
          .append("_p").append(sPid));
      }();
      //static const QString str = QDir(dir_).filePath(
      //  QString(QDateTime::currentDateTime().toString("yyyyMMdd_HHmmsszzz"))
      // .append("_p")
      // .append(QString::number(QCoreApplication::applicationPid())));
      //return str;
      return namePrefix;
    }
References dir_.
Referenced by ALogger(), and ~ALogger().
Member Data Documentation
dir_
const QString anonymous_namespace{Log.cpp}::ALogger::dir_ private
Definition at line 281 of file Log.cpp.
Referenced by ALogger(), and fileNamePrefix_().
file_
QFile anonymous_namespace{Log.cpp}::ALogger::file_ private
Definition at line 283 of file Log.cpp.
Referenced by ALogger(), and ~ALogger().
mainThreadId_
const QString anonymous_namespace{Log.cpp}::ALogger::mainThreadId_ private
Definition at line 282 of file Log.cpp.
stream_
QTextStream anonymous_namespace{Log.cpp}::ALogger::stream_ private
Definition at line 284 of file Log.cpp.
Referenced by ALogger(), and ~ALogger().
The documentation for this class was generated from the following file:
Log.cpp