Main Project: anonymous_namespace{Log.cpp}::safe Namespace Reference
anonymous_namespace{Log.cpp}::safe Namespace Reference
Functions
void append2Digits (char *out, size_t &pos, const unsigned num) noexcept
void append3Digits (char *out, size_t &pos, const unsigned num) noexcept
void append4Digits (char *out, size_t &pos, const unsigned num) noexcept
void appendChr (char *out, size_t &pos, const char chr) noexcept
void appendChr (char *out, size_t &pos, const wchar_t chr) noexcept
void appendDec (char *out, size_t &pos, const int num) noexcept
void appendFileName (char *out, size_t &pos, const char *file) noexcept
void appendFuncName (char *out, size_t &pos, const char *func) noexcept
void appendHex (char *out, size_t &pos, const uint32_t val) noexcept
void appendLvl (char *out, size_t &pos, const QtMsgType typ) noexcept
void appendMsg (char *out, size_t &pos, const QString &msg) noexcept
void appendTxt (char *out, size_t &pos, const char *txt) noexcept
void appendTxt (char *out, size_t &pos, const wchar_t *txt) noexcept
unsigned decDigits (const unsigned num) noexcept
void hardFailFast () noexcept
void impLogWrite (const char *data, size_t len, bool crash)
void installCrashHandlers () noexcept
void invalidParamHandler (const wchar_t *expression, const wchar_t *function, const wchar_t *file, unsigned int line, uintptr_t) noexcept
bool isIdentifierChar (unsigned char ch) noexcept
bool isSpaceChar (unsigned char ch) noexcept
void msgHandler (QtMsgType typ, const QMessageLogContext &ctx, const QString &msg, bool late=false) noexcept
void pureCallHandler () noexcept
void reraiseDefault (int signum) noexcept
void signalHandler (int signum) noexcept
void startImpLogProcess (const std::wstring &primaryFullPath, const std::wstring &backupFullPath)
void terminateHandler () noexcept
std::wstring win32ErrorText (DWORD err)
std::wstring win32LastError ()
LONG WINAPI windowsExceptionFilter (EXCEPTION_POINTERS *ep)
Variables
volatile LONG crashing = 0
char cTxtBuf [txtCap] {}
size_t cTxtPos = 0
volatile LONG fatalLog = 0
HANDLE hImpLogPipe = INVALID_HANDLE_VALUE
HANDLE hImpLogProc = nullptr
constexpr size_t txtCap = 2048
Function Documentation
append2Digits()
void anonymous_namespace{Log.cpp}::safe::append2Digits (char * out, size_t & pos, const unsigned num) noexcept
Definition at line 481 of file Log.cpp.
    {
      if(!out || pos >= txtCap - 5) return;
      out[pos++] = static_cast<char>('0' + ((num / 10U) % 10U));
      out[pos++] = static_cast<char>('0' + (num % 10U));
      out[pos] = '\0';
    }
References append2Digits(), and txtCap.
Referenced by append2Digits(), and msgHandler().
append3Digits()
void anonymous_namespace{Log.cpp}::safe::append3Digits (char * out, size_t & pos, const unsigned num) noexcept
Definition at line 490 of file Log.cpp.
    {
      if(!out || pos >= txtCap - 6) return;
      out[pos++] = static_cast<char>('0' + ((num / 100U) % 10U));
      out[pos++] = static_cast<char>('0' + ((num / 10U) % 10U));
      out[pos++] = static_cast<char>('0' + (num % 10U));
      out[pos] = '\0';
    }
References append3Digits(), and txtCap.
Referenced by append3Digits(), and msgHandler().
append4Digits()
void anonymous_namespace{Log.cpp}::safe::append4Digits (char * out, size_t & pos, const unsigned num) noexcept
Definition at line 500 of file Log.cpp.
    {
      if(!out || pos >= txtCap - 7) return;
      out[pos++] = static_cast<char>('0' + ((num / 1000U) % 10U));
      out[pos++] = static_cast<char>('0' + ((num / 100U) % 10U));
      out[pos++] = static_cast<char>('0' + ((num / 10U) % 10U));
      out[pos++] = static_cast<char>('0' + (num % 10U));
      out[pos] = '\0';
    }
References append4Digits(), and txtCap.
Referenced by append4Digits(), and msgHandler().
appendChr() [1/2]
void anonymous_namespace{Log.cpp}::safe::appendChr (char * out, size_t & pos, const char chr) noexcept
Definition at line 429 of file Log.cpp.
    {
      if(!out || pos >= txtCap - 3) return;
      const unsigned char uc = static_cast<unsigned char>(chr);
      if(isSpaceChar(uc)) {
        if(pos > 0 && out[pos - 1] != ' ')
          out[pos++] = ' ';
      }
      else if(uc < 0x20u || uc > 0x7Eu) {
        out[pos++] = '?';
      }
      else {
        out[pos++] = static_cast<char>(uc);
      }
    }
References appendChr(), isSpaceChar(), and txtCap.
Referenced by appendChr(), appendChr(), appendFileName(), appendFuncName(), appendMsg(), appendTxt(), appendTxt(), invalidParamHandler(), and msgHandler().
appendChr() [2/2]
void anonymous_namespace{Log.cpp}::safe::appendChr (char * out, size_t & pos, const wchar_t chr) noexcept
Definition at line 445 of file Log.cpp.
    {
      if(chr <= 0x7F)
        appendChr(out, pos, static_cast<char>(chr));
      else
        appendChr(out, pos, '?');
    }
References appendChr().
appendDec()
void anonymous_namespace{Log.cpp}::safe::appendDec (char * out, size_t & pos, const int num) noexcept
Definition at line 539 of file Log.cpp.
    {
      if(!out || pos >= txtCap - 3) return;
      if(num == 0) {
        out[pos++] = '0';
        out[pos] = '\0';
        return;
      }
      // Safe absolute value for INT_MIN via modulo arithmetic.
      const bool neg = (num < 0);
      unsigned uNum = neg ? (0U - static_cast<unsigned>(num)) : static_cast<unsigned>(num);
      const unsigned digits = decDigits(uNum);
      const size_t needed = static_cast<size_t>(digits) + (neg ? 1u : 0u);
      if(pos >= txtCap - 3 - needed) return;
      if(neg) out[pos++] = '-';
      if(uNum >= 1000000000U) out[pos++] = static_cast<char>('0' + ((uNum / 1000000000U) % 10U));
      if(uNum >= 100000000U) out[pos++] = static_cast<char>('0' + ((uNum / 100000000U) % 10U));
      if(uNum >= 10000000U) out[pos++] = static_cast<char>('0' + ((uNum / 10000000U) % 10U));
      if(uNum >= 1000000U) out[pos++] = static_cast<char>('0' + ((uNum / 1000000U) % 10U));
      if(uNum >= 100000U) out[pos++] = static_cast<char>('0' + ((uNum / 100000U) % 10U));
      if(uNum >= 10000U) out[pos++] = static_cast<char>('0' + ((uNum / 10000U) % 10U));
      if(uNum >= 1000U) out[pos++] = static_cast<char>('0' + ((uNum / 1000U) % 10U));
      if(uNum >= 100U) out[pos++] = static_cast<char>('0' + ((uNum / 100U) % 10U));
      if(uNum >= 10U) out[pos++] = static_cast<char>('0' + ((uNum / 10U) % 10U));
      out[pos++] = static_cast<char>('0' + (uNum % 10U));
      out[pos] = '\0';
    }
References appendDec(), decDigits(), and txtCap.
Referenced by appendDec(), invalidParamHandler(), msgHandler(), and signalHandler().
appendFileName()
void anonymous_namespace{Log.cpp}::safe::appendFileName (char * out, size_t & pos, const char * file) noexcept
Definition at line 611 of file Log.cpp.
    {
      if(!out || !file || !*file || pos >= txtCap - 3) return;
      size_t cap = 0;
      const char* lastSep = nullptr;
      for(const char* p = file; cap < txtCap && *p != '\0'; ++p) {
        if(*p == '\\' || *p == '/') lastSep = p;
        ++cap;
      }
      const char* start = lastSep ? (lastSep + 1) : file;
      const size_t pos0 = pos;
      for(size_t n = 0; pos < txtCap - 3 && n < 128 && start[n] != '\0'; ++n)
        appendChr(out, pos, start[n]);
      while(pos > pos0 && out[pos - 1] == ' ')
        --pos;
      out[pos] = '\0';
    }
References appendChr(), appendFileName(), and txtCap.
Referenced by appendFileName(), and msgHandler().
appendFuncName()
void anonymous_namespace{Log.cpp}::safe::appendFuncName (char * out, size_t & pos, const char * func) noexcept
Definition at line 633 of file Log.cpp.
    {
      if(!out || !func || !*func || pos >= txtCap - 3) return;
      size_t cap = 0;
      const char* end = func;
      while(cap < txtCap && *end != '\0' && *end != '(') {
        ++end;
        ++cap;
      }
      // Find last "operator" token in [func, end)
      const char* ope = nullptr;
      for(const char* p = func; p < end; ++p) {
        if((end - p) < 8) break;
        if(p[0] == 'o' && p[1] == 'p' && p[2] == 'e' && p[3] == 'r' &&
           p[4] == 'a' && p[5] == 't' && p[6] == 'o' && p[7] == 'r') {
          const bool lftOk = (p == func) || isSpaceChar(static_cast<unsigned char>(p[-1])) || (p[-1] == ':');
          const bool ritOk = ((p + 8) == end) || !isIdentifierChar(static_cast<unsigned char>(p[8]));
          if(lftOk && ritOk) ope = p; // keep last
        }
      }
      const char* spa = nullptr;
      size_t ignoreSpace = 0;
      const char* tmp = ope ? ope : end;
      while(tmp > func) {
        --tmp;
        if(*tmp == '>') {
          ++ignoreSpace;
        }
        else if(*tmp == '<') {
          if(ignoreSpace > 0)
            --ignoreSpace;
        }
        else if(ignoreSpace == 0 && isSpaceChar(static_cast<unsigned char>(*tmp))) {
          spa = tmp;
          break;
        }
      }
      const char* beg = spa ? (spa + 1) : func;
      while(beg < end && isSpaceChar(static_cast<unsigned char>(*beg))) ++beg;
      const size_t pos0 = pos;
      for(size_t n = 0; pos < txtCap - 3 && n < 160 && beg + n < end && beg[n] != '\0'; ++n)
        appendChr(out, pos, beg[n]);
      while(pos > pos0 && out[pos - 1] == ' ')
        --pos;
      out[pos] = '\0';
    }
References appendChr(), appendFuncName(), isIdentifierChar(), isSpaceChar(), and txtCap.
Referenced by appendFuncName(), and msgHandler().
appendHex()
void anonymous_namespace{Log.cpp}::safe::appendHex (char * out, size_t & pos, const uint32_t val) noexcept
Definition at line 511 of file Log.cpp.
    {
      static constexpr char Hex[] = "0123456789ABCDEF";
      if(out == nullptr || pos >= txtCap - 13) return;
      out[pos++] = '0';
      out[pos++] = 'x';
      for(int ii = 7; ii >= 0; --ii) {
        const uint32_t nib = (val >> (ii * 4)) & 0xFu;
        out[pos++] = Hex[nib];
      }
      out[pos] = '\0';
    }
References appendHex(), and txtCap.
Referenced by appendHex(), msgHandler(), and windowsExceptionFilter().
appendLvl()
void anonymous_namespace{Log.cpp}::safe::appendLvl (char * out, size_t & pos, const QtMsgType typ) noexcept
Definition at line 572 of file Log.cpp.
    {
      if(!out || pos >= txtCap - 7) return;
      switch(typ) {
        case QtDebugMsg:
          out[pos++] = 'D';
          out[pos++] = 'B';
          out[pos++] = 'U';
          out[pos++] = 'G';
          break;
        case QtInfoMsg:
          out[pos++] = 'I';
          out[pos++] = 'N';
          out[pos++] = 'F';
          out[pos++] = 'O';
          break;
        case QtWarningMsg:
          out[pos++] = 'W';
          out[pos++] = 'A';
          out[pos++] = 'R';
          out[pos++] = 'N';
          break;
        case QtCriticalMsg:
          out[pos++] = 'C';
          out[pos++] = 'R';
          out[pos++] = 'I';
          out[pos++] = 'T';
          break;
        case QtFatalMsg:
          out[pos++] = 'F';
          out[pos++] = 'A';
          out[pos++] = 'T';
          out[pos++] = 'L';
          break;
      }
      out[pos] = '\0';
    }
References appendLvl(), and txtCap.
Referenced by appendLvl(), and msgHandler().
appendMsg()
void anonymous_namespace{Log.cpp}::safe::appendMsg (char * out, size_t & pos, const QString & msg) noexcept
Definition at line 685 of file Log.cpp.
    {
      if(!out || pos >= txtCap - 3) return;
      const ushort* txt = msg.utf16();   // no allocation
      const qsizetype qlen = msg.size(); // no allocation
      if(!txt || qlen <= 0) return;
      const size_t len = static_cast<size_t>(qlen);
      const size_t nmax = (len < txtCap) ? len : txtCap;
      const size_t pos0 = pos;
      for(size_t ii = 0; ii < nmax && pos < txtCap - 3; ++ii)
        appendChr(out, pos, static_cast<wchar_t>(txt[ii]));
      while(pos > pos0 && out[pos - 1] == ' ')
        --pos;
      out[pos] = '\0';
    }
References appendChr(), appendMsg(), and txtCap.
Referenced by appendMsg(), and msgHandler().
appendTxt() [1/2]
void anonymous_namespace{Log.cpp}::safe::appendTxt (char * out, size_t & pos, const char * txt) noexcept
Definition at line 453 of file Log.cpp.
    {
      if(!out || !txt || pos >= txtCap - 3) return;
      size_t n = 0;
      const size_t pos0 = pos;
      while(pos < txtCap - 3 && n < txtCap && txt[n] != '\0')
        appendChr(out, pos, txt[n++]);
      while(pos > pos0 && out[pos - 1] == ' ')
        --pos;
      out[pos] = '\0';
    }
References appendChr(), appendTxt(), and txtCap.
Referenced by appendTxt(), appendTxt(), invalidParamHandler(), msgHandler(), pureCallHandler(), signalHandler(), terminateHandler(), and windowsExceptionFilter().
appendTxt() [2/2]
void anonymous_namespace{Log.cpp}::safe::appendTxt (char * out, size_t & pos, const wchar_t * txt) noexcept
Definition at line 467 of file Log.cpp.
    {
      if(!out || !txt || pos >= txtCap - 3) return;
      size_t n = 0;
      const size_t pos0 = pos;
      while(pos < txtCap - 3 && n < txtCap && txt[n] != L'\0')
        appendChr(out, pos, txt[n++]);
      while(pos > pos0 && out[pos - 1] == ' ')
        --pos;
      out[pos] = '\0';
    }
References appendChr(), appendTxt(), and txtCap.
decDigits()
unsigned anonymous_namespace{Log.cpp}::safe::decDigits (const unsigned num) noexcept
Definition at line 525 of file Log.cpp.
    {
      if(num >= 1000000000U) return 10;
      if(num >= 100000000U) return 9;
      if(num >= 10000000U) return 8;
      if(num >= 1000000U) return 7;
      if(num >= 100000U) return 6;
      if(num >= 10000U) return 5;
      if(num >= 1000U) return 4;
      if(num >= 100U) return 3;
      if(num >= 10U) return 2;
      return 1;
    }
References decDigits().
Referenced by appendDec(), and decDigits().
hardFailFast()
void anonymous_namespace{Log.cpp}::safe::hardFailFast () noexcept
Definition at line 857 of file Log.cpp.
    {
      //::RaiseFailFastException(nullptr, nullptr, 0);
      __fastfail(FAST_FAIL_FATAL_APP_EXIT);
      // ReSharper disable once CppUnreachableCode
      ::TerminateProcess(::GetCurrentProcess(), 0x40000015u); // STATUS_FATAL_APP_EXIT  // NOLINT(clang-diagnostic-unreachable-code)
      //__assume(0);
    }
References hardFailFast().
Referenced by hardFailFast(), invalidParamHandler(), pureCallHandler(), reraiseDefault(), signalHandler(), and terminateHandler().
impLogWrite()
void anonymous_namespace{Log.cpp}::safe::impLogWrite (const char * data, size_t len, bool crash)
Definition at line 327 of file Log.cpp.
    {
      if(hImpLogProc == nullptr ||
         hImpLogPipe == nullptr ||
         hImpLogPipe == INVALID_HANDLE_VALUE ||
         data == nullptr ||
         len == 0) {
        return;
      }
      const unsigned char* p = reinterpret_cast<const unsigned char*>(data);
      size_t remaining = len;
      int noProgressTries = 0;
      while(remaining > 0) {
        const size_t chunkSz = (remaining > static_cast<size_t>(0xFFFFFFFFu))
                                 ? static_cast<size_t>(0xFFFFFFFFu)
                                 : remaining;
        const DWORD chunk = static_cast<DWORD>(chunkSz);
        DWORD wrote = 0;
        const BOOL ok = ::WriteFile(hImpLogPipe, p, chunk, &wrote, nullptr);
        if(!ok || wrote == 0) {
          const DWORD err = ::GetLastError(); // capture immediately
          ++noProgressTries;
          if(crash)
            return;
          // If the pipe is already dead, retries are pointless.
          if(err == ERROR_BROKEN_PIPE || err == ERROR_NO_DATA)
            noProgressTries = 16;
          if(noProgressTries < 16) {
            ::SwitchToThread();
            continue;
          }
          QString msg = QStringLiteral("WriteFile to npiImpLog pipe failed (no progress after 16 tries).");
          msg += QStringLiteral("\nGetLastError %1: %2")
                .arg(static_cast<qulonglong>(err))
                .arg(QString::fromStdWString(win32ErrorText(err)));
          if(err == ERROR_BROKEN_PIPE || err == ERROR_NO_DATA)
            msg += QStringLiteral("\nPipe is closed (helper likely exited or did not start).");
          DWORD code = STILL_ACTIVE;
          if(::GetExitCodeProcess(hImpLogProc, &code)) {
            if(code == STILL_ACTIVE) {
              msg += QStringLiteral("\nHelper process is still running.");
            }
            else {
              QString meaning;
              switch(code) {
                case 1: meaning = QStringLiteral("Missing/invalid primary log file path argument.");
                  break;
                case 2: meaning = QStringLiteral("Missing/invalid STDIN handle (pipe not redirected/inherited).");
                  break;
                case 3: meaning = QStringLiteral("ReadFile(STDIN) failed (unexpected error).");
                  break;
                case 4: meaning = QStringLiteral("Failed to open/create both primary and backup log files.");
                  break;
                case 5: meaning = QStringLiteral("Failed to open/create primary log file (no backup).");
                  break;
                case 6: meaning = QStringLiteral("WriteFile(log file) failed / no progress.");
                  break;
                case 7: meaning = QStringLiteral("Failed to write all data within retry limit.");
                  break;
                default: break;
              }
              msg += QStringLiteral("\nHelper exited with code %1").arg(static_cast<qulonglong>(code));
              if(!meaning.isEmpty())
                msg += QStringLiteral(": %1").arg(meaning);
            }
          }
          npi::app::nativeFatalMessage("ImpLog Write Failed", msg);
        }
        // Progress.
        noProgressTries = 0;
        p += wrote;
        remaining -= static_cast<size_t>(wrote);
      }
    }
References hImpLogPipe, hImpLogProc, impLogWrite(), npi::app::nativeFatalMessage(), and win32ErrorText().
Referenced by impLogWrite(), invalidParamHandler(), msgHandler(), pureCallHandler(), signalHandler(), terminateHandler(), and windowsExceptionFilter().
installCrashHandlers()
void anonymous_namespace{Log.cpp}::safe::installCrashHandlers () noexcept
Definition at line 993 of file Log.cpp.
    {
      // 1. Windows Hardware Exceptions (SEH)
      ::SetUnhandledExceptionFilter(windowsExceptionFilter);
      // 2. C++ Uncaught Exceptions
      std::set_terminate(terminateHandler);
      // 3. Pure Virtual Calls
      _set_purecall_handler(pureCallHandler);
      // 4. Invalid Parameters (CRT)
      _set_invalid_parameter_handler(invalidParamHandler);
      // 5. Abort Signal
      (void)std::signal(SIGABRT, signalHandler);
    }
References installCrashHandlers(), invalidParamHandler(), pureCallHandler(), signalHandler(), terminateHandler(), and windowsExceptionFilter().
Referenced by anonymous_namespace{Log.cpp}::initLogging(), and installCrashHandlers().
invalidParamHandler()
void anonymous_namespace{Log.cpp}::safe::invalidParamHandler (const wchar_t * expression, const wchar_t * function, const wchar_t * file, unsigned int line, uintptr_t) noexcept
Definition at line 916 of file Log.cpp.
    {
      // Re-Entrancy Guard
      if(::InterlockedExchange(&crashing, 1) != 0)
        hardFailFast();
      cTxtPos = 0;
      cTxtBuf[0] = '\0';
      appendTxt(cTxtBuf, cTxtPos, "Invalid Parameter Handler |");
      if(expression) {
        appendTxt(cTxtBuf, cTxtPos, " Expression: ");
        appendTxt(cTxtBuf, cTxtPos, expression);
      }
      if(function) {
        if(expression)
          appendChr(cTxtBuf, cTxtPos, ';');
        appendTxt(cTxtBuf, cTxtPos, " Function: ");
        appendTxt(cTxtBuf, cTxtPos, function);
      }
      if(file) {
        if(expression || function)
          appendChr(cTxtBuf, cTxtPos, ';');
        appendTxt(cTxtBuf, cTxtPos, " File: ");
        appendTxt(cTxtBuf, cTxtPos, file);
      }
      if(expression || function || file)
        appendChr(cTxtBuf, cTxtPos, ';');
      appendTxt(cTxtBuf, cTxtPos, " Line: ");
      appendDec(cTxtBuf, cTxtPos, static_cast<int>(line));
      impLogWrite(cTxtBuf, cTxtPos, true);
      hardFailFast();
    }
References appendChr(), appendDec(), appendTxt(), crashing, cTxtBuf, cTxtPos, hardFailFast(), impLogWrite(), and invalidParamHandler().
Referenced by installCrashHandlers(), and invalidParamHandler().
isIdentifierChar()
bool anonymous_namespace{Log.cpp}::safe::isIdentifierChar (unsigned char ch) noexcept
Definition at line 421 of file Log.cpp.
    {
      return (ch >= 'a' && ch <= 'z') ||
             (ch >= 'A' && ch <= 'Z') ||
             (ch >= '0' && ch <= '9') ||
             (ch == '_');
    }
References isIdentifierChar().
Referenced by appendFuncName(), and isIdentifierChar().
isSpaceChar()
bool anonymous_namespace{Log.cpp}::safe::isSpaceChar (unsigned char ch) noexcept
Definition at line 416 of file Log.cpp.
    {
      return ch == ' ' || ch == '\t' || ch == '\r' || ch == '\n';
    }
References isSpaceChar().
Referenced by appendChr(), appendFuncName(), and isSpaceChar().
msgHandler()
void anonymous_namespace{Log.cpp}::safe::msgHandler (QtMsgType typ, const QMessageLogContext & ctx, const QString & msg, bool late = false) noexcept
Definition at line 705 of file Log.cpp.
    {
      const bool isFatal{typ == QtFatalMsg};
      char fOut[txtCap]{};
      size_t fPos = 0;
      SYSTEMTIME st{};
      ::GetLocalTime(&st);
      append4Digits(fOut, fPos, st.wYear);
      appendChr(fOut, fPos, '.');
      append2Digits(fOut, fPos, st.wMonth);
      appendChr(fOut, fPos, '.');
      append2Digits(fOut, fPos, st.wDay);
      appendChr(fOut, fPos, ' ');
      append2Digits(fOut, fPos, st.wHour);
      appendChr(fOut, fPos, ':');
      append2Digits(fOut, fPos, st.wMinute);
      appendChr(fOut, fPos, ':');
      append2Digits(fOut, fPos, st.wSecond);
      appendChr(fOut, fPos, '.');
      append3Digits(fOut, fPos, st.wMilliseconds);
      appendChr(fOut, fPos, ' ');
      appendLvl(fOut, fPos, typ);
      appendChr(fOut, fPos, ' ');
      appendHex(fOut, fPos, static_cast<uint32_t>(::GetCurrentThreadId()));
      appendChr(fOut, fPos, ' ');
      appendTxt(fOut, fPos, ctx.category);
      appendChr(fOut, fPos, ' ');
      appendFileName(fOut, fPos, ctx.file);
      appendChr(fOut, fPos, ':');
      appendDec(fOut, fPos, ctx.line);
      appendChr(fOut, fPos, ' ');
      appendFuncName(fOut, fPos, ctx.function);
      if(late) appendTxt(fOut, fPos, " | LATE");
      appendTxt(fOut, fPos, " |");
      appendChr(fOut, fPos, ' ');
      appendMsg(fOut, fPos, msg);
      if(fPos > txtCap - 3) fPos = txtCap - 3;
      fOut[fPos++] = '\r';
      fOut[fPos++] = '\n';
      fOut[fPos] = '\0';
      impLogWrite(fOut, fPos, isFatal);
      if(isFatal && ::IsDebuggerPresent() != 0) {
        char dOut[txtCap]{};
        size_t dPos = 0;
        if(late) appendTxt(dOut, dPos, "LATE | ");
        appendLvl(dOut, dPos, typ);
        appendChr(dOut, dPos, ' ');
        appendHex(dOut, dPos, static_cast<uint32_t>(::GetCurrentThreadId()));
        appendChr(dOut, dPos, ' ');
        appendTxt(dOut, dPos, ctx.category);
        appendChr(dOut, dPos, ' ');
        appendFileName(dOut, dPos, ctx.file);
        appendChr(dOut, dPos, ':');
        appendDec(dOut, dPos, ctx.line);
        appendChr(dOut, dPos, ' ');
        appendFuncName(dOut, dPos, ctx.function);
        appendTxt(dOut, dPos, " | ");
        appendMsg(dOut, dPos, msg);
        if(dPos > txtCap - 3) dPos = txtCap - 3;
        dOut[dPos++] = '\r';
        dOut[dPos++] = '\n';
        dOut[dPos] = '\0';
        ::OutputDebugStringA(dOut);
      }
    }
References append2Digits(), append3Digits(), append4Digits(), appendChr(), appendDec(), appendFileName(), appendFuncName(), appendHex(), appendLvl(), appendMsg(), appendTxt(), impLogWrite(), msgHandler(), and txtCap.
Referenced by msgHandler(), and anonymous_namespace{Log.cpp}::LogCore::msgHandler_().
pureCallHandler()
void anonymous_namespace{Log.cpp}::safe::pureCallHandler () noexcept
Definition at line 866 of file Log.cpp.
    {
      // Re-Entrancy Guard
      if(::InterlockedExchange(&crashing, 1) != 0)
        hardFailFast();
      cTxtPos = 0;
      cTxtBuf[0] = '\0';
      appendTxt(cTxtBuf, cTxtPos, "Runtime Error | Pure Virtual Function Call");
      impLogWrite(cTxtBuf, cTxtPos, true);
      hardFailFast();
    }
References appendTxt(), crashing, cTxtBuf, cTxtPos, hardFailFast(), impLogWrite(), and pureCallHandler().
Referenced by installCrashHandlers(), and pureCallHandler().
reraiseDefault()
void anonymous_namespace{Log.cpp}::safe::reraiseDefault (int signum) noexcept
Definition at line 955 of file Log.cpp.
    {
      if(std::signal(signum, SIG_DFL) == SIG_ERR)
        hardFailFast();
      (void)std::raise(signum);
      // If the default action did not terminate (or raise returned for any reason),
      hardFailFast();
    }
References hardFailFast(), and reraiseDefault().
Referenced by reraiseDefault(), and signalHandler().
signalHandler()
void anonymous_namespace{Log.cpp}::safe::signalHandler (int signum) noexcept
Definition at line 964 of file Log.cpp.
    {
      static volatile LONG inSignal = 0;
      if(::InterlockedExchange(&inSignal, 1) != 0)
        hardFailFast();
      // This handler is expected to be installed only for SIGABRT.
      if(signum != SIGABRT)
        reraiseDefault(signum);
      // Known "fatal log -> abort()" path: do not write crash log, just let default happen.
      if(::InterlockedCompareExchange(&fatalLog, 0, 0) != 0)
        reraiseDefault(SIGABRT);
      // Absolute recursion stopper: any re-entry => immediate termination.
      if(::InterlockedExchange(&crashing, 1) != 0)
        hardFailFast();
      cTxtPos = 0;
      cTxtBuf[0] = '\0';
      appendTxt(cTxtBuf, cTxtPos, "C Runtime Signal | [");
      appendDec(cTxtBuf, cTxtPos, signum);
      appendTxt(cTxtBuf, cTxtPos, "] SIGABRT: Abnormal termination (e.g. abort() or failed assert).");
      impLogWrite(cTxtBuf, cTxtPos, true);
      // Preserve default abort semantics (WER/debugger/etc.).
      reraiseDefault(SIGABRT);
    }
References appendDec(), appendTxt(), crashing, cTxtBuf, cTxtPos, fatalLog, hardFailFast(), impLogWrite(), reraiseDefault(), and signalHandler().
Referenced by installCrashHandlers(), and signalHandler().
startImpLogProcess()
void anonymous_namespace{Log.cpp}::safe::startImpLogProcess (const std::wstring & primaryFullPath, const std::wstring & backupFullPath)
Definition at line 141 of file Log.cpp.
    {
      if(hImpLogProc != nullptr || hImpLogPipe != INVALID_HANDLE_VALUE)
        return;
      wchar_t impLogExePathBuf[fileNameMaxLen]{};
      const DWORD n = ::GetModuleFileNameW(nullptr, impLogExePathBuf, fileNameMaxLen);
      if(n == 0 || n >= fileNameMaxLen) {
        npi::app::nativeFatalMessage("Start Imp Log Process Failed",
          QStringLiteral("'GetModuleFileNameW' Error: %1").arg(QString::fromStdWString(win32LastError())));
      }
      std::wstring impLogExePath(impLogExePathBuf, impLogExePathBuf + n);
      const size_t slash = impLogExePath.find_last_of(L"\\/");
      if(slash == std::wstring::npos)
        npi::app::nativeFatalMessage("Start Imp Log Process Failed", "npiImpLog.exe path could not be determined");
      impLogExePath.resize(slash + 1);
      impLogExePath += L"npiImpLog.exe";
      // Create inheritable anonymous pipe: child reads, parent writes.
      SECURITY_ATTRIBUTES sa{};
      sa.nLength = sizeof(sa);
      sa.bInheritHandle = TRUE;
      HANDLE hRead = INVALID_HANDLE_VALUE;
      HANDLE hWrite = INVALID_HANDLE_VALUE;
      if(!::CreatePipe(&hRead, &hWrite, &sa, 0)) {
        npi::app::nativeFatalMessage("Start Imp Log Process Failed",
          QStringLiteral("'CreatePipe' Error: %1").arg(QString::fromStdWString(win32LastError())));
      }
      // Critical: child must NOT inherit the write end.
      if(!::SetHandleInformation(hWrite, HANDLE_FLAG_INHERIT, 0)) {
        const auto eTxt = win32LastError();
        ::CloseHandle(hRead);
        ::CloseHandle(hWrite);
        npi::app::nativeFatalMessage("Start Imp Log Process Failed",
          QStringLiteral("'SetHandleInformation' Error: %1").arg(QString::fromStdWString(eTxt)));
      }
      // stdout/stderr to NUL (GUI apps often have no valid std handles).
      HANDLE hNull = ::CreateFileW(
        L"NUL",
        GENERIC_WRITE,
        FILE_SHARE_READ | FILE_SHARE_WRITE,
        &sa, // inheritable
        OPEN_EXISTING,
        FILE_ATTRIBUTE_NORMAL,
        nullptr);
      if(hNull == INVALID_HANDLE_VALUE || hNull == nullptr) {
        const auto eTxt = win32LastError();
        ::CloseHandle(hRead);
        ::CloseHandle(hWrite);
        npi::app::nativeFatalMessage("Start Imp Log Process Failed",
          QStringLiteral("'CreateFileW(NUL)' Error: %1").arg(QString::fromStdWString(eTxt)));
      }
      // Command line: "npiImpLog.exe" "primary" "backup"
      std::wstring cmdLine;
      cmdLine.reserve(impLogExePath.size() + primaryFullPath.size() + backupFullPath.size() + 16);
      cmdLine += L"\"";
      cmdLine += impLogExePath;
      cmdLine += L"\" \"";
      cmdLine += primaryFullPath;
      cmdLine += L"\"";
      if(!backupFullPath.empty()) {
        cmdLine += L" \"";
        cmdLine += backupFullPath;
        cmdLine += L"\"";
      }
      // Restrict handle inheritance to only what we explicitly pass.
      HANDLE inheritList[2]{hRead, hNull};
      SIZE_T attrListBytes = 0;
      (void)::InitializeProcThreadAttributeList(nullptr, 1, 0, &attrListBytes);
      auto* attrList = static_cast<LPPROC_THREAD_ATTRIBUTE_LIST>(
        ::HeapAlloc(::GetProcessHeap(), 0, attrListBytes));
      if(!attrList) {
        ::CloseHandle(hNull);
        ::CloseHandle(hRead);
        ::CloseHandle(hWrite);
        npi::app::nativeFatalMessage("Start Imp Log Process Failed", "'HeapAlloc' failed for attribute list");
      }
      if(!::InitializeProcThreadAttributeList(attrList, 1, 0, &attrListBytes)) {
        const auto eTxt = win32LastError();
        ::HeapFree(::GetProcessHeap(), 0, attrList);
        ::CloseHandle(hNull);
        ::CloseHandle(hRead);
        ::CloseHandle(hWrite);
        npi::app::nativeFatalMessage("Start Imp Log Process Failed",
          QStringLiteral("'InitializeProcThreadAttributeList' Error: %1").arg(QString::fromStdWString(eTxt)));
      }
      if(!::UpdateProcThreadAttribute(
        attrList,
        0,
        PROC_THREAD_ATTRIBUTE_HANDLE_LIST,
        reinterpret_cast<void*>(inheritList),
        sizeof(inheritList),
        nullptr,
        nullptr)) {
        const auto eTxt = win32LastError();
        ::DeleteProcThreadAttributeList(attrList);
        ::HeapFree(::GetProcessHeap(), 0, attrList);
        ::CloseHandle(hNull);
        ::CloseHandle(hRead);
        ::CloseHandle(hWrite);
        npi::app::nativeFatalMessage("Start Imp Log Process Failed",
          QStringLiteral("'UpdateProcThreadAttribute(HANDLE_LIST)' Error: %1").arg(QString::fromStdWString(eTxt)));
      }
      STARTUPINFOEXW siex{};
      siex.StartupInfo.cb = sizeof(STARTUPINFOEXW);
      siex.StartupInfo.dwFlags = STARTF_USESTDHANDLES;
      siex.StartupInfo.hStdInput = hRead;
      siex.StartupInfo.hStdOutput = hNull;
      siex.StartupInfo.hStdError = hNull;
      siex.lpAttributeList = attrList;
      PROCESS_INFORMATION pi{};
      std::wstring mutableCmd = cmdLine; // CreateProcessW needs mutable buffer.
      const BOOL ok = ::CreateProcessW(
        impLogExePath.c_str(),
        mutableCmd.data(),
        nullptr,
        nullptr,
        TRUE, // must be TRUE when using HANDLE_LIST attribute
        CREATE_NO_WINDOW | EXTENDED_STARTUPINFO_PRESENT,
        nullptr,
        nullptr,
        &siex.StartupInfo,
        &pi);
      ::DeleteProcThreadAttributeList(attrList);
      ::HeapFree(::GetProcessHeap(), 0, attrList);
      if(!ok) {
        const auto eTxt = win32LastError();
        ::CloseHandle(hNull);
        ::CloseHandle(hRead);
        ::CloseHandle(hWrite);
        npi::app::nativeFatalMessage("Start Imp Log Process Failed",
          QStringLiteral("'CreateProcessW' Error: %1").arg(QString::fromStdWString(eTxt)));
      }
      // Parent closes handles it must not keep.
      ::CloseHandle(hNull);
      ::CloseHandle(hRead);
      ::CloseHandle(pi.hThread);
      hImpLogProc = pi.hProcess;
      hImpLogPipe = hWrite;
      // Optional: detect immediate startup failure (your existing behavior).
      const DWORD w = ::WaitForSingleObject(hImpLogProc, 250);
      if(w == WAIT_FAILED) {
        const auto eTxt = win32LastError();
        npi::app::nativeFatalMessage("Start Imp Log Process Failed",
          QStringLiteral("'WaitForSingleObject' Error: %1").arg(QString::fromStdWString(eTxt)));
      }
      if(w == WAIT_OBJECT_0) {
        DWORD code = 0;
        (void)::GetExitCodeProcess(hImpLogProc, &code);
        if(code == 1)
          npi::app::nativeFatalMessage("Start Imp Log Process Failed",
            "npiImpLog.exe returned 1: Missing/invalid primary log file path argument");
        if(code == 2)
          npi::app::nativeFatalMessage("Start Imp Log Process Failed",
            "npiImpLog.exe returned 2: Missing/invalid STDIN handle (pipe not redirected/inherited)");
        npi::app::nativeFatalMessage("Start Imp Log Process Failed",
          QString("npiImpLog.exe returned %1: Unknown error").arg(code));
      }
    }
References anonymous_namespace{Log.cpp}::fileNameMaxLen, hImpLogPipe, hImpLogProc, npi::app::nativeFatalMessage(), startImpLogProcess(), and win32LastError().
Referenced by startImpLogProcess(), and anonymous_namespace{Log.cpp}::LogCore::startImpLogProcess_().
terminateHandler()
void anonymous_namespace{Log.cpp}::safe::terminateHandler () noexcept
Definition at line 880 of file Log.cpp.
    {
      // Re-Entrancy Guard
      if(::InterlockedExchange(&crashing, 1) != 0)
        hardFailFast();
      cTxtPos = 0;
      cTxtBuf[0] = '\0';
      appendTxt(cTxtBuf, cTxtPos, "Terminate Handler | ");
      try {
        std::exception_ptr ptr = std::current_exception();
        if(ptr) {
          try {
            std::rethrow_exception(ptr);
          }
          catch(const std::exception& e) {
            appendTxt(cTxtBuf, cTxtPos, "Uncaught C++ Exception: ");
            appendTxt(cTxtBuf, cTxtPos, e.what());
          }
          catch(...) {
            appendTxt(cTxtBuf, cTxtPos, "Uncaught C++ Exception: Unknown Type");
          }
        }
        else {
          appendTxt(cTxtBuf, cTxtPos, "Called without active exception");
        }
      }
      catch(...) {
        appendTxt(cTxtBuf, cTxtPos, "Formatting failure while handling terminate");
      }
      impLogWrite(cTxtBuf, cTxtPos, true);
      hardFailFast();
    }
References appendTxt(), crashing, cTxtBuf, cTxtPos, hardFailFast(), impLogWrite(), and terminateHandler().
Referenced by installCrashHandlers(), and terminateHandler().
win32ErrorText()
std::wstring anonymous_namespace{Log.cpp}::safe::win32ErrorText (DWORD err)
Definition at line 101 of file Log.cpp.
    {
      if(err == 0)
        return L"(no error)";
      LPWSTR buf = nullptr;
      constexpr DWORD flags = FORMAT_MESSAGE_ALLOCATE_BUFFER |
                              FORMAT_MESSAGE_FROM_SYSTEM |
                              FORMAT_MESSAGE_IGNORE_INSERTS;
      const DWORD len = ::FormatMessageW(
        flags,
        nullptr,
        err,
        MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
        reinterpret_cast<LPWSTR>(&buf),
        0,
        nullptr);
      std::wstring msg;
      if(len != 0 && buf) {
        msg.assign(buf, buf + len);
        while(!msg.empty() && (msg.back() == L'\r' || msg.back() == L'\n' || msg.back() == L' ' || msg.back() == L'\t'))
          msg.pop_back();
      }
      else {
        msg = L"(FormatMessageW failed)";
      }
      if(buf)
        ::LocalFree(buf);
      return msg;
    }
References win32ErrorText().
Referenced by impLogWrite(), win32ErrorText(), and win32LastError().
win32LastError()
std::wstring anonymous_namespace{Log.cpp}::safe::win32LastError ()
Definition at line 136 of file Log.cpp.
    {
      return win32ErrorText(::GetLastError());
    }
References win32ErrorText(), and win32LastError().
Referenced by startImpLogProcess(), and win32LastError().
windowsExceptionFilter()
LONG WINAPI anonymous_namespace{Log.cpp}::safe::windowsExceptionFilter (EXCEPTION_POINTERS * ep)
Definition at line 792 of file Log.cpp.
    {
      if(!ep || !ep->ExceptionRecord)
        return EXCEPTION_CONTINUE_SEARCH;
      const DWORD code = ep->ExceptionRecord->ExceptionCode;
      if(code == EXCEPTION_BREAKPOINT || code == EXCEPTION_SINGLE_STEP)
        return EXCEPTION_CONTINUE_SEARCH;
      if(::InterlockedExchange(&crashing, 1) != 0) {
        ::TerminateProcess(::GetCurrentProcess(), static_cast<UINT>(code));
        return EXCEPTION_EXECUTE_HANDLER;
      }
      cTxtPos = 0;
      cTxtBuf[0] = '\0';
      // CASE 1: Stack Overflow (Critical / Low Stack)
      if(code == EXCEPTION_STACK_OVERFLOW) {
        if(_resetstkoflw()) {
          // Reset guard page to proceed safely (include malloc.h)
          appendTxt(cTxtBuf, cTxtPos, "Windows (SEH) Exception | Stack Overflow (Recursion or Stack Exhaustion)");
          impLogWrite(cTxtBuf, cTxtPos, true);
        }
        // Kill immediately - we cannot recover safely
        ::TerminateProcess(::GetCurrentProcess(), static_cast<UINT>(code));
        return EXCEPTION_EXECUTE_HANDLER;
      }
      // CASE 2: Standard SEH Crash (Stack is Safe)
      appendTxt(cTxtBuf, cTxtPos, "Windows (SEH) Exception | ");
      switch(code) {
        case EXCEPTION_ACCESS_VIOLATION:
          appendTxt(cTxtBuf, cTxtPos, "Access Violation (Invalid Memory Read/Write/Execute)");
          break;
        case EXCEPTION_ARRAY_BOUNDS_EXCEEDED:
          appendTxt(cTxtBuf, cTxtPos, "Array Bounds Exceeded (Bounds-check fault)");
          break;
        case EXCEPTION_FLT_DIVIDE_BY_ZERO:
          appendTxt(cTxtBuf, cTxtPos, "Float Divide By Zero");
          break;
        case EXCEPTION_INT_DIVIDE_BY_ZERO:
          appendTxt(cTxtBuf, cTxtPos, "Integer Divide By Zero");
          break;
        case EXCEPTION_ILLEGAL_INSTRUCTION:
          appendTxt(cTxtBuf, cTxtPos, "Illegal Instruction (Invalid or unsupported CPU instruction)");
          break;
        case EXCEPTION_PRIV_INSTRUCTION:
          appendTxt(cTxtBuf, cTxtPos, "Privileged Instruction (Privileged CPU instruction in user mode)");
          break;
        case EXCEPTION_DATATYPE_MISALIGNMENT:
          appendTxt(cTxtBuf, cTxtPos, "Datatype Misalignment (Alignment fault)");
          break;
        default:
          appendTxt(cTxtBuf, cTxtPos, "Unknown Code: ");
          appendHex(cTxtBuf, cTxtPos, code);
          break;
      }
      impLogWrite(cTxtBuf, cTxtPos, true);
      return EXCEPTION_EXECUTE_HANDLER;
    }
References appendHex(), appendTxt(), crashing, cTxtBuf, cTxtPos, impLogWrite(), and windowsExceptionFilter().
Referenced by installCrashHandlers(), and windowsExceptionFilter().
Variable Documentation
crashing
volatile LONG anonymous_namespace{Log.cpp}::safe::crashing = 0 inline
Definition at line 96 of file Log.cpp.
Referenced by invalidParamHandler(), pureCallHandler(), signalHandler(), terminateHandler(), and windowsExceptionFilter().
cTxtBuf
char anonymous_namespace{Log.cpp}::safe::cTxtBuf[txtCap] {} inline
Definition at line 99 of file Log.cpp.
{};
Referenced by invalidParamHandler(), pureCallHandler(), signalHandler(), terminateHandler(), and windowsExceptionFilter().
cTxtPos
size_t anonymous_namespace{Log.cpp}::safe::cTxtPos = 0 inline
Definition at line 98 of file Log.cpp.
Referenced by invalidParamHandler(), pureCallHandler(), signalHandler(), terminateHandler(), and windowsExceptionFilter().
fatalLog
volatile LONG anonymous_namespace{Log.cpp}::safe::fatalLog = 0 inline
Definition at line 95 of file Log.cpp.
Referenced by anonymous_namespace{Log.cpp}::LogCore::msgHandler_(), and signalHandler().
hImpLogPipe
HANDLE anonymous_namespace{Log.cpp}::safe::hImpLogPipe = INVALID_HANDLE_VALUE inline
Definition at line 91 of file Log.cpp.
Referenced by impLogWrite(), and startImpLogProcess().
hImpLogProc
HANDLE anonymous_namespace{Log.cpp}::safe::hImpLogProc = nullptr inline
Definition at line 90 of file Log.cpp.
Referenced by impLogWrite(), and startImpLogProcess().
txtCap
size_t anonymous_namespace{Log.cpp}::safe::txtCap = 2048 inline constexpr
Definition at line 93 of file Log.cpp.
Referenced by append2Digits(), append3Digits(), append4Digits(), appendChr(), appendDec(), appendFileName(), appendFuncName(), appendHex(), appendLvl(), appendMsg(), appendTxt(), appendTxt(), and msgHandler().