Main Project: npi::app Namespace Reference
npi::app Namespace Reference
Common namespace for application data and utilities.
Functions
const QString & appProgramDataDir () noexcept
Absolute application-level ProgramData path.
const QString & appPublicDocumentsDir () noexcept
Absolute application-level Public/Documents path.
const QString & orgProgramDataDir () noexcept
Absolute organization-level ProgramData path.
const QString & orgPublicDocumentsDir () noexcept
Absolute organization-level Public/Documents path.
Variables
constexpr QLatin1StringView appDirName {"D141_Base"}
Application directory name.
constexpr QLatin1StringView appName {"D141_Base"}
Application display name.
constexpr QLatin1StringView appVersion {"0.1.0"}
Application version string.
constexpr QLatin1StringView orgDirName {"npi_electronic"}
Organization directory name.
constexpr QLatin1StringView orgDomain {"npielectronic.com"}
Organization domain name.
constexpr QLatin1StringView orgName {"npi electronics GmbH"}
Organization display name.
Detailed Description
Common namespace for application data and utilities.
This namespace contains module-agnostic application-wide identifiers, compile-time defaults, and lightweight utilities.
Note
Only for cross-cutting code; place domain-specific code in a dedicated child namespace e.g. npi::log or npi::net.
Function Documentation
appProgramDataDir()
const QString & npi::app::appProgramDataDir () nodiscard noexcept
Absolute application-level ProgramData path.
Returns the absolute, normalized path to: [ProgramData]/[OrganizationName]/[ApplicationName] Implementation:
Obtains the organization-level base from orgProgramDataDir().
Ensures the application subdirectory exists (creates it; fatal if it fails).
Canonicalizes when possible; otherwise cleans the absolute path.
Converts separators to forward slashes; UNC is returned as //server/share/....
The result is cached in a function-local static and reused on subsequent calls.
Returns
Reference to a process-lifetime QString with the absolute path using forward slashes.
Postcondition
The returned reference remains valid for the lifetime of the process.
Note
Windows-only: Paths use forward slashes for Qt friendliness; call QDir::toNativeSeparators(...) before passing to Win32 APIs.
Multi-Thread: Safe, first-call initialization is thread-safe (C++11). Subsequent calls are lock-free.
Warning
On unrecoverable failure to create the directory, a native dialog is shown and the process terminates (no return).
Example
const QString appPD = npi::app::appProgramDataDir();           // e.g. C:/ProgramData/npi_electronic/test_app
const QString cfg   = QDir(appPD).filePath("settings.ini");
Definition at line 141 of file AppMeta.cpp.
{
  static const QString path = []() -> QString {
    // Get the organization-level ProgramData directory
    QDir base{npi::app::orgProgramDataDir()};
    // Ensure [ProgramData]/[OrganizationName]/[ApplicationName] exists
    const QString appName = npi::app::appDirName;
    const QString target = base.filePath(appName);
    if(!base.mkpath(appName)) {
      npi::win::abortMsgBox(
        "ABORT: Create Directory Failed",
        QString("Unable to create required directory '%1'.")
       .arg(QDir::toNativeSeparators(target)));
    }
    // Normalize and return
    QString out = QFileInfo(target).canonicalFilePath();                           // absolute + symlinks/junctions resolved
    if(out.isEmpty()) out = QDir::cleanPath(QFileInfo(target).absoluteFilePath()); // defensive fallback
    return QDir::fromNativeSeparators(out);                                        // forward slashes; UNC as //server/share
  }();
  // Return cached path
  return path;
}
References npi::win::abortMsgBox(), appDirName, appName, and orgProgramDataDir().
appPublicDocumentsDir()
const QString & npi::app::appPublicDocumentsDir () nodiscard noexcept
Absolute application-level Public/Documents path.
Returns the absolute, normalized path to: [Public]/Documents/[OrganizationName]/[ApplicationName] Implementation:
Obtains the organization-level base from orgPublicDocumentsDir().
Ensures the application subdirectory exists (creates it; fatal if it fails).
Canonicalizes when possible; otherwise cleans the absolute path.
Converts separators to forward slashes; UNC is returned as //server/share/....
The result is cached in a function-local static and reused on subsequent calls.
Returns
Reference to a process-lifetime QString with the absolute path using forward slashes.
Postcondition
The returned reference remains valid for the lifetime of the process.
Note
Windows-only: Paths use forward slashes for Qt friendliness; call QDir::toNativeSeparators(...) before passing to Win32 APIs.
Multi-Thread: Safe, first-call initialization is thread-safe (C++11). Subsequent calls are lock-free.
Warning
On unrecoverable failure to create the directory, a native dialog is shown and the process terminates (no return).
Example
const QString appPub = npi::app::appPublicDocumentsDir();      // e.g. C:/Users/Public/Documents/npi_electronic/Log_Test
const QString demo   = QDir(appPub).filePath("examples/demo.txt");
Definition at line 167 of file AppMeta.cpp.
{
  static const QString path = []() -> QString {
    // Get the organization-level Public/Documents directory
    QDir base{npi::app::orgPublicDocumentsDir()};
    // Ensure Public/Documents/[OrganizationName]/[ApplicationName] exists
    const QString appName = npi::app::appDirName;
    const QString target = base.filePath(appName);
    if(!base.mkpath(appName)) {
      npi::win::abortMsgBox(
        "ABORT: Create Directory Failed",
        QString("Unable to create required directory '%1'.")
       .arg(QDir::toNativeSeparators(target)));
    }
    // Normalize and return
    QString out = QFileInfo(target).canonicalFilePath();                           // absolute + symlinks/junctions resolved
    if(out.isEmpty()) out = QDir::cleanPath(QFileInfo(target).absoluteFilePath()); // defensive fallback
    return QDir::fromNativeSeparators(out);                                        // forward slashes; UNC as //server/share
  }();
  // Return cached path
  return path;
}
References npi::win::abortMsgBox(), appDirName, appName, and orgPublicDocumentsDir().
orgProgramDataDir()
const QString & npi::app::orgProgramDataDir () nodiscard noexcept
Absolute organization-level ProgramData path.
Returns the absolute, normalized path to: [ProgramData]/[OrganizationName] Resolution order: 1) Windows API (SHGetKnownFolderPath with FOLDERID_ProgramData) 2) Environment variable fallback: PROGRAMDATA Then:
Verifies the base folder exists (fatal if missing).
Ensures the organization subdirectory exists (creates it; fatal if it fails).
Canonicalizes when possible (resolves junctions/symlinks); otherwise cleans the absolute path.
Converts separators to forward slashes; UNC is returned as //server/share/....
The result is cached in a function-local static and reused on subsequent calls.
Returns
Reference to a process-lifetime QString with the absolute path using forward slashes.
Postcondition
The returned reference remains valid for the lifetime of the process.
Note
Windows-only: Paths use forward slashes for Qt friendliness; call QDir::toNativeSeparators(...) before passing to Win32 APIs.
Multi-Thread: Safe, first-call initialization is thread-safe (C++11). Subsequent calls are lock-free.
Warning
On unrecoverable failure (cannot locate or create the required directory), a native dialog is shown and the process is terminated (no return).
Example
// Build a file path within the org folder (Qt accepts forward slashes)
const QString orgDir = npi::app::orgProgramDataDir();          // e.g. C:/ProgramData/npi_electronic
const QString file   = QDir(orgDir).filePath("global.log");
// When calling Win32, convert once:
const QString native = QDir::toNativeSeparators(orgDir);        // e.g. C:\ProgramData\npi_electronic
// CreateDirectoryW(reinterpret_cast<LPCWSTR>(native.utf16()), nullptr);
Definition at line 29 of file AppMeta.cpp.
{
  static const QString path = []() -> QString {
    // Determine ProgramData base path
    QString base;
    // Windows API
    PWSTR p = nullptr;
    const HRESULT hr = SHGetKnownFolderPath(FOLDERID_ProgramData, KF_FLAG_DEFAULT, nullptr, &p);
    if(SUCCEEDED(hr) && p) {
      base = QString::fromWCharArray(p);
      CoTaskMemFree(p);
    }
    // Fallback to env
    if(base.isEmpty()) {
      if(const QByteArray env = qgetenv("PROGRAMDATA"); !env.isEmpty())
        base = QString::fromLocal8Bit(env);
    }
    // Abort if missing
    if(base.isEmpty()) {
      npi::win::abortMsgBox(
        "ABORT: ProgramData Unavailable",
        "Unable to determine the ProgramData path.");
    }
    // Ensure ProgramData exists
    QDir root(base);
    if(!root.exists()) {
      npi::win::abortMsgBox(
        "ABORT: ProgramData Missing",
        QString("ProgramData path '%1' does not exist.")
       .arg(QDir::toNativeSeparators(root.absolutePath())));
    }
    // Ensure [ProgramData]/[OrganizationName] exists
    const auto orgName = QString{npi::app::orgDirName};
    const QString target = root.filePath(orgName);
    if(!root.mkpath(orgName)) {
      npi::win::abortMsgBox(
        "ABORT: Create Directory Failed",
        QString("Unable to create required directory '%1'.")
       .arg(QDir::toNativeSeparators(target)));
    }
    // Normalize and return
    QString out = QFileInfo(target).canonicalFilePath();                           // absolute + symlinks/junctions resolved
    if(out.isEmpty()) out = QDir::cleanPath(QFileInfo(target).absoluteFilePath()); // defensive fallback
    return QDir::fromNativeSeparators(out);                                        // forward slashes; UNC as //server/share
  }();
  // Return cached path
  return path;
}
References npi::win::abortMsgBox(), orgDirName, and orgName.
Referenced by appProgramDataDir().
orgPublicDocumentsDir()
const QString & npi::app::orgPublicDocumentsDir () nodiscard noexcept
Absolute organization-level Public/Documents path.
Returns the absolute, normalized path to: [Public]/Documents/[OrganizationName] Resolution order: 1) Windows API (SHGetKnownFolderPath with FOLDERID_PublicDocuments) 2) Environment variable fallback: PUBLIC + "Documents" Then:
Verifies the base folder exists (fatal if missing).
Ensures the organization subdirectory exists (creates it; fatal if it fails).
Canonicalizes when possible; otherwise cleans the absolute path.
Converts separators to forward slashes; UNC is returned as //server/share/....
The result is cached in a function-local static and reused on subsequent calls.
Returns
Reference to a process-lifetime QString with the absolute path using forward slashes.
Postcondition
The returned reference remains valid for the lifetime of the process.
Note
Windows-only: Paths use forward slashes for Qt friendliness; call QDir::toNativeSeparators(...) before passing to Win32 APIs.
Multi-Thread: Safe, first-call initialization is thread-safe (C++11). Subsequent calls are lock-free.
Warning
On unrecoverable failure, a native dialog is shown and the process terminates (no return).
Example
const QString pubOrg = npi::app::orgPublicDocumentsDir();      // e.g. C:/Users/Public/Documents/npi_electronic
const QString readme = QDir(pubOrg).filePath("ReadMe.txt");
Definition at line 85 of file AppMeta.cpp.
{
  static const QString path = []() -> QString {
    // Determine Public/Documents base path
    QString base;
    // Windows API
    PWSTR p = nullptr;
    const HRESULT hr = SHGetKnownFolderPath(FOLDERID_PublicDocuments, KF_FLAG_DEFAULT, nullptr, &p);
    if(SUCCEEDED(hr) && p) {
      base = QString::fromWCharArray(p);
      CoTaskMemFree(p);
    }
    // Fallback to env
    if(base.isEmpty()) {
      if(const QByteArray env = qgetenv("PUBLIC"); !env.isEmpty())
        base = QDir(QString::fromLocal8Bit(env)).filePath(QStringLiteral("Documents"));
    }
    // Abort if missing
    if(base.isEmpty()) {
      npi::win::abortMsgBox(
        "ABORT: Public/Documents Unavailable",
        "Unable to determine the Public/Documents path.");
    }
    // Ensure Public/Documents exists
    QDir root(base);
    if(!root.exists()) {
      npi::win::abortMsgBox(
        "ABORT: Public/Documents Missing",
        QString("Public/Documents path '%1' does not exist.")
       .arg(QDir::toNativeSeparators(root.absolutePath())));
    }
    // Ensure Public/Documents/[OrganizationName] exists
    const auto orgName = QString{npi::app::orgDirName};
    const QString target = root.filePath(orgName);
    if(!root.mkpath(orgName)) {
      npi::win::abortMsgBox(
        "ABORT: Create Directory Failed",
        QString("Unable to create required directory '%1'.")
       .arg(QDir::toNativeSeparators(target)));
    }
    // Normalize and return
    QString out = QFileInfo(target).canonicalFilePath();                           // absolute + symlinks/junctions resolved
    if(out.isEmpty()) out = QDir::cleanPath(QFileInfo(target).absoluteFilePath()); // defensive fallback
    return QDir::fromNativeSeparators(out);                                        // forward slashes; UNC as //server/share
  }();
  // Return cached path
  return path;
}
References npi::win::abortMsgBox(), orgDirName, and orgName.
Referenced by appPublicDocumentsDir().
Variable Documentation
appDirName
QLatin1StringView npi::app::appDirName {"D141_Base"} inline constexpr
Application directory name.
Definition at line 40 of file AppMeta.h.
{"D141_Base"};         ///< Application directory name
Referenced by appProgramDataDir(), and appPublicDocumentsDir().
appName
QLatin1StringView npi::app::appName {"D141_Base"} inline constexpr
Application display name.
Definition at line 36 of file AppMeta.h.
{"D141_Base"};            ///< Application display name
Referenced by appProgramDataDir(), and appPublicDocumentsDir().
appVersion
QLatin1StringView npi::app::appVersion {"0.1.0"} inline constexpr
Application version string.
Definition at line 38 of file AppMeta.h.
{"0.1.0"};             ///< Application version string
orgDirName
QLatin1StringView npi::app::orgDirName {"npi_electronic"} inline constexpr
Organization directory name.
Definition at line 39 of file AppMeta.h.
{"npi_electronic"};    ///< Organization directory name
Referenced by orgProgramDataDir(), and orgPublicDocumentsDir().
orgDomain
QLatin1StringView npi::app::orgDomain {"npielectronic.com"} inline constexpr
Organization domain name.
Definition at line 37 of file AppMeta.h.
{"npielectronic.com"};  ///< Organization domain name
orgName
QLatin1StringView npi::app::orgName {"npi electronics GmbH"} inline constexpr
Organization display name.
Definition at line 35 of file AppMeta.h.
{"npi electronics GmbH"}; ///< Organization display name
Referenced by orgProgramDataDir(), and orgPublicDocumentsDir().