Main Project: npi::win::MutexLocker Class Reference
npi::win::MutexLocker Class Reference
RAII wrapper around a Windows named mutex.
#include <WinMutexLocker.hpp>
Public Member Functions
MutexLocker (const MutexLocker &other)=delete
Deleted Copy Constructor.
MutexLocker (const QString &name)
Create or open a session-local named mutex and acquire it.
MutexLocker (MutexLocker &&other)=delete
Deleted Move Constructor.
~MutexLocker ()
Release the mutex (if owned) and close the HANDLE.
bool isLocked_ () const
Query whether this instance currently holds the mutex.
bool lock_ ()
Attempt to acquire the mutex after construction.
operator bool () const
Boolean conversion for convenient checks.
MutexLocker & operator= (const MutexLocker &other)=delete
Deleted Copy Assignment.
MutexLocker & operator= (MutexLocker &&other)=delete
Deleted Move Assignment.
void unlock_ ()
Release the mutex if currently owned by this instance.
Private Attributes
HANDLE handle_ {nullptr}
HANDLE to the named mutex returned by CreateMutexW; nullptr if creation/open failed.
bool locked_ {false}
Tracks whether this instance currently owns the mutex (true) or not (false).
Detailed Description
RAII wrapper around a Windows named mutex.
Constructs or opens a named mutex, waits to acquire ownership, and releases it on destruction. The name is qualified with the "Local\\" prefix to scope the mutex to the current session. This class therefore acts as a lock between:
Multiple threads of the same process, and
Multiple processes/applications in the same Windows logon session.
Key points:
Constructor blocks until the mutex is acquired, unless CreateMutexW fails.
Destructor safely releases and closes the handle if owned/opened.
Copy and move are disabled to prevent double-release issues.
WAIT_ABANDONED is treated as successful acquisition as per Win32 semantics.
Definition at line 61 of file WinMutexLocker.hpp.
Constructor & Destructor Documentation
MutexLocker() [1/3]
npi::win::MutexLocker::MutexLocker (const QString & name) inline explicit
Create or open a session-local named mutex and acquire it.
Parameters
name Logical mutex name (without "Local\\"). Example: "npi-SharedFileLock".
Internally, the name is converted to UTF-16 and prefixed with "Local\\". This constructor: 1) Calls CreateMutexW(nullptr, FALSE, L"Local\{name}"). Passing FALSE means the mutex is not acquired at creation time. 2) If the handle is valid, calls WaitForSingleObject(h, INFINITE). On WAIT_OBJECT_0 or WAIT_ABANDONED, the lock is considered acquired. Otherwise, the handle is closed and the locker remains invalid. If another thread/process already owns the mutex, this call blocks until it becomes available.
Definition at line 73 of file WinMutexLocker.hpp.
    {
      // Build "Local\{name}" so the mutex is scoped to the current logon session.
      const QString lockName = QStringLiteral("Local\\") + name;
      const wchar_t* wLockName = reinterpret_cast<const wchar_t*>(lockName.utf16());
      HANDLE h = ::CreateMutexW(nullptr, FALSE, wLockName);
      if(!h) return;
      DWORD w = ::WaitForSingleObject(h, INFINITE);
      if(w == WAIT_OBJECT_0 || w == WAIT_ABANDONED) {
        handle_ = h;
        locked_ = true;
      }
      else {
        ::CloseHandle(h); // Avoid handle leak on failure.
      }
    }
References handle_, and locked_.
Referenced by MutexLocker(), MutexLocker(), operator=(), and operator=().
~MutexLocker()
npi::win::MutexLocker::~MutexLocker () inline
Release the mutex (if owned) and close the HANDLE.
Calls ReleaseMutex only if this instance previously acquired the lock (locked_ == true). The HANDLE is then closed. This guarantees no handle leak even if acquisition failed.
Definition at line 94 of file WinMutexLocker.hpp.
    {
      if(handle_) {
        if(locked_) {
          ::ReleaseMutex(handle_);
          locked_ = false;
        }
        ::CloseHandle(handle_);
      }
    }
References handle_, and locked_.
MutexLocker() [2/3]
npi::win::MutexLocker::MutexLocker (MutexLocker && other) delete
Deleted Move Constructor.
References MutexLocker().
MutexLocker() [3/3]
npi::win::MutexLocker::MutexLocker (const MutexLocker & other) delete
Deleted Copy Constructor.
References MutexLocker().
Member Function Documentation
isLocked_()
bool npi::win::MutexLocker::isLocked_ () const inline
Query whether this instance currently holds the mutex.
Returns
true if the mutex is owned by this instance; false otherwise.
Definition at line 112 of file WinMutexLocker.hpp.
{ return locked_; }
References locked_.
lock_()
bool npi::win::MutexLocker::lock_ () inline
Attempt to acquire the mutex after construction.
Returns
true if the mutex becomes owned by this instance; false otherwise.
If a HANDLE exists but the lock is not currently held by this instance, this method blocks with INFINITE timeout until the mutex is available. WAIT_OBJECT_0 and WAIT_ABANDONED are treated as success per Win32 semantics.
Definition at line 130 of file WinMutexLocker.hpp.
    {
      if(handle_ && !locked_) {
        DWORD w = ::WaitForSingleObject(handle_, INFINITE);
        if(w == WAIT_OBJECT_0 || w == WAIT_ABANDONED) {
          locked_ = true;
        }
      }
      return locked_;
    }
References handle_, and locked_.
operator bool()
npi::win::MutexLocker::operator bool () const inline explicit
Boolean conversion for convenient checks.
Returns
true if the mutex is owned by this instance; false otherwise.
Enables patterns like:
MutexLocker lock(...);
if(!lock) return;
Definition at line 122 of file WinMutexLocker.hpp.
{ return locked_; }
References locked_.
operator=() [1/2]
MutexLocker & npi::win::MutexLocker::operator= (const MutexLocker & other) delete
Deleted Copy Assignment.
References MutexLocker().
operator=() [2/2]
MutexLocker & npi::win::MutexLocker::operator= (MutexLocker && other) delete
Deleted Move Assignment.
References MutexLocker().
unlock_()
void npi::win::MutexLocker::unlock_ () inline
Release the mutex if currently owned by this instance.
Calls ReleaseMutex(handle_) only when locked_ == true. After a successful release, sets locked_ to false. It does not close the HANDLE; the destructor will close the HANDLE. Note: ReleaseMutex must be called exactly once for each successful acquisition on the same thread. This class ensures that by tracking locked_.
Definition at line 147 of file WinMutexLocker.hpp.
    {
      if(handle_ && locked_) {
        if(::ReleaseMutex(handle_)) {
          locked_ = false;
        }
      }
    }
References handle_, and locked_.
Member Data Documentation
handle_
HANDLE npi::win::MutexLocker::handle_ {nullptr} private
HANDLE to the named mutex returned by CreateMutexW; nullptr if creation/open failed.
Definition at line 157 of file WinMutexLocker.hpp.
{nullptr}; ///< HANDLE to the named mutex returned by CreateMutexW; nullptr if creation/open failed.
Referenced by MutexLocker(), ~MutexLocker(), lock_(), and unlock_().
locked_
bool npi::win::MutexLocker::locked_ {false} private
Tracks whether this instance currently owns the mutex (true) or not (false).
Definition at line 158 of file WinMutexLocker.hpp.
{false};     ///< Tracks whether this instance currently owns the mutex (true) or not (false).
Referenced by MutexLocker(), ~MutexLocker(), isLocked_(), lock_(), operator bool(), and unlock_().
The documentation for this class was generated from the following file:
WinMutexLocker.hpp