Main Project: npi::StageWindow Class Reference
npi::StageWindow Class Reference
Helper to display a top-level widget with optional animation and robust on-screen positioning.
#include <StageWindow.hpp>
Classes
struct OpacityGuard
Helper for StageWindow class. A RAII guard that restores a widget's window opacity on scope exit.
Public Member Functions
StageWindow ()=default
Default constructor.
StageWindow (QWidget *widget, QWidget *caller=nullptr, QWidget *center=nullptr)
Construct and seed the main, caller, and center widgets.
~StageWindow ()=default
Default destructor.
void animate_ () const
Show with an animated transition from a small source rect (cursor or caller) to the target.
QPointer< QWidget > getCaller_ () const
Get the caller widget.
QPointer< QWidget > getCenter_ () const
Get the center widget.
int getDuration_ () const
Get configured duration (ms), or -1 for auto.
QEasingCurve getEasingCurve_ () const
Get the easing curve used for animation.
QPointer< QWidget > getWidget_ () const
Get the main widget.
void quick_ () const
Show immediately without animation.
StageWindow & setCaller_ (QWidget *caller=nullptr)
Set the caller widget (visual origin for animation).
StageWindow & setCenter_ (QWidget *center=nullptr)
Set the center widget (target for centering).
StageWindow & setDuration_ (const int duration=-1)
Set animation duration.
StageWindow & setEasingCurve_ (const QEasingCurve &easingCurve=QEasingCurve::InQuad)
Set easing curve for the animation.
StageWindow & setWidget_ (QWidget *widget)
Set the main widget to be shown.
Private Member Functions
void callWidgetCorrectShowMethod_ () const
Show the widget in a state-correct way.
void positionWidget_ () const
Compute and apply an on-screen position for widget_, respecting frames/title bars.
Private Attributes
QPointer< QWidget > caller_
Visual origin for animation (cursor if null).
QPointer< QWidget > center_
If set, widget_ is centered over this before showing.
int duration_ {-1}
Duration in ms; -1 means auto.
QEasingCurve easingCurve_ {QEasingCurve::InQuad}
Easing curve for animation.
QPointer< QWidget > widget_
Main top-level widget to show.
Static Private Attributes
static constexpr int MaxDura_ {999}
Maximum duration for animation for the path-length-based heuristic.
static constexpr int MinDura_ {400}
Minimum duration for animation for the path-length-based heuristic.
Detailed Description
Helper to display a top-level widget with optional animation and robust on-screen positioning.
This class provides a convenient way to show a top-level widget with various display options, including immediate display and animated transitions. It handles positioning the widget within the available screen space and offers customization options for the animation duration and easing curve.
Definition at line 50 of file StageWindow.hpp.
Constructor & Destructor Documentation
StageWindow() [1/2]
npi::StageWindow::StageWindow () explicit default
Default constructor.
Postcondition
No widget is set; calls to quick_()/animate_() will no-op until a valid top-level widget is set.
Referenced by setCaller_(), setCenter_(), setDuration_(), setEasingCurve_(), and setWidget_().
StageWindow() [2/2]
npi::StageWindow::StageWindow (QWidget * widget, QWidget * caller = nullptr, QWidget * center = nullptr) inline explicit
Construct and seed the main, caller, and center widgets.
Parameters
widget Top-level widget to show.
caller Optional widget that acts as the visual origin for the animation (e.g., a button).
center Optional widget over which the main widget should be centered before showing.
Warning
widget must be a top-level widget (i.e., isWindow() true) for show operations to execute.
Definition at line 61 of file StageWindow.hpp.
      : widget_{widget}, caller_{caller}, center_{center} {}
References caller_, center_, and widget_.
~StageWindow()
npi::StageWindow::~StageWindow () default
Default destructor.
Member Function Documentation
animate_()
void npi::StageWindow::animate_ () const inline
Show with an animated transition from a small source rect (cursor or caller) to the target.
Steps:
Compute begRect from caller_ or a tiny rect at QCursor::pos().
Call positionWidget_() to place within screen bounds and center if requested.
Set target widget opacity to 0.0 and show it using callWidgetCorrectShowMethod_().
Create a temporary frameless tool window (overlay) at begRect with a background color derived from the target widget palette (slightly lightened/darkened for contrast).
Animate the overlay geometry from begRect to the target frame geometry.
On finish, set target opacity to 1.0 if still alive and delete the overlay.
Note
The overlay is Qt::Tool and WA_TransparentForMouseEvents to avoid focus/taskbar issues.
The animation object uses DeleteWhenStopped for cleanup.
The lambda does not capture this to avoid lifetime hazards.
Definition at line 158 of file StageWindow.hpp.
    {
      if(widget_.isNull() || !widget_->isWindow())
        return;
      // Determine starting rect for the overlay animation.
      const QRect begRect{
        caller_.isNull()
          ? QRect{QCursor::pos().x() - 1, QCursor::pos().y() - 1, 3, 3}
          : (caller_->isWindow()
               ? caller_->frameGeometry()
               : QRect{caller_->mapToGlobal(QPoint{0, 0}), caller_->size()})
      };
      // Position target and compute its final frame geometry now.
      positionWidget_();
      // Make target invisible first, then show it correctly so frameGeometry() is valid for the end rect.
      widget_->setWindowOpacity(0.0);
      callWidgetCorrectShowMethod_();
      // Guard ensures we do not leave the widget transparent on early exit.
      OpacityGuard guard{widget_};
      // Derive overlay background color for a subtle contrast flash.
      QColor bgColor{widget_->palette().color(QPalette::Window)};
      const int avg = (bgColor.red() + bgColor.green() + bgColor.blue()) / 3;
      bgColor = (avg > 127) ? bgColor.darker(120) : bgColor.lighter(120);
      // Create temporary overlay; no parent so it is its own top-level.
      QWidget* temp = new QWidget;
      temp->setWindowFlags(Qt::FramelessWindowHint | Qt::Tool);
      temp->setAttribute(Qt::WA_StyledBackground, true);
      temp->setAttribute(Qt::WA_TransparentForMouseEvents, true);
      temp->setGeometry(begRect);
      temp->setStyleSheet(QString("background-color: %1;").arg(bgColor.name()));
      // Determine duration.
      int dura = duration_;
      if(dura == -1) { // Use auto-duration heuristic
        const QPoint diff = begRect.topLeft() - widget_->frameGeometry().topLeft();
        // Heuristic: base plus path-length factor, clamped to [MinDura_, MaxDura_].
        const int term = static_cast<int>(qSqrt((diff.x() * diff.x()) + (diff.y() * diff.y())) / 4);
        dura = qMin(MaxDura_, MinDura_ + term);
      }
      // Animate overlay geometry.
      QPropertyAnimation* amin = new QPropertyAnimation(temp, "geometry");
      amin->setDuration(dura);
      amin->setStartValue(begRect);
      amin->setEndValue(widget_->frameGeometry());
      amin->setEasingCurve(easingCurve_);
      // Capture a safe handle to the widget to avoid dereferencing a dead `this`.
      QPointer<QWidget> target = widget_;
      QObject::connect(amin, &QPropertyAnimation::finished, [temp, target]() {
        if(!target.isNull())
          target->setWindowOpacity(1.0);
        temp->deleteLater();
      });
      temp->show();
      amin->start(QAbstractAnimation::DeleteWhenStopped);
      // At this point the normal path hands off restoration to the finished-callback.
      // Disable the guard so it does not undo the fade.
      guard.release_();
    }
References caller_, and widget_.
callWidgetCorrectShowMethod_()
void npi::StageWindow::callWidgetCorrectShowMethod_ () const inline private
Show the widget in a state-correct way.
If minimized: call showNormal().
Else: if visible, hide() first to reset painting, then show().
Else: show().
Definition at line 324 of file StageWindow.hpp.
    {
      if(widget_.isNull() || !widget_->isWindow())
        return;
      if(widget_->isMinimized()) {
        widget_->showNormal();
      }
      else {
        if(widget_->isVisible())
          widget_->hide();
        widget_->show();
      }
    }
References widget_.
Referenced by quick_().
getCaller_()
QPointer< QWidget > npi::StageWindow::getCaller_ () const inline
Get the caller widget.
Definition at line 120 of file StageWindow.hpp.
{ return caller_; }
References caller_.
getCenter_()
QPointer< QWidget > npi::StageWindow::getCenter_ () const inline
Get the center widget.
Definition at line 123 of file StageWindow.hpp.
{ return center_; }
References center_.
getDuration_()
int npi::StageWindow::getDuration_ () const inline
Get configured duration (ms), or -1 for auto.
Definition at line 126 of file StageWindow.hpp.
{ return duration_; }
References duration_.
getEasingCurve_()
QEasingCurve npi::StageWindow::getEasingCurve_ () const inline
Get the easing curve used for animation.
Definition at line 129 of file StageWindow.hpp.
{ return easingCurve_; }
References easingCurve_.
getWidget_()
QPointer< QWidget > npi::StageWindow::getWidget_ () const inline
Get the main widget.
Definition at line 117 of file StageWindow.hpp.
{ return widget_; }
References widget_.
positionWidget_()
void npi::StageWindow::positionWidget_ () const inline private
Compute and apply an on-screen position for widget_, respecting frames/title bars.
Logic:
Estimate full framed size if not yet shown (geometry == frameGeometry).
If center_ is set, center over it (using frame geometry when it is a window).
Else, if the widget has never been displayed and sits at (0,0), center on the screen under the cursor.
Select screen using the frame-geometry center of widget_ (or center_); fallback to primary.
Clamp position to available geometry (no overflow left/top/right/bottom).
Definition at line 248 of file StageWindow.hpp.
    {
      if(widget_.isNull() || !widget_->isWindow())
        return;
      // Calculate the extra space needed for the title bar.
      // If the widget has a title (WindowTitleHint is set), obtain the title bar height
      const auto titleHeight{(widget_->windowFlags() & Qt::WindowTitleHint) ? qApp->style()->pixelMetric(QStyle::PM_TitleBarHeight) : 0};
      // Calculate the extra space needed for the window frame.
      // If the widget is frameless, set frameSize to 0; otherwise, use the default frame width.
      const auto frameSize{(widget_->windowFlags() & Qt::FramelessWindowHint) ? 0 : qApp->style()->pixelMetric(QStyle::PM_DefaultFrameWidth)};
      // Determine full framed size.
      QSize widFullSize;
      if(widget_->geometry() == widget_->frameGeometry()) {
        // Not shown yet; synthesize framed size from client size.
        widFullSize = QSize{
          widget_->size().width() + (2 * frameSize),
          widget_->size().height() + titleHeight + (2 * frameSize)
        };
      }
      else {
        widFullSize = widget_->frameGeometry().size();
      }
      // Start from current position.
      QPoint widPos{widget_->pos()};
      // Choose a screen reference.
      QScreen* screen{qApp->screenAt(widget_->frameGeometry().center())};
      if(!center_.isNull()) {
        // Center over `center_`.
        screen = qApp->screenAt(center_->geometry().center());
        const QRect cenRect = center_->isWindow() ? center_->frameGeometry() : center_->geometry();
        const int widPosX = cenRect.x() + (cenRect.width() - widFullSize.width()) / 2;
        const int widPosY = cenRect.y() + (cenRect.height() - widFullSize.height()) / 2;
        widPos = QPoint{widPosX, widPosY};
      }
      else if(widget_->pos() == QPoint{0, 0} && widget_->geometry() == widget_->frameGeometry()) {
        // Likely first show and no explicit centering widget; center on cursor's screen.
        screen = qApp->screenAt(QCursor::pos());
        if(screen) {
          const QRect avail = screen->availableGeometry();
          const int widPosX = avail.center().x() - (widFullSize.width() / 2);
          const int widPosY = avail.center().y() - (widFullSize.height() / 2);
          widPos = QPoint{widPosX, widPosY};
        }
      }
      if(screen == nullptr)
        screen = qApp->primaryScreen();
      const QRect avail = screen->availableGeometry();
      // Horizontal clamp.
      if(widPos.x() + widFullSize.width() > avail.x() + avail.width())
        widPos.setX(avail.x() + avail.width() - widFullSize.width());
      if(widPos.x() < avail.x())
        widPos.setX(avail.x());
      // Vertical clamp.
      if(widPos.y() + widFullSize.height() > avail.y() + avail.height())
        widPos.setY(avail.y() + avail.height() - widFullSize.height());
      if(widPos.y() < avail.y())
        widPos.setY(avail.y());
      widget_->move(widPos);
    }
References center_, and widget_.
Referenced by quick_().
quick_()
void npi::StageWindow::quick_ () const inline
Show immediately without animation.
Validates that widget_ exists and is a top-level window.
Positions the widget within current screen bounds.
Uses callWidgetCorrectShowMethod_() to handle minimized/visible states robustly.
Definition at line 136 of file StageWindow.hpp.
    {
      if(widget_.isNull() || !widget_->isWindow())
        return;
      positionWidget_();
      callWidgetCorrectShowMethod_();
    }
References callWidgetCorrectShowMethod_(), positionWidget_(), and widget_.
setCaller_()
StageWindow & npi::StageWindow::setCaller_ (QWidget * caller = nullptr) inline
Set the caller widget (visual origin for animation).
Parameters
caller May be a top-level or child widget; if null, cursor position is used.
Returns
Self reference for chaining.
Definition at line 78 of file StageWindow.hpp.
    {
      caller_ = caller;
      return *this;
    }
References StageWindow(), and caller_.
setCenter_()
StageWindow & npi::StageWindow::setCenter_ (QWidget * center = nullptr) inline
Set the center widget (target for centering).
Parameters
center If provided, widget_ is centered over this before showing.
Returns
Self reference for chaining.
Definition at line 87 of file StageWindow.hpp.
    {
      center_ = center;
      return *this;
    }
References StageWindow(), and center_.
setDuration_()
StageWindow & npi::StageWindow::setDuration_ (const int duration = -1) inline
Set animation duration.
Parameters
duration Milliseconds. If <10 or >10000, sets to -1 (auto).
Returns
Self reference for chaining.
Auto duration (-1) computes a path-length-based value clamped to [MinDura_, MaxDura_].
Definition at line 98 of file StageWindow.hpp.
    {
      if(duration < 10 || duration > 10000)
        duration_ = -1;
      else
        duration_ = duration;
      return *this;
    }
References StageWindow(), and duration_.
setEasingCurve_()
StageWindow & npi::StageWindow::setEasingCurve_ (const QEasingCurve & easingCurve = QEasingCurve::InQuad) inline
Set easing curve for the animation.
Parameters
easingCurve The easing curve (default: InQuad).
Returns
Self reference for chaining.
Definition at line 110 of file StageWindow.hpp.
    {
      easingCurve_ = easingCurve;
      return *this;
    }
References StageWindow(), and easingCurve_.
setWidget_()
StageWindow & npi::StageWindow::setWidget_ (QWidget * widget) inline
Set the main widget to be shown.
Parameters
widget Top-level widget to show.
Returns
Self reference for chaining.
Definition at line 69 of file StageWindow.hpp.
    {
      widget_ = widget;
      return *this;
    }
References StageWindow(), and widget_.
Member Data Documentation
caller_
QPointer<QWidget> npi::StageWindow::caller_ private
Visual origin for animation (cursor if null).
Definition at line 230 of file StageWindow.hpp.
Referenced by StageWindow(), animate_(), getCaller_(), and setCaller_().
center_
QPointer<QWidget> npi::StageWindow::center_ private
If set, widget_ is centered over this before showing.
Definition at line 231 of file StageWindow.hpp.
Referenced by StageWindow(), getCenter_(), positionWidget_(), and setCenter_().
duration_
int npi::StageWindow::duration_ {-1} private
Duration in ms; -1 means auto.
Definition at line 233 of file StageWindow.hpp.
{-1};                               ///< Duration in ms; -1 means auto.
Referenced by getDuration_(), and setDuration_().
easingCurve_
QEasingCurve npi::StageWindow::easingCurve_ {QEasingCurve::InQuad} private
Easing curve for animation.
Definition at line 234 of file StageWindow.hpp.
{QEasingCurve::InQuad}; ///< Easing curve for animation.
Referenced by getEasingCurve_(), and setEasingCurve_().
MaxDura_
int npi::StageWindow::MaxDura_ {999} static constexpr private
Maximum duration for animation for the path-length-based heuristic.
Definition at line 238 of file StageWindow.hpp.
{999}; ///< Maximum duration for animation for the path-length-based heuristic.
MinDura_
int npi::StageWindow::MinDura_ {400} static constexpr private
Minimum duration for animation for the path-length-based heuristic.
Definition at line 237 of file StageWindow.hpp.
{400}; ///< Minimum duration for animation for the path-length-based heuristic.
widget_
QPointer<QWidget> npi::StageWindow::widget_ private
Main top-level widget to show.
Definition at line 229 of file StageWindow.hpp.
Referenced by StageWindow(), animate_(), callWidgetCorrectShowMethod_(), getWidget_(), positionWidget_(), quick_(), and setWidget_().
The documentation for this class was generated from the following file:
StageWindow.hpp