var dp_arch_dir_architecture =
[
    [ "Logging System", "d8/da3/dp_arch_logging_system.html", [
      [ "Overview", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__overview", null ],
      [ "Log Category Usage", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__log_category_usage", null ],
      [ "Implementation", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__implementation", null ],
      [ "Initialization", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__initialization", null ],
      [ "Log Records and Context Caches", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__log_records_and_context_caches", null ],
      [ "Log Fields and Formatting", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__fields_and_formatting", null ],
      [ "Normal Log Files", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__normal_log_files", null ],
      [ "Important, Fatal, and Crash Logging", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__imp_fatal_crash_logging", null ],
      [ "Worker Threads and Queue Ownership", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__workers_and_queue", null ],
      [ "Console and Debugger Output", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__console_and_debugger", null ],
      [ "Configuration and Persistence", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__config_and_persistence", null ],
      [ "Directory Validation and Switching", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__directory_validation_and_switching", null ],
      [ "Maximum Folder Size and Cleanup", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__max_folder_size_and_cleanup", null ],
      [ "Category Filtering", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__category_filtering", null ],
      [ "Shutdown", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__shutdown", null ],
      [ "Thread Safety and Usage Rules", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__thread_safety_and_usage_rules", null ],
      [ "Design Limits", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__design_limits", null ],
      [ "Public API", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__public_api", null ],
      [ "Test: Overview", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__test_overview", null ],
      [ "Test: Environment", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__test_environment", null ],
      [ "Test: Handler Time", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__test_handler_time", null ],
      [ "Test: Extreme Stress", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__test_extreme_stress", null ],
      [ "Test: Cache Text", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__test_context_cache", null ],
      [ "Test: Text Sanitization", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__test_text_sanitization", null ],
      [ "Test: Logging Behavior", "d8/da3/dp_arch_logging_system.html#dp_arch_logging_system__test_logging_behavior", null ]
    ] ],
    [ "GUI System", "da/d86/dp_arch_gui_system.html", [
      [ "Introduction", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__intro", null ],
      [ "Details", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__details", null ],
      [ "Initialization", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__initialization", null ],
      [ "Custom Properties", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__custom_properties", null ],
      [ "Public Interface", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__public_interface", null ],
      [ "Usage", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__usage", null ],
      [ "Application Font", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__app_font", null ],
      [ "Technical Font", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__technical_font", null ],
      [ "Themes and Colors", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__themes_colors", null ],
      [ "Theme-Dependent Icons", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__dynamic_icons", null ],
      [ "Grouped and Embedded Widgets", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__widget_hierarchies", null ],
      [ "Custom Drawing and Sizing", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__drawing_sizing", null ],
      [ "Table and Tree Headers", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__headers", null ],
      [ "Completion Popups", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__completion", null ],
      [ "Limitations", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__limitations", null ],
      [ "Diagnostics and Maintenance", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__diagnostics", null ],
      [ "Testing", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__testing", null ],
      [ "Bug: Font CacheOverflowException", "da/d86/dp_arch_gui_system.html#dp_arch_gui_system__bug_font_CacheOverflowException", null ]
    ] ]
];