Main Project: anonymous_namespace{Log.cpp}::LogCore::FixedStrings Struct Reference
anonymous_namespace{Log.cpp}::LogCore::FixedStrings Struct Reference
Public Member Functions
constexpr FixedStrings ()=default
constexpr FixedStrings (const char *category, const char *fileName, const char *funcName=nullptr) noexcept
void appendCategoryTo_ (QByteArray &buffer) const
void appendCategoryTo_ (QString &buffer) const
void appendFileNameTo_ (QByteArray &buffer) const
void appendFileNameTo_ (QString &buffer) const
void appendFuncNameTo_ (QByteArray &buffer) const
void appendFuncNameTo_ (QString &buffer) const
Private Member Functions
template<typename LenT, size_t N>
constexpr void assign_ (char(&buf)[N], LenT &lenOut, std::string_view sv) noexcept
bool isIdentifierChar_ (unsigned char ch) noexcept
bool isSpaceChar_ (unsigned char ch) noexcept
Private Attributes
char category_ [24] {}
uint16_t categoryLen_ {0}
char fileName_ [32] {}
uint16_t fileNameLen_ {0}
char funcName_ [56] {}
uint32_t funcNameLen_ {0}
Detailed Description
Definition at line 1599 of file Log.cpp.
Constructor & Destructor Documentation
FixedStrings() [1/2]
anonymous_namespace{Log.cpp}::LogCore::FixedStrings::FixedStrings () constexpr default
FixedStrings() [2/2]
anonymous_namespace{Log.cpp}::LogCore::FixedStrings::FixedStrings (const char * category, const char * fileName, const char * funcName = nullptr) inline explicit constexpr noexcept
Definition at line 1659 of file Log.cpp.
      {
        if(category && *category)
          assign_(category_, categoryLen_, std::string_view(category));
        if(fileName && *fileName) {
          const std::string_view s{fileName};
          const auto lastWin = s.rfind('\\');
          const auto lastUnix = s.rfind('/');
          const auto last = (lastWin == std::string_view::npos)
                              ? lastUnix
                              : (lastUnix == std::string_view::npos)
                              ? lastWin
                              : std::max(lastWin, lastUnix);
          const auto begin = (last == std::string_view::npos) ? 0 : last + 1;
          if(begin < s.size())
            assign_(fileName_, fileNameLen_, s.substr(begin));
        }
        if(funcName && *funcName) {
          size_t endIdx = 0;
          while(endIdx < 2048 && funcName[endIdx] != '\0' && funcName[endIdx] != '(')
            ++endIdx;
          bool opeFound{false};
          size_t opeIdx = 0;
          for(size_t ii = 0; ii < endIdx; ++ii) {
            if(endIdx - ii < 8) break;
            if(funcName[ii + 0] == 'o' && funcName[ii + 1] == 'p' && funcName[ii + 2] == 'e' && funcName[ii + 3] == 'r' &&
               funcName[ii + 4] == 'a' && funcName[ii + 5] == 't' && funcName[ii + 6] == 'o' && funcName[ii + 7] == 'r') {
              const bool lftOk = (ii == 0) || isSpaceChar_(static_cast<unsigned char>(funcName[ii - 1])) || (funcName[ii - 1] == ':');
              const bool ritOk = ((ii + 8) == endIdx) || !isIdentifierChar_(static_cast<unsigned char>(funcName[ii + 8]));
              if(lftOk && ritOk) {
                opeFound = true;
                opeIdx = ii;
              }
            }
          }
          size_t begIdx = 0;
          size_t ignoreSpace = 0;
          size_t tmpIdx = opeFound ? opeIdx : endIdx;
          while(tmpIdx > 0) {
            --tmpIdx;
            if(funcName[tmpIdx] == '>') {
              ++ignoreSpace;
            }
            else if(funcName[tmpIdx] == '<') {
              if(ignoreSpace > 0)
                --ignoreSpace;
            }
            else if(ignoreSpace == 0 && isSpaceChar_(static_cast<unsigned char>(funcName[tmpIdx]))) {
              begIdx = tmpIdx + 1;
              break;
            }
          }
          while(begIdx < endIdx && isSpaceChar_(static_cast<unsigned char>(funcName[begIdx])))
            ++begIdx;
          if(begIdx < endIdx) {
            const std::string_view sv(funcName + begIdx, endIdx - begIdx);
            assign_(funcName_, funcNameLen_, sv);
          }
        }
      }
References assign_(), category_, categoryLen_, fileName_, fileNameLen_, funcName_, funcNameLen_, isIdentifierChar_(), and isSpaceChar_().
Member Function Documentation
appendCategoryTo_() [1/2]
void anonymous_namespace{Log.cpp}::LogCore::FixedStrings::appendCategoryTo_ (QByteArray & buffer) const inline
Definition at line 1729 of file Log.cpp.
      {
        if(categoryLen_ < 1) return;
        buffer.append(category_, categoryLen_);
      }
References category_, and categoryLen_.
Referenced by anonymous_namespace{Log.cpp}::LogCore::FormatOneLine_().
appendCategoryTo_() [2/2]
void anonymous_namespace{Log.cpp}::LogCore::FixedStrings::appendCategoryTo_ (QString & buffer) const inline
Definition at line 1736 of file Log.cpp.
      {
        if(categoryLen_ < 1) return;
        // operator+= with QUtf8StringView is optimized in Qt 6 to avoid
        // creating a temporary QString object before appending.
        buffer += QUtf8StringView(category_, categoryLen_);
      }
References category_, and categoryLen_.
appendFileNameTo_() [1/2]
void anonymous_namespace{Log.cpp}::LogCore::FixedStrings::appendFileNameTo_ (QByteArray & buffer) const inline
Definition at line 1745 of file Log.cpp.
      {
        if(fileNameLen_ < 1) return;
        buffer.append(fileName_, fileNameLen_);
      }
References fileName_, and fileNameLen_.
Referenced by anonymous_namespace{Log.cpp}::LogCore::FormatOneLine_().
appendFileNameTo_() [2/2]
void anonymous_namespace{Log.cpp}::LogCore::FixedStrings::appendFileNameTo_ (QString & buffer) const inline
Definition at line 1752 of file Log.cpp.
      {
        if(fileNameLen_ < 1) return;
        // operator+= with QUtf8StringView is optimized in Qt 6 to avoid
        // creating a temporary QString object before appending.
        buffer += QUtf8StringView(fileName_, fileNameLen_);
      }
References fileName_, and fileNameLen_.
appendFuncNameTo_() [1/2]
void anonymous_namespace{Log.cpp}::LogCore::FixedStrings::appendFuncNameTo_ (QByteArray & buffer) const inline
Definition at line 1761 of file Log.cpp.
      {
        if(funcNameLen_ < 1) return;
        buffer.append(funcName_, funcNameLen_);
      }
References funcName_, and funcNameLen_.
Referenced by anonymous_namespace{Log.cpp}::LogCore::FormatOneLine_().
appendFuncNameTo_() [2/2]
void anonymous_namespace{Log.cpp}::LogCore::FixedStrings::appendFuncNameTo_ (QString & buffer) const inline
Definition at line 1768 of file Log.cpp.
      {
        if(funcNameLen_ < 1) return;
        // operator+= with QUtf8StringView is optimized in Qt 6 to avoid
        // creating a temporary QString object before appending.
        buffer += QUtf8StringView(funcName_, funcNameLen_);
      }
References funcName_, and funcNameLen_.
assign_()
template<typename LenT, size_t N> void anonymous_namespace{Log.cpp}::LogCore::FixedStrings::assign_ (char(&) buf[N], LenT & lenOut, std::string_view sv) inline constexpr private noexcept
Definition at line 1626 of file Log.cpp.
      {
        if(sv.empty()) return;
        size_t beg{0};
        size_t cpy = sv.size();
        constexpr size_t MaxLen = N - 1; // Reserve 1 for null terminator
        if(cpy > MaxLen) {
          buf[0] = '~';
          buf[MaxLen] = '\0';
          beg = 1;
          cpy = MaxLen - 1; // Truncate logic: Max capacity minus tilde
          lenOut = static_cast<LenT>(MaxLen);
        }
        else {
          buf[cpy] = '\0';
          lenOut = static_cast<LenT>(cpy);
        }
        if(cpy > 0) {
          // Logic: copy the *end* of the string (suffix)
          const char* srcStart = sv.data() + sv.size() - cpy;
          if(std::is_constant_evaluated())
            std::copy_n(srcStart, cpy, buf + beg);
          else
            std::memcpy(buf + beg, srcStart, cpy);
        }
      }
Referenced by FixedStrings().
isIdentifierChar_()
bool anonymous_namespace{Log.cpp}::LogCore::FixedStrings::isIdentifierChar_ (unsigned char ch) inline private noexcept
Definition at line 1616 of file Log.cpp.
      {
        return (ch >= 'a' && ch <= 'z') ||
               (ch >= 'A' && ch <= 'Z') ||
               (ch >= '0' && ch <= '9') ||
               (ch == '_');
      }
Referenced by FixedStrings().
isSpaceChar_()
bool anonymous_namespace{Log.cpp}::LogCore::FixedStrings::isSpaceChar_ (unsigned char ch) inline private noexcept
Definition at line 1611 of file Log.cpp.
      {
        return ch == ' ' || ch == '\t' || ch == '\r' || ch == '\n';
      }
Referenced by FixedStrings().
Member Data Documentation
category_
char anonymous_namespace{Log.cpp}::LogCore::FixedStrings::category_[24] {} private
Definition at line 1607 of file Log.cpp.
{};
Referenced by FixedStrings(), appendCategoryTo_(), and appendCategoryTo_().
categoryLen_
uint16_t anonymous_namespace{Log.cpp}::LogCore::FixedStrings::categoryLen_ {0} private
Definition at line 1603 of file Log.cpp.
{0};
Referenced by FixedStrings(), appendCategoryTo_(), and appendCategoryTo_().
fileName_
char anonymous_namespace{Log.cpp}::LogCore::FixedStrings::fileName_[32] {} private
Definition at line 1608 of file Log.cpp.
{};
Referenced by FixedStrings(), appendFileNameTo_(), and appendFileNameTo_().
fileNameLen_
uint16_t anonymous_namespace{Log.cpp}::LogCore::FixedStrings::fileNameLen_ {0} private
Definition at line 1604 of file Log.cpp.
{0};
Referenced by FixedStrings(), appendFileNameTo_(), and appendFileNameTo_().
funcName_
char anonymous_namespace{Log.cpp}::LogCore::FixedStrings::funcName_[56] {} private
Definition at line 1609 of file Log.cpp.
{};
Referenced by FixedStrings(), appendFuncNameTo_(), and appendFuncNameTo_().
funcNameLen_
uint32_t anonymous_namespace{Log.cpp}::LogCore::FixedStrings::funcNameLen_ {0} private
Definition at line 1602 of file Log.cpp.
{0};
Referenced by FixedStrings(), appendFuncNameTo_(), and appendFuncNameTo_().
The documentation for this struct was generated from the following file:
Log.cpp