Main Project: npi::StageWindow::OpacityGuard Struct Reference
npi::StageWindow::OpacityGuard Struct Reference
Helper for StageWindow class. A RAII guard that restores a widget's window opacity on scope exit.
Public Member Functions
OpacityGuard (const OpacityGuard &)=delete
deleted copy constructor
OpacityGuard (OpacityGuard &&)=delete
deleted move constructor
OpacityGuard (QWidget *w)
Construct a guard for the given widget.
~OpacityGuard ()
Destructor; restores opacity if still active and the widget is alive.
OpacityGuard & operator= (const OpacityGuard &)=delete
deleted copy assignment
OpacityGuard & operator= (OpacityGuard &&)=delete
deleted move assignment
void release_ ()
Disable the guard so the destructor does not restore opacity.
Public Attributes
bool active_ {true}
Whether the guard is active.
QPointer< QWidget > guardedWid_
QPointer to the guarded widget (may become null if the widget is deleted).
Detailed Description
Helper for StageWindow class. A RAII guard that restores a widget's window opacity on scope exit.
Use when you temporarily set a target widget's opacity to 0.0 before an animation is fully wired. If control leaves the scope early (exception or early return) and the guard is still active, it restores the widget to full opacity (1.0) in the destructor. After the animation has been started and its own finished-handler will handle restoration, call release_() to disable the guard.
Note
The guard holds a QPointer to avoid dereferencing a deleted widget. If the widget is destroyed before scope exit, no action is taken.
Warning
Construct and use from the GUI thread only. The opacity change affects GUI state.
Definition at line 354 of file StageWindow.hpp.
Constructor & Destructor Documentation
OpacityGuard() [1/3]
npi::StageWindow::OpacityGuard::OpacityGuard (QWidget * w) inline explicit
Construct a guard for the given widget.
Parameters
w Pointer to the widget whose opacity should be restored on scope exit.
Postcondition
guardedWid_ points to w; active_ is true.
Definition at line 371 of file StageWindow.hpp.
: guardedWid_{w} {}
References guardedWid_.
Referenced by OpacityGuard(), OpacityGuard(), operator=(), and operator=().
~OpacityGuard()
npi::StageWindow::OpacityGuard::~OpacityGuard () inline
Destructor; restores opacity if still active and the widget is alive.
If active_ is true and guardedWid_ is non-null, sets guardedWid_->setWindowOpacity(1.0). If the widget was deleted during the guarded scope, guardedWid_ is null and no action is taken.
Definition at line 377 of file StageWindow.hpp.
      {
        if(active_ && !guardedWid_.isNull())
          guardedWid_->setWindowOpacity(1.0);
      }
References active_, and guardedWid_.
OpacityGuard() [2/3]
npi::StageWindow::OpacityGuard::OpacityGuard (const OpacityGuard &) delete
deleted copy constructor
References OpacityGuard().
OpacityGuard() [3/3]
npi::StageWindow::OpacityGuard::OpacityGuard (OpacityGuard &&) delete
deleted move constructor
References OpacityGuard().
Member Function Documentation
operator=() [1/2]
OpacityGuard & npi::StageWindow::OpacityGuard::operator= (const OpacityGuard &) delete
deleted copy assignment
References OpacityGuard().
operator=() [2/2]
OpacityGuard & npi::StageWindow::OpacityGuard::operator= (OpacityGuard &&) delete
deleted move assignment
References OpacityGuard().
release_()
void npi::StageWindow::OpacityGuard::release_ () inline
Disable the guard so the destructor does not restore opacity.
Call this after you have successfully started your animation and arranged for normal restoration (e.g., in the animation's finished handler).
Postcondition
active_ is false; the destructor will not modify widget opacity.
Definition at line 388 of file StageWindow.hpp.
{ active_ = false; }
References active_.
Member Data Documentation
active_
bool npi::StageWindow::OpacityGuard::active_ {true}
Whether the guard is active.
If true at destruction time and the widget pointer is valid, the guard will restore opacity to 1.0. Calling release_() sets this to false to make the destructor a no-op regarding opacity restoration.
Definition at line 366 of file StageWindow.hpp.
{true};
Referenced by ~OpacityGuard(), and release_().
guardedWid_
QPointer<QWidget> npi::StageWindow::OpacityGuard::guardedWid_
QPointer to the guarded widget (may become null if the widget is deleted).
QPointer auto-nullifies on QObject destruction, preventing use-after-free in the destructor when attempting to restore opacity.
Definition at line 359 of file StageWindow.hpp.
Referenced by OpacityGuard(), and ~OpacityGuard().
The documentation for this struct was generated from the following file:
StageWindow.hpp