Main Project: npi::LinkFromThis< T > Class Template Reference
npi::LinkFromThis< T > Class Template Reference
Enables objects that inherits from this class to produce a Link object referencing themselves if the object is wrapped in a LinkHost.
#include <Link.hpp>
Public Member Functions
LinkFromThis () noexcept=default
Default constructor.
LinkFromThis (const LinkFromThis &other) noexcept=default
Default copy constructor.
LinkFromThis (LinkFromThis &&other) noexcept=default
Default move constructor.
~LinkFromThis () noexcept=default
Default destructor.
bool isLinkFromThisAvailable_ () const noexcept
Check whether a Link can be obtained from this object i.e. if the object is wrapped in a LinkHost.
Link< T > linkFromThis_ () const noexcept
Create a Link to this object if still alive and is wrapped in a LinkHost.
LinkFromThis & operator= (const LinkFromThis &other) noexcept=default
Default copy assignment operator.
LinkFromThis & operator= (LinkFromThis &&other) noexcept=default
Default move assignment operator.
void swap_ (LinkFromThis &other) noexcept
Member swap function.
Private Attributes
std::weak_ptr< typename LinkHost< T >::Obs > weakUni_
Weak pointer to the uni_ in LinkHost.
Friends
template<typename U>
class LinkHost
Friend declarations of LinkHost class.
void swap (LinkFromThis &a, LinkFromThis &b) noexcept
Friend swap to exchange two LinkFromThis instances.
Detailed Description
template<typename T>
class npi::LinkFromThis< T >
Enables objects that inherits from this class to produce a Link object referencing themselves if the object is wrapped in a LinkHost.
Behaves like a std::enable_shared_from_this but for LinkHost.
Stores a weak reference to the universal observer in the LinkHost.
Provides a way to obtain a Link object to itself using the universal observer if the LinkHost object is still alive.
Template Parameters
T The type of the object being wrapped in LinkHost and supporting enable-from-this semantics.
Note
This class only holds a weak reference to the universal observer in the LinkHost. This means that as long as any LinkHost object is alive, the LinkFromThis object will be able to create a Link object to itself and that Link object will be valid as long as the LinkHost object is alive.
Example of using LinkFromThis:
struct MyClass : LinkFromThis<MyClass> {
  void hello() {}
};
auto host = LinkHost<MyClass>(new MyClass());
auto link = host.universal_()->linkFromThis_();
if(link) link->hello();
Definition at line 1171 of file Link.hpp.
Constructor & Destructor Documentation
LinkFromThis() [1/3]
template<typename T> npi::LinkFromThis< T >::LinkFromThis () default noexcept
Default constructor.
Referenced by LinkFromThis(), LinkFromThis(), ~LinkFromThis(), operator=(), operator=(), swap, and swap_().
LinkFromThis() [2/3]
template<typename T> npi::LinkFromThis< T >::LinkFromThis (const LinkFromThis< T > & other) default noexcept
Default copy constructor.
References LinkFromThis().
LinkFromThis() [3/3]
template<typename T> npi::LinkFromThis< T >::LinkFromThis (LinkFromThis< T > && other) default noexcept
Default move constructor.
References LinkFromThis().
~LinkFromThis()
template<typename T> npi::LinkFromThis< T >::~LinkFromThis () default noexcept
Default destructor.
References LinkFromThis().
Member Function Documentation
isLinkFromThisAvailable_()
template<typename T> bool npi::LinkFromThis< T >::isLinkFromThisAvailable_ () const inline noexcept
Check whether a Link can be obtained from this object i.e. if the object is wrapped in a LinkHost.
Returns
true if the universal observer has not expired and the object is wrapped in a LinkHost.
Definition at line 1203 of file Link.hpp.
{ return weakUni_.expired() == false; }
References weakUni_.
linkFromThis_()
template<typename T> Link< T > npi::LinkFromThis< T >::linkFromThis_ () const inline noexcept
Create a Link to this object if still alive and is wrapped in a LinkHost.
Returns
A valid Link if the universal observer exists, otherwise an empty Link.
Attempts to lock the weak universal observer and returns a Link pointing to the stored ptr.
Definition at line 1194 of file Link.hpp.
    {
      if(auto uni = weakUni_.lock())
        return Link<T>{uni->ptr_};
      return Link<T>{nullptr};
    }
References linkFromThis_(), and weakUni_.
Referenced by linkFromThis_().
operator=() [1/2]
template<typename T> LinkFromThis & npi::LinkFromThis< T >::operator= (const LinkFromThis< T > & other) default noexcept
Default copy assignment operator.
References LinkFromThis().
operator=() [2/2]
template<typename T> LinkFromThis & npi::LinkFromThis< T >::operator= (LinkFromThis< T > && other) default noexcept
Default move assignment operator.
References LinkFromThis().
swap_()
template<typename T> void npi::LinkFromThis< T >::swap_ (LinkFromThis< T > & other) inline noexcept
Member swap function.
Parameters
other The LinkFromThis object to swap with.
Definition at line 1216 of file Link.hpp.
    {
      using std::swap;
      swap(*this, other);
    }
References LinkFromThis(), and swap.
Friends And Related Symbol Documentation
LinkHost
template<typename T> template<typename U> friend class LinkHost friend
Friend declarations of LinkHost class.
Definition at line 1224 of file Link.hpp.
References LinkHost.
Referenced by LinkHost.
swap
template<typename T> void swap (LinkFromThis< T > & a, LinkFromThis< T > & b) friend
Friend swap to exchange two LinkFromThis instances.
Parameters
a First LinkFromThis object.
b Second LinkFromThis object.
Definition at line 1208 of file Link.hpp.
    {
      using std::swap;
      swap(a.weakUni_, b.weakUni_);
    }
References LinkFromThis(), and swap.
Referenced by swap, and swap_().
Member Data Documentation
weakUni_
template<typename T> std::weak_ptr<typename LinkHost<T>::Obs> npi::LinkFromThis< T >::weakUni_ mutable private
Weak pointer to the uni_ in LinkHost.
Definition at line 1227 of file Link.hpp.
Referenced by isLinkFromThisAvailable_(), and linkFromThis_().
The documentation for this class was generated from the following file:
Link.hpp