Main Project: npi::OrgMetaData Struct Reference
npi::OrgMetaData Struct Reference final
Organization metadata container.
#include <OrgMetaData.hpp>
Public Member Functions
OrgMetaData ()=delete
Default constructor deleted.
OrgMetaData (const OrgMetaData &)=delete
Copy constructor deleted.
OrgMetaData (OrgMetaData &&)=delete
Move constructor deleted.
~OrgMetaData ()=delete
Destructor deleted.
OrgMetaData & operator= (const OrgMetaData &)=delete
Copy assignment deleted.
OrgMetaData & operator= (OrgMetaData &&)=delete
Move assignment deleted.
Static Public Attributes
static constexpr QLatin1StringView Domain_ {"npielectronic.com"}
Organization domain name.
static constexpr QLatin1StringView Name_ {"npi electronic GmbH"}
Organization display name.
Detailed Description
Organization metadata container.
This struct holds static constexpr members that define metadata about the organization.
Note
This struct is non-instantiable and non-copyable.
Do not add any methods to this struct.
Only add organization related metadata as static constexpr members.
Definition at line 32 of file OrgMetaData.hpp.
Constructor & Destructor Documentation
OrgMetaData() [1/3]
npi::OrgMetaData::OrgMetaData () delete
Default constructor deleted.
Referenced by OrgMetaData(), OrgMetaData(), operator=(), and operator=().
OrgMetaData() [2/3]
npi::OrgMetaData::OrgMetaData (OrgMetaData &&) delete
Move constructor deleted.
References OrgMetaData().
OrgMetaData() [3/3]
npi::OrgMetaData::OrgMetaData (const OrgMetaData &) delete
Copy constructor deleted.
References OrgMetaData().
~OrgMetaData()
npi::OrgMetaData::~OrgMetaData () delete
Destructor deleted.
Member Function Documentation
operator=() [1/2]
OrgMetaData & npi::OrgMetaData::operator= (const OrgMetaData &) delete
Copy assignment deleted.
References OrgMetaData().
operator=() [2/2]
OrgMetaData & npi::OrgMetaData::operator= (OrgMetaData &&) delete
Move assignment deleted.
References OrgMetaData().
Member Data Documentation
Domain_
QLatin1StringView npi::OrgMetaData::Domain_ {"npielectronic.com"} inline static constexpr
Organization domain name.
Definition at line 41 of file OrgMetaData.hpp.
{"npielectronic.com"};  ///< Organization domain name
Name_
QLatin1StringView npi::OrgMetaData::Name_ {"npi electronic GmbH"} inline static constexpr
Organization display name.
Definition at line 40 of file OrgMetaData.hpp.
{"npi electronic GmbH"}; ///< Organization display name
Referenced by npi::app::orgProgramDataDir(), and npi::app::orgPublicDocumentsDir().
The documentation for this struct was generated from the following file:
OrgMetaData.hpp