Main Project: npi::RefPtrHost< T > Class Template Reference
npi::RefPtrHost< T > Class Template Reference
A thread-safe, owning host that manages an object of type T and notifies RefPtr objects upon destruction.
#include <RefPtrClasses.hpp>
Classes
struct Obs
Inner observer type holding a type-erased pointer to the object. Used to broadcast the lifetime of the main object to RefPtr objects.
Public Member Functions
RefPtrHost () noexcept=default
Default constructor.
RefPtrHost (const RefPtrHost &other) noexcept=default
Default copy constructor.
template<typename U>
requires PolymorphicallyRelated<T, U>
RefPtrHost (const RefPtrHost< U > &other)
Polymorphic converting copy constructor.
RefPtrHost (RefPtrHost &&other) noexcept=default
Default move constructor.
template<typename Deleter = std::default_delete<T>>
RefPtrHost (T *ptr, Deleter deleter=Deleter{})
Construct a RefPtrHost that owns a raw pointer with an optional custom deleter.
~RefPtrHost () noexcept=default
Default destructor.
RefPtrHost< T > duplicateWithNewLocal_ () const
Duplicate host with a new local observer.
T * get_ () const noexcept
Retrieve the raw pointer to the hosted object.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool isSame_ (const RefPtrHost< U > &other) const noexcept
Check whether two RefPtrHost instances refer to the same object and observers (universal and local). For checking just the object (without the local observer) use the equality operators.
bool isValid_ () const noexcept
Check whether the host owns an object.
RefPtr< T > local_ () const noexcept
Create a local RefPtr object tied to the local observer. This RefPtr object will remain valid as long as a copy of the local observer exists (copying the RefPtrHost object also copies the local observer).
operator bool () const noexcept
Explicit boolean conversion operator (e.g. if(refPtrHost){...}).
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const RefPtr< U > &other) const noexcept
Compare this RefPtrHost object to a RefPtr object for inequality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const RefPtrHost< U > &other) const noexcept
Compare this RefPtrHost object to another RefPtrHost object for inequality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const U *raw) const noexcept
Compare to raw pointer for inequality.
bool operator!= (std::nullptr_t) const noexcept
Inequality comparison with a null pointer.
T & operator* () const noexcept
Dereference operator to obtain a reference to the hosted object.
T * operator-> () const noexcept
Pointer-like access operator.
RefPtrHost & operator= (const RefPtrHost &other) noexcept=default
Default copy assignment operator.
template<typename U>
requires PolymorphicallyRelated<T, U>
RefPtrHost & operator= (const RefPtrHost< U > &other)
Polymorphic assignment operator.
RefPtrHost & operator= (RefPtrHost &&other) noexcept=default
Default move assignment operator.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const RefPtr< U > &other) const noexcept
Compare this RefPtrHost object to a RefPtr object for equality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const RefPtrHost< U > &other) const noexcept
Compare this RefPtrHost object to another RefPtrHost object for equality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const U *raw) const noexcept
Compare to raw pointer for equality.
bool operator== (std::nullptr_t) const noexcept
Compare the stored pointer to a null pointer.
std::shared_ptr< T > pureShared_ () const noexcept
Obtain the underlying std::shared_ptr<T> object. This object can be used as an independent shared pointer to the hosted object. Using this shared pointer will not affect the functionality of RefPtrHost or other RefPtr-Family classes.
void reset_ () noexcept
Reset the host, releasing the object and invalidating all links.
void swap_ (RefPtrHost &other) noexcept
Member swap.
RefPtr< T > universal_ () const noexcept
Create a universal RefPtr object tied to the universal observer. This RefPtr object will remain valid as long as the hosted object is alive.
RefPtrWeakHost< T > weakHost_ () const noexcept
Create a RefPtrWeakHost object i.e. weak reference to RefPtrHost. Similar to what std::weak_ptr does for std::shared_ptr. Will also hold a weak reference to the local observer in the RefPtrHost.
Private Member Functions
RefPtrHost (const std::shared_ptr< T > &obj, const std::shared_ptr< Obs > &uni, const std::shared_ptr< Obs > &loc) noexcept
Private constructor for duplicates with custom observers.
template<typename U>
requires PolymorphicallyRelated<T, U>
void assign_ (const RefPtrHost< U > &other)
Internal helper to assign from another polymorphically related RefPtrHost object.
Private Attributes
std::shared_ptr< Obs > loc_ {nullptr}
Local observer that is valid as long as the last local copy of RefPtrHost is alive.
std::shared_ptr< T > obj_ {nullptr}
The owned object of type T wrapped in a shared pointer.
std::shared_ptr< Obs > uni_ {nullptr}
Universal observer that is valid as long as the object is alive.
Friends
template<typename U>
class RefPtrHost
Friend declarations of RefPtrHost class with type as U. This makes any RefPtrHost class object a friend of any other RefPtrHost class object.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const U *raw, const RefPtrHost< T > &refPtrHost) noexcept
Compare raw pointer (lhs) to a RefPtrHost object for inequality.
bool operator!= (std::nullptr_t, const RefPtrHost< T > &refPtrHost) noexcept
Inequality comparison between a null pointer and the stored pointer.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const U *raw, const RefPtrHost< T > &refPtrHost) noexcept
Compare raw pointer (lhs) to a RefPtrHost object for equality.
bool operator== (std::nullptr_t, const RefPtrHost< T > &refPtrHost) noexcept
Compare a null pointer to the stored pointer.
template<typename U>
class RefPtr
Friend declarations of RefPtr class.
template<typename U>
class RefPtrFromThis
Friend declarations of RefPtrFromThis class.
template<typename U>
class RefPtrWeakHost
Friend declarations of RefPtrWeakHost class.
void swap (RefPtrHost< T > &a, RefPtrHost< T > &b) noexcept
Swap two hosts.
Detailed Description
template<typename T>
class npi::RefPtrHost< T >
A thread-safe, owning host that manages an object of type T and notifies RefPtr objects upon destruction.
Behaves like a std::shared_ptr i.e. owns the object T and destroys it when the last reference is released.
Provides direct pointer-like access to the object.
Supports polymorphic conversion and comparison.
Maintains two RefPtr channels: Universal and Local.
RefPtr object obtained through Universal channel is valid while the object is alive.
RefPtr object obtained through Local channel is valid only while the last local copy of RefPtrHost is alive.
Template Parameters
T The type of the object being hosted.
Example of creating and using links:
RefPtrHost<MyClass> host(new MyClass());
auto refPtr = host.universal_();
if (refPtr) refPtr->doSomething_();
Definition at line 546 of file RefPtrClasses.hpp.
Constructor & Destructor Documentation
RefPtrHost() [1/6]
template<typename T> npi::RefPtrHost< T >::RefPtrHost () default noexcept
Default constructor.
RefPtrHost() [2/6]
template<typename T> npi::RefPtrHost< T >::RefPtrHost (const RefPtrHost< T > & other) default noexcept
Default copy constructor.
References RefPtrHost.
RefPtrHost() [3/6]
template<typename T> npi::RefPtrHost< T >::RefPtrHost (RefPtrHost< T > && other) default noexcept
Default move constructor.
References RefPtrHost.
~RefPtrHost()
template<typename T> npi::RefPtrHost< T >::~RefPtrHost () default noexcept
Default destructor.
References RefPtrHost.
RefPtrHost() [4/6]
template<typename T> template<typename Deleter = std::default_delete<T>> npi::RefPtrHost< T >::RefPtrHost (T * ptr, Deleter deleter = Deleter{}) inline explicit
Construct a RefPtrHost that owns a raw pointer with an optional custom deleter.
Template Parameters
Deleter The type of the deleter used to destroy the object.
Parameters
ptr The raw pointer to the object being hosted.
deleter The deleter to call when the object is destroyed.
Note
If T inherits from RefPtrFromThis<T>, sets up weakUni_ inside the object.
Stores ptr and deleter into obj_.
Creates both uni_ and loc_ observers pointing at the object.
If the object supports RefPtrFromThis, registers the universal observer inside it.
Definition at line 575 of file RefPtrClasses.hpp.
                                                                                                            {})
      : obj_{ptr, std::move(deleter)},
        uni_{std::make_shared<Obs>(ptr)},
        loc_{std::make_shared<Obs>(ptr)}
    {
      if constexpr(std::is_base_of_v<RefPtrFromThis<T>, T>)
        static_cast<RefPtrFromThis<T>*>(ptr)->weakUni_ = uni_;
    }
References RefPtrHost.
RefPtrHost() [5/6]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> npi::RefPtrHost< T >::RefPtrHost (const RefPtrHost< U > & other) inline
Polymorphic converting copy constructor.
Template Parameters
U The type of the other hosted object; must be polymorphically related to T.
Parameters
other The RefPtrHost instance to copy from.
Exceptions
std::bad_cast if a safe downcast from U to T fails.
Precondition
U must be polymorphically related to T.
Delegates to assign_() helper to perform casting and observer wiring.
Definition at line 592 of file RefPtrClasses.hpp.
{ assign_(other); }
References RefPtrHost, and assign_().
RefPtrHost() [6/6]
template<typename T> npi::RefPtrHost< T >::RefPtrHost (const std::shared_ptr< T > & obj, const std::shared_ptr< Obs > & uni, const std::shared_ptr< Obs > & loc) inline private noexcept
Private constructor for duplicates with custom observers.
Parameters
obj Shared ownership of the object.
uni Shared universal observer.
loc Shared local observer.
Definition at line 886 of file RefPtrClasses.hpp.
      : obj_{obj}, uni_{uni}, loc_{loc} {}
References obj_.
Member Function Documentation
assign_()
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> void npi::RefPtrHost< T >::assign_ (const RefPtrHost< U > & other) inline private
Internal helper to assign from another polymorphically related RefPtrHost object.
Template Parameters
U The type of object to assign from; must be polymorphically related to T.
Parameters
other The RefPtrHost object to copy from.
Exceptions
std::bad_cast if a safe downcast from U* to T* fails.
Precondition
U must be polymorphically related to T.
Note
Private function for internal use only.
If identical, return.
If other.get_() non-null:
Upcast via static_pointer_cast if U->T (i.e. if U is T or derived from T).
Otherwise downcast via dynamic_pointer_cast, throwing std::bad_cast on failure.
Copy uni_ and loc_.
Update weakUni_ if applicable.
Else reset obj_, uni_, and loc_ to empty (using reset_()).
Definition at line 907 of file RefPtrClasses.hpp.
    {
      // Skip assignment if the pointers are the same (isSame_() also checks the loc_ pointer)
      if(isSame_(other))
        return;
      if(auto raw = other.get_(); raw) {
        std::shared_ptr<T> obj;
        if constexpr(std::is_same_v<T, U> || std::is_base_of_v<T, U>) {
          // Upcast: If T and U are the same or T is a base of U.
          // Use static_pointer_cast since it is safe to use here.
          obj = std::static_pointer_cast<T>(other.obj_);
        }
        else {
          // Downcast: If T is not a base of U, use dynamic_pointer_cast to ensure safe downcasting.
          // The use of dynamic_pointer_cast requires U to be polymorphic.
          // Throw std::bad_cast if the cast fails.
          static_assert(std::is_polymorphic_v<U>, "U must be polymorphic for dynamic_cast");
          obj = std::dynamic_pointer_cast<T>(other.obj_);
          if(!obj)
            throw std::bad_cast();
        }
        // Assign the new object and observers
        obj_ = std::move(obj);
        uni_ = other.uni_;
        loc_ = other.loc_;
        // Update the weakUni_ pointer if applicable
        if constexpr(std::is_base_of_v<RefPtrFromThis<T>, T>) {
          if(auto* refPtrFromThis = static_cast<RefPtrFromThis<T>*>(obj_.get()))
            refPtrFromThis->weakUni_ = uni_;
        }
      }
      else {
        // If the raw pointer is null, reset the shared pointers to null.
        reset_();
      }
    }
References RefPtrHost, get_(), isSame_(), loc_, obj_, RefPtrFromThis, reset_(), and uni_.
Referenced by RefPtrHost(), and operator=().
duplicateWithNewLocal_()
template<typename T> RefPtrHost< T > npi::RefPtrHost< T >::duplicateWithNewLocal_ () const inline
Duplicate host with a new local observer.
Returns
A new RefPtrHost with a new local observer while sharing the same object.
Definition at line 702 of file RefPtrClasses.hpp.
{ return RefPtrHost<T>{obj_, uni_, std::make_shared<Obs>(obj_.get())}; }
References RefPtrHost, obj_, and uni_.
get_()
template<typename T> T * npi::RefPtrHost< T >::get_ () const inline nodiscard noexcept
Retrieve the raw pointer to the hosted object.
Returns
A pointer to T or nullptr if empty.
Note
This method is noexcept and [[nodiscard]].
Definition at line 626 of file RefPtrClasses.hpp.
{ return obj_.get(); }
References obj_.
Referenced by assign_(), isValid_(), operator!=(), operator*(), operator->(), operator==(), operator==(), operator==(), and operator==().
isSame_()
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::RefPtrHost< T >::isSame_ (const RefPtrHost< U > & other) const inline noexcept
Check whether two RefPtrHost instances refer to the same object and observers (universal and local). For checking just the object (without the local observer) use the equality operators.
Template Parameters
U The type of the other hosted object; must be polymorphically related to T.
Parameters
other The RefPtrHost to compare against.
Returns
true if both host the same object and observers (universal and local).
Definition at line 616 of file RefPtrClasses.hpp.
    {
      return obj_.get() == other.obj_.get()
             && uni_.get() == other.uni_.get()
             && loc_.get() == other.loc_.get();
    }
References RefPtrHost, loc_, obj_, and uni_.
Referenced by assign_().
isValid_()
template<typename T> bool npi::RefPtrHost< T >::isValid_ () const inline noexcept
Check whether the host owns an object.
Returns
true if non-null, false otherwise.
Definition at line 652 of file RefPtrClasses.hpp.
{ return get_() != nullptr; }
References get_().
Referenced by operator bool().
local_()
template<typename T> RefPtr< T > npi::RefPtrHost< T >::local_ () const inline nodiscard noexcept
Create a local RefPtr object tied to the local observer. This RefPtr object will remain valid as long as a copy of the local observer exists (copying the RefPtrHost object also copies the local observer).
Returns
A RefPtr object that is valid as long as the local observer is alive.
Definition at line 693 of file RefPtrClasses.hpp.
{ return RefPtr<T>{loc_ ? loc_->ptr_ : nullptr}; }
References loc_, and RefPtr.
operator bool()
template<typename T> npi::RefPtrHost< T >::operator bool () const inline explicit noexcept
Explicit boolean conversion operator (e.g. if(refPtrHost){...}).
Returns
true if valid, false if empty.
Definition at line 656 of file RefPtrClasses.hpp.
{ return isValid_(); }
References isValid_().
operator!=() [1/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::RefPtrHost< T >::operator!= (const RefPtr< U > & other) const inline noexcept
Compare this RefPtrHost object to a RefPtr object for inequality.
Template Parameters
U Polymorphically related type.
Parameters
other The RefPtr object to compare.
Returns
true if underlying pointers do not match.
Definition at line 797 of file RefPtrClasses.hpp.
{ return !(*this == other); }
References RefPtr.
operator!=() [2/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::RefPtrHost< T >::operator!= (const RefPtrHost< U > & other) const inline noexcept
Compare this RefPtrHost object to another RefPtrHost object for inequality.
Template Parameters
U Polymorphically related type.
Parameters
other The RefPtrHost object to compare.
Returns
true if underlying pointers do not match.
Definition at line 813 of file RefPtrClasses.hpp.
{ return !(*this == other); }
References RefPtrHost.
operator!=() [3/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::RefPtrHost< T >::operator!= (const U * raw) const inline noexcept
Compare to raw pointer for inequality.
Template Parameters
U Polymorphically related type.
Parameters
raw Raw pointer to compare.
Returns
true if not pointing to the same object.
Definition at line 763 of file RefPtrClasses.hpp.
{ return !(*this == raw); }
operator!=() [4/4]
template<typename T> bool npi::RefPtrHost< T >::operator!= (std::nullptr_t) const inline noexcept
Inequality comparison with a null pointer.
Returns
true if the stored pointer is not null, false otherwise.
Definition at line 728 of file RefPtrClasses.hpp.
    {
      return get_() != nullptr;
    }
References get_().
operator*()
template<typename T> T & npi::RefPtrHost< T >::operator* () const inline nodiscard noexcept
Dereference operator to obtain a reference to the hosted object.
Returns
A reference to T.
Precondition
get_() must not return nullptr.
Warning
Dereferencing a null pointer is undefined behavior.
Definition at line 643 of file RefPtrClasses.hpp.
    {
      auto ptr = get_();
      assert(ptr && "RefPtrHost::operator* on nullptr");
      return *ptr;
    }
References get_().
operator->()
template<typename T> T * npi::RefPtrHost< T >::operator-> () const inline nodiscard noexcept
Pointer-like access operator.
Returns
A non-null T* suitable for member access.
Precondition
get_() must not return nullptr.
Warning
Dereferencing a null pointer is undefined behavior.
Definition at line 632 of file RefPtrClasses.hpp.
    {
      auto ptr = get_();
      assert(ptr && "RefPtrHost::operator-> on nullptr");
      return ptr;
    }
References get_().
operator=() [1/3]
template<typename T> RefPtrHost & npi::RefPtrHost< T >::operator= (const RefPtrHost< T > & other) default noexcept
Default copy assignment operator.
References RefPtrHost.
operator=() [2/3]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> RefPtrHost & npi::RefPtrHost< T >::operator= (const RefPtrHost< U > & other) inline
Polymorphic assignment operator.
Template Parameters
U The type of the other hosted object; must be polymorphically related to T.
Parameters
other The RefPtrHost instance to assign from.
Exceptions
std::bad_cast if a safe downcast from U to T fails.
Precondition
U must be polymorphically related to T.
Returns
A reference to this RefPtrHost.
Uses assign_() helper for casting and observer wiring.
Definition at line 603 of file RefPtrClasses.hpp.
    {
      assign_(other);
      return *this;
    }
References RefPtrHost, and assign_().
operator=() [3/3]
template<typename T> RefPtrHost & npi::RefPtrHost< T >::operator= (RefPtrHost< T > && other) default noexcept
Default move assignment operator.
References RefPtrHost.
operator==() [1/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::RefPtrHost< T >::operator== (const RefPtr< U > & other) const inline noexcept
Compare this RefPtrHost object to a RefPtr object for equality.
Template Parameters
U Polymorphically related type.
Parameters
other The RefPtr object to compare.
Returns
true if underlying pointers match.
Definition at line 789 of file RefPtrClasses.hpp.
{ return get_() == other.get_(); }
References get_(), and RefPtr.
operator==() [2/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::RefPtrHost< T >::operator== (const RefPtrHost< U > & other) const inline noexcept
Compare this RefPtrHost object to another RefPtrHost object for equality.
Template Parameters
U Polymorphically related type.
Parameters
other The RefPtrHost object to compare.
Returns
true if underlying pointers match.
Definition at line 805 of file RefPtrClasses.hpp.
{ return get_() == other.get_(); }
References RefPtrHost, and get_().
operator==() [3/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::RefPtrHost< T >::operator== (const U * raw) const inline noexcept
Compare to raw pointer for equality.
Template Parameters
U Polymorphically related type.
Parameters
raw Raw pointer to compare.
Returns
true if pointing to the same object.
Definition at line 755 of file RefPtrClasses.hpp.
{ return get_() == raw; }
References get_().
operator==() [4/4]
template<typename T> bool npi::RefPtrHost< T >::operator== (std::nullptr_t) const inline noexcept
Compare the stored pointer to a null pointer.
Returns
true if the stored pointer is null, false otherwise.
Definition at line 721 of file RefPtrClasses.hpp.
    {
      return get_() == nullptr;
    }
References get_().
pureShared_()
template<typename T> std::shared_ptr< T > npi::RefPtrHost< T >::pureShared_ () const inline noexcept
Obtain the underlying std::shared_ptr<T> object. This object can be used as an independent shared pointer to the hosted object. Using this shared pointer will not affect the functionality of RefPtrHost or other RefPtr-Family classes.
Returns
A shared pointer to the hosted object.
Note
Using the std::shared_ptr<T> obtained from this method does not in any way affect the RefPtrHost or other RefPtr-Family classes.
Definition at line 717 of file RefPtrClasses.hpp.
{ return obj_; }
References obj_.
reset_()
template<typename T> void npi::RefPtrHost< T >::reset_ () inline noexcept
Reset the host, releasing the object and invalidating all links.
Calls reset() on loc_, uni_, and obj_ to release the object and observers.
Note
calls reset in reverse order to avoid any destructor issues
Definition at line 661 of file RefPtrClasses.hpp.
    {
      // call reset in reverse order only
      loc_.reset();
      uni_.reset();
      obj_.reset();
    }
References loc_, obj_, and uni_.
Referenced by assign_().
swap_()
template<typename T> void npi::RefPtrHost< T >::swap_ (RefPtrHost< T > & other) inline noexcept
Member swap.
Parameters
other RefPtrHost to swap with.
Definition at line 683 of file RefPtrClasses.hpp.
    {
      using std::swap;
      swap(*this, other);
    }
References RefPtrHost, and swap.
universal_()
template<typename T> RefPtr< T > npi::RefPtrHost< T >::universal_ () const inline nodiscard noexcept
Create a universal RefPtr object tied to the universal observer. This RefPtr object will remain valid as long as the hosted object is alive.
Returns
A RefPtr object that is valid as long as the hosted object is alive.
Definition at line 698 of file RefPtrClasses.hpp.
{ return RefPtr<T>{uni_ ? uni_->ptr_ : nullptr}; }
References RefPtr, and uni_.
weakHost_()
template<typename T> RefPtrWeakHost< T > npi::RefPtrHost< T >::weakHost_ () const inline noexcept
Create a RefPtrWeakHost object i.e. weak reference to RefPtrHost. Similar to what std::weak_ptr does for std::shared_ptr. Will also hold a weak reference to the local observer in the RefPtrHost.
Returns
A RefPtrWeakHost object that can be locked to get a copy of this RefPtrHost.
Definition at line 708 of file RefPtrClasses.hpp.
{ return RefPtrWeakHost<T>{*this}; }
References RefPtrWeakHost.
Friends And Related Symbol Documentation
RefPtrHost
template<typename T> template<typename U> friend class RefPtrHost friend
Friend declarations of RefPtrHost class with type as U. This makes any RefPtrHost class object a friend of any other RefPtrHost class object.
Definition at line 821 of file RefPtrClasses.hpp.
References RefPtrHost.
Referenced by RefPtrHost(), RefPtrHost(), RefPtrHost(), RefPtrHost(), RefPtrHost, ~RefPtrHost(), assign_(), duplicateWithNewLocal_(), isSame_(), operator!=(), operator!=, operator!=, operator=(), operator=(), operator=(), operator==(), operator==, operator==, swap, and swap_().
operator!= [1/2]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool operator!= (const U * raw, const RefPtrHost< T > & refPtrHost) friend
Compare raw pointer (lhs) to a RefPtrHost object for inequality.
Template Parameters
U Polymorphically related type.
Parameters
raw Raw pointer.
refPtrHost The RefPtrHost object to compare.
Returns
true if both refPtrHost and raw do not point to the same object.
Definition at line 781 of file RefPtrClasses.hpp.
{ return !(refPtrHost == raw); }
References RefPtrHost.
operator!= [2/2]
template<typename T> bool operator!= (std::nullptr_t , const RefPtrHost< T > & refPtrHost) friend
Inequality comparison between a null pointer and the stored pointer.
Parameters
refPtrHost A RefPtrHost object instance.
Returns
true if the stored pointer is not null, false otherwise.
Definition at line 744 of file RefPtrClasses.hpp.
    {
      return refPtrHost.get_() != nullptr;
    }
References RefPtrHost.
operator== [1/2]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool operator== (const U * raw, const RefPtrHost< T > & refPtrHost) friend
Compare raw pointer (lhs) to a RefPtrHost object for equality.
Template Parameters
U Polymorphically related type.
Parameters
raw Raw pointer.
refPtrHost The RefPtrHost object to compare.
Returns
true if both refPtrHost and raw point to the same object.
Definition at line 772 of file RefPtrClasses.hpp.
{ return refPtrHost.get_() == raw; }
References RefPtrHost.
operator== [2/2]
template<typename T> bool operator== (std::nullptr_t , const RefPtrHost< T > & refPtrHost) friend
Compare a null pointer to the stored pointer.
Parameters
refPtrHost A RefPtrHost object instance.
Returns
true if the stored pointer is null, false otherwise.
Definition at line 736 of file RefPtrClasses.hpp.
    {
      return refPtrHost.get_() == nullptr;
    }
References RefPtrHost.
RefPtr
template<typename T> template<typename U> friend class RefPtr friend
Friend declarations of RefPtr class.
Definition at line 817 of file RefPtrClasses.hpp.
References RefPtr.
Referenced by local_(), operator!=(), operator==(), RefPtr, and universal_().
RefPtrFromThis
template<typename T> template<typename U> friend class RefPtrFromThis friend
Friend declarations of RefPtrFromThis class.
Definition at line 827 of file RefPtrClasses.hpp.
References RefPtrFromThis.
Referenced by assign_(), and RefPtrFromThis.
RefPtrWeakHost
template<typename T> template<typename U> friend class RefPtrWeakHost friend
Friend declarations of RefPtrWeakHost class.
Definition at line 824 of file RefPtrClasses.hpp.
References RefPtrWeakHost.
Referenced by RefPtrWeakHost, and weakHost_().
swap
template<typename T> void swap (RefPtrHost< T > & a, RefPtrHost< T > & b) friend
Swap two hosts.
Parameters
a First host.
b Second host.
Swaps obj_, uni_, and loc_.
Definition at line 673 of file RefPtrClasses.hpp.
    {
      using std::swap;
      swap(a.obj_, b.obj_);
      swap(a.uni_, b.uni_);
      swap(a.loc_, b.loc_);
    }
References RefPtrHost, and swap.
Referenced by swap, and swap_().
Member Data Documentation
loc_
template<typename T> std::shared_ptr<Obs> npi::RefPtrHost< T >::loc_ {nullptr} private
Local observer that is valid as long as the last local copy of RefPtrHost is alive.
Definition at line 880 of file RefPtrClasses.hpp.
{nullptr};
Referenced by assign_(), isSame_(), local_(), and reset_().
obj_
template<typename T> std::shared_ptr<T> npi::RefPtrHost< T >::obj_ {nullptr} private
The owned object of type T wrapped in a shared pointer.
Definition at line 874 of file RefPtrClasses.hpp.
{nullptr};
Referenced by RefPtrHost(), assign_(), duplicateWithNewLocal_(), get_(), isSame_(), pureShared_(), and reset_().
uni_
template<typename T> std::shared_ptr<Obs> npi::RefPtrHost< T >::uni_ {nullptr} private
Universal observer that is valid as long as the object is alive.
Definition at line 877 of file RefPtrClasses.hpp.
{nullptr};
Referenced by assign_(), duplicateWithNewLocal_(), isSame_(), reset_(), and universal_().
The documentation for this class was generated from the following file:
RefPtrClasses.hpp