Main Project: npi::RefPtrWeakHost< T > Class Template Reference
npi::RefPtrWeakHost< T > Class Template Reference
A non-owning weak host that references a RefPtrHost managed object and its observers including local observer.
#include <RefPtrClasses.hpp>
Public Member Functions
RefPtrWeakHost () noexcept=default
Default constructor.
RefPtrWeakHost (const RefPtrHost< T > &refPtrHost) noexcept
Construct a RefPtrWeakHost from a RefPtrHost.
RefPtrWeakHost (const RefPtrWeakHost &other) noexcept=default
Default copy constructor.
RefPtrWeakHost (RefPtrWeakHost &&other) noexcept=default
Default move constructor.
~RefPtrWeakHost () noexcept=default
Default destructor.
bool expired_ () const noexcept
Check if the weak reference is expired.
bool isValid_ () const noexcept
Check if the weak host still references a live object.
RefPtrHost< T > lock_ () const noexcept
This function attempts to create a new RefPtrHost object from this RefPtrWeakHost object if the underlying object is still alive. This method calls lock() on the weak pointers to obtain the shared pointers to the object T as well as universal and local observers from which it was created. If any of the lock() fails the returned RefPtrHost object will be empty.
operator bool () const noexcept
Explicit boolean conversion operator.
RefPtrWeakHost & operator= (const RefPtrHost< T > &refPtrHost) noexcept
Assign a RefPtrHost to this RefPtrWeakHost.
RefPtrWeakHost & operator= (const RefPtrWeakHost &other) noexcept=default
Default copy assignment operator.
RefPtrWeakHost & operator= (RefPtrWeakHost &&other) noexcept=default
Default move assignment operator.
void reset_ () noexcept
Reset all weak references.
void swap_ (RefPtrWeakHost &other) noexcept
Member swap function.
Private Attributes
std::weak_ptr< typename RefPtrHost< T >::Obs > weakLoc_
Weak pointer to the loc_ in RefPtrHost.
std::weak_ptr< T > weakObj_
Weak pointer to the obj_ in RefPtrHost.
std::weak_ptr< typename RefPtrHost< T >::Obs > weakUni_
Weak pointer to the uni_ in RefPtrHost.
Friends
void swap (RefPtrWeakHost< T > &a, RefPtrWeakHost< T > &b) noexcept
Friend swap to exchange two RefPtrWeakHost instances.
Detailed Description
template<typename T>
class npi::RefPtrWeakHost< T >
A non-owning weak host that references a RefPtrHost managed object and its observers including local observer.
Behaves like a std::weak_ptr i.e. holds a weak reference to the object and observers.
Allows lock() to temporarily acquire a strong RefPtrHost if the object is still alive.
Provides polymorphic comparisons.
Template Parameters
T The type of the object being weakly hosted. T must be wrapped in RefPtrHost.
Note
RefPtrWeakHost also contains a weak reference to the local observer in the RefPtrHost. This means that if the local observer is destroyed, the RefPtrWeakHost will not be able to create a valid RefPtrHost object using its lock_() method and will return true for expired_().
Example of using LinkWeakHost:
RefPtrHost<MyClass> host(new MyClass());
RefPtrWeakHost<MyClass> weak(host);
if (auto locked = weak.lock_()) {
  locked->doSomething_();
}
Definition at line 973 of file RefPtrClasses.hpp.
Constructor & Destructor Documentation
RefPtrWeakHost() [1/4]
template<typename T> npi::RefPtrWeakHost< T >::RefPtrWeakHost () default noexcept
Default constructor.
Referenced by RefPtrWeakHost(), RefPtrWeakHost(), RefPtrWeakHost(), ~RefPtrWeakHost(), operator=(), operator=(), operator=(), swap, and swap_().
RefPtrWeakHost() [2/4]
template<typename T> npi::RefPtrWeakHost< T >::RefPtrWeakHost (const RefPtrWeakHost< T > & other) default noexcept
Default copy constructor.
References RefPtrWeakHost().
RefPtrWeakHost() [3/4]
template<typename T> npi::RefPtrWeakHost< T >::RefPtrWeakHost (RefPtrWeakHost< T > && other) default noexcept
Default move constructor.
References RefPtrWeakHost().
~RefPtrWeakHost()
template<typename T> npi::RefPtrWeakHost< T >::~RefPtrWeakHost () default noexcept
Default destructor.
References RefPtrWeakHost().
RefPtrWeakHost() [4/4]
template<typename T> npi::RefPtrWeakHost< T >::RefPtrWeakHost (const RefPtrHost< T > & refPtrHost) inline noexcept
Construct a RefPtrWeakHost from a RefPtrHost.
Parameters
refPtrHost The RefPtrHost instance to reference.
Stores std::weak_ptr for the std::shared_ptr for object T and Obs observers in the RefPtrHost object. This allows RefPtrWeakHost to act as a weak reference to the RefPtrHost object and its observers.
Definition at line 998 of file RefPtrClasses.hpp.
    {
      weakObj_ = refPtrHost.obj_;
      weakUni_ = refPtrHost.uni_;
      weakLoc_ = refPtrHost.loc_;
    }
References RefPtrWeakHost(), weakLoc_, weakObj_, and weakUni_.
Member Function Documentation
expired_()
template<typename T> bool npi::RefPtrWeakHost< T >::expired_ () const inline noexcept
Check if the weak reference is expired.
Returns
true if the weak reference is expired, false otherwise.
Definition at line 1043 of file RefPtrClasses.hpp.
    {
      return weakObj_.expired() || weakUni_.expired() || weakLoc_.expired();
    }
References weakLoc_, weakObj_, and weakUni_.
Referenced by isValid_(), and operator bool().
isValid_()
template<typename T> bool npi::RefPtrWeakHost< T >::isValid_ () const inline nodiscard noexcept
Check if the weak host still references a live object.
Returns
true if all the weak references are valid, false otherwise.
Definition at line 1050 of file RefPtrClasses.hpp.
{ return !expired_(); }
References expired_().
lock_()
template<typename T> RefPtrHost< T > npi::RefPtrWeakHost< T >::lock_ () const inline noexcept
This function attempts to create a new RefPtrHost object from this RefPtrWeakHost object if the underlying object is still alive. This method calls lock() on the weak pointers to obtain the shared pointers to the object T as well as universal and local observers from which it was created. If any of the lock() fails the returned RefPtrHost object will be empty.
Returns
A RefPtrHost object that is an exact copy of the RefPtrHost object from which this RefPtrWeakHost was created. If the object is no longer alive, the returned object will be empty.
Note
Locking only succeeds if all the three std::shared_ptr: obj_, uni_, and loc_ inside the RefPtrHost object are still alive.
Definition at line 1029 of file RefPtrClasses.hpp.
    {
      if(auto obj = weakObj_.lock()) {
        if(auto uni = weakUni_.lock()) {
          if(auto loc = weakLoc_.lock()) {
            return RefPtrHost<T>{obj, uni, loc};
          }
        }
      }
      return {}; // Return an empty RefPtrHost if any of the weak pointers are expired
    }
References weakLoc_, weakObj_, and weakUni_.
operator bool()
template<typename T> npi::RefPtrWeakHost< T >::operator bool () const inline explicit noexcept
Explicit boolean conversion operator.
Returns
true if the weak host is valid, false otherwise.
Definition at line 1054 of file RefPtrClasses.hpp.
{ return !expired_(); }
References expired_().
operator=() [1/3]
template<typename T> RefPtrWeakHost & npi::RefPtrWeakHost< T >::operator= (const RefPtrHost< T > & refPtrHost) inline noexcept
Assign a RefPtrHost to this RefPtrWeakHost.
Parameters
refPtrHost The RefPtrHost instance to assign.
Returns
A reference to this RefPtrWeakHost object.
This method resets the current std::weak_ptr inside this RefPtrWeakHost to the RefPtrHost object passed in. This allows the RefPtrWeakHost to hold a reference to the RefPtrHost object and its observers.
Definition at line 1011 of file RefPtrClasses.hpp.
    {
      weakObj_ = refPtrHost.obj_;
      weakUni_ = refPtrHost.uni_;
      weakLoc_ = refPtrHost.loc_;
      return *this;
    }
References RefPtrWeakHost(), weakLoc_, weakObj_, and weakUni_.
operator=() [2/3]
template<typename T> RefPtrWeakHost & npi::RefPtrWeakHost< T >::operator= (const RefPtrWeakHost< T > & other) default noexcept
Default copy assignment operator.
References RefPtrWeakHost().
operator=() [3/3]
template<typename T> RefPtrWeakHost & npi::RefPtrWeakHost< T >::operator= (RefPtrWeakHost< T > && other) default noexcept
Default move assignment operator.
References RefPtrWeakHost().
reset_()
template<typename T> void npi::RefPtrWeakHost< T >::reset_ () inline noexcept
Reset all weak references.
Resets the std::weak_ptr to obj_, uni_, and loc_.
Definition at line 1058 of file RefPtrClasses.hpp.
    {
      weakLoc_.reset();
      weakUni_.reset();
      weakObj_.reset();
    }
References weakLoc_, weakObj_, and weakUni_.
swap_()
template<typename T> void npi::RefPtrWeakHost< T >::swap_ (RefPtrWeakHost< T > & other) inline noexcept
Member swap function.
Parameters
other The RefPtrWeakHost object to swap with.
Definition at line 1079 of file RefPtrClasses.hpp.
    {
      using std::swap;
      swap(*this, other);
    }
References RefPtrWeakHost(), and swap.
Friends And Related Symbol Documentation
swap
template<typename T> void swap (RefPtrWeakHost< T > & a, RefPtrWeakHost< T > & b) friend
Friend swap to exchange two RefPtrWeakHost instances.
Parameters
a The first RefPtrWeakHost.
b The second RefPtrWeakHost.
Swaps weak references for object and observers.
Definition at line 1069 of file RefPtrClasses.hpp.
    {
      using std::swap;
      swap(a.weakObj_, b.weakObj_);
      swap(a.weakUni_, b.weakUni_);
      swap(a.weakLoc_, b.weakLoc_);
    }
References RefPtrWeakHost(), and swap.
Referenced by swap, and swap_().
Member Data Documentation
weakLoc_
template<typename T> std::weak_ptr<typename RefPtrHost<T>::Obs> npi::RefPtrWeakHost< T >::weakLoc_ private
Weak pointer to the loc_ in RefPtrHost.
Definition at line 1093 of file RefPtrClasses.hpp.
Referenced by RefPtrWeakHost(), expired_(), lock_(), operator=(), and reset_().
weakObj_
template<typename T> std::weak_ptr<T> npi::RefPtrWeakHost< T >::weakObj_ private
Weak pointer to the obj_ in RefPtrHost.
Definition at line 1087 of file RefPtrClasses.hpp.
Referenced by RefPtrWeakHost(), expired_(), lock_(), operator=(), and reset_().
weakUni_
template<typename T> std::weak_ptr<typename RefPtrHost<T>::Obs> npi::RefPtrWeakHost< T >::weakUni_ private
Weak pointer to the uni_ in RefPtrHost.
Definition at line 1090 of file RefPtrClasses.hpp.
Referenced by RefPtrWeakHost(), expired_(), lock_(), operator=(), and reset_().
The documentation for this class was generated from the following file:
RefPtrClasses.hpp