Main Project: npi::GuiProps Struct Reference
npi::GuiProps Struct Reference final
Scope-only container for GUI property keys.
#include <GuiProps.hpp>
Public Member Functions
GuiProps ()=delete
Default constructor deleted.
GuiProps (const GuiProps &)=delete
Copy constructor deleted.
GuiProps (GuiProps &&)=delete
Move constructor deleted.
~GuiProps ()=delete
Destructor deleted.
GuiProps & operator= (const GuiProps &)=delete
Copy assignment deleted.
GuiProps & operator= (GuiProps &&)=delete
Move assignment deleted.
Static Public Attributes
static constexpr char BackgroundColor_ [] = "BackgroundColor"
Marks a property as background color.
static constexpr char CancelButton_ [] = "CancelButton"
Marks a button as the standard Cancel button.
static constexpr char ColorDisplayWidget_ [] = "ColorDisplayWidget"
Marks a QWidget as a color display widget.
static constexpr char FixedWidthFontWidget_ [] = "FixedWidthFontWidget"
Marks a QWidget to use a fixed-width font.
static constexpr char GroupButton_ [] = "GroupButton"
Marks a button as part of a button group.
static constexpr char GroupLeftButton_ [] = "GroupLeftButton"
Marks a button as the left button in a button group.
static constexpr char GroupRightButton_ [] = "GroupRightButton"
Marks a button as the right button in a button group.
static constexpr char HeightNoResize_ [] = "HeightNoResize"
Disables vertical resizing.
static constexpr char IconName_ [] = "IconName"
Name of the icon resource.
static constexpr char IconNoResize_ [] = "IconNoResize"
Disables icon resizing.
static constexpr char IconOnName_ [] = "IconOnName"
Name of the icon resource when active.
static constexpr char ItemWidget_ [] = "ItemWidget"
Marks a QWidget as a table, etc. item widget.
static constexpr char OkButton_ [] = "OkButton"
Marks a button as the standard OK button.
static constexpr char PasswordLineEdit_ [] = "PasswordLineEdit"
Marks a QLineEdit as password field.
static constexpr char PushButtonRightIcon_ [] = "PushButtonRightIcon"
Marks a QPushButton to have its icon on the right side.
static constexpr char PushButtonWidthNoChange_ [] = "PushButtonWidthNoChange"
Disables width changes on QPushButton.
static constexpr char TransparentForMouseWheel_ [] = "TransparentForMouseWheel"
Passes mouse wheel events to underlying widgets.
Detailed Description
Scope-only container for GUI property keys.
GuiProps provides a closed set of GUI-related dynamic property names for use with QObject. The type cannot be constructed, copied, moved, or destroyed. Only the static members are intended to be used. All keys are ASCII-only and stable by contract so they can be relied upon by styles, delegates, and other UI infrastructure without string duplication or translation.
Invariants:
No instances of GuiProps exist at runtime.
All keys are null-terminated and suitable for QObject::setProperty().
Keys are intended to be read-only and never modified.
Extension policy:
Add new keys as additional static members in this type to keep a single source of truth and predictable auto-complete. If third-party modules must contribute keys without editing this file, prefer a namespace container.
Definition at line 50 of file GuiProps.hpp.
Constructor & Destructor Documentation
GuiProps() [1/3]
npi::GuiProps::GuiProps () delete
Default constructor deleted.
Referenced by GuiProps(), GuiProps(), operator=(), and operator=().
GuiProps() [2/3]
npi::GuiProps::GuiProps (GuiProps &&) delete
Move constructor deleted.
References GuiProps().
GuiProps() [3/3]
npi::GuiProps::GuiProps (const GuiProps &) delete
Copy constructor deleted.
References GuiProps().
~GuiProps()
npi::GuiProps::~GuiProps () delete
Destructor deleted.
Member Function Documentation
operator=() [1/2]
GuiProps & npi::GuiProps::operator= (const GuiProps &) delete
Copy assignment deleted.
References GuiProps().
operator=() [2/2]
GuiProps & npi::GuiProps::operator= (GuiProps &&) delete
Move assignment deleted.
References GuiProps().
Member Data Documentation
BackgroundColor_
char npi::GuiProps::BackgroundColor_[] = "BackgroundColor" inline static constexpr
Marks a property as background color.
Definition at line 73 of file GuiProps.hpp.
CancelButton_
char npi::GuiProps::CancelButton_[] = "CancelButton" inline static constexpr
Marks a button as the standard Cancel button.
Definition at line 67 of file GuiProps.hpp.
ColorDisplayWidget_
char npi::GuiProps::ColorDisplayWidget_[] = "ColorDisplayWidget" inline static constexpr
Marks a QWidget as a color display widget.
Definition at line 72 of file GuiProps.hpp.
FixedWidthFontWidget_
char npi::GuiProps::FixedWidthFontWidget_[] = "FixedWidthFontWidget" inline static constexpr
Marks a QWidget to use a fixed-width font.
Definition at line 74 of file GuiProps.hpp.
Referenced by npi::TextSpec::SetFixFont_().
GroupButton_
char npi::GuiProps::GroupButton_[] = "GroupButton" inline static constexpr
Marks a button as part of a button group.
Definition at line 69 of file GuiProps.hpp.
GroupLeftButton_
char npi::GuiProps::GroupLeftButton_[] = "GroupLeftButton" inline static constexpr
Marks a button as the left button in a button group.
Definition at line 71 of file GuiProps.hpp.
GroupRightButton_
char npi::GuiProps::GroupRightButton_[] = "GroupRightButton" inline static constexpr
Marks a button as the right button in a button group.
Definition at line 70 of file GuiProps.hpp.
HeightNoResize_
char npi::GuiProps::HeightNoResize_[] = "HeightNoResize" inline static constexpr
Disables vertical resizing.
Definition at line 61 of file GuiProps.hpp.
IconName_
char npi::GuiProps::IconName_[] = "IconName" inline static constexpr
Name of the icon resource.
Definition at line 59 of file GuiProps.hpp.
IconNoResize_
char npi::GuiProps::IconNoResize_[] = "IconNoResize" inline static constexpr
Disables icon resizing.
Definition at line 62 of file GuiProps.hpp.
IconOnName_
char npi::GuiProps::IconOnName_[] = "IconOnName" inline static constexpr
Name of the icon resource when active.
Definition at line 60 of file GuiProps.hpp.
ItemWidget_
char npi::GuiProps::ItemWidget_[] = "ItemWidget" inline static constexpr
Marks a QWidget as a table, etc. item widget.
Definition at line 65 of file GuiProps.hpp.
OkButton_
char npi::GuiProps::OkButton_[] = "OkButton" inline static constexpr
Marks a button as the standard OK button.
Definition at line 66 of file GuiProps.hpp.
PasswordLineEdit_
char npi::GuiProps::PasswordLineEdit_[] = "PasswordLineEdit" inline static constexpr
Marks a QLineEdit as password field.
Definition at line 63 of file GuiProps.hpp.
PushButtonRightIcon_
char npi::GuiProps::PushButtonRightIcon_[] = "PushButtonRightIcon" inline static constexpr
Marks a QPushButton to have its icon on the right side.
Definition at line 68 of file GuiProps.hpp.
PushButtonWidthNoChange_
char npi::GuiProps::PushButtonWidthNoChange_[] = "PushButtonWidthNoChange" inline static constexpr
Disables width changes on QPushButton.
Definition at line 64 of file GuiProps.hpp.
TransparentForMouseWheel_
char npi::GuiProps::TransparentForMouseWheel_[] = "TransparentForMouseWheel" inline static constexpr
Passes mouse wheel events to underlying widgets.
Definition at line 58 of file GuiProps.hpp.
The documentation for this struct was generated from the following file:
GuiProps.hpp