Main Project: npi::LinkWeakHost< T > Class Template Reference
npi::LinkWeakHost< T > Class Template Reference
A non-owning weak host that references a LinkHost-managed object and its observers including local observer.
#include <Link.hpp>
Public Member Functions
LinkWeakHost () noexcept=default
Default constructor.
LinkWeakHost (const LinkHost< T > &linkHost) noexcept
Construct a LinkWeakHost from a LinkHost.
LinkWeakHost (const LinkWeakHost &other) noexcept=default
Default copy constructor.
LinkWeakHost (LinkWeakHost &&other) noexcept=default
Default move constructor.
~LinkWeakHost () noexcept=default
Default destructor.
bool expired_ () const noexcept
Check if the weak reference is expired.
bool isValid_ () const noexcept
Check if the weak host still references a live object.
LinkHost< T > lock_ () const noexcept
This function attempts to create a new LinkHost object from this LinkWeakHost object if the underlying object is still alive. This method calls lock() on the weak pointers to obtain the shared pointers to the object T as well as universal and local observers from which it was created. If any of the lock() fails the returned LinkHost object will be empty.
operator bool () const noexcept
Explicit boolean conversion operator.
LinkWeakHost & operator= (const LinkHost< T > &linkHost) noexcept
Assign a LinkHost to this LinkWeakHost.
LinkWeakHost & operator= (const LinkWeakHost &other) noexcept=default
Default copy assignment operator.
LinkWeakHost & operator= (LinkWeakHost &&other) noexcept=default
Default move assignment operator.
void reset_ () noexcept
Reset all weak references.
void swap_ (LinkWeakHost &other) noexcept
Member swap function.
Private Attributes
std::weak_ptr< typename LinkHost< T >::Obs > weakLoc_
Weak pointer to the loc_ in LinkHost.
std::weak_ptr< T > weakObj_
Weak pointer to the obj_ in LinkHost.
std::weak_ptr< typename LinkHost< T >::Obs > weakUni_
Weak pointer to the uni_ in LinkHost.
Friends
void swap (LinkWeakHost< T > &a, LinkWeakHost< T > &b) noexcept
Friend swap to exchange two LinkWeakHost instances.
Detailed Description
template<typename T>
class npi::LinkWeakHost< T >
A non-owning weak host that references a LinkHost-managed object and its observers including local observer.
Behaves like a std::weak_ptr i.e. holds a weak reference to the object and observers.
Allows lock() to temporarily acquire a strong LinkHost if the object is still alive.
Provides polymorphic comparisons.
Template Parameters
T The type of the object being weakly hosted. T must be wrapped in LinkHost.
Note
LinkWeakHost also contains a weak reference to the local observer in the LinkHost. This means that if the local observer is destroyed, the LinkWeakHost will not be able to create a valid LinkHost object using its lock_() method and will return true for expired_().
Example of using LinkWeakHost:
LinkHost<MyClass> host(new MyClass());
LinkWeakHost<MyClass> weak(host);
if (auto locked = weak.lock_()) {
  locked->doSomething_();
}
Definition at line 962 of file Link.hpp.
Constructor & Destructor Documentation
LinkWeakHost() [1/4]
template<typename T> npi::LinkWeakHost< T >::LinkWeakHost () default noexcept
Default constructor.
Referenced by LinkWeakHost(), LinkWeakHost(), LinkWeakHost(), ~LinkWeakHost(), operator=(), operator=(), operator=(), swap, and swap_().
LinkWeakHost() [2/4]
template<typename T> npi::LinkWeakHost< T >::LinkWeakHost (const LinkWeakHost< T > & other) default noexcept
Default copy constructor.
References LinkWeakHost().
LinkWeakHost() [3/4]
template<typename T> npi::LinkWeakHost< T >::LinkWeakHost (LinkWeakHost< T > && other) default noexcept
Default move constructor.
References LinkWeakHost().
~LinkWeakHost()
template<typename T> npi::LinkWeakHost< T >::~LinkWeakHost () default noexcept
Default destructor.
References LinkWeakHost().
LinkWeakHost() [4/4]
template<typename T> npi::LinkWeakHost< T >::LinkWeakHost (const LinkHost< T > & linkHost) inline noexcept
Construct a LinkWeakHost from a LinkHost.
Parameters
linkHost The LinkHost instance to reference.
Stores std::weak_ptr for the std::shared_ptr for object T and Obs observers in the LinkHost object. This allows LinkWeakHost to act as a weak reference to the LinkHost object and its observers.
Definition at line 987 of file Link.hpp.
{
      weakObj_ = linkHost.obj_;
      weakUni_ = linkHost.uni_;
      weakLoc_ = linkHost.loc_;
    }
References LinkWeakHost(), weakLoc_, weakObj_, and weakUni_.
Member Function Documentation
expired_()
template<typename T> bool npi::LinkWeakHost< T >::expired_ () const inline noexcept
Check if the weak reference is expired.
Returns
true if the weak reference is expired, false otherwise.
Definition at line 1029 of file Link.hpp.
{
      return weakObj_.expired() || weakUni_.expired() || weakLoc_.expired();
    }
References weakLoc_, weakObj_, and weakUni_.
Referenced by isValid_(), and operator bool().
isValid_()
template<typename T> bool npi::LinkWeakHost< T >::isValid_ () const inline nodiscard noexcept
Check if the weak host still references a live object.
Returns
true if all the weak references are valid, false otherwise.
Definition at line 1035 of file Link.hpp.
{ return !expired_(); }
References expired_().
lock_()
template<typename T> LinkHost< T > npi::LinkWeakHost< T >::lock_ () const inline noexcept
This function attempts to create a new LinkHost object from this LinkWeakHost object if the underlying object is still alive. This method calls lock() on the weak pointers to obtain the shared pointers to the object T as well as universal and local observers from which it was created. If any of the lock() fails the returned LinkHost object will be empty.
Returns
A LinkHost object that is an exact copy of the LinkHost object from which this LinkWeakHost was created. If the object is no longer alive, the returned object will be empty.
Note
Locking only succeeds if all the three std::shared_ptr: obj_, uni_, and loc_ inside the LinkHost object are still alive.
Definition at line 1016 of file Link.hpp.
{
      if(auto obj = weakObj_.lock()) {
        if(auto uni = weakUni_.lock()) {
          if(auto loc = weakLoc_.lock()) {
            return LinkHost<T>{obj, uni, loc};
          }
        }
      }
      return {}; // Return an empty LinkHost if any of the weak pointers are expired
    }
References weakLoc_, weakObj_, and weakUni_.
operator bool()
template<typename T> npi::LinkWeakHost< T >::operator bool () const inline explicit noexcept
Explicit boolean conversion operator.
Returns
true if the weak host is valid, false otherwise.
Definition at line 1039 of file Link.hpp.
{ return !expired_(); }
References expired_().
operator=() [1/3]
template<typename T> LinkWeakHost & npi::LinkWeakHost< T >::operator= (const LinkHost< T > & linkHost) inline noexcept
Assign a LinkHost to this LinkWeakHost.
Parameters
linkHost The LinkHost instance to assign.
Returns
A reference to this LinkWeakHost object.
This method resets the current std::weak_ptr inside this LinkWeakHost to the LinkHost object passed in. This allows the LinkWeakHost to hold a reference to the LinkHost object and its observers.
Definition at line 999 of file Link.hpp.
{
      weakObj_ = linkHost.obj_;
      weakUni_ = linkHost.uni_;
      weakLoc_ = linkHost.loc_;
      return *this;
    }
References LinkWeakHost(), weakLoc_, weakObj_, and weakUni_.
operator=() [2/3]
template<typename T> LinkWeakHost & npi::LinkWeakHost< T >::operator= (const LinkWeakHost< T > & other) default noexcept
Default copy assignment operator.
References LinkWeakHost().
operator=() [3/3]
template<typename T> LinkWeakHost & npi::LinkWeakHost< T >::operator= (LinkWeakHost< T > && other) default noexcept
Default move assignment operator.
References LinkWeakHost().
reset_()
template<typename T> void npi::LinkWeakHost< T >::reset_ () inline noexcept
Reset all weak references.
Resets the std::weak_ptr to obj_, uni_, and loc_.
Definition at line 1043 of file Link.hpp.
{
      weakObj_.reset();
      weakUni_.reset();
      weakLoc_.reset();
    }
References weakLoc_, weakObj_, and weakUni_.
swap_()
template<typename T> void npi::LinkWeakHost< T >::swap_ (LinkWeakHost< T > & other) inline noexcept
Member swap function.
Parameters
other The LinkWeakHost object to swap with.
Definition at line 1062 of file Link.hpp.
{
      using std::swap;
      swap(*this, other);
    }
References LinkWeakHost(), and swap.
Friends And Related Symbol Documentation
swap
template<typename T> void swap (LinkWeakHost< T > & a, LinkWeakHost< T > & b) friend
Friend swap to exchange two LinkWeakHost instances.
Parameters
a The first LinkWeakHost.
b The second LinkWeakHost.
Swaps weak references for object and observers.
Definition at line 1053 of file Link.hpp.
{
      using std::swap;
      swap(a.weakObj_, b.weakObj_);
      swap(a.weakUni_, b.weakUni_);
      swap(a.weakLoc_, b.weakLoc_);
    }
References LinkWeakHost(), and swap.
Referenced by swap, and swap_().
Member Data Documentation
weakLoc_
template<typename T> std::weak_ptr<typename LinkHost<T>::Obs> npi::LinkWeakHost< T >::weakLoc_ private
Weak pointer to the loc_ in LinkHost.
Definition at line 1075 of file Link.hpp.
Referenced by LinkWeakHost(), expired_(), lock_(), operator=(), and reset_().
weakObj_
template<typename T> std::weak_ptr<T> npi::LinkWeakHost< T >::weakObj_ private
Weak pointer to the obj_ in LinkHost.
Definition at line 1069 of file Link.hpp.
Referenced by LinkWeakHost(), expired_(), lock_(), operator=(), and reset_().
weakUni_
template<typename T> std::weak_ptr<typename LinkHost<T>::Obs> npi::LinkWeakHost< T >::weakUni_ private
Weak pointer to the uni_ in LinkHost.
Definition at line 1072 of file Link.hpp.
Referenced by LinkWeakHost(), expired_(), lock_(), operator=(), and reset_().
The documentation for this class was generated from the following file:
Link.hpp