Main Project: MainWindow Class Reference
MainWindow Class Reference
#include <MainWindow.h>
Public Member Functions
MainWindow (QWidget *parent=nullptr)
~MainWindow ()
Private Slots
void on_cats_list_currentTextChanged (const QString &text)
void on_coloredConsole_chk_checkStateChanged (Qt::CheckState state)
void on_debugConsole_btn_clicked ()
void on_defDir_btn_clicked ()
void on_filterRulesApply_btn_clicked ()
void on_filterRulesClear_btn_clicked ()
void on_logFieldsApply_btn_clicked ()
void on_logFieldsDefault_btn_clicked ()
void on_maxSize_spin_valueChanged (int value)
void on_msgFieldsApply_btn_clicked ()
void on_msgFieldsDefault_btn_clicked ()
void on_muteDisp_chk_checkStateChanged (Qt::CheckState state)
void on_newDir_btn_clicked ()
void on_threadStart_btn_clicked ()
void on_writeMsg_txt_editingFinished ()
Private Attributes
QStringList logCats_
bool slotState_ {false}
Ui::ui_MainWindow ui
Detailed Description
Definition at line 43 of file MainWindow.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (QWidget * parent = nullptr)
Definition at line 96 of file MainWindow.cpp.
                                      : QWidget(parent)
{
  qCInfo(npi_MainWindow) << "MainWindow Constructor";
  qCInfo(npi_data) << "Data Category Log";
  qCInfo(npi_test) << "Test Category Log";
  ui.setupUi(this);
  logCats_ = npi::log::categories();
  ui.writeMsgCat_combo->addItems(logCats_);
  ui.cats_list->addItems(logCats_);
  ui.curDir_lbl->setText(npi::log::dir());
  ui.maxSize_spin->setValue(static_cast<int>(npi::log::getMaxFolderSizeMb()));
  ui.baseRules_txt->appendPlainText(npi::log::getFilterBaseRules().join('\n'));
  ui.filterRules_txt->appendPlainText(npi::log::getFilterRules().join("\n"));
  ui.availableFields_list->addItems(npi::log::availableFieldNames());
  ui.logFields_txt->appendPlainText(npi::log::getLogFields().join('\n'));
  ui.msgFields_txt->appendPlainText(npi::log::getMsgFields().join('\n'));
  ui.muteDisp_chk->setChecked(npi::log::isDisplayMuted());
  ui.coloredConsole_chk->setChecked(npi::log::isConsoleColored());
  if(npi::log::isConsolePermanent()) {
    ui.debugConsole_btn->setEnabled(false);
    ui.debugConsole_btn->setText("Auto Console");
  }
  else {
    if(npi::log::isConsoleOpen())
      ui.debugConsole_btn->setText("Close Console");
    else
      ui.debugConsole_btn->setText("Open Console");
  }
  slotState_ = true;
  test << "Main Window Constructor Done...";
  test << "FixedStrings: " << sizeof(FixedStrings);
  test << "OneLog: " << sizeof(OneLog);
}
References npi::log::availableFieldNames(), npi::log::categories(), npi::log::dir(), npi::log::getFilterBaseRules(), npi::log::getFilterRules(), npi::log::getLogFields(), npi::log::getMaxFolderSizeMb(), npi::log::getMsgFields(), npi::log::isConsoleColored(), npi::log::isConsoleOpen(), npi::log::isConsolePermanent(), npi::log::isDisplayMuted(), logCats_, slotState_, test, and ui.
~MainWindow()
MainWindow::~MainWindow ()
Definition at line 140 of file MainWindow.cpp.
{
  qCInfo(npi_MainWindow) << "MainWindow Destructor";
}
Member Function Documentation
on_cats_list_currentTextChanged
void MainWindow::on_cats_list_currentTextChanged (const QString & text) private slot
Definition at line 197 of file MainWindow.cpp.
{
  if(slotState_) {
    const auto saved = slotState_;
    slotState_ = false;
    const QByteArray catBytes = text.toUtf8();
    QLoggingCategory cat{catBytes.constData()};
    ui.debg_chk->setChecked(cat.isDebugEnabled());
    ui.info_chk->setChecked(cat.isInfoEnabled());
    ui.warn_chk->setChecked(cat.isWarningEnabled());
    ui.fail_chk->setChecked(cat.isCriticalEnabled());
    slotState_ = saved;
  }
}
References slotState_, and ui.
on_coloredConsole_chk_checkStateChanged
void MainWindow::on_coloredConsole_chk_checkStateChanged (Qt::CheckState state) private slot
Definition at line 322 of file MainWindow.cpp.
{
  if(slotState_) {
    const bool isChecked{state == Qt::Checked};
    npi::log::setColoredConsole(isChecked);
  }
}
References npi::log::setColoredConsole(), and slotState_.
on_debugConsole_btn_clicked
void MainWindow::on_debugConsole_btn_clicked () private slot
Definition at line 330 of file MainWindow.cpp.
{
  if(slotState_) {
    //benchClocks();
    if(npi::log::isConsoleOpen()) {
      npi::log::closeConsole();
      ui.debugConsole_btn->setText("Open Console");
    }
    else {
      npi::log::openConsole();
      ui.debugConsole_btn->setText("Close Console");
    }
  }
}
References npi::log::closeConsole(), npi::log::isConsoleOpen(), npi::log::openConsole(), slotState_, and ui.
on_defDir_btn_clicked
void MainWindow::on_defDir_btn_clicked () private slot
Definition at line 176 of file MainWindow.cpp.
{
  if(slotState_) {
    const auto saved = slotState_;
    slotState_ = false;
    ui.info_txt->appendPlainText(npi::log::restoreDefaultDir().message_);
    slotState_ = saved;
  }
}
References npi::log::restoreDefaultDir(), slotState_, and ui.
on_filterRulesApply_btn_clicked
void MainWindow::on_filterRulesApply_btn_clicked () private slot
Definition at line 224 of file MainWindow.cpp.
{
  if(slotState_) {
    const auto saved = slotState_;
    slotState_ = false;
    QStringList ruleList = ui.filterRules_txt->toPlainText().split('\n', Qt::SkipEmptyParts);
    for(auto& str : ruleList)
      str.remove(' ');
    bool temp = ui.filterRulesTemp_chk->isChecked();
    auto cleanList = npi::log::setFilterRules(ruleList, temp);
    ui.filterRules_txt->clear();
    ui.filterRules_txt->appendPlainText(cleanList.join('\n'));
    slotState_ = saved;
  }
}
References npi::log::setFilterRules(), slotState_, and ui.
on_filterRulesClear_btn_clicked
void MainWindow::on_filterRulesClear_btn_clicked () private slot
Definition at line 212 of file MainWindow.cpp.
{
  if(slotState_) {
    const auto saved = slotState_;
    slotState_ = false;
    bool temp = ui.filterRulesTemp_chk->isChecked();
    npi::log::clearFilterRules(temp);
    ui.filterRules_txt->clear();
    slotState_ = saved;
  }
}
References npi::log::clearFilterRules(), slotState_, and ui.
on_logFieldsApply_btn_clicked
void MainWindow::on_logFieldsApply_btn_clicked () private slot
Definition at line 252 of file MainWindow.cpp.
{
  if(slotState_) {
    const auto saved = slotState_;
    slotState_ = false;
    auto list = ui.logFields_txt->toPlainText().split('\n', Qt::SkipEmptyParts);
    const bool temp = ui.logFieldsTemp_chk->isChecked();
    ui.logFields_txt->clear();
    ui.logFields_txt->appendPlainText(npi::log::setLogFields(list, temp).join('\n'));
    slotState_ = saved;
  }
}
References npi::log::setLogFields(), slotState_, and ui.
on_logFieldsDefault_btn_clicked
void MainWindow::on_logFieldsDefault_btn_clicked () private slot
Definition at line 240 of file MainWindow.cpp.
{
  if(slotState_) {
    const auto saved = slotState_;
    slotState_ = false;
    const bool temp = ui.logFieldsTemp_chk->isChecked();
    ui.logFields_txt->clear();
    ui.logFields_txt->appendPlainText(npi::log::setDefaultLogFields(temp).join('\n'));
    slotState_ = saved;
  }
}
References npi::log::setDefaultLogFields(), slotState_, and ui.
on_maxSize_spin_valueChanged
void MainWindow::on_maxSize_spin_valueChanged (int value) private slot
Definition at line 170 of file MainWindow.cpp.
{
  if(slotState_)
    npi::log::setMaxFolderSizeMb(value);
}
References npi::log::setMaxFolderSizeMb(), and slotState_.
on_msgFieldsApply_btn_clicked
void MainWindow::on_msgFieldsApply_btn_clicked () private slot
Definition at line 277 of file MainWindow.cpp.
{
  if(slotState_) {
    const auto saved = slotState_;
    slotState_ = false;
    auto list = ui.msgFields_txt->toPlainText().split('\n', Qt::SkipEmptyParts);
    const bool temp = ui.msgFieldsTemp_chk->isChecked();
    ui.msgFields_txt->clear();
    ui.msgFields_txt->appendPlainText(npi::log::setMsgFields(list, temp).join('\n'));
    slotState_ = saved;
  }
}
References npi::log::setMsgFields(), slotState_, and ui.
on_msgFieldsDefault_btn_clicked
void MainWindow::on_msgFieldsDefault_btn_clicked () private slot
Definition at line 265 of file MainWindow.cpp.
{
  if(slotState_) {
    const auto saved = slotState_;
    slotState_ = false;
    const bool temp = ui.msgFieldsTemp_chk->isChecked();
    ui.msgFields_txt->clear();
    ui.msgFields_txt->appendPlainText(npi::log::setDefaultMsgFields(temp).join('\n'));
    slotState_ = saved;
  }
}
References npi::log::setDefaultMsgFields(), slotState_, and ui.
on_muteDisp_chk_checkStateChanged
void MainWindow::on_muteDisp_chk_checkStateChanged (Qt::CheckState state) private slot
Definition at line 314 of file MainWindow.cpp.
{
  if(slotState_) {
    const bool isChecked{state == Qt::Checked};
    npi::log::setMuteDisplay(isChecked);
  }
}
References npi::log::setMuteDisplay(), and slotState_.
on_newDir_btn_clicked
void MainWindow::on_newDir_btn_clicked () private slot
Definition at line 186 of file MainWindow.cpp.
{
  if(slotState_) {
    const auto saved = slotState_;
    slotState_ = false;
    const auto path = QFileDialog::getExistingDirectory(this, "New Log Directory", npi::log::dir());
    if(!path.isEmpty()) ui.info_txt->appendPlainText(npi::log::setDir(path).message_);
    slotState_ = saved;
  }
}
References npi::log::dir(), npi::log::setDir(), slotState_, and ui.
on_threadStart_btn_clicked
void MainWindow::on_threadStart_btn_clicked () private slot
Definition at line 290 of file MainWindow.cpp.
{
  if(slotState_) {
    static int counter{0};
    const auto saved = slotState_;
    slotState_ = false;
    for(int ii = 0; ii < 50; ++ii) {
      auto obj = new Thread;
      auto thread = new QThread;
      obj->moveToThread(thread);
      connect(thread, &QThread::started, obj, &Thread::start);
      //connect(qApp, &QApplication::aboutToQuit, qApp, [o = obj, t = thread]() {
      //  o->deleteLater();
      //  t->quit();
      //  t->wait();
      //});
      thread->start();
      ++counter;
    }
    ui.threadNum_lbl->setText(QStringLiteral("Thread Number: ").append(QString::number(++counter)));
    slotState_ = saved;
  }
}
References slotState_, Thread::start(), and ui.
on_writeMsg_txt_editingFinished
void MainWindow::on_writeMsg_txt_editingFinished () private slot
Definition at line 145 of file MainWindow.cpp.
{
  if(slotState_) {
    if(const QString text = ui.writeMsg_txt->text(); !text.isEmpty()) {
      QString catString{ui.writeMsgCat_combo->currentText()};
      const QByteArray catBytes = catString.toUtf8();
      QLoggingCategory cat{catBytes.constData()};
      const int idx = ui.writeMsgLvl_combo->currentIndex();
      //for(auto ii = 0; ii < 100; ++ii) {
        //std::this_thread::sleep_for(std::chrono::milliseconds(10));
        if(idx == 0)
          qCDebug(cat).noquote() << text;
        else if(idx == 1)
          qCInfo(cat).noquote() << text;
        else if(idx == 2)
          qCWarning(cat).noquote() << text;
        else if(idx == 3)
          qCCritical(cat).noquote() << text;
        else if(idx == 4)
          qCFatal(cat).noquote() << text;
      //}
    }
  }
}
References slotState_, and ui.
Member Data Documentation
logCats_
QStringList MainWindow::logCats_ private
Definition at line 52 of file MainWindow.h.
Referenced by MainWindow().
slotState_
bool MainWindow::slotState_ {false} private
Definition at line 53 of file MainWindow.h.
{false};
Referenced by MainWindow(), on_cats_list_currentTextChanged(), on_coloredConsole_chk_checkStateChanged(), on_debugConsole_btn_clicked(), on_defDir_btn_clicked(), on_filterRulesApply_btn_clicked(), on_filterRulesClear_btn_clicked(), on_logFieldsApply_btn_clicked(), on_logFieldsDefault_btn_clicked(), on_maxSize_spin_valueChanged(), on_msgFieldsApply_btn_clicked(), on_msgFieldsDefault_btn_clicked(), on_muteDisp_chk_checkStateChanged(), on_newDir_btn_clicked(), on_threadStart_btn_clicked(), and on_writeMsg_txt_editingFinished().
ui
Ui::ui_MainWindow MainWindow::ui private
Definition at line 51 of file MainWindow.h.
Referenced by MainWindow(), on_cats_list_currentTextChanged(), on_debugConsole_btn_clicked(), on_defDir_btn_clicked(), on_filterRulesApply_btn_clicked(), on_filterRulesClear_btn_clicked(), on_logFieldsApply_btn_clicked(), on_logFieldsDefault_btn_clicked(), on_msgFieldsApply_btn_clicked(), on_msgFieldsDefault_btn_clicked(), on_newDir_btn_clicked(), on_threadStart_btn_clicked(), and on_writeMsg_txt_editingFinished().
The documentation for this class was generated from the following files:
MainWindow.h
MainWindow.cpp