Main Project: npi::Props Struct Reference
npi::Props Struct Reference final
#include <PropsNew.hpp>
Public Member Functions
Props ()=delete
Props (const Props &&)=delete
Props (const Props &)=delete
~Props ()=delete
Props & operator= (const Props &&)=delete
Props & operator= (const Props &)=delete
Static Public Attributes
static constexpr char IconName_ [] = "IconName"
static constexpr char IconOnName_ [] = "IconOnName"
static constexpr char TransparentForMouseWheel_ [] = "TransparentForMouseWheel"
Detailed Description
Definition at line 5 of file PropsNew.hpp.
Constructor & Destructor Documentation
Props() [1/3]
npi::Props::Props () delete
Referenced by Props(), Props(), operator=(), and operator=().
Props() [2/3]
npi::Props::Props (const Props &) delete
References Props().
Props() [3/3]
npi::Props::Props (const Props &&) delete
References Props().
~Props()
npi::Props::~Props () delete
Member Function Documentation
operator=() [1/2]
Props & npi::Props::operator= (const Props &&) delete
References Props().
operator=() [2/2]
Props & npi::Props::operator= (const Props &) delete
References Props().
Member Data Documentation
IconName_
char npi::Props::IconName_[] = "IconName" static constexpr
Definition at line 13 of file PropsNew.hpp.
IconOnName_
char npi::Props::IconOnName_[] = "IconOnName" static constexpr
Definition at line 14 of file PropsNew.hpp.
TransparentForMouseWheel_
char npi::Props::TransparentForMouseWheel_[] = "TransparentForMouseWheel" static constexpr
Definition at line 15 of file PropsNew.hpp.
The documentation for this struct was generated from the following file:
PropsNew.hpp