Main Project: anonymous_namespace{Log.cpp}::LogCore Class Reference
anonymous_namespace{Log.cpp}::LogCore Class Reference final
Classes
struct FieldConfig
struct FixedStrings
struct InitialLog
struct OneLog
struct StartupSettings
struct UnitInfo
Public Member Functions
LogCore (const LogCore &)=delete
LogCore (LogCore &&)=delete
~LogCore ()=delete
void addLogCategory_ (const char *name)
void applyStartupFilterRules_ ()
void closeConsole_ ()
const QStringList & getAvailableFieldNames_ () const
QString getDir_ () const
QStringList getFields_ (const bool forLog)
bool getFieldTempState_ (const bool forLog)
QStringList getFilterRules_ ()
bool getFilterRulesTempState_ ()
QString getFutureDir_ ()
QStringList getLogCategories_ ()
qint64 getMaxFolderSizeMb_ ()
void initiateShutdown_ ()
bool isConsoleColored_ () const
bool isConsoleOpen_ () const
bool isDisplayMuted_ () const
bool isPermanentConsole_ () const
bool isWarnImp_ () const
void msgHandler_ (QtMsgType typ, const QMessageLogContext &ctx, const QString &msg)
bool openConsole_ ()
LogCore & operator= (const LogCore &)=delete
LogCore & operator= (LogCore &&)=delete
void setColoredConsole_ (const bool state)
npi::log::DirResult setDir_ (const QString &path={})
QStringList setFields_ (const bool forLog, const bool temp=false, const QStringList &list={})
QStringList setFilterRules_ (const bool temp=false, const QStringList &ruleList={})
qint64 setMaxFolderSizeMb_ (const qint64 size=-1)
void setMuteDisplay_ (const bool state)
void setWarnIsImp_ (bool state, bool temp=false)
void writeInitialLogs_ ()
Static Public Member Functions
static QStringList GetFilterBaseRules_ ()
static LogCore * Inst_ ()
Public Attributes
std::atomic< QLoggingCategory::CategoryFilter > prevLogFilter_ = nullptr
Private Types
enum class Field : quint8 {
DateTime , UpTime , ThreadTime , ThreadDelta ,
ThreadNumber , ThreadHexId , Level , Category ,
FileLine , Function
}
Private Member Functions
LogCore ()
bool getConsole_ ()
QString getCurrentDirFromSettings_ (QSettings &settings)
StartupSettings getStartupSettings_ ()
void insertLogMessage_ (QtMsgType typ, const QString &msg)
void saveSettings_ (const QLatin1StringView &view, const std::optional< QVariant > &var=std::nullopt) const
bool startDisplay_ ()
void startImpLogProcess_ ()
void startWriting_ ()
QList< Field > stringsToFields_ (const QStringList &strings) const
Static Private Member Functions
static void AppendChar_ (QByteArray &buf, const char *data, size_t len)
static void AppendChar_ (QString &buf, const char *data, size_t len)
template<typename BufferT>
static void AppendDateTime_ (BufferT &buffer, const std::chrono::system_clock::time_point &tp) noexcept
template<typename BufferT>
static void AppendDelta_ (BufferT &buf, const qint64 ns)
template<typename BufferT>
static void AppendLevel_ (BufferT &buf, const QtMsgType typ)
static void AppendStr_ (QByteArray &buf, const QString &s)
static void AppendStr_ (QString &buf, const QString &s)
static QString CheckAndValidateDir_ (const QString &path, QString *errorText)
static QStringList CleanedFilterRulesList_ (const QStringList &list)
static bool ComparePaths_ (const QString &a, const QString &b)
static void DirCleanup_ (QString dirPath, qint64 maxSize, QString lockName)
static QStringList FieldsToStrings_ (const QList< Field > &fields)
template<typename BufferT>
static void FormatOneLine_ (BufferT &buffer, const QList< Field > &fields, const OneLog &one)
Private Attributes
const QStringList availableFieldNames_
std::atomic_bool coloredConsole_ {false}
const QString configLockName_ {QStringLiteral("npi-") % npi::AppMetaData::Name_ % QLatin1StringView("-log-config-lock")}
std::atomic< qint64 > currentMaxMb_ {DefaultMaxFolderSizeMb_}
const QString defDir_
const QList< Field > defLogFields_
const QList< Field > defMsgFields_
const QString dirCleaningLockName_ {QStringLiteral("npi-") % npi::AppMetaData::Name_ % QLatin1StringView("-log-dir-cleaning-lock")}
moodycamel::ConcurrentQueue< OneLog > dispQueue_ {20480}
std::jthread dispThread_
std::atomic_bool dispThreadRunning_ {false}
const QHash< QString, Field > fieldHash_
const QString fileBaseName_
moodycamel::ConcurrentQueue< OneLog > fileQueue_ {20480}
std::jthread fileThread_
std::atomic_bool fileThreadRunning_ {false}
QStringList filterRules_
QReadWriteLock filterRulesLock_
bool filterRulesTempState_ {false}
QList< InitialLog > initialLogs_
std::mutex initialLogsMutex_
QStringList logCategories_
QReadWriteLock logCategoriesLock_
FieldConfig logConfig_
std::atomic< int64_t > maxMbLastChangeTime_ {0}
std::mutex maxMbSettingsMutex_
std::jthread maxMbThread_
std::condition_variable_any maxMbThreadWakeup_
FieldConfig msgConfig_
std::atomic_bool muteDisplay_ {false}
const bool permConsole_
std::atomic_bool runtimeLogs_ {false}
std::atomic_bool shutdownMode_ {false}
const std::chrono::steady_clock::time_point startTp_ = std::chrono::steady_clock::now()
const StartupSettings startup_
std::atomic_bool tempConsole_ {false}
std::atomic_uint64_t threadCounter_ {0}
std::atomic_bool warnIsImp_ {false}
Static Private Attributes
static constexpr QLatin1StringView BaseFilterRule_
static constexpr QLatin1StringView ConfigFileName_ {"log_config.ini"}
static constexpr QLatin1StringView DefaultDirName_ {"logs"}
static constexpr qint64 DefaultMaxFolderSizeMb_ {512}
static constexpr std::array< UnitInfo, 5 > DeltaUnits_
static constexpr std::chrono::milliseconds DrainInterval_ {100}
static constexpr std::chrono::milliseconds FlushInterval_ {500}
static constexpr QLatin1StringView SettingsColoredConsoleKey_ {"ColoredConsole"}
static constexpr QLatin1StringView SettingsDirKey_ {"CurrentDirectory"}
static constexpr QLatin1StringView SettingsFilterRulesKey_ {"FilterRules"}
static constexpr QLatin1StringView SettingsLogFieldsKey_ {"LogFields"}
static constexpr QLatin1StringView SettingsMaxFolderSizeKey_ {"MaxFolderSizeMB"}
static constexpr QLatin1StringView SettingsMsgFieldsKey_ {"MsgFields"}
static constexpr QLatin1StringView SettingsWarnIsImpKey_ {"WarnIsImp"}
Detailed Description
Definition at line 1008 of file Log.cpp.
Class Documentation
anonymous_namespace{Log.cpp}::LogCore::FieldConfig
struct anonymous_namespace{Log.cpp}::LogCore::FieldConfig
Definition at line 1812 of file Log.cpp.
Class Members
QList< Field > fields_
QReadWriteLock lock_
QStringList strings_
bool temp_ {false}
atomic_uint64_t version_ {0}
anonymous_namespace{Log.cpp}::LogCore::InitialLog
struct anonymous_namespace{Log.cpp}::LogCore::InitialLog
Definition at line 1799 of file Log.cpp.
Class Members
QtMsgType level_ {QtInfoMsg}
QString message_
anonymous_namespace{Log.cpp}::LogCore::OneLog
struct anonymous_namespace{Log.cpp}::LogCore::OneLog
Definition at line 1777 of file Log.cpp.
Class Members
time_point dateTime_ = std::chrono::system_clock::time_point::min()
int fileLine_ {-1}
FixedStrings fixedStrings_
QtMsgType level_ {QtInfoMsg}
QString message_
quint32 thread_ {0}
qint64 threadDelta_ {-1}
DWORD threadId_ {0}
qint64 threadTime_ {-1}
qint64 upTime_ {-1}
anonymous_namespace{Log.cpp}::LogCore::StartupSettings
struct anonymous_namespace{Log.cpp}::LogCore::StartupSettings
Definition at line 1804 of file Log.cpp.
Class Members
QString dir_
QStringList filterRules_
QStringList logFields_
qint64 maxFolderMb_
QStringList msgFields_
anonymous_namespace{Log.cpp}::LogCore::UnitInfo
struct anonymous_namespace{Log.cpp}::LogCore::UnitInfo
Definition at line 1470 of file Log.cpp.
Class Members
qint64 scale_
char suffix_
Member Enumeration Documentation
Field
enum class anonymous_namespace{Log.cpp}::LogCore::Field : quint8 strong private
Enumerator
DateTime
UpTime
ThreadTime
ThreadDelta
ThreadNumber
ThreadHexId
Level
Category
FileLine
Function
Definition at line 1487 of file Log.cpp.
                     : quint8 {
      DateTime,
      UpTime,
      ThreadTime,
      ThreadDelta,
      ThreadNumber,
      ThreadHexId,
      Level,
      Category,
      FileLine,
      Function
    };
Constructor & Destructor Documentation
LogCore() [1/3]
anonymous_namespace{Log.cpp}::LogCore::LogCore (const LogCore &) delete
References LogCore().
Referenced by LogCore(), LogCore(), Inst_(), operator=(), and operator=().
LogCore() [2/3]
anonymous_namespace{Log.cpp}::LogCore::LogCore (LogCore &&) delete
References LogCore().
~LogCore()
anonymous_namespace{Log.cpp}::LogCore::~LogCore () delete
LogCore() [3/3]
anonymous_namespace{Log.cpp}::LogCore::LogCore () inline private
Definition at line 1861 of file Log.cpp.
              : permConsole_{getConsole_()},
                defDir_{QDir::cleanPath(QDir(npi::app::appPublicDocumentsDir()).filePath(DefaultDirName_.toString()))},
                startup_{getStartupSettings_()},
                fileBaseName_{QDateTime::currentDateTime().toString("yyyyMMdd_HHmmsszzz")
                                                          .append(QStringLiteral("_P%1")
                                                                 .arg(static_cast<quint32>(::GetCurrentProcessId()),
                                                                    8, 16, QLatin1Char('0')).toUpper())}
    {
      startImpLogProcess_();
      currentMaxMb_.store(startup_.maxFolderMb_, std::memory_order_release);
      maxMbThread_ = std::jthread([this](std::stop_token st) {
        while(!st.stop_requested()) {
          std::unique_lock lock{maxMbSettingsMutex_};
          // Wait for change
          maxMbThreadWakeup_.wait(lock, st, [this] { return maxMbLastChangeTime_.load(std::memory_order_acquire) > 0; });
          if(st.stop_requested()) break;
          // Debounce Loop: We capture the timestamp we are waiting for
          int64_t lastChange = 0;
          while(true) {
            auto now = std::chrono::steady_clock::now().time_since_epoch();
            int64_t nowMs = std::chrono::duration_cast<std::chrono::milliseconds>(now).count();
            // Load current dirty time
            lastChange = maxMbLastChangeTime_.load(std::memory_order_acquire);
            int64_t diff = nowMs - lastChange;
            if(diff >= 100) break; // Settled
            lock.unlock();
            std::this_thread::sleep_for(std::chrono::milliseconds(100 - diff));
            lock.lock();
            if(st.stop_requested()) return;
          }
          lock.unlock();
          // --- SAVE START ---
          // We leave maxMbLastChangeTime_ > 0 here.
          // This ensures getMaxFolderSizeMb_() continues to use MEMORY (correct value)
          // while we are busy writing to disk.
          qint64 val = currentMaxMb_.load(std::memory_order_acquire);
          if(val == DefaultMaxFolderSizeMb_)
            saveSettings_(SettingsMaxFolderSizeKey_);
          else
            saveSettings_(SettingsMaxFolderSizeKey_, val);
          npiInfo << QStringLiteral("Settings saved: max folder size %1 MB.").arg(val);
          // --- SAVE END ---
          // NOW we mark as clean, but ONLY if the user hasn't typed again.
          // We try to swap 'lastChange' (the time we saved) with 0.
          // If maxMbLastChangeTime_ is different (user typed), this fails,
          // the loop repeats, and we debounce the new value.
          maxMbLastChangeTime_.compare_exchange_strong(lastChange, 0, std::memory_order_acq_rel);
        }
        // Final flush on stop
        // If compare_exchange failed above, lastChange is still > 0, so this catches it.
        if(maxMbLastChangeTime_.load(std::memory_order_acquire) > 0) {
          qint64 val = currentMaxMb_.load(std::memory_order_acquire);
          if(val == DefaultMaxFolderSizeMb_)
            saveSettings_(SettingsMaxFolderSizeKey_);
          else
            saveSettings_(SettingsMaxFolderSizeKey_, val);
          npiInfo << QStringLiteral("Settings saved: max folder size %1 MB.").arg(val);
        }
      });
      {
        auto fields = stringsToFields_(startup_.logFields_);
        if(fields.isEmpty()) fields = defLogFields_;
        const auto strings = FieldsToStrings_(fields);
        QWriteLocker locker{&logConfig_.lock_};
        logConfig_.fields_ = fields;
        logConfig_.strings_ = strings;
        logConfig_.temp_ = false;
      }
      {
        auto fields = stringsToFields_(startup_.msgFields_);
        if(fields.isEmpty()) fields = defMsgFields_;
        const auto strings = FieldsToStrings_(fields);
        QWriteLocker locker{&msgConfig_.lock_};
        msgConfig_.fields_ = fields;
        msgConfig_.strings_ = strings;
        msgConfig_.temp_ = false;
      }
      {
        QWriteLocker locker{&filterRulesLock_};
        filterRules_ = startup_.filterRules_;
        filterRulesTempState_ = false;
      }
      startWriting_();
      startDisplay_();
      std::thread([d = startup_.dir_, m = startup_.maxFolderMb_, l = dirCleaningLockName_]() mutable { DirCleanup_(d, m, l); }).detach();
      initialLogs_.append({
        .level_ = QtInfoMsg,
        .message_ = QStringLiteral("LogCore initialized successfully")
      });
    }
References currentMaxMb_, DefaultDirName_, DefaultMaxFolderSizeMb_, defDir_, defLogFields_, defMsgFields_, dirCleaningLockName_, FieldsToStrings_(), fileBaseName_, filterRules_, filterRulesLock_, filterRulesTempState_, getConsole_(), getStartupSettings_(), initialLogs_, logConfig_, maxMbLastChangeTime_, maxMbSettingsMutex_, maxMbThread_, maxMbThreadWakeup_, msgConfig_, npiInfo, permConsole_, saveSettings_(), SettingsMaxFolderSizeKey_, startDisplay_(), startImpLogProcess_(), startup_, startWriting_(), and stringsToFields_().
Member Function Documentation
addLogCategory_()
void anonymous_namespace{Log.cpp}::LogCore::addLogCategory_ (const char * name) inline
Definition at line 1233 of file Log.cpp.
    {
      if(name) {
        const QString cat{QString::fromLatin1(name)};
        QWriteLocker locker{&logCategoriesLock_};
        if(!logCategories_.contains(cat))
          logCategories_.append(cat);
      }
    }
References logCategories_, and logCategoriesLock_.
Referenced by anonymous_namespace{Log.cpp}::loggingCategoryFilter().
AppendChar_() [1/2]
void anonymous_namespace{Log.cpp}::LogCore::AppendChar_ (QByteArray & buf, const char * data, size_t len) inline static private
Definition at line 2783 of file Log.cpp.
{ buf.append(data, static_cast<qsizetype>(len)); }
Referenced by AppendDateTime_().
AppendChar_() [2/2]
void anonymous_namespace{Log.cpp}::LogCore::AppendChar_ (QString & buf, const char * data, size_t len) inline static private
Definition at line 2785 of file Log.cpp.
{ buf += QUtf8StringView(data, static_cast<qsizetype>(len)); }
AppendDateTime_()
template<typename BufferT> void anonymous_namespace{Log.cpp}::LogCore::AppendDateTime_ (BufferT & buffer, const std::chrono::system_clock::time_point & tp) inline static private noexcept
Definition at line 2788 of file Log.cpp.
    {
      // Handle invalid/empty/default time points
      if(tp == std::chrono::system_clock::time_point::min()) {
        AppendChar_(buffer, "----.--.-- --:--:--.---", 23);
        return;
      }
      // Floor to seconds and derive milliseconds from it
      const auto secTp = std::chrono::floor<std::chrono::seconds>(tp);
      const std::time_t sec = std::chrono::system_clock::to_time_t(secTp);
      // Thread local "cached" (holds "YYYY-MM-DD HH:MM:SS" + null = 20 bytes)
      thread_local bool haveCache = false;
      thread_local std::time_t lastSec = 0;
      thread_local char cached[20] = {}; // 19 + \0
      // Only update cache if the second has changed
      if(sec != lastSec || !haveCache) {
        std::tm bt{};
        // `localtime_s` returns 0 on success
        const int ok = ::localtime_s(&bt, &sec);
        // `std::snprintf` returns no. of characters written
        const int written = (ok == 0)
                              ? std::snprintf(cached, sizeof(cached),
                                "%04d.%02d.%02d %02d:%02d:%02d",
                                bt.tm_year + 1900, bt.tm_mon + 1, bt.tm_mday,
                                bt.tm_hour, bt.tm_min, bt.tm_sec)
                              : -1;
        // On error append zeros and return
        if(written != 19) {
          AppendChar_(buffer, "----.--.-- --:--:--.---", 23);
          return;
        }
        // On success update the thread local values
        lastSec = sec;
        haveCache = true;
      }
      // Append the cached date/time (19 chars)
      AppendChar_(buffer, cached, 19);
      // Get milliseconds from the time point and floored seconds
      qint64 msPart = std::chrono::duration_cast<std::chrono::milliseconds>(tp - secTp).count();
      if(msPart < 0) msPart = 0;       // defensive
      if(msPart > 999) msPart %= 1000; // defensive
      const int ms = static_cast<int>(msPart);
      // Append milliseconds
      char msBuf[4];
      msBuf[0] = '.';
      msBuf[1] = static_cast<char>('0' + (ms / 100));
      msBuf[2] = static_cast<char>('0' + ((ms / 10) % 10));
      msBuf[3] = static_cast<char>('0' + (ms % 10));
      AppendChar_(buffer, msBuf, 4);
    }
References AppendChar_().
Referenced by FormatOneLine_().
AppendDelta_()
template<typename BufferT> void anonymous_namespace{Log.cpp}::LogCore::AppendDelta_ (BufferT & buf, const qint64 ns) inline static private
Definition at line 2850 of file Log.cpp.
    {
      if(ns < 0) {
        buf.append("---.--");
        return;
      }
      qint64 val = 0;
      char suf = 'h';
      for(const auto& [scale, suffix] : DeltaUnits_) {
        val = (ns + (scale / 2)) / scale;
        suf = suffix;
        if(val < 10000) break;
      }
      // Ensures we never exceed "999.9" even for huge hours, preventing garbage chars.
      if(val > 9999) val = 9999;
      const qint64 iPart = val / 10; // 0..999
      const qint64 fPart = val % 10; // 0..9
      buf.append(static_cast<char>('0' + (iPart / 100)));       // Hundreds Digit
      buf.append(static_cast<char>('0' + ((iPart / 10) % 10))); // Tens Digit
      buf.append(static_cast<char>('0' + (iPart % 10)));        // Ones Digit
      buf.append('.');
      buf.append(static_cast<char>('0' + fPart)); // Fractional Digit
      buf.append(suf);                            // Unit
    }
References DeltaUnits_.
Referenced by FormatOneLine_().
AppendLevel_()
template<typename BufferT> void anonymous_namespace{Log.cpp}::LogCore::AppendLevel_ (BufferT & buf, const QtMsgType typ) inline static private
Definition at line 2881 of file Log.cpp.
    {
      switch(typ) {
        case QtDebugMsg: buf.append("DBUG");
          break;
        case QtInfoMsg: buf.append("INFO");
          break;
        case QtWarningMsg: buf.append("WARN");
          break;
        case QtCriticalMsg: buf.append("CRIT");
          break;
        case QtFatalMsg: buf.append("FATL");
          break;
      }
    }
Referenced by FormatOneLine_().
AppendStr_() [1/2]
void anonymous_namespace{Log.cpp}::LogCore::AppendStr_ (QByteArray & buf, const QString & s) inline static private
Definition at line 2899 of file Log.cpp.
{ buf.append(s.toUtf8()); }
AppendStr_() [2/2]
void anonymous_namespace{Log.cpp}::LogCore::AppendStr_ (QString & buf, const QString & s) inline static private
Definition at line 2897 of file Log.cpp.
{ buf.append(s); }
Referenced by FormatOneLine_().
applyStartupFilterRules_()
void anonymous_namespace{Log.cpp}::LogCore::applyStartupFilterRules_ () inline
Definition at line 1328 of file Log.cpp.
    {
      static std::once_flag once;
      std::call_once(once, [this] {
        QString rules{BaseFilterRule_.toString()};
        {
          QReadLocker locker{&filterRulesLock_};
          if(!filterRules_.isEmpty())
            rules.append('\n').append(filterRules_.join('\n'));
        }
        QLoggingCategory::setFilterRules(rules);
      });
    }
References BaseFilterRule_, filterRules_, and filterRulesLock_.
CheckAndValidateDir_()
QString anonymous_namespace{Log.cpp}::LogCore::CheckAndValidateDir_ (const QString & path, QString * errorText) inline static private
Definition at line 2209 of file Log.cpp.
    {
      if(errorText) errorText->clear();
      const QString trimmed = path.trimmed();
      if(trimmed.isEmpty()) {
        if(errorText) *errorText = QStringLiteral("Path is empty.");
        return {};
      }
      QDir dir{trimmed};
      if(!dir.isAbsolute()) {
        if(errorText) *errorText = QStringLiteral("Path must be absolute.");
        return {};
      }
      const QString cleanAbs = QDir::cleanPath(dir.absolutePath());
      const QFileInfo fi{cleanAbs};
      if(fi.exists() && !fi.isDir()) {
        if(errorText) *errorText = QStringLiteral("Path exists but is not a directory.");
        return {};
      }
      QDir cleanDir{cleanAbs};
      if(!cleanDir.mkpath(QStringLiteral("."))) {
        if(errorText) *errorText = QStringLiteral("Failed to create the directory (permission denied or a file exists with the same name).");
        return {};
      }
      // Unique, atomic temp file in that directory
      QTemporaryFile tf{cleanDir.filePath(QStringLiteral("npi_rw_check_XXXXXX.tmp"))};
      if(!tf.open()) {
        if(errorText) *errorText = QStringLiteral("Directory is not writable.");
        return {};
      }
      return cleanAbs; // NOLINT(clang-diagnostic-nrvo, performance-no-automatic-move)
    }
Referenced by getStartupSettings_().
CleanedFilterRulesList_()
QStringList anonymous_namespace{Log.cpp}::LogCore::CleanedFilterRulesList_ (const QStringList & list) inline static private
Definition at line 2288 of file Log.cpp.
    {
      QStringList out;
      out.reserve(list.size());
      for(const QString& raw : list) {
        if(raw.isEmpty()) continue;
        QString s = raw;
        s.removeIf([](const QChar ch) { return ch.isSpace(); }); // handles tabs, etc.
        const auto eq = s.indexOf('=');
        if(eq <= 0) continue;                  // rejects "" and "=true"
        if(eq != s.lastIndexOf('=')) continue; // rejects "a=b=c"
        const QString key = s.left(eq);
        QString val = s.mid(eq + 1).toLower();
        if(key.isEmpty()) continue;
        if(val != "true" && val != "false") continue;
        out.append(key + "=" + val);
      }
      return out;
    }
Referenced by getStartupSettings_().
closeConsole_()
void anonymous_namespace{Log.cpp}::LogCore::closeConsole_ () inline
Definition at line 1304 of file Log.cpp.
    {
      if(tempConsole_.load(std::memory_order_acquire)) {
        tempConsole_.store(false, std::memory_order_release);
        // Redirect CRT streams to NUL for safety
        FILE* dummy;
        (void)::freopen_s(&dummy, "NUL", "w", stdout);
        (void)::freopen_s(&dummy, "NUL", "w", stderr);
      }
    }
References tempConsole_.
Referenced by npi::log::closeConsole().
ComparePaths_()
bool anonymous_namespace{Log.cpp}::LogCore::ComparePaths_ (const QString & a, const QString & b) inline static private
Definition at line 2249 of file Log.cpp.
    {
      // Fast check to avoid object allocation
      if(!a.isEmpty() && a == b) return true;
      const QString aTrim = a.trimmed();
      const QString bTrim = b.trimmed();
      if(aTrim.isEmpty() || bTrim.isEmpty())
        return false;
      // static checking for absolute paths
      if(!QDir::isAbsolutePath(aTrim) || !QDir::isAbsolutePath(bTrim))
        return false;
      const QString aClean = QDir::cleanPath(aTrim);
      const QString bClean = QDir::cleanPath(bTrim);
    #ifdef Q_OS_WIN
      return aClean.compare(bClean, Qt::CaseInsensitive) == 0;
    #else
      return aClean == bClean;
    #endif
    }
Referenced by getCurrentDirFromSettings_(), getFutureDir_(), and getStartupSettings_().
DirCleanup_()
void anonymous_namespace{Log.cpp}::LogCore::DirCleanup_ (QString dirPath, qint64 maxSize, QString lockName) inline static private
Definition at line 2315 of file Log.cpp.
    {
      npi::GlobalLocker locker{lockName};
      QDir dir(dirPath);
      if(!dir.exists())
        return;
      // maxsize < 1 = infinite size
      if(maxSize < 1) return;
      quint64 maxBytes;
      const quint64 maxMb = static_cast<quint64>(maxSize);
      if(maxMb > (std::numeric_limits<quint64>::max() / (1024ULL * 1024ULL)))
        maxBytes = std::numeric_limits<quint64>::max();
      else
        maxBytes = maxMb * 1024ULL * 1024ULL;
      auto fileInfoList = dir.entryInfoList({"*.log"}, QDir::Files, QDir::Time | QDir::Reversed);
      quint64 curBytes = 0;
      for(const QFileInfo& fi : fileInfoList)
        curBytes += fi.size();
      if(curBytes > maxBytes) {
        for(const QFileInfo& fi : fileInfoList) {
          const quint64 fileSize = fi.size();
          if(QFile::remove(fi.absoluteFilePath()))
            curBytes -= fileSize;
          if(curBytes <= maxBytes)
            break;
        }
      }
    }
FieldsToStrings_()
QStringList anonymous_namespace{Log.cpp}::LogCore::FieldsToStrings_ (const QList< Field > & fields) inline static private
Definition at line 2273 of file Log.cpp.
    {
      QStringList out;
      out.reserve(fields.size());
      for(qsizetype ii = 0; ii < fields.length(); ++ii) {
        auto sv = magic_enum::enum_name(fields[ii]);
        if(!sv.empty()) {
          const auto str = QString::fromLatin1(sv.data(), static_cast<qsizetype>(sv.size()));
          if(!out.contains(str))
            out.append(str);
        }
      }
      return out;
    }
Referenced by LogCore(), and getStartupSettings_().
FormatOneLine_()
template<typename BufferT> void anonymous_namespace{Log.cpp}::LogCore::FormatOneLine_ (BufferT & buffer, const QList< Field > & fields, const OneLog & one) inline static private
Definition at line 2902 of file Log.cpp.
    {
      bool notFirst{false};
      for(const Field& field : fields) {
        if(notFirst) buffer.append(' ');
        else notFirst = true;
        switch(field) {
          case Field::DateTime:
            AppendDateTime_(buffer, one.dateTime_);
            break;
          case Field::UpTime:
            buffer.append("t=");
            AppendDelta_(buffer, one.upTime_);
            break;
          case Field::ThreadTime:
            buffer.append("tT=");
            AppendDelta_(buffer, one.threadTime_);
            break;
          case Field::ThreadDelta:
            buffer.append("dT=");
            AppendDelta_(buffer, one.threadDelta_);
            break;
          case Field::ThreadNumber:
            if(one.thread_ == 0u) {
              buffer.append("T=-");
            }
            else {
              buffer.append("T=");
              buffer.append(BufferT::number(one.thread_));
            }
            break;
          case Field::ThreadHexId: {
            const quint32 v = one.threadId_;
            constexpr char hexMap[] = "0123456789ABCDEF";
            buffer.append("0x");
            for(int i = 7; i >= 0; --i) {
              const quint32 nib = (v >> (i * 4)) & 0xFu;
              buffer.append(hexMap[nib]);
            }
            break;
          }
          case Field::Level:
            AppendLevel_(buffer, one.level_);
            break;
          case Field::Category:
            one.fixedStrings_.appendCategoryTo_(buffer);
            break;
          case Field::FileLine:
            one.fixedStrings_.appendFileNameTo_(buffer);
            buffer.append(':');
            buffer.append(BufferT::number(one.fileLine_));
            break;
          case Field::Function:
            one.fixedStrings_.appendFuncNameTo_(buffer);
            break;
        }
      }
      buffer.append(" | ");
      AppendStr_(buffer, one.message_);
      buffer.append('\n');
    }
References anonymous_namespace{Log.cpp}::LogCore::FixedStrings::appendCategoryTo_(), AppendDateTime_(), AppendDelta_(), anonymous_namespace{Log.cpp}::LogCore::FixedStrings::appendFileNameTo_(), anonymous_namespace{Log.cpp}::LogCore::FixedStrings::appendFuncNameTo_(), AppendLevel_(), AppendStr_(), Category, DateTime, anonymous_namespace{Log.cpp}::LogCore::OneLog::dateTime_, FileLine, anonymous_namespace{Log.cpp}::LogCore::OneLog::fileLine_, anonymous_namespace{Log.cpp}::LogCore::OneLog::fixedStrings_, Function, Level, anonymous_namespace{Log.cpp}::LogCore::OneLog::level_, anonymous_namespace{Log.cpp}::LogCore::OneLog::message_, anonymous_namespace{Log.cpp}::LogCore::OneLog::thread_, ThreadDelta, anonymous_namespace{Log.cpp}::LogCore::OneLog::threadDelta_, ThreadHexId, anonymous_namespace{Log.cpp}::LogCore::OneLog::threadId_, ThreadNumber, ThreadTime, anonymous_namespace{Log.cpp}::LogCore::OneLog::threadTime_, UpTime, and anonymous_namespace{Log.cpp}::LogCore::OneLog::upTime_.
Referenced by startDisplay_(), and startWriting_().
getAvailableFieldNames_()
const QStringList & anonymous_namespace{Log.cpp}::LogCore::getAvailableFieldNames_ () const inline
Definition at line 1154 of file Log.cpp.
{ return availableFieldNames_; }
References availableFieldNames_.
getConsole_()
bool anonymous_namespace{Log.cpp}::LogCore::getConsole_ () inline private
Definition at line 1985 of file Log.cpp.
    {
      // 1. Configure OUTPUT Handle (STD_ERROR_HANDLE)
      // This handles text wrapping and newline processing.
      const HANDLE hOut = ::GetStdHandle(STD_ERROR_HANDLE);
      if(hOut == INVALID_HANDLE_VALUE || hOut == nullptr)
        return false;
      // specific check: Is this a real console?
      // If h is a file redirect, GetConsoleMode fails.
      // We want to fail in that case because WriteConsoleW won't work on files.
      DWORD outMode = 0;
      if(::GetConsoleMode(hOut, &outMode) == 0)
        return false; // Not a real console
      const DWORD desiredOutMode = outMode | ENABLE_PROCESSED_OUTPUT | ENABLE_WRAP_AT_EOL_OUTPUT;
      if(outMode != desiredOutMode)
        ::SetConsoleMode(hOut, desiredOutMode);
      // 2. Configure INPUT Handle (STD_INPUT_HANDLE)
      // This handles Mouse Clicks and Quick Edit Mode.
      const HANDLE hIn = ::GetStdHandle(STD_INPUT_HANDLE);
      if(hIn != INVALID_HANDLE_VALUE && hIn != nullptr) {
        DWORD inMode = 0;
        if(::GetConsoleMode(hIn, &inMode)) {
          // ENABLE_EXTENDED_FLAGS is required to change Quick Edit settings
          DWORD desiredInMode = inMode | ENABLE_EXTENDED_FLAGS;
          // DISABLE Quick Edit Mode (stops mouse clicks from pausing execution)
          desiredInMode &= ~ENABLE_QUICK_EDIT_MODE;
          // DISABLE Insert Mode
          desiredInMode &= ~ENABLE_INSERT_MODE;
          // DISABLE Mouse Input (Prevents accidental processing overhead)
          desiredInMode &= ~ENABLE_MOUSE_INPUT;
          if(inMode != desiredInMode)
            ::SetConsoleMode(hIn, desiredInMode);
        }
      }
      QString title{QString(npi::AppMetaData::Name_).append(" Console")};
      ::SetConsoleTitleW(reinterpret_cast<LPCWSTR>(title.utf16()));
      return true;
    }
References npi::AppMetaData::Name_.
Referenced by LogCore(), and openConsole_().
getCurrentDirFromSettings_()
QString anonymous_namespace{Log.cpp}::LogCore::getCurrentDirFromSettings_ (QSettings & settings) inline private
Definition at line 2167 of file Log.cpp.
    {
      QString iniDir{defDir_};
      if(settings.contains(SettingsDirKey_.toString())) {
        const QString iniString = settings.value(SettingsDirKey_.toString()).toString().trimmed();
        if(!iniString.isEmpty()) {
          if(QDir dir{iniString}; dir.isAbsolute())
            iniDir = QDir::cleanPath(dir.absolutePath());
        }
        if(iniDir.isEmpty() || ComparePaths_(defDir_, iniDir)) {
          iniDir = defDir_;
          settings.remove(SettingsDirKey_.toString());
          settings.sync();
        }
      }
      return iniDir;
    }
References ComparePaths_(), defDir_, and SettingsDirKey_.
Referenced by getFutureDir_().
getDir_()
QString anonymous_namespace{Log.cpp}::LogCore::getDir_ () const inline
Definition at line 1025 of file Log.cpp.
{ return startup_.dir_; }
References startup_.
getFields_()
QStringList anonymous_namespace{Log.cpp}::LogCore::getFields_ (const bool forLog) inline
Definition at line 1156 of file Log.cpp.
    {
      auto& group = forLog ? logConfig_ : msgConfig_;
      QReadLocker locker{&group.lock_};
      return group.strings_;
    }
References logConfig_, and msgConfig_.
getFieldTempState_()
bool anonymous_namespace{Log.cpp}::LogCore::getFieldTempState_ (const bool forLog) inline
Definition at line 1163 of file Log.cpp.
    {
      auto& group = forLog ? logConfig_ : msgConfig_;
      QReadLocker locker{&group.lock_};
      return group.temp_;
    }
References logConfig_, and msgConfig_.
GetFilterBaseRules_()
QStringList anonymous_namespace{Log.cpp}::LogCore::GetFilterBaseRules_ () inline static
Definition at line 1196 of file Log.cpp.
{ return BaseFilterRule_.toString().split('\n'); }
References BaseFilterRule_.
getFilterRules_()
QStringList anonymous_namespace{Log.cpp}::LogCore::getFilterRules_ () inline
Definition at line 1198 of file Log.cpp.
    {
      QReadLocker locker{&filterRulesLock_};
      return filterRules_;
    }
References filterRules_, and filterRulesLock_.
getFilterRulesTempState_()
bool anonymous_namespace{Log.cpp}::LogCore::getFilterRulesTempState_ () inline
Definition at line 1204 of file Log.cpp.
    {
      QReadLocker locker{&filterRulesLock_};
      return filterRulesTempState_;
    }
References filterRulesLock_, and filterRulesTempState_.
getFutureDir_()
QString anonymous_namespace{Log.cpp}::LogCore::getFutureDir_ () inline
Definition at line 1108 of file Log.cpp.
    {
      npi::GlobalLocker locker{configLockName_};
      QSettings settings{QDir(npi::app::appProgramDataDir()).filePath(ConfigFileName_.toString()), QSettings::IniFormat};
      QString iniDir = getCurrentDirFromSettings_(settings);
      if(ComparePaths_(iniDir, startup_.dir_)) iniDir.clear();
      return iniDir;
    }
References npi::app::appProgramDataDir(), ComparePaths_(), ConfigFileName_, configLockName_, getCurrentDirFromSettings_(), and startup_.
getLogCategories_()
QStringList anonymous_namespace{Log.cpp}::LogCore::getLogCategories_ () inline
Definition at line 1243 of file Log.cpp.
    {
      QReadLocker locker{&logCategoriesLock_};
      return logCategories_;
    }
References logCategories_, and logCategoriesLock_.
getMaxFolderSizeMb_()
qint64 anonymous_namespace{Log.cpp}::LogCore::getMaxFolderSizeMb_ () inline
Definition at line 1117 of file Log.cpp.
    {
      if(maxMbLastChangeTime_.load(std::memory_order_acquire) > 0)
        return currentMaxMb_.load(std::memory_order_relaxed);
      npi::GlobalLocker locker{configLockName_};
      QSettings settings{QDir(npi::app::appProgramDataDir()).filePath(ConfigFileName_.toString()), QSettings::IniFormat};
      qint64 savedVal{DefaultMaxFolderSizeMb_};
      if(settings.contains(SettingsMaxFolderSizeKey_.toString())) {
        bool ok{false};
        qint64 temp = settings.value(SettingsMaxFolderSizeKey_.toString()).toLongLong(&ok);
        if(!ok || temp < 0 || temp == DefaultMaxFolderSizeMb_) {
          settings.remove(SettingsMaxFolderSizeKey_.toString());
          settings.sync();
        }
        else {
          savedVal = temp;
        }
      }
      currentMaxMb_.store(savedVal, std::memory_order_relaxed);
      return savedVal;
    }
References npi::app::appProgramDataDir(), ConfigFileName_, configLockName_, currentMaxMb_, DefaultMaxFolderSizeMb_, maxMbLastChangeTime_, and SettingsMaxFolderSizeKey_.
getStartupSettings_()
StartupSettings anonymous_namespace{Log.cpp}::LogCore::getStartupSettings_ () inline private
Definition at line 2031 of file Log.cpp.
    {
    #ifdef NDEBUG      // Release
      initialLogs_.append({.level_ = QtInfoMsg, .message_ = QStringLiteral("----RELEASE BUILD----")});
    #else              // Debug
      initialLogs_.append({.level_ = QtInfoMsg, .message_ = QStringLiteral("----DEBUG BUILD----")});
    #endif
      npi::GlobalLocker locker{configLockName_};
      QSettings settings{QDir(npi::app::appProgramDataDir()).filePath(ConfigFileName_.toString()), QSettings::IniFormat};
      QString curDir;
      if(settings.contains(SettingsDirKey_.toString())) {
        const QString path = settings.value(SettingsDirKey_.toString()).toString().trimmed();
        if(path.isEmpty() || ComparePaths_(path, defDir_)) {
          settings.remove(SettingsDirKey_.toString());
        }
        else {
          QString errorText;
          const QString cleanPath = CheckAndValidateDir_(path, &errorText);
          if(cleanPath.isEmpty()) {
            initialLogs_.append({
              .level_ = QtWarningMsg,
              .message_ = QStringLiteral("Unable to use %1 as log directory: %2\n\nFalling back to the default log directory.").arg(path, errorText)
            });
            settings.remove(SettingsDirKey_.toString());
          }
          else {
            curDir = cleanPath;
          }
        }
      }
      if(curDir.isEmpty()) {
        QString errorText;
        curDir = CheckAndValidateDir_(defDir_, &errorText);
        if(curDir.isEmpty()) {
          npi::app::nativeFatalMessage(
            "Create Default Log Directory Failed",
            QString(
              "Unable to create default log directory at '%1': %2\n\nThis folder is required to store application logs."
              " The application cannot continue safely without logging support and will now exit.").arg(defDir_, errorText));
        }
      }
      qint64 maxSize{DefaultMaxFolderSizeMb_};
      if(settings.contains(SettingsMaxFolderSizeKey_.toString())) {
        bool maxSizeOk{false};
        const qint64 maxSizeTemp = settings.value(SettingsMaxFolderSizeKey_.toString(), DefaultMaxFolderSizeMb_).toLongLong(&maxSizeOk);
        if(maxSizeOk && maxSizeTemp >= 0 && maxSizeTemp != DefaultMaxFolderSizeMb_)
          maxSize = maxSizeTemp;
        else
          settings.remove(SettingsMaxFolderSizeKey_.toString());
      }
      QStringList logFields{FieldsToStrings_(defLogFields_)};
      if(settings.contains(SettingsLogFieldsKey_.toString())) {
        const QStringList temp = settings.value(SettingsLogFieldsKey_.toString()).toStringList();
        const auto tempFields = stringsToFields_(temp);
        const auto tempStrings = FieldsToStrings_(tempFields);
        if(tempStrings.isEmpty() || tempStrings == logFields) {
          settings.remove(SettingsLogFieldsKey_.toString());
        }
        else {
          settings.setValue(SettingsLogFieldsKey_.toString(), tempStrings);
          logFields = tempStrings;
        }
      }
      QStringList msgFields{FieldsToStrings_(defMsgFields_)};
      if(settings.contains(SettingsMsgFieldsKey_.toString())) {
        const QStringList temp = settings.value(SettingsMsgFieldsKey_.toString()).toStringList();
        const auto tempFields = stringsToFields_(temp);
        const auto tempStrings = FieldsToStrings_(tempFields);
        if(tempStrings.isEmpty() || tempStrings == msgFields) {
          settings.remove(SettingsMsgFieldsKey_.toString());
        }
        else {
          settings.setValue(SettingsMsgFieldsKey_.toString(), tempStrings);
          msgFields = tempStrings;
        }
      }
      QStringList filterRules;
      if(settings.contains(SettingsFilterRulesKey_.toString())) {
        const QStringList ruleList = settings.value(SettingsFilterRulesKey_.toString()).toStringList();
        filterRules = CleanedFilterRulesList_(ruleList);
        if(filterRules.isEmpty())
          settings.remove(SettingsFilterRulesKey_.toString());
        else
          settings.setValue(SettingsFilterRulesKey_.toString(), filterRules);
      }
      const bool colorConsole = settings.value(SettingsColoredConsoleKey_.toString(), false).toBool();
      coloredConsole_.store(colorConsole, std::memory_order_release);
      const bool warnIsImp = settings.value(SettingsWarnIsImpKey_.toString(), false).toBool();
      warnIsImp_.store(warnIsImp, std::memory_order_release);
      settings.sync();
      return {
        .dir_ = curDir,
        .maxFolderMb_ = maxSize,
        .logFields_ = logFields,
        .msgFields_ = msgFields,
        .filterRules_ = filterRules
      };
    }
References npi::app::appProgramDataDir(), CheckAndValidateDir_(), CleanedFilterRulesList_(), coloredConsole_, ComparePaths_(), ConfigFileName_, configLockName_, DefaultMaxFolderSizeMb_, defDir_, defLogFields_, defMsgFields_, FieldsToStrings_(), initialLogs_, npi::app::nativeFatalMessage(), SettingsColoredConsoleKey_, SettingsDirKey_, SettingsFilterRulesKey_, SettingsLogFieldsKey_, SettingsMaxFolderSizeKey_, SettingsMsgFieldsKey_, SettingsWarnIsImpKey_, stringsToFields_(), and warnIsImp_.
Referenced by LogCore().
initiateShutdown_()
void anonymous_namespace{Log.cpp}::LogCore::initiateShutdown_ () inline
Definition at line 1417 of file Log.cpp.
    {
      static std::once_flag once;
      std::call_once(once, [this] {
        if(maxMbThread_.joinable()) {
          maxMbThread_.request_stop();
          maxMbThreadWakeup_.notify_all();
          maxMbThread_.join();
        }
        if(fileThreadRunning_.load(std::memory_order_acquire) && fileThread_.joinable()) {
          fileThread_.request_stop();
          fileThread_.join();
        }
        if(dispThreadRunning_.load(std::memory_order_acquire) && dispThread_.joinable()) {
          dispThread_.request_stop();
          DWORD result = ::WaitForSingleObject(dispThread_.native_handle(), 500);
          if(result == WAIT_OBJECT_0)
            dispThread_.join();
        }
      });
    }
References dispThread_, dispThreadRunning_, fileThread_, fileThreadRunning_, maxMbThread_, and maxMbThreadWakeup_.
Referenced by anonymous_namespace{Log.cpp}::shuttingDown().
insertLogMessage_()
void anonymous_namespace{Log.cpp}::LogCore::insertLogMessage_ (QtMsgType typ, const QString & msg) inline private
Definition at line 2185 of file Log.cpp.
    {
      if(runtimeLogs_.load(std::memory_order_acquire)) {
        switch(typ) {
          case QtDebugMsg: npiDbug << msg;
            break;
          case QtInfoMsg: npiInfo << msg;
            break;
          case QtWarningMsg: npiWarn << msg;
            break;
          case QtCriticalMsg: npiCrit << msg;
            break;
          case QtFatalMsg: npiFatl << msg;
            break;
        }
      }
      else {
        std::lock_guard guard{initialLogsMutex_};
        initialLogs_ << InitialLog{.level_ = typ, .message_ = msg};
      }
    }
References initialLogs_, initialLogsMutex_, npiCrit, npiDbug, npiFatl, npiInfo, npiWarn, and runtimeLogs_.
Referenced by startDisplay_().
Inst_()
LogCore * anonymous_namespace{Log.cpp}::LogCore::Inst_ () inline static
Definition at line 1013 of file Log.cpp.
    {
      static auto inst = new LogCore;
      return inst;
    }
References LogCore().
Referenced by npi::log::clearFilterRules(), npi::log::closeConsole(), anonymous_namespace{Log.cpp}::initLogging(), anonymous_namespace{Log.cpp}::loggingCategoryFilter(), anonymous_namespace{Log.cpp}::msgHandler(), npi::log::setColoredConsole(), npi::log::setMuteDisplay(), npi::log::setWarnAsImpLog(), and anonymous_namespace{Log.cpp}::shuttingDown().
isConsoleColored_()
bool anonymous_namespace{Log.cpp}::LogCore::isConsoleColored_ () const inline
Definition at line 1253 of file Log.cpp.
{ return coloredConsole_.load(std::memory_order_acquire); }
References coloredConsole_.
isConsoleOpen_()
bool anonymous_namespace{Log.cpp}::LogCore::isConsoleOpen_ () const inline
Definition at line 1266 of file Log.cpp.
{ return permConsole_ || tempConsole_.load(std::memory_order_acquire); }
References permConsole_, and tempConsole_.
isDisplayMuted_()
bool anonymous_namespace{Log.cpp}::LogCore::isDisplayMuted_ () const inline
Definition at line 1249 of file Log.cpp.
{ return muteDisplay_.load(std::memory_order_acquire); }
References muteDisplay_.
isPermanentConsole_()
bool anonymous_namespace{Log.cpp}::LogCore::isPermanentConsole_ () const inline
Definition at line 1264 of file Log.cpp.
{ return permConsole_; }
References permConsole_.
isWarnImp_()
bool anonymous_namespace{Log.cpp}::LogCore::isWarnImp_ () const inline
Definition at line 1315 of file Log.cpp.
{ return warnIsImp_.load(std::memory_order_acquire); }
References warnIsImp_.
msgHandler_()
void anonymous_namespace{Log.cpp}::LogCore::msgHandler_ (QtMsgType typ, const QMessageLogContext & ctx, const QString & msg) inline
Definition at line 1368 of file Log.cpp.
    {
      const auto t1 = std::chrono::steady_clock::now();
      if(typ == QtFatalMsg) {
        ::InterlockedExchange(&safe::fatalLog, 1); // stops signal handler from getting triggered
        safe::msgHandler(typ, ctx, msg);
        std::abort();
      }
      if(shutdownMode_.load(std::memory_order_acquire)) {
        safe::msgHandler(typ, ctx, msg, true);
        return;
      }
      if(typ == QtCriticalMsg || (typ == QtWarningMsg && warnIsImp_.load(std::memory_order_acquire)))
        safe::msgHandler(typ, ctx, msg);
      const auto nowTp = std::chrono::steady_clock::now();
      const qint64 upTime = std::chrono::duration_cast<std::chrono::nanoseconds>(nowTp - startTp_).count();
      thread_local const qint64 threadBeg{upTime};
      const qint64 threadTime = upTime - threadBeg;
      thread_local qint64 prevThreadTime = 0;
      const qint64 threadDelta = threadTime - prevThreadTime;
      prevThreadTime = threadTime;
      thread_local const quint32 threadNumber = static_cast<quint32>(1u + threadCounter_.fetch_add(1u, std::memory_order_relaxed));
      OneLog one{
        .thread_ = threadNumber,
        .threadId_ = ::GetCurrentThreadId(),
        .fileLine_ = ctx.line,
        .level_ = typ,
        .dateTime_ = std::chrono::system_clock::now(),
        .upTime_ = upTime,
        .threadTime_ = threadTime,
        .threadDelta_ = threadDelta,
        .message_ = msg,
        .fixedStrings_ = FixedStrings(ctx.category, ctx.file, ctx.function)
      };
      thread_local moodycamel::ProducerToken pFileToken{fileQueue_};
      fileQueue_.enqueue(pFileToken, std::move(one));
      const qint64 nst = std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now() - t1).count();
      const QString nsBuf = QString::number(nst) % "\n";
      ::OutputDebugStringW(reinterpret_cast<LPCWSTR>(nsBuf.utf16()));
      //MsgHandlerTiming_::Record_(nst);
    }
References anonymous_namespace{Log.cpp}::safe::fatalLog, fileQueue_, anonymous_namespace{Log.cpp}::safe::msgHandler(), shutdownMode_, startTp_, threadCounter_, and warnIsImp_.
Referenced by anonymous_namespace{Log.cpp}::msgHandler().
openConsole_()
bool anonymous_namespace{Log.cpp}::LogCore::openConsole_ () inline
Definition at line 1268 of file Log.cpp.
    {
      if(permConsole_ || tempConsole_.load(std::memory_order_acquire)) return true;
      // Safety: If a console window exists (attached), don't alloc another.
      if(::GetConsoleWindow() != nullptr) return false;
      // Allocate
      if(!::AllocConsole()) return false;
      if(getConsole_()) {
        // Disable the Close Button (Prevent user from killing app via Console X)
        const HWND consoleWindow = ::GetConsoleWindow();
        if(consoleWindow != nullptr) {
          const HMENU hMenu = ::GetSystemMenu(consoleWindow, FALSE);
          if(hMenu != nullptr)
            ::DeleteMenu(hMenu, SC_CLOSE, MF_BYCOMMAND);
        }
        // Redirect standard C streams to the new console
        // This allows 3rd party libs using printf/std::cout to work.
        FILE* f = nullptr;
        if(::freopen_s(&f, "CONOUT$", "w", stdout) == 0)
          (void)std::setvbuf(stdout, nullptr, _IONBF, 0);
        if(::freopen_s(&f, "CONOUT$", "w", stderr) == 0)
          (void)std::setvbuf(stderr, nullptr, _IONBF, 0);
        tempConsole_.store(true, std::memory_order_release);
        startDisplay_();
        return true;
      }
      ::FreeConsole();
      return false;
    }
References getConsole_(), permConsole_, startDisplay_(), and tempConsole_.
operator=() [1/2]
LogCore & anonymous_namespace{Log.cpp}::LogCore::operator= (const LogCore &) delete
References LogCore().
operator=() [2/2]
LogCore & anonymous_namespace{Log.cpp}::LogCore::operator= (LogCore &&) delete
References LogCore().
saveSettings_()
void anonymous_namespace{Log.cpp}::LogCore::saveSettings_ (const QLatin1StringView & view, const std::optional< QVariant > & var = std::nullopt) const inline private
Definition at line 2156 of file Log.cpp.
    {
      npi::GlobalLocker locker{configLockName_};
      QSettings settings{QDir(npi::app::appProgramDataDir()).filePath(ConfigFileName_.toString()), QSettings::IniFormat};
      if(var.has_value())
        settings.setValue(view.toString(), *var);
      else
        settings.remove(view.toString());
      settings.sync();
    }
References npi::app::appProgramDataDir(), ConfigFileName_, and configLockName_.
Referenced by LogCore(), setColoredConsole_(), and setWarnIsImp_().
setColoredConsole_()
void anonymous_namespace{Log.cpp}::LogCore::setColoredConsole_ (const bool state) inline
Definition at line 1255 of file Log.cpp.
    {
      coloredConsole_.store(state, std::memory_order_release);
      if(state)
        saveSettings_(SettingsColoredConsoleKey_, true);
      else
        saveSettings_(SettingsColoredConsoleKey_);
    }
References coloredConsole_, saveSettings_(), and SettingsColoredConsoleKey_.
Referenced by npi::log::setColoredConsole().
setDir_()
npi::log::DirResult anonymous_namespace{Log.cpp}::LogCore::setDir_ (const QString & path = {}) inline
Definition at line 1027 of file Log.cpp.
                                                  {})
    {
      npi::log::DirResult result;
      QString newDir;
      bool newIsDef{false};
      const QString trimmed = path.trimmed();
      if(trimmed.isEmpty()) {
        newDir = defDir_;
        newIsDef = true;
      }
      else {
        QDir dir{trimmed};
        if(!dir.isAbsolute()) {
          result.error_ = true;
          result.message_ = QStringLiteral("Path '%1' rejected: Path must be absolute.").arg(trimmed);
          npiWarn << result.message_;
          return result;
        }
        const QString clean = QDir::cleanPath(dir.absolutePath());
        const QFileInfo fi{clean};
        if(fi.exists() && !fi.isDir()) {
          result.error_ = true;
          result.message_ = QStringLiteral("Path '%1' rejected: Path exists and is not a directory.").arg(clean);
          npiWarn << result.message_;
          return result;
        }
        if(ComparePaths_(clean, defDir_)) {
          newDir = defDir_;
          newIsDef = true;
        }
        else {
          newDir = clean;
        }
      }
      const QString dispPath = newIsDef ? QStringLiteral("default log directory (%1)").arg(defDir_) : newDir;
      npi::GlobalLocker locker{configLockName_};
      QSettings settings{QDir(npi::app::appProgramDataDir()).filePath(ConfigFileName_.toString()), QSettings::IniFormat};
      const QString iniDir = getCurrentDirFromSettings_(settings);
      const bool newIsIni = ComparePaths_(newDir, iniDir);
      bool changed{false};
      if(ComparePaths_(newDir, startup_.dir_)) {
        // staying at current or cancelling a move
        if(newIsIni) {
          result.message_ = QStringLiteral("Current log directory is already set to %1.").arg(dispPath);
        }
        else {
          result.message_ = QStringLiteral("Log directory reverted to %1.").arg(dispPath);
          changed = true;
        }
      }
      else {
        // moving to a new path
        result.newPath_ = newDir;
        if(newIsIni) {
          result.message_ = QStringLiteral("Log directory already set to %1. Changes will take effect after the application restarts.").arg(dispPath);
        }
        else {
          result.message_ = QStringLiteral("Log directory set to %1. Changes will take effect after the application restarts.").arg(dispPath);
          changed = true;
        }
      }
      if(changed) {
        if(newIsDef)
          settings.remove(SettingsDirKey_.toString());
        else
          settings.setValue(SettingsDirKey_.toString(), newDir);
        settings.sync();
      }
      npiInfo << result.message_;
      return result;
    }
setFields_()
QStringList anonymous_namespace{Log.cpp}::LogCore::setFields_ (const bool forLog, const bool temp = false, const QStringList & list = {}) inline
Definition at line 1170 of file Log.cpp.
                                                                                                 {})
    {
      auto newFields = stringsToFields_(list);
      auto& defFields = forLog ? defLogFields_ : defMsgFields_;
      if(newFields.isEmpty()) newFields = defFields;
      const auto newStrings = FieldsToStrings_(newFields);
      if(!temp) {
        const auto& key = forLog ? SettingsLogFieldsKey_ : SettingsMsgFieldsKey_;
        if(newFields == defFields)
          saveSettings_(key);
        else
          saveSettings_(key, newStrings);
      }
      auto& group = forLog ? logConfig_ : msgConfig_;
      {
        QWriteLocker locker{&group.lock_};
        group.fields_ = newFields;
        group.strings_ = newStrings;
        group.temp_ = temp;
        group.version_.fetch_add(1, std::memory_order_relaxed);
      }
      return newStrings;
    }
setFilterRules_()
QStringList anonymous_namespace{Log.cpp}::LogCore::setFilterRules_ (const bool temp = false, const QStringList & ruleList = {}) inline
Definition at line 1210 of file Log.cpp.
                                                                                       {})
    {
      const QStringList cleanList = CleanedFilterRulesList_(ruleList);
      if(!temp) {
        if(cleanList.isEmpty())
          saveSettings_(SettingsFilterRulesKey_);
        else
          saveSettings_(SettingsFilterRulesKey_, cleanList);
      }
      QString rules{BaseFilterRule_.toString()};
      if(!cleanList.isEmpty())
        rules.append('\n').append(cleanList.join('\n'));
      {
        QWriteLocker locker{&filterRulesLock_};
        filterRules_ = cleanList;
        filterRulesTempState_ = temp;
      }
      QLoggingCategory::setFilterRules(rules);
      return cleanList;
    }
Referenced by npi::log::clearFilterRules().
setMaxFolderSizeMb_()
qint64 anonymous_namespace{Log.cpp}::LogCore::setMaxFolderSizeMb_ (const qint64 size = -1) inline
Definition at line 1142 of file Log.cpp.
    {
      const qint64 nSize = size >= 0 ? size : DefaultMaxFolderSizeMb_;
      currentMaxMb_.store(nSize, std::memory_order_release);
      auto now = std::chrono::steady_clock::now().time_since_epoch();
      int64_t nowMs = std::chrono::duration_cast<std::chrono::milliseconds>(now).count();
      maxMbLastChangeTime_.store(nowMs, std::memory_order_release);
      maxMbThreadWakeup_.notify_one();
      return nSize;
    }
References currentMaxMb_, DefaultMaxFolderSizeMb_, maxMbLastChangeTime_, and maxMbThreadWakeup_.
setMuteDisplay_()
void anonymous_namespace{Log.cpp}::LogCore::setMuteDisplay_ (const bool state) inline
Definition at line 1251 of file Log.cpp.
{ muteDisplay_.store(state, std::memory_order_release); }
References muteDisplay_.
Referenced by npi::log::setMuteDisplay().
setWarnIsImp_()
void anonymous_namespace{Log.cpp}::LogCore::setWarnIsImp_ (bool state, bool temp = false) inline
Definition at line 1317 of file Log.cpp.
    {
      warnIsImp_.store(state, std::memory_order_release);
      if(!temp) {
        if(state)
          saveSettings_(SettingsWarnIsImpKey_, true);
        else
          saveSettings_(SettingsWarnIsImpKey_);
      }
    }
References saveSettings_(), SettingsWarnIsImpKey_, and warnIsImp_.
Referenced by npi::log::setWarnAsImpLog().
startDisplay_()
bool anonymous_namespace{Log.cpp}::LogCore::startDisplay_ () inline private
Definition at line 2579 of file Log.cpp.
    {
      if(bool expected = false; !dispThreadRunning_.compare_exchange_strong(expected, true, std::memory_order_acq_rel)) {
        insertLogMessage_(QtWarningMsg, "Ignored display thread start request while it is already running.");
        return true; // already running/starting
      }
      try {
        dispThread_ = std::jthread([this](std::stop_token st) {
          const auto clearRunning = qScopeGuard([this] { dispThreadRunning_.store(false, std::memory_order_release); });
          try {
            insertLogMessage_(QtInfoMsg, "Display thread started successfully");
            constexpr quint32 maxLinesPerSec = 10000;
            moodycamel::ConsumerToken cDispToken(dispQueue_);
            constexpr size_t bSize{128};
            OneLog batch[bSize];
            QString buffer;
            buffer.reserve(bSize * 1024);
            std::uint64_t vHad = msgConfig_.version_.load(std::memory_order_acquire);
            QList<Field> fields;
            {
              QReadLocker locker{&msgConfig_.lock_};
              fields = msgConfig_.fields_;
            }
            int finalDrainCounter{0};
            quint32 shownLines = 0;
            quint32 droppedLines = 0;
            auto begTp = std::chrono::steady_clock::now();
            while(true) {
              // Check if we have a window that needs closing
              if(const HWND hwnd = ::GetConsoleWindow(); hwnd != nullptr && !permConsole_ && !tempConsole_.load(std::memory_order_acquire)) {
                ::GetSystemMenu(hwnd, TRUE); // Revert menu to default state
                ::FreeConsole();             // Close the Console Window
              }
              // Acquire handle only if it is a real console buffer
              HANDLE console = nullptr;
              if(const HANDLE h = ::GetStdHandle(STD_ERROR_HANDLE); h != nullptr && h != INVALID_HANDLE_VALUE) {
                DWORD outMode = 0;
                if(::GetConsoleMode(h, &outMode) != 0) // Only assign if not redirected to file
                  console = h;
              }
              QString droppedMessage;
              if(const auto nowTp = std::chrono::steady_clock::now(); nowTp - begTp > std::chrono::seconds(1)) {
                if(droppedLines > 0)
                  droppedMessage = QStringLiteral("-------------------- Dropped %1 Lines --------------------\n").arg(droppedLines);
                begTp = nowTp;
                shownLines = 0;
                droppedLines = 0;
              }
              if(const auto vNew = msgConfig_.version_.load(std::memory_order_acquire); vNew != vHad) {
                QReadLocker locker{&msgConfig_.lock_};
                fields = msgConfig_.fields_;
                vHad = vNew;
              }
              size_t totalCount{0};
              if(console) {
                if(!droppedMessage.isEmpty()) {
                  DWORD written = 0;
                  ::WriteConsoleW(console, droppedMessage.utf16(), static_cast<DWORD>(droppedMessage.length()), &written, nullptr);
                }
                CONSOLE_SCREEN_BUFFER_INFO info{};
                if(coloredConsole_.load(std::memory_order_acquire) && ::GetConsoleScreenBufferInfo(console, &info)) {
                  const WORD oldAttr = info.wAttributes;
                  const WORD bgAttr = oldAttr & 0xF0;
                  while(const size_t count = dispQueue_.try_dequeue_bulk(cDispToken, batch, bSize)) {
                    totalCount += count;
                    for(size_t ii = 0; ii < count; ++ii) {
                      if(shownLines < maxLinesPerSec) {
                        ++shownLines;
                        buffer.clear();
                        FormatOneLine_(buffer, fields, batch[ii]);
                        switch(batch[ii].level_) {
                          case QtDebugMsg:
                            ::SetConsoleTextAttribute(console, bgAttr | FOREGROUND_GREEN);
                            break;
                          case QtInfoMsg:
                            ::SetConsoleTextAttribute(console, bgAttr | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE);
                            break;
                          case QtWarningMsg:
                            ::SetConsoleTextAttribute(console, bgAttr | FOREGROUND_RED | FOREGROUND_GREEN);
                            break;
                          case QtCriticalMsg:
                          case QtFatalMsg:
                            ::SetConsoleTextAttribute(console, bgAttr | FOREGROUND_RED | FOREGROUND_INTENSITY);
                            break;
                        }
                        DWORD written = 0;
                        ::WriteConsoleW(console, buffer.utf16(), static_cast<DWORD>(buffer.length()), &written, nullptr);
                      }
                      else {
                        ++droppedLines;
                      }
                    }
                    if(totalCount > 5120)
                      break;
                  }
                  ::SetConsoleTextAttribute(console, oldAttr);
                }
                else {
                  while(const size_t count = dispQueue_.try_dequeue_bulk(cDispToken, batch, bSize)) {
                    totalCount += count;
                    buffer.clear();
                    for(size_t ii = 0; ii < count; ++ii) {
                      if(shownLines < maxLinesPerSec) {
                        ++shownLines;
                        FormatOneLine_(buffer, fields, batch[ii]);
                      }
                      else {
                        ++droppedLines;
                      }
                    }
                    if(!buffer.isEmpty()) {
                      DWORD written = 0;
                      ::WriteConsoleW(console, buffer.utf16(), static_cast<DWORD>(buffer.length()), &written, nullptr);
                    }
                    if(totalCount > 5120)
                      break;
                  }
                }
              }
              else if(::IsDebuggerPresent()) {
                if(!droppedMessage.isEmpty())
                  ::OutputDebugStringW(reinterpret_cast<LPCWSTR>(droppedMessage.utf16()));
                while(const size_t count = dispQueue_.try_dequeue_bulk(cDispToken, batch, bSize)) {
                  totalCount += count;
                  buffer.clear();
                  for(size_t ii = 0; ii < count; ++ii) {
                    if(shownLines < maxLinesPerSec) {
                      ++shownLines;
                      FormatOneLine_(buffer, fields, batch[ii]);
                    }
                    else {
                      ++droppedLines;
                    }
                  }
                  if(!buffer.isEmpty())
                    ::OutputDebugStringW(reinterpret_cast<LPCWSTR>(buffer.utf16()));
                  if(totalCount > 5120)
                    break;
                }
              }
              else {
                break;
              }
              if(st.stop_requested()) {
                if(totalCount > 0) {
                  finalDrainCounter = 0;
                }
                else {
                  if(++finalDrainCounter < 20)
                    std::this_thread::sleep_for(std::chrono::milliseconds{10});
                  else
                    break;
                }
              }
              else if(totalCount == 0) {
                std::this_thread::sleep_for(DrainInterval_); // DrainInterval_ = 100ms
              }
            }
          }
          catch(const std::exception& e) {
            insertLogMessage_(QtCriticalMsg, QStringLiteral("Display Thread Start. Error: %1.").arg(QString::fromLocal8Bit(e.what())));
          }
          catch(...) {
            insertLogMessage_(QtCriticalMsg, "Display Thread Failed (Unhandled unknown exception).");
          }
        });
      }
      catch(const std::system_error& e) {
        dispThreadRunning_.store(false, std::memory_order_release);
        insertLogMessage_(QtCriticalMsg, QStringLiteral("Display Thread Start Failed. Error: %1 (Code %2).")
                                        .arg(QString::fromLocal8Bit(e.what()))
                                        .arg(e.code().value()));
        return false;
      }
      catch(...) {
        dispThreadRunning_.store(false, std::memory_order_release);
        insertLogMessage_(QtCriticalMsg, "Display Thread Start Failed (Unhandled unknown exception).");
        return false;
      }
      return true;
    }
References coloredConsole_, dispQueue_, dispThread_, dispThreadRunning_, DrainInterval_, FormatOneLine_(), insertLogMessage_(), msgConfig_, permConsole_, and tempConsole_.
Referenced by LogCore(), and openConsole_().
startImpLogProcess_()
void anonymous_namespace{Log.cpp}::LogCore::startImpLogProcess_ () inline private
Definition at line 1974 of file Log.cpp.
    {
      const QString fileName = fileBaseName_ + QStringLiteral(".imp.log");
      const QString pFileStr = QDir(startup_.dir_).filePath(fileName);
      const QString bFileStr = QDir(npi::app::appProgramDataDir()).filePath(QStringLiteral("ImpLogs/%1").arg(fileName));
      const std::wstring pFile = QDir::toNativeSeparators(pFileStr).toStdWString();
      const std::wstring bFile = QDir::toNativeSeparators(bFileStr).toStdWString();
      safe::startImpLogProcess(pFile, bFile);
    }
References npi::app::appProgramDataDir(), fileBaseName_, anonymous_namespace{Log.cpp}::safe::startImpLogProcess(), and startup_.
Referenced by LogCore().
startWriting_()
void anonymous_namespace{Log.cpp}::LogCore::startWriting_ () inline private
Definition at line 2350 of file Log.cpp.
    {
      if(bool expected = false; !fileThreadRunning_.compare_exchange_strong(expected, true, std::memory_order_acq_rel))
        return;
      try {
        fileThread_ = std::jthread([this](std::stop_token st) {
          const auto cleanup = qScopeGuard([this] { fileThreadRunning_.store(false, std::memory_order_release); });
          try {
            QFile file{QDir(startup_.dir_).filePath(fileBaseName_ + QStringLiteral(".log"))};
            if(!file.open(QIODevice::WriteOnly)) {
              npi::app::nativeFatalMessage(
                "Open Log File Failed",
                QString("Failed to open log file '%1' for writing.\n\n"
                  "The application cannot continue safely without logging support and will now exit.")
               .arg(QDir::cleanPath(file.fileName())));
            }
            moodycamel::ProducerToken pFileToken{fileQueue_};
            moodycamel::ConsumerToken cFileToken{fileQueue_};
            moodycamel::ProducerToken pDispToken{dispQueue_};
            moodycamel::ConsumerToken cDispToken{dispQueue_};
            constexpr size_t bSize{128};
            OneLog batch[bSize];
            QByteArray buffer;
            buffer.reserve(bSize * 1024);
            // Startup message
            OneLog startupMsg{
              .thread_ = 0,
              .threadId_ = ::GetCurrentThreadId(),
              .fileLine_ = -1,
              .level_ = QtInfoMsg,
              .dateTime_ = std::chrono::system_clock::now(),
              .upTime_ = std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now() - startTp_).count(),
              .message_ = QStringLiteral("---- Logger Thread Startup ----"),
              .fixedStrings_ = FixedStrings{"Special", "Log.cpp"}
            };
            fileQueue_.enqueue(pFileToken, std::move(startupMsg));
            std::uint64_t vHad = logConfig_.version_.load(std::memory_order_acquire);
            QList<Field> fields;
            {
              QReadLocker locker{&logConfig_.lock_};
              fields = logConfig_.fields_;
            }
            int finalDrainCounter{0};
            bool awaitingFlush{false};
            bool dispWasActive{false};
            bool stopRequested{false};
            auto lastFlushTp = std::chrono::steady_clock::now();
            while(true) {
              const bool dispState{dispThreadRunning_.load(std::memory_order_acquire) && !muteDisplay_.load(std::memory_order_acquire)};
              if(dispState) {
                dispWasActive = true;
              }
              else if(dispWasActive) {
                OneLog dummy;
                while(dispQueue_.try_dequeue(cDispToken, dummy)) {}
                dispWasActive = false;
              }
              if(const auto vNew = logConfig_.version_.load(std::memory_order_acquire); vNew != vHad) {
                QReadLocker locker{&logConfig_.lock_};
                fields = logConfig_.fields_;
                vHad = vNew;
              }
              if(!stopRequested && st.stop_requested()) {
                shutdownMode_.store(true, std::memory_order_release);
                stopRequested = true;
                OneLog shutdownMsg{
                  .thread_ = 0,
                  .threadId_ = ::GetCurrentThreadId(),
                  .fileLine_ = -1,
                  .level_ = QtInfoMsg,
                  .dateTime_ = std::chrono::system_clock::now(),
                  .upTime_ = std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now() - startTp_).count(),
                  .message_ = QStringLiteral("---- Logger Thread Shutdown ----"),
                  .fixedStrings_ = FixedStrings{"Special", "Log.cpp"}
                };
                fileQueue_.enqueue(pFileToken, std::move(shutdownMsg));
              }
              size_t totalCount{0};
              while(const size_t count = fileQueue_.try_dequeue_bulk(cFileToken, batch, bSize)) {
                totalCount += count;
                buffer.clear();
                for(size_t ii = 0; ii < count; ++ii)
                  FormatOneLine_(buffer, fields, batch[ii]);
                if(const qsizetype bufSize = buffer.size(); bufSize > 0) {
                  awaitingFlush = true;
                  qsizetype written = 0;
                  int noProgressStreak = 0;
                  while(noProgressStreak < 3 && written < bufSize) {
                    const qint64 want = static_cast<qint64>(bufSize - written);
                    const qint64 n = file.write(buffer.constData() + written, want);
                    if(n < 0) {
                      npi::app::nativeFatalMessage(
                        "Write Log File Failed",
                        QString("Failed to write to the log file '%1'.\n\nError: %2\n\n"
                          "The application cannot continue safely without logging support and will now exit.")
                       .arg(QDir::cleanPath(file.fileName()), file.errorString()));
                    }
                    if(n > want) {
                      npi::app::nativeFatalMessage(
                        "Write Log File Failed",
                        QString("Failed to write to the log file '%1'.\n\n"
                          "Overflow/Corruption Error: file.write() returned %2 bytes, which exceeds the requested %3 bytes.\n\n"
                          "The application cannot continue safely without logging support and will now exit.")
                       .arg(QDir::cleanPath(file.fileName()))
                       .arg(n)
                       .arg(want));
                    }
                    if(n == 0) {
                      ++noProgressStreak;
                      std::this_thread::sleep_for(std::chrono::milliseconds{1});
                      continue;
                    }
                    written += static_cast<qsizetype>(n);
                    noProgressStreak = 0;
                  }
                  if(written != bufSize) {
                    npi::app::nativeFatalMessage(
                      "Write Log File Failed",
                      QString("Failed to write to the log file '%1'.\n\n"
                        "Error: 3 consecutive attempts with no progress.\n\n"
                        "The application cannot continue safely without logging support and will now exit.")
                     .arg(QDir::cleanPath(file.fileName())));
                  }
                }
                if(dispState && dispQueue_.size_approx() + count < 20480)
                  dispQueue_.enqueue_bulk(pDispToken, std::make_move_iterator(batch), count);
                if(totalCount > 5120)
                  break;
              }
              if(awaitingFlush) {
                const auto nowTp = std::chrono::steady_clock::now();
                if(stopRequested || nowTp - lastFlushTp > FlushInterval_) {
                  bool flushOk = false;
                  for(int attempt = 0; attempt < 3; ++attempt) {
                    if(file.flush()) {
                      flushOk = true;
                      break;
                    }
                    std::this_thread::sleep_for(std::chrono::milliseconds{1});
                  }
                  if(!flushOk) {
                    npi::app::nativeFatalMessage(
                      "Flush Log File Failed",
                      QString("Failed to flush the contents of the log file '%1'.\n\nError: %2\n\n"
                        "The application cannot continue safely without logging support and will now exit.")
                     .arg(QDir::cleanPath(file.fileName()), file.errorString()));
                  }
                  lastFlushTp = nowTp;
                  awaitingFlush = false;
                }
              }
              if(stopRequested) {
                if(totalCount > 0) {
                  finalDrainCounter = 0;
                }
                else {
                  if(++finalDrainCounter < 20)
                    std::this_thread::sleep_for(std::chrono::milliseconds{10});
                  else
                    break;
                }
              }
              else if(totalCount == 0) {
                std::this_thread::sleep_for(DrainInterval_); // DrainInterval_ = 100ms
              }
            }
          }
          catch(const std::exception& e) {
            npi::app::nativeFatalMessage(
              "Logger Thread Failed",
              QString("Unhandled exception in logger thread.\n\nError: %1\n\n"
                "The application cannot continue safely without logging support and will now exit.")
             .arg(QString::fromLocal8Bit(e.what())));
          }
          catch(...) {
            npi::app::nativeFatalMessage(
              "Logger Thread Failed",
              QString("Unhandled unknown exception in logger thread.\n\n"
                "The application cannot continue safely without logging support and will now exit."));
          }
        });
      }
      catch(const std::system_error& e) {
        fileThreadRunning_.store(false, std::memory_order_release);
        npi::app::nativeFatalMessage(
          "Logger Thread Start Failed",
          QString("Failed to start logger thread.\n\nError: %1 (code %2)\n\n"
            "The application cannot continue safely without logging support and will now exit.")
         .arg(QString::fromLocal8Bit(e.what()))
         .arg(e.code().value()));
      }
      catch(...) { // e.g. std::bad_alloc
        fileThreadRunning_.store(false, std::memory_order_release);
        npi::app::nativeFatalMessage(
          "Logger Thread Start Failed",
          QString("Failed to start logger thread (Unhandled unknown exception).\n\n"
            "The application cannot continue safely without logging support and will now exit."));
      }
    }
References dispQueue_, dispThreadRunning_, DrainInterval_, fileBaseName_, fileQueue_, fileThread_, fileThreadRunning_, FlushInterval_, FormatOneLine_(), logConfig_, muteDisplay_, npi::app::nativeFatalMessage(), shutdownMode_, startTp_, and startup_.
Referenced by LogCore().
stringsToFields_()
QList< Field > anonymous_namespace{Log.cpp}::LogCore::stringsToFields_ (const QStringList & strings) const inline private
Definition at line 2141 of file Log.cpp.
    {
      QList<Field> out;
      out.reserve(strings.size());
      for(const QString& raw : strings) {
        QString s = raw.toLower()
                       .remove(QLatin1Char(' '))
                       .remove(QLatin1Char('_'))
                       .remove(QLatin1Char('-'));
        if(auto it = fieldHash_.constFind(s); it != fieldHash_.constEnd())
          if(!out.contains(it.value())) out.append(it.value());
      }
      return out;
    }
References fieldHash_.
Referenced by LogCore(), and getStartupSettings_().
writeInitialLogs_()
void anonymous_namespace{Log.cpp}::LogCore::writeInitialLogs_ () inline
Definition at line 1342 of file Log.cpp.
    {
      static std::once_flag once;
      std::call_once(once, [this] {
        if(!initialLogs_.isEmpty()) {
          for(auto& iLog : initialLogs_) {
            if(iLog.message_.isEmpty())
              continue;
            switch(iLog.level_) {
              case QtDebugMsg: npiDbug << iLog.message_;
                break;
              case QtInfoMsg: npiInfo << iLog.message_;
                break;
              case QtWarningMsg: npiWarn << iLog.message_;
                break;
              case QtCriticalMsg: npiCrit << iLog.message_;
                break;
              case QtFatalMsg: npiFatl << iLog.message_;
                break;
            }
          }
        }
      });
    }
References initialLogs_, npiCrit, npiDbug, npiFatl, npiInfo, and npiWarn.
Member Data Documentation
availableFieldNames_
const QStringList anonymous_namespace{Log.cpp}::LogCore::availableFieldNames_ private
Initial value:
{
      "DateTime",
      "UpTime",
      "ThreadTime",
      "ThreadDelta",
      "ThreadNumber",
      "ThreadHexId",
      "Level",
      "Category",
      "FileLine",
      "Function"
    }
Definition at line 1500 of file Log.cpp.
{
      "DateTime",
      "UpTime",
      "ThreadTime",
      "ThreadDelta",
      "ThreadNumber",
      "ThreadHexId",
      "Level",
      "Category",
      "FileLine",
      "Function"
    };
Referenced by getAvailableFieldNames_().
BaseFilterRule_
QLatin1StringView anonymous_namespace{Log.cpp}::LogCore::BaseFilterRule_ static constexpr private
Initial value:
{
      "*.debug=true\n*.info=true\n*.warning=true\n*.critical=true"
      "\ndefault.debug=true\ndefault.info=true"
      "\nqt*.debug=false\nqt*.info=false"
      "\nnpi*.debug=true\nnpi*.info=true"}
Definition at line 1463 of file Log.cpp.
{
      "*.debug=true\n*.info=true\n*.warning=true\n*.critical=true"
      "\ndefault.debug=true\ndefault.info=true"
      "\nqt*.debug=false\nqt*.info=false"
      "\nnpi*.debug=true\nnpi*.info=true"};
Referenced by applyStartupFilterRules_(), and GetFilterBaseRules_().
coloredConsole_
std::atomic_bool anonymous_namespace{Log.cpp}::LogCore::coloredConsole_ {false} private
Definition at line 1846 of file Log.cpp.
{false};
Referenced by getStartupSettings_(), isConsoleColored_(), setColoredConsole_(), and startDisplay_().
ConfigFileName_
QLatin1StringView anonymous_namespace{Log.cpp}::LogCore::ConfigFileName_ {"log_config.ini"} static constexpr private
Definition at line 1450 of file Log.cpp.
{"log_config.ini"};
Referenced by getFutureDir_(), getMaxFolderSizeMb_(), getStartupSettings_(), and saveSettings_().
configLockName_
const QString anonymous_namespace{Log.cpp}::LogCore::configLockName_ {QStringLiteral("npi-") % npi::AppMetaData::Name_ % QLatin1StringView("-log-config-lock")} private
Definition at line 1484 of file Log.cpp.
{QStringLiteral("npi-") % npi::AppMetaData::Name_ % QLatin1StringView("-log-config-lock")};
Referenced by getFutureDir_(), getMaxFolderSizeMb_(), getStartupSettings_(), and saveSettings_().
currentMaxMb_
std::atomic<qint64> anonymous_namespace{Log.cpp}::LogCore::currentMaxMb_ {DefaultMaxFolderSizeMb_} private
Definition at line 1824 of file Log.cpp.
{DefaultMaxFolderSizeMb_};
Referenced by LogCore(), getMaxFolderSizeMb_(), and setMaxFolderSizeMb_().
DefaultDirName_
QLatin1StringView anonymous_namespace{Log.cpp}::LogCore::DefaultDirName_ {"logs"} static constexpr private
Definition at line 1451 of file Log.cpp.
{"logs"};
Referenced by LogCore().
DefaultMaxFolderSizeMb_
qint64 anonymous_namespace{Log.cpp}::LogCore::DefaultMaxFolderSizeMb_ {512} static constexpr private
Definition at line 1452 of file Log.cpp.
{512};
Referenced by LogCore(), getMaxFolderSizeMb_(), getStartupSettings_(), and setMaxFolderSizeMb_().
defDir_
const QString anonymous_namespace{Log.cpp}::LogCore::defDir_ private
Definition at line 1857 of file Log.cpp.
Referenced by LogCore(), getCurrentDirFromSettings_(), and getStartupSettings_().
defLogFields_
const QList<Field> anonymous_namespace{Log.cpp}::LogCore::defLogFields_ private
Initial value:
{
      Field::DateTime,
      Field::ThreadHexId,
      Field::Level,
      Field::Category,
      Field::FileLine,
      Field::Function
    }
Definition at line 1580 of file Log.cpp.
{
      Field::DateTime,
      Field::ThreadHexId,
      Field::Level,
      Field::Category,
      Field::FileLine,
      Field::Function
    };
Referenced by LogCore(), and getStartupSettings_().
defMsgFields_
const QList<Field> anonymous_namespace{Log.cpp}::LogCore::defMsgFields_ private
Initial value:
{
      Field::UpTime,
      Field::ThreadDelta,
      Field::ThreadNumber,
      Field::Level,
      Field::Category,
      Field::FileLine,
      Field::Function
    }
Definition at line 1589 of file Log.cpp.
{
      Field::UpTime,
      Field::ThreadDelta,
      Field::ThreadNumber,
      Field::Level,
      Field::Category,
      Field::FileLine,
      Field::Function
    };
Referenced by LogCore(), and getStartupSettings_().
DeltaUnits_
std::array<UnitInfo, 5> anonymous_namespace{Log.cpp}::LogCore::DeltaUnits_ static constexpr private
Initial value:
= {{
      {.scale_ = Q_INT64_C(100), .suffix_ = 'u'},
      {.scale_ = Q_INT64_C(100000), .suffix_ = 'z'},
      {.scale_ = Q_INT64_C(100000000), .suffix_ = 's'},
      {.scale_ = Q_INT64_C(6000000000), .suffix_ = 'm'},
      {.scale_ = Q_INT64_C(360000000000), .suffix_ = 'h'}
    }}
Definition at line 1475 of file Log.cpp.
                                                         {{
      {.scale_ = Q_INT64_C(100), .suffix_ = 'u'},
      {.scale_ = Q_INT64_C(100000), .suffix_ = 'z'},
      {.scale_ = Q_INT64_C(100000000), .suffix_ = 's'},
      {.scale_ = Q_INT64_C(6000000000), .suffix_ = 'm'},
      {.scale_ = Q_INT64_C(360000000000), .suffix_ = 'h'}
    }};
Referenced by AppendDelta_().
dirCleaningLockName_
const QString anonymous_namespace{Log.cpp}::LogCore::dirCleaningLockName_ {QStringLiteral("npi-") % npi::AppMetaData::Name_ % QLatin1StringView("-log-dir-cleaning-lock")} private
Definition at line 1485 of file Log.cpp.
{QStringLiteral("npi-") % npi::AppMetaData::Name_ % QLatin1StringView("-log-dir-cleaning-lock")};
Referenced by LogCore().
dispQueue_
moodycamel::ConcurrentQueue<OneLog> anonymous_namespace{Log.cpp}::LogCore::dispQueue_ {20480} private
Definition at line 1850 of file Log.cpp.
{20480};
Referenced by startDisplay_(), and startWriting_().
dispThread_
std::jthread anonymous_namespace{Log.cpp}::LogCore::dispThread_ private
Definition at line 1854 of file Log.cpp.
Referenced by initiateShutdown_(), and startDisplay_().
dispThreadRunning_
std::atomic_bool anonymous_namespace{Log.cpp}::LogCore::dispThreadRunning_ {false} private
Definition at line 1852 of file Log.cpp.
{false};
Referenced by initiateShutdown_(), startDisplay_(), and startWriting_().
DrainInterval_
std::chrono::milliseconds anonymous_namespace{Log.cpp}::LogCore::DrainInterval_ {100} static constexpr private
Definition at line 1453 of file Log.cpp.
{100};
Referenced by startDisplay_(), and startWriting_().
fieldHash_
const QHash<QString, Field> anonymous_namespace{Log.cpp}::LogCore::fieldHash_ private
Definition at line 1514 of file Log.cpp.
{
      // DateTime mappings
      {"datetime", Field::DateTime},
      {"date", Field::DateTime},
      {"time", Field::DateTime},
      {"dt", Field::DateTime},
      // UpTime mappings
      {"uptime", Field::UpTime},
      {"since", Field::UpTime},
      {"apptime", Field::UpTime},
      // ThreadTime mappings
      {"threadtime", Field::ThreadTime},
      {"sincethreadstart", Field::ThreadTime},
      {"sincethread", Field::ThreadTime},
      {"sincet", Field::ThreadTime},
      {"tsince", Field::ThreadTime},
      {"tt", Field::ThreadTime},
      // ThreadDelta mappings
      {"threaddelta", Field::ThreadDelta},
      {"deltathread", Field::ThreadDelta},
      {"deltat", Field::ThreadDelta},
      {"tdelta", Field::ThreadDelta},
      {"delta", Field::ThreadDelta},
      {"td", Field::ThreadDelta},
      // ThreadNumber mappings
      {"threadnumber", Field::ThreadNumber},
      {"threadnum", Field::ThreadNumber},
      {"nthread", Field::ThreadNumber},
      {"tnum", Field::ThreadNumber},
      {"tn", Field::ThreadNumber},
      // ThreadHexId mappings
      {"threadhexid", Field::ThreadHexId},
      {"threadhex", Field::ThreadHexId},
      {"threadid", Field::ThreadHexId},
      {"tid", Field::ThreadHexId},
      // Level mappings
      {"loglevel", Field::Level},
      {"level", Field::Level},
      {"lvl", Field::Level},
      {"ll", Field::Level},
      // Category mappings
      {"logcategory", Field::Category},
      {"category", Field::Category},
      {"logcat", Field::Category},
      {"cat", Field::Category},
      {"lc", Field::Category},
      // FileLine mappings
      {"fileline", Field::FileLine},
      {"file", Field::FileLine},
      {"line", Field::FileLine},
      {"fl", Field::FileLine},
      // Function mappings
      {"function", Field::Function},
      {"func", Field::Function},
      {"fn", Field::Function}
    };
Referenced by stringsToFields_().
fileBaseName_
const QString anonymous_namespace{Log.cpp}::LogCore::fileBaseName_ private
Definition at line 1859 of file Log.cpp.
Referenced by LogCore(), startImpLogProcess_(), and startWriting_().
fileQueue_
moodycamel::ConcurrentQueue<OneLog> anonymous_namespace{Log.cpp}::LogCore::fileQueue_ {20480} private
Definition at line 1849 of file Log.cpp.
{20480};
Referenced by msgHandler_(), and startWriting_().
fileThread_
std::jthread anonymous_namespace{Log.cpp}::LogCore::fileThread_ private
Definition at line 1853 of file Log.cpp.
Referenced by initiateShutdown_(), and startWriting_().
fileThreadRunning_
std::atomic_bool anonymous_namespace{Log.cpp}::LogCore::fileThreadRunning_ {false} private
Definition at line 1851 of file Log.cpp.
{false};
Referenced by initiateShutdown_(), and startWriting_().
filterRules_
QStringList anonymous_namespace{Log.cpp}::LogCore::filterRules_ private
Definition at line 1834 of file Log.cpp.
Referenced by LogCore(), applyStartupFilterRules_(), and getFilterRules_().
filterRulesLock_
QReadWriteLock anonymous_namespace{Log.cpp}::LogCore::filterRulesLock_ private
Definition at line 1833 of file Log.cpp.
Referenced by LogCore(), applyStartupFilterRules_(), getFilterRules_(), and getFilterRulesTempState_().
filterRulesTempState_
bool anonymous_namespace{Log.cpp}::LogCore::filterRulesTempState_ {false} private
Definition at line 1835 of file Log.cpp.
{false};
Referenced by LogCore(), and getFilterRulesTempState_().
FlushInterval_
std::chrono::milliseconds anonymous_namespace{Log.cpp}::LogCore::FlushInterval_ {500} static constexpr private
Definition at line 1454 of file Log.cpp.
{500};
Referenced by startWriting_().
initialLogs_
QList<InitialLog> anonymous_namespace{Log.cpp}::LogCore::initialLogs_ private
Definition at line 1821 of file Log.cpp.
Referenced by LogCore(), getStartupSettings_(), insertLogMessage_(), and writeInitialLogs_().
initialLogsMutex_
std::mutex anonymous_namespace{Log.cpp}::LogCore::initialLogsMutex_ private
Definition at line 1820 of file Log.cpp.
Referenced by insertLogMessage_().
logCategories_
QStringList anonymous_namespace{Log.cpp}::LogCore::logCategories_ private
Definition at line 1838 of file Log.cpp.
Referenced by addLogCategory_(), and getLogCategories_().
logCategoriesLock_
QReadWriteLock anonymous_namespace{Log.cpp}::LogCore::logCategoriesLock_ private
Definition at line 1837 of file Log.cpp.
Referenced by addLogCategory_(), and getLogCategories_().
logConfig_
FieldConfig anonymous_namespace{Log.cpp}::LogCore::logConfig_ private
Definition at line 1830 of file Log.cpp.
Referenced by LogCore(), getFields_(), getFieldTempState_(), and startWriting_().
maxMbLastChangeTime_
std::atomic<int64_t> anonymous_namespace{Log.cpp}::LogCore::maxMbLastChangeTime_ {0} private
Definition at line 1825 of file Log.cpp.
{0}; // Timestamp (steady_clock ms)
Referenced by LogCore(), getMaxFolderSizeMb_(), and setMaxFolderSizeMb_().
maxMbSettingsMutex_
std::mutex anonymous_namespace{Log.cpp}::LogCore::maxMbSettingsMutex_ private
Definition at line 1826 of file Log.cpp.
Referenced by LogCore().
maxMbThread_
std::jthread anonymous_namespace{Log.cpp}::LogCore::maxMbThread_ private
Definition at line 1828 of file Log.cpp.
Referenced by LogCore(), and initiateShutdown_().
maxMbThreadWakeup_
std::condition_variable_any anonymous_namespace{Log.cpp}::LogCore::maxMbThreadWakeup_ private
Definition at line 1827 of file Log.cpp.
Referenced by LogCore(), initiateShutdown_(), and setMaxFolderSizeMb_().
msgConfig_
FieldConfig anonymous_namespace{Log.cpp}::LogCore::msgConfig_ private
Definition at line 1831 of file Log.cpp.
Referenced by LogCore(), getFields_(), getFieldTempState_(), and startDisplay_().
muteDisplay_
std::atomic_bool anonymous_namespace{Log.cpp}::LogCore::muteDisplay_ {false} private
Definition at line 1847 of file Log.cpp.
{false}; // stops display and discards
Referenced by isDisplayMuted_(), setMuteDisplay_(), and startWriting_().
permConsole_
const bool anonymous_namespace{Log.cpp}::LogCore::permConsole_ private
Definition at line 1856 of file Log.cpp.
Referenced by LogCore(), isConsoleOpen_(), isPermanentConsole_(), openConsole_(), and startDisplay_().
prevLogFilter_
std::atomic<QLoggingCategory::CategoryFilter> anonymous_namespace{Log.cpp}::LogCore::prevLogFilter_ = nullptr
Definition at line 1011 of file Log.cpp.
runtimeLogs_
std::atomic_bool anonymous_namespace{Log.cpp}::LogCore::runtimeLogs_ {false} private
Definition at line 1822 of file Log.cpp.
{false};
Referenced by insertLogMessage_().
SettingsColoredConsoleKey_
QLatin1StringView anonymous_namespace{Log.cpp}::LogCore::SettingsColoredConsoleKey_ {"ColoredConsole"} static constexpr private
Definition at line 1447 of file Log.cpp.
{"ColoredConsole"};
Referenced by getStartupSettings_(), and setColoredConsole_().
SettingsDirKey_
QLatin1StringView anonymous_namespace{Log.cpp}::LogCore::SettingsDirKey_ {"CurrentDirectory"} static constexpr private
Definition at line 1442 of file Log.cpp.
{"CurrentDirectory"};
Referenced by getCurrentDirFromSettings_(), and getStartupSettings_().
SettingsFilterRulesKey_
QLatin1StringView anonymous_namespace{Log.cpp}::LogCore::SettingsFilterRulesKey_ {"FilterRules"} static constexpr private
Definition at line 1446 of file Log.cpp.
{"FilterRules"};
Referenced by getStartupSettings_().
SettingsLogFieldsKey_
QLatin1StringView anonymous_namespace{Log.cpp}::LogCore::SettingsLogFieldsKey_ {"LogFields"} static constexpr private
Definition at line 1444 of file Log.cpp.
{"LogFields"};
Referenced by getStartupSettings_().
SettingsMaxFolderSizeKey_
QLatin1StringView anonymous_namespace{Log.cpp}::LogCore::SettingsMaxFolderSizeKey_ {"MaxFolderSizeMB"} static constexpr private
Definition at line 1443 of file Log.cpp.
{"MaxFolderSizeMB"};
Referenced by LogCore(), getMaxFolderSizeMb_(), and getStartupSettings_().
SettingsMsgFieldsKey_
QLatin1StringView anonymous_namespace{Log.cpp}::LogCore::SettingsMsgFieldsKey_ {"MsgFields"} static constexpr private
Definition at line 1445 of file Log.cpp.
{"MsgFields"};
Referenced by getStartupSettings_().
SettingsWarnIsImpKey_
QLatin1StringView anonymous_namespace{Log.cpp}::LogCore::SettingsWarnIsImpKey_ {"WarnIsImp"} static constexpr private
Definition at line 1448 of file Log.cpp.
{"WarnIsImp"};
Referenced by getStartupSettings_(), and setWarnIsImp_().
shutdownMode_
std::atomic_bool anonymous_namespace{Log.cpp}::LogCore::shutdownMode_ {false} private
Definition at line 1842 of file Log.cpp.
{false};
Referenced by msgHandler_(), and startWriting_().
startTp_
const std::chrono::steady_clock::time_point anonymous_namespace{Log.cpp}::LogCore::startTp_ = std::chrono::steady_clock::now() private
Definition at line 1483 of file Log.cpp.
Referenced by msgHandler_(), and startWriting_().
startup_
const StartupSettings anonymous_namespace{Log.cpp}::LogCore::startup_ private
Definition at line 1858 of file Log.cpp.
Referenced by LogCore(), getDir_(), getFutureDir_(), startImpLogProcess_(), and startWriting_().
tempConsole_
std::atomic_bool anonymous_namespace{Log.cpp}::LogCore::tempConsole_ {false} private
Definition at line 1845 of file Log.cpp.
{false};
Referenced by closeConsole_(), isConsoleOpen_(), openConsole_(), and startDisplay_().
threadCounter_
std::atomic_uint64_t anonymous_namespace{Log.cpp}::LogCore::threadCounter_ {0} private
Definition at line 1840 of file Log.cpp.
{0};
Referenced by msgHandler_().
warnIsImp_
std::atomic_bool anonymous_namespace{Log.cpp}::LogCore::warnIsImp_ {false} private
Definition at line 1843 of file Log.cpp.
{false};
Referenced by getStartupSettings_(), isWarnImp_(), msgHandler_(), and setWarnIsImp_().
The documentation for this class was generated from the following file:
Log.cpp