Main Project: npi::LinkHost< T > Class Template Reference
npi::LinkHost< T > Class Template Reference
A thread-safe, owning host that manages an object of type T and notifies linked pointers upon destruction.
#include <Link.hpp>
Classes
struct Obs
Inner observer type holding a type-erased pointer to the object. Used to broadcast the lifetime of the main object to Link objects.
Public Member Functions
LinkHost () noexcept=default
Default constructor.
LinkHost (const LinkHost &other) noexcept=default
Default copy constructor.
template<typename U>
requires PolymorphicallyRelated<T, U>
LinkHost (const LinkHost< U > &other)
Polymorphic converting copy constructor.
LinkHost (LinkHost &&other) noexcept=default
Default move constructor.
template<typename Deleter = std::default_delete<T>>
LinkHost (T *ptr, Deleter deleter=Deleter{})
Construct a LinkHost that owns a raw pointer with an optional custom deleter.
~LinkHost () noexcept=default
Default destructor.
LinkHost< T > duplicateWithNewLocal_ () const
Duplicate host with a new local observer.
T * get_ () const noexcept
Retrieve the raw pointer to the hosted object.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool isSame_ (const LinkHost< U > &other) const noexcept
Check whether two LinkHost instances refer to the same object and observers (universal and local). For checking just the object (without the local observer) use the equality operators.
bool isValid_ () const noexcept
Check whether the host owns an object.
Link< T > local_ () const noexcept
Create a local Link object tied to the local observer. This Link object will remain valid as long as a copy of the local observer exists (copying the LinkHost object also copies the local observer).
operator bool () const noexcept
Explicit boolean conversion operator (e.g. if(linkHost){...}).
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const Link< U > &other) const noexcept
Compare this LinkHost object to a Link object for inequality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const LinkHost< U > &other) const noexcept
Compare this LinkHost object to another LinkHost object for inequality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const U *raw) const noexcept
Compare to raw pointer for inequality.
bool operator!= (std::nullptr_t) const noexcept
Inequality comparison with a null pointer.
T & operator* () const noexcept
Dereference operator to obtain a reference to the hosted object.
T * operator-> () const noexcept
Pointer-like access operator.
LinkHost & operator= (const LinkHost &other) noexcept=default
Default copy assignment operator.
template<typename U>
requires PolymorphicallyRelated<T, U>
LinkHost & operator= (const LinkHost< U > &other)
Polymorphic assignment operator.
LinkHost & operator= (LinkHost &&other) noexcept=default
Default move assignment operator.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const Link< U > &other) const noexcept
Compare this LinkHost object to a Link object for equality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const LinkHost< U > &other) const noexcept
Compare this LinkHost object to another LinkHost object for equality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const U *raw) const noexcept
Compare to raw pointer for equality.
bool operator== (std::nullptr_t) const noexcept
Compare the stored pointer to a null pointer.
std::shared_ptr< T > pureShared_ () const noexcept
Obtain the underlying std::shared_ptr<T> object. This object can be used as an independent shared pointer to the hosted object. Using this shared pointer will not affect the functionality of LinkHost or other Link-Family classes.
void reset_ () noexcept
Reset the host, releasing the object and invalidating all links.
void swap_ (LinkHost &other) noexcept
Member swap.
Link< T > universal_ () const noexcept
Create a universal Link object tied to the universal observer. This Link object will remain valid as long as the hosted object is alive.
LinkWeakHost< T > weakHost_ () const noexcept
Create a LinkWeakHost object i.e. weak reference to LinkHost. Similar to what std::weak_ptr does for std::shared_ptr. Will also hold a weak reference to the local observer in the LinkHost.
Private Member Functions
LinkHost (const std::shared_ptr< T > &obj, const std::shared_ptr< Obs > &uni, const std::shared_ptr< Obs > &loc) noexcept
Private constructor for duplicates with custom observers.
template<typename U>
requires PolymorphicallyRelated<T, U>
void assign_ (const LinkHost< U > &other)
Internal helper to assign from another polymorphically related LinkHost object.
Private Attributes
std::shared_ptr< Obs > loc_ {nullptr}
Local observer that is valid as long as the last local copy of LinkHost is alive.
std::shared_ptr< T > obj_ {nullptr}
The owned object of type T wrapped in a shared pointer.
std::shared_ptr< Obs > uni_ {nullptr}
Universal observer that is valid as long as the object is alive.
Friends
template<typename U>
class LinkHost
Friend declarations of LinkHost class with type as U. This makes any LinkHost class object a friend of any other LinkHost class object.
template<typename U>
class Link
Friend declarations of Link class.
template<typename U>
class LinkFromThis
Friend declarations of LinkFromThis class.
template<typename U>
class LinkWeakHost
Friend declarations of LinkWeakHost class.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const U *raw, const LinkHost< T > &linkHost) noexcept
Compare raw pointer (lhs) to a LinkHost object for inequality.
bool operator!= (std::nullptr_t, const LinkHost< T > &linkHost) noexcept
Inequality comparison between a null pointer and the stored pointer.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const U *raw, const LinkHost< T > &linkHost) noexcept
Compare raw pointer (lhs) to a LinkHost object for equality.
bool operator== (std::nullptr_t, const LinkHost< T > &linkHost) noexcept
Compare a null pointer to the stored pointer.
void swap (LinkHost< T > &a, LinkHost< T > &b) noexcept
Swap two hosts.
Detailed Description
template<typename T>
class npi::LinkHost< T >
A thread-safe, owning host that manages an object of type T and notifies linked pointers upon destruction.
Behaves like a std::shared_ptr i.e. owns the object T and destroys it when the last reference is released.
Provides direct pointer-like access to the object.
Supports polymorphic conversion and comparison.
Maintains two Link channels: Universal and Local.
Link object obtained through Universal channel is valid while the object is alive.
Link object obtained through Local channel is valid only while the last local copy of LinkHost is alive.
Template Parameters
T The type of the object being hosted.
Example of creating and using links:
LinkHost<MyClass> host(new MyClass());
auto link = host.universal_();
if (link) link->doSomething_();
Definition at line 546 of file Link.hpp.
Constructor & Destructor Documentation
LinkHost() [1/6]
template<typename T> npi::LinkHost< T >::LinkHost () default noexcept
Default constructor.
LinkHost() [2/6]
template<typename T> npi::LinkHost< T >::LinkHost (const LinkHost< T > & other) default noexcept
Default copy constructor.
References LinkHost.
LinkHost() [3/6]
template<typename T> npi::LinkHost< T >::LinkHost (LinkHost< T > && other) default noexcept
Default move constructor.
References LinkHost.
~LinkHost()
template<typename T> npi::LinkHost< T >::~LinkHost () default noexcept
Default destructor.
References LinkHost.
LinkHost() [4/6]
template<typename T> template<typename Deleter = std::default_delete<T>> npi::LinkHost< T >::LinkHost (T * ptr, Deleter deleter = Deleter{}) inline explicit
Construct a LinkHost that owns a raw pointer with an optional custom deleter.
Template Parameters
Deleter The type of the deleter used to destroy the object.
Parameters
ptr The raw pointer to the object being hosted.
deleter The deleter to call when the object is destroyed.
Note
If T inherits from LinkFromThis<T>, sets up weakUni_ inside the object.
Stores ptr and deleter into obj_.
Creates both uni_ and loc_ observers pointing at the object.
If the object supports LinkFromThis, registers the universal observer inside it.
Definition at line 576 of file Link.hpp.
                                                       {})
      : obj_{ptr, std::move(deleter)},
        uni_{std::make_shared<Obs>(ptr)},
        loc_{std::make_shared<Obs>(ptr)} {
      if(auto linkFromThis = dynamic_cast<LinkFromThis<T>*>(ptr))
        linkFromThis->weakUni_ = uni_;
    }
References LinkHost.
LinkHost() [5/6]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> npi::LinkHost< T >::LinkHost (const LinkHost< U > & other) inline
Polymorphic converting copy constructor.
Template Parameters
U The type of the other hosted object; must be polymorphically related to T.
Parameters
other The LinkHost instance to copy from.
Exceptions
std::bad_cast if a safe downcast from U to T fails.
Precondition
U must be polymorphically related to T.
Delegates to assign_() helper to perform casting and observer wiring.
Definition at line 592 of file Link.hpp.
{ assign_(other); }
References LinkHost, and assign_().
LinkHost() [6/6]
template<typename T> npi::LinkHost< T >::LinkHost (const std::shared_ptr< T > & obj, const std::shared_ptr< Obs > & uni, const std::shared_ptr< Obs > & loc) inline private noexcept
Private constructor for duplicates with custom observers.
Parameters
obj Shared ownership of the object.
uni Shared universal observer.
loc Shared local observer.
Definition at line 877 of file Link.hpp.
      : obj_{obj}, uni_{uni}, loc_{loc} {}
References obj_.
Member Function Documentation
assign_()
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> void npi::LinkHost< T >::assign_ (const LinkHost< U > & other) inline private
Internal helper to assign from another polymorphically related LinkHost object.
Template Parameters
U The type of object to assign from; must be polymorphically related to T.
Parameters
other The LinkHost object to copy from.
Exceptions
std::bad_cast if a safe downcast from U* to T* fails.
Precondition
U must be polymorphically related to T.
Note
Private function for internal use only.
If identical, return.
If other.get_() non-null:
Upcast via static_pointer_cast if U->T (i.e. if U is T or derived from T).
Otherwise downcast via dynamic_pointer_cast, throwing std::bad_cast on failure.
Copy uni_ and loc_.
Update weakUni_ if applicable.
Else reset obj_, uni_, and loc_ to empty (using reset_()).
Definition at line 898 of file Link.hpp.
{
      // Skip assignment if the pointers are the same (isSame_() also checks the loc_ pointer)
      if(isSame_(other))
        return;
      if(auto raw = other.get_(); raw) {
        std::shared_ptr<T> obj;
        if constexpr(std::is_same_v<T, U> || std::is_base_of_v<T, U>) {
          // Upcast: If T and U are the same or T is a base of U.
          // Use static_pointer_cast since it is safe to use here.
          obj = std::static_pointer_cast<T>(other.obj_);
        }
        else {
          // Downcast: If T is not a base of U, use dynamic_pointer_cast to ensure safe downcasting.
          // The use of dynamic_pointer_cast requires U to be polymorphic.
          // Throw std::bad_cast if the cast fails.
          static_assert(std::is_polymorphic_v<U>, "U must be polymorphic for dynamic_cast");
          obj = std::dynamic_pointer_cast<T>(other.obj_);
          if(!obj)
            throw std::bad_cast();
        }
        // Assign the new object and observers
        obj_ = std::move(obj);
        uni_ = other.uni_;
        loc_ = other.loc_;
        // Update the weakUni_ pointer if applicable
        if(auto* linkFromThis = dynamic_cast<LinkFromThis<T>*>(obj_.get()))
          linkFromThis->weakUni_ = uni_;
      }
      else {
        // If the raw pointer is null, reset the shared pointers to null.
        reset_();
      }
    }
References LinkHost, get_(), isSame_(), LinkFromThis, loc_, obj_, reset_(), and uni_.
Referenced by LinkHost(), and operator=().
duplicateWithNewLocal_()
template<typename T> LinkHost< T > npi::LinkHost< T >::duplicateWithNewLocal_ () const inline
Duplicate host with a new local observer.
Returns
A new LinkHost with a new local observer while sharing the same object.
Definition at line 693 of file Link.hpp.
{ return LinkHost<T>{obj_, uni_, std::make_shared<Obs>(obj_.get())}; }
References LinkHost, obj_, and uni_.
get_()
template<typename T> T * npi::LinkHost< T >::get_ () const inline nodiscard noexcept
Retrieve the raw pointer to the hosted object.
Returns
A pointer to T or nullptr if empty.
Note
This method is noexcept and [[nodiscard]].
Definition at line 624 of file Link.hpp.
{ return obj_.get(); }
References obj_.
Referenced by assign_(), isValid_(), operator!=(), operator*(), operator->(), operator==(), operator==(), operator==(), and operator==().
isSame_()
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::LinkHost< T >::isSame_ (const LinkHost< U > & other) const inline noexcept
Check whether two LinkHost instances refer to the same object and observers (universal and local). For checking just the object (without the local observer) use the equality operators.
Template Parameters
U The type of the other hosted object; must be polymorphically related to T.
Parameters
other The LinkHost to compare against.
Returns
true if both host the same object and observers (universal and local).
Definition at line 615 of file Link.hpp.
{
      return obj_.get() == other.obj_.get()
             && uni_.get() == other.uni_.get()
             && loc_.get() == other.loc_.get();
    }
References LinkHost, loc_, obj_, and uni_.
Referenced by assign_().
isValid_()
template<typename T> bool npi::LinkHost< T >::isValid_ () const inline noexcept
Check whether the host owns an object.
Returns
true if non-null, false otherwise.
Definition at line 648 of file Link.hpp.
{ return get_() != nullptr; }
References get_().
Referenced by operator bool().
local_()
template<typename T> Link< T > npi::LinkHost< T >::local_ () const inline noexcept
Create a local Link object tied to the local observer. This Link object will remain valid as long as a copy of the local observer exists (copying the LinkHost object also copies the local observer).
Returns
A Link object that is valid as long as the local observer is alive.
Definition at line 684 of file Link.hpp.
{ return Link<T>{loc_->ptr_}; }
References Link, and loc_.
operator bool()
template<typename T> npi::LinkHost< T >::operator bool () const inline explicit noexcept
Explicit boolean conversion operator (e.g. if(linkHost){...}).
Returns
true if valid, false if empty.
Definition at line 652 of file Link.hpp.
{ return isValid_(); }
References isValid_().
operator!=() [1/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::LinkHost< T >::operator!= (const Link< U > & other) const inline noexcept
Compare this LinkHost object to a Link object for inequality.
Template Parameters
U Polymorphically related type.
Parameters
other The Link object to compare.
Returns
true if underlying pointers do not match.
Definition at line 784 of file Link.hpp.
{ return !(*this == other); }
References Link.
operator!=() [2/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::LinkHost< T >::operator!= (const LinkHost< U > & other) const inline noexcept
Compare this LinkHost object to another LinkHost object for inequality.
Template Parameters
U Polymorphically related type.
Parameters
other The LinkHost object to compare.
Returns
true if underlying pointers do not match.
Definition at line 800 of file Link.hpp.
{ return !(*this == other); }
References LinkHost.
operator!=() [3/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::LinkHost< T >::operator!= (const U * raw) const inline noexcept
Compare to raw pointer for inequality.
Template Parameters
U Polymorphically related type.
Parameters
raw Raw pointer to compare.
Returns
true if not pointing to the same object.
Definition at line 750 of file Link.hpp.
{ return !(*this == raw); }
operator!=() [4/4]
template<typename T> bool npi::LinkHost< T >::operator!= (std::nullptr_t) const inline noexcept
Inequality comparison with a null pointer.
Returns
true if the stored pointer is not null, false otherwise.
Definition at line 718 of file Link.hpp.
{
      return get_() != nullptr;
    }
References get_().
operator*()
template<typename T> T & npi::LinkHost< T >::operator* () const inline nodiscard noexcept
Dereference operator to obtain a reference to the hosted object.
Returns
A reference to T.
Precondition
get_() must not return nullptr.
Warning
Dereferencing a null pointer is undefined behavior.
Definition at line 640 of file Link.hpp.
{
      auto ptr = get_();
      assert(ptr && "LinkHost::operator* on nullptr");
      return *ptr;
    }
References get_().
operator->()
template<typename T> T * npi::LinkHost< T >::operator-> () const inline nodiscard noexcept
Pointer-like access operator.
Returns
A non-null T* suitable for member access.
Precondition
get_() must not return nullptr.
Warning
Dereferencing a null pointer is undefined behavior.
Definition at line 630 of file Link.hpp.
{
      auto ptr = get_();
      assert(ptr && "LinkHost::operator-> on nullptr");
      return ptr;
    }
References get_().
operator=() [1/3]
template<typename T> LinkHost & npi::LinkHost< T >::operator= (const LinkHost< T > & other) default noexcept
Default copy assignment operator.
References LinkHost.
operator=() [2/3]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> LinkHost & npi::LinkHost< T >::operator= (const LinkHost< U > & other) inline
Polymorphic assignment operator.
Template Parameters
U The type of the other hosted object; must be polymorphically related to T.
Parameters
other The LinkHost instance to assign from.
Exceptions
std::bad_cast if a safe downcast from U to T fails.
Precondition
U must be polymorphically related to T.
Returns
A reference to this LinkHost.
Uses assign_() helper for casting and observer wiring.
Definition at line 603 of file Link.hpp.
{
      assign_(other);
      return *this;
    }
References LinkHost, and assign_().
operator=() [3/3]
template<typename T> LinkHost & npi::LinkHost< T >::operator= (LinkHost< T > && other) default noexcept
Default move assignment operator.
References LinkHost.
operator==() [1/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::LinkHost< T >::operator== (const Link< U > & other) const inline noexcept
Compare this LinkHost object to a Link object for equality.
Template Parameters
U Polymorphically related type.
Parameters
other The Link object to compare.
Returns
true if underlying pointers match.
Definition at line 776 of file Link.hpp.
{ return get_() == other.get_(); }
References get_(), and Link.
operator==() [2/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::LinkHost< T >::operator== (const LinkHost< U > & other) const inline noexcept
Compare this LinkHost object to another LinkHost object for equality.
Template Parameters
U Polymorphically related type.
Parameters
other The LinkHost object to compare.
Returns
true if underlying pointers match.
Definition at line 792 of file Link.hpp.
{ return get_() == other.get_(); }
References LinkHost, and get_().
operator==() [3/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::LinkHost< T >::operator== (const U * raw) const inline noexcept
Compare to raw pointer for equality.
Template Parameters
U Polymorphically related type.
Parameters
raw Raw pointer to compare.
Returns
true if pointing to the same object.
Definition at line 742 of file Link.hpp.
{ return get_() == raw; }
References get_().
operator==() [4/4]
template<typename T> bool npi::LinkHost< T >::operator== (std::nullptr_t) const inline noexcept
Compare the stored pointer to a null pointer.
Returns
true if the stored pointer is null, false otherwise.
Definition at line 712 of file Link.hpp.
{
      return get_() == nullptr;
    }
References get_().
pureShared_()
template<typename T> std::shared_ptr< T > npi::LinkHost< T >::pureShared_ () const inline noexcept
Obtain the underlying std::shared_ptr<T> object. This object can be used as an independent shared pointer to the hosted object. Using this shared pointer will not affect the functionality of LinkHost or other Link-Family classes.
Returns
A shared pointer to the hosted object.
Note
Using the std::shared_ptr<T> obtained from this method does not in any way affect the LinkHost or other Link-Family classes.
Definition at line 708 of file Link.hpp.
{ return obj_; }
References obj_.
reset_()
template<typename T> void npi::LinkHost< T >::reset_ () inline noexcept
Reset the host, releasing the object and invalidating all links.
Calls reset() on obj_, uni_, and loc_ to release the object and observers.
Definition at line 656 of file Link.hpp.
{
      obj_.reset();
      uni_.reset();
      loc_.reset();
    }
References loc_, obj_, and uni_.
Referenced by assign_().
swap_()
template<typename T> void npi::LinkHost< T >::swap_ (LinkHost< T > & other) inline noexcept
Member swap.
Parameters
other LinkHost to swap with.
Definition at line 675 of file Link.hpp.
{
      using std::swap;
      swap(*this, other);
    }
References LinkHost, and swap.
universal_()
template<typename T> Link< T > npi::LinkHost< T >::universal_ () const inline noexcept
Create a universal Link object tied to the universal observer. This Link object will remain valid as long as the hosted object is alive.
Returns
A Link object that is valid as long as the hosted object is alive.
Definition at line 689 of file Link.hpp.
{ return Link<T>{uni_->ptr_}; }
References Link, and uni_.
weakHost_()
template<typename T> LinkWeakHost< T > npi::LinkHost< T >::weakHost_ () const inline noexcept
Create a LinkWeakHost object i.e. weak reference to LinkHost. Similar to what std::weak_ptr does for std::shared_ptr. Will also hold a weak reference to the local observer in the LinkHost.
Returns
A LinkWeakHost object that can be locked to get a copy of this LinkHost.
Definition at line 699 of file Link.hpp.
{ return LinkWeakHost<T>{*this}; }
References LinkWeakHost.
Friends And Related Symbol Documentation
LinkHost
template<typename T> template<typename U> friend class LinkHost friend
Friend declarations of LinkHost class with type as U. This makes any LinkHost class object a friend of any other LinkHost class object.
Definition at line 810 of file Link.hpp.
References LinkHost.
Referenced by LinkHost(), LinkHost(), LinkHost(), LinkHost(), LinkHost, ~LinkHost(), assign_(), duplicateWithNewLocal_(), isSame_(), operator!=(), operator!=, operator!=, operator=(), operator=(), operator=(), operator==(), operator==, operator==, swap, and swap_().
Link
template<typename T> template<typename U> friend class Link friend
Friend declarations of Link class.
Definition at line 805 of file Link.hpp.
References Link.
Referenced by Link, local_(), operator!=(), operator==(), and universal_().
LinkFromThis
template<typename T> template<typename U> friend class LinkFromThis friend
Friend declarations of LinkFromThis class.
Definition at line 818 of file Link.hpp.
References LinkFromThis.
Referenced by assign_(), and LinkFromThis.
LinkWeakHost
template<typename T> template<typename U> friend class LinkWeakHost friend
Friend declarations of LinkWeakHost class.
Definition at line 814 of file Link.hpp.
References LinkWeakHost.
Referenced by LinkWeakHost, and weakHost_().
operator!= [1/2]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool operator!= (const U * raw, const LinkHost< T > & linkHost) friend
Compare raw pointer (lhs) to a LinkHost object for inequality.
Template Parameters
U Polymorphically related type.
Parameters
raw Raw pointer.
linkHost The LinkHost object to compare.
Returns
true if both linkHost and raw do not point to the same object.
Definition at line 768 of file Link.hpp.
{ return !(linkHost == raw); }
References LinkHost.
operator!= [2/2]
template<typename T> bool operator!= (std::nullptr_t , const LinkHost< T > & linkHost) friend
Inequality comparison between a null pointer and the stored pointer.
Parameters
linkHost A LinkHost object instance.
Returns
true if the stored pointer is not null, false otherwise.
Definition at line 732 of file Link.hpp.
{
      return linkHost.get_() != nullptr;
    }
References LinkHost.
operator== [1/2]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool operator== (const U * raw, const LinkHost< T > & linkHost) friend
Compare raw pointer (lhs) to a LinkHost object for equality.
Template Parameters
U Polymorphically related type.
Parameters
raw Raw pointer.
linkHost The LinkHost object to compare.
Returns
true if both linkHost and raw point to the same object.
Definition at line 759 of file Link.hpp.
{ return linkHost.get_() == raw; }
References LinkHost.
operator== [2/2]
template<typename T> bool operator== (std::nullptr_t , const LinkHost< T > & linkHost) friend
Compare a null pointer to the stored pointer.
Parameters
linkHost A LinkHost object instance.
Returns
true if the stored pointer is null, false otherwise.
Definition at line 725 of file Link.hpp.
{
      return linkHost.get_() == nullptr;
    }
References LinkHost.
swap
template<typename T> void swap (LinkHost< T > & a, LinkHost< T > & b) friend
Swap two hosts.
Parameters
a First host.
b Second host.
Swaps obj_, uni_, and loc_.
Definition at line 666 of file Link.hpp.
{
      using std::swap;
      swap(a.obj_, b.obj_);
      swap(a.uni_, b.uni_);
      swap(a.loc_, b.loc_);
    }
References LinkHost, and swap.
Referenced by swap, and swap_().
Member Data Documentation
loc_
template<typename T> std::shared_ptr<Obs> npi::LinkHost< T >::loc_ {nullptr} private
Local observer that is valid as long as the last local copy of LinkHost is alive.
Definition at line 871 of file Link.hpp.
{nullptr};
Referenced by assign_(), isSame_(), local_(), and reset_().
obj_
template<typename T> std::shared_ptr<T> npi::LinkHost< T >::obj_ {nullptr} private
The owned object of type T wrapped in a shared pointer.
Definition at line 865 of file Link.hpp.
{nullptr};
Referenced by LinkHost(), assign_(), duplicateWithNewLocal_(), get_(), isSame_(), pureShared_(), and reset_().
uni_
template<typename T> std::shared_ptr<Obs> npi::LinkHost< T >::uni_ {nullptr} private
Universal observer that is valid as long as the object is alive.
Definition at line 868 of file Link.hpp.
{nullptr};
Referenced by assign_(), duplicateWithNewLocal_(), isSame_(), reset_(), and universal_().
The documentation for this class was generated from the following file:
Link.hpp