Main Project: anonymous_namespace{Log.cpp} Namespace Reference
anonymous_namespace{Log.cpp} Namespace Reference
Namespaces
namespace safe
Classes
class LogCore
Functions
void initLogging ()
void loggingCategoryFilter (QLoggingCategory *category)
void msgHandler (QtMsgType typ, const QMessageLogContext &ctx, const QString &msg)
void shuttingDown ()
Variables
constexpr size_t fileNameMaxLen = 4096
Function Documentation
initLogging()
void anonymous_namespace{Log.cpp}::initLogging ()
Definition at line 2983 of file Log.cpp.
  {
    static std::once_flag once;
    std::call_once(once, [] {
      auto logCore = LogCore::Inst_(); // fully construct logger
      auto old = QLoggingCategory::installFilter(loggingCategoryFilter);
      logCore->prevLogFilter_.store(old, std::memory_order_release);
      logCore->applyStartupFilterRules_();
      qInstallMessageHandler(msgHandler);
      safe::installCrashHandlers();
      logCore->writeInitialLogs_();
      if(std::atexit(shuttingDown) != 0)
        npiWarn << "Unable to register shutdown handler for LogCore";
    });
  }
References anonymous_namespace{Log.cpp}::LogCore::Inst_(), anonymous_namespace{Log.cpp}::safe::installCrashHandlers(), loggingCategoryFilter(), msgHandler(), npiWarn, and shuttingDown().
loggingCategoryFilter()
void anonymous_namespace{Log.cpp}::loggingCategoryFilter (QLoggingCategory * category)
Definition at line 2966 of file Log.cpp.
  {
    LogCore::Inst_()->addLogCategory_(category->categoryName());
    if(auto prev = LogCore::Inst_()->prevLogFilter_.load(std::memory_order_acquire))
      prev(category);
  }
References anonymous_namespace{Log.cpp}::LogCore::addLogCategory_(), and anonymous_namespace{Log.cpp}::LogCore::Inst_().
Referenced by initLogging().
msgHandler()
void anonymous_namespace{Log.cpp}::msgHandler (QtMsgType typ, const QMessageLogContext & ctx, const QString & msg)
Definition at line 2973 of file Log.cpp.
  {
    LogCore::Inst_()->msgHandler_(typ, ctx, msg);
  }
References anonymous_namespace{Log.cpp}::LogCore::Inst_(), and anonymous_namespace{Log.cpp}::LogCore::msgHandler_().
Referenced by initLogging().
shuttingDown()
void anonymous_namespace{Log.cpp}::shuttingDown ()
Definition at line 2978 of file Log.cpp.
  {
    ::LogCore::Inst_()->initiateShutdown_();
  }
References anonymous_namespace{Log.cpp}::LogCore::initiateShutdown_(), and anonymous_namespace{Log.cpp}::LogCore::Inst_().
Referenced by initLogging().
Variable Documentation
fileNameMaxLen
size_t anonymous_namespace{Log.cpp}::fileNameMaxLen = 4096 inline constexpr
Definition at line 86 of file Log.cpp.
Referenced by anonymous_namespace{Log.cpp}::safe::startImpLogProcess().