Main Project: npi::Link< T > Class Template Reference
npi::Link< T > Class Template Reference final
A thread-safe, non-owning, auto-nullifying safe pointer to an object of type T.
#include <Link.hpp>
Public Member Functions
Link () noexcept=default
Default constructor.
Link (const Link &other) noexcept=default
Default copy constructor.
template<typename U>
requires PolymorphicallyRelated<T, U>
Link (const Link< U > &other)
Polymorphic non-explicit converting copy constructor.
Link (Link &&other) noexcept=default
Default move constructor.
~Link () noexcept=default
Default destructor.
T * get_ () const noexcept
Retrieve a raw pointer to the managed object, if any.
bool isValid_ () const noexcept
Check whether the link currently holds a valid object.
operator bool () const noexcept
Explicit boolean conversion operator (e.g. if(link){...}).
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const Link< U > &other) const noexcept
Compare two Link objects for inequality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const LinkHost< U > &other) const noexcept
Compare this Link to a LinkHost for inequality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const U *raw) const noexcept
Inequality comparison with a raw pointer.
bool operator!= (std::nullptr_t) const noexcept
Inequality comparison with a null pointer.
T & operator* () const noexcept
Dereference operator to obtain a reference to the managed object.
T * operator-> () const noexcept
Pointer-like access operator.
Link & operator= (const Link &other) noexcept=default
Default copy assignment operator.
template<typename U>
requires PolymorphicallyRelated<T, U>
Link & operator= (const Link< U > &other)
Polymorphic assignment operator.
Link & operator= (Link &&other) noexcept=default
Default move assignment operator.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const Link< U > &other) const noexcept
Compare two Link objects for equality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const LinkHost< U > &other) const noexcept
Compare this Link to a LinkHost for equality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const U *raw) const noexcept
Compare the stored pointer to a raw pointer.
bool operator== (std::nullptr_t) const noexcept
Compare the stored pointer to a null pointer.
void reset_ () noexcept
Reset the link to empty.
void swap_ (Link &other) noexcept
Member swap function.
Public Attributes
int someValue_ {42}
Test variable.
Private Member Functions
Link (std::shared_ptr< std::atomic< void * > > ptr) noexcept
Private constructor that initializes the Link with a shared pointer. It used by other Link-Family of classes to create a Link instance.
template<typename U>
requires PolymorphicallyRelated<T, U>
void assign_ (const Link< U > &other)
Internal helper to assign from another polymorphically related Link object.
Private Attributes
std::shared_ptr< std::atomic< void * > > ptr_ {nullptr}
Pointer to the object being linked to. static_cast is used to ensure the correct type is provided in the get_() method.
Friends
template<typename U>
class Link
Friend declarations of Link class with type as U. This makes any Link class object a friend of any other Link class object.
template<typename U>
class LinkFromThis
Friend declarations of LinkFromThis class.
template<typename U>
class LinkHost
Friend declarations of LinkHost class.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const U *raw, const Link< T > &link) noexcept
Inequality comparison between a raw pointer and a Link object.
bool operator!= (std::nullptr_t, const Link< T > &link) noexcept
Inequality comparison between a null pointer and the stored pointer.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const U *raw, const Link< T > &link) noexcept
Compare a raw pointer to a Link object.
bool operator== (std::nullptr_t, const Link< T > &link) noexcept
Compare a null pointer to the stored pointer.
void swap (Link< T > &a, Link< T > &b) noexcept
Swap the contents of two Link objects.
Detailed Description
template<typename T>
class npi::Link< T >
A thread-safe, non-owning, auto-nullifying safe pointer to an object of type T.
Does not own the object T.
Object must be wrapped in LinkHost.
Provides safe pointer-like access to T.
Supports polymorphic conversion and comparison.
Offers a safe boolean conversion to check if the linked object is still alive.
Template Parameters
T The type of the object being linked to.
Example of using the explicit boolean operator:
Link<A> link;
// assignment from LinkHost<A>
if(link) {
  link->hello_(); // calling base class method
}
Definition at line 144 of file Link.hpp.
Constructor & Destructor Documentation
Link() [1/5]
template<typename T> npi::Link< T >::Link () default noexcept
Default constructor.
Link() [2/5]
template<typename T> npi::Link< T >::Link (const Link< T > & other) default noexcept
Default copy constructor.
References Link.
Link() [3/5]
template<typename T> npi::Link< T >::Link (Link< T > && other) default noexcept
Default move constructor.
References Link.
~Link()
template<typename T> npi::Link< T >::~Link () default noexcept
Default destructor.
References Link.
Link() [4/5]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> npi::Link< T >::Link (const Link< U > & other) inline
Polymorphic non-explicit converting copy constructor.
Template Parameters
U The type of the object being linked to; must be polymorphically related to T.
Parameters
other The Link object to copy from.
Exceptions
std::bad_cast if a safe downcast from U* to T* fails.
Precondition
U must be polymorphically related to T.
Note
This constructor is not explicit, allowing implicit conversions from Link<U> to Link<T>.
This routine does three things:
Equality check:
If the two pointers are already the same, it returns immediately.
Pointer assignment:
If U is T or derived from T, it does a static_cast (upcast).
Otherwise it does a dynamic_cast (downcast), throwing std::bad_cast if that fails.
Null reset:
If other.get_() is null, resets ptr_ to empty instead of assigning.
Definition at line 185 of file Link.hpp.
{
      assign_(other);
    }
References Link, and assign_().
Link() [5/5]
template<typename T> npi::Link< T >::Link (std::shared_ptr< std::atomic< void * > > ptr) inline explicit private noexcept
Private constructor that initializes the Link with a shared pointer. It used by other Link-Family of classes to create a Link instance.
Parameters
ptr Shared pointer to the atomic void pointer stored in the LinkHost object.
Definition at line 458 of file Link.hpp.
: ptr_{std::move(ptr)} {}
References ptr_.
Member Function Documentation
assign_()
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> void npi::Link< T >::assign_ (const Link< U > & other) inline private
Internal helper to assign from another polymorphically related Link object.
Template Parameters
U The type of object to assign from; must be polymorphically related to T.
Parameters
other The Link object to assign from.
Exceptions
std::bad_cast if a safe downcast from U* to T* fails.
Precondition
U must be polymorphically related to T.
Note
Private function for internal use only.
If identical, return.
If other.get_() non-null:
Upcast via static_cast if U->T (i.e. if U is T or derived from T).
Otherwise downcast via dynamic_cast, throwing std::bad_cast on failure.
Else reset ptr_ to empty. This routine does three things:
Equality check:
If the two pointers are already the same, it returns immediately.
Pointer assignment:
If U is T or derived from T, it does a static_cast (upcast).
Otherwise it does a dynamic_cast (downcast), throwing std::bad_cast if that fails.
Null reset:
If other.get_() is null, resets ptr_ to empty instead of assigning.
// Example of the dynamic_cast path:
if(auto raw = other.get_(); raw) {
  static_assert(std::is_polymorphic_v<U>);
  if(auto d = dynamic_cast<T*>(raw))
    ptr_ = other.ptr_;
  else
    throw std::bad_cast();
}
Definition at line 492 of file Link.hpp.
{
      // Skip assignment if the pointers are the same
      if(ptr_.get() == other.ptr_.get())
        return;
      if(auto raw = other.get_(); raw) {
        if constexpr(std::is_same_v<T, U> || std::is_base_of_v<T, U>) {
          // Upcast: If T and U are the same or T is a base of U.
          // Use static_cast since it is safe to use here.
          ptr_ = other.ptr_;
        }
        else {
          // Downcast: If T is not a base of U, use dynamic_cast to ensure safe downcasting.
          // The use of dynamic_cast requires U to be polymorphic.
          // Throw std::bad_cast if the cast fails.
          static_assert(std::is_polymorphic_v<U>, "U must be polymorphic for dynamic_cast");
          if(auto dynamicRaw = dynamic_cast<T*>(raw))
            ptr_ = other.ptr_;
          else
            throw std::bad_cast();
        }
      }
      else {
        // If the raw pointer is null, reset the shared pointer to null.
        ptr_.reset();
      }
    }
References Link, get_(), and ptr_.
Referenced by Link(), and operator=().
get_()
template<typename T> T * npi::Link< T >::get_ () const inline nodiscard noexcept
Retrieve a raw pointer to the managed object, if any.
Returns
A pointer to the object of type T, or nullptr if no object is set.
Warning
Check for validity before using the pointer to the object.
Note
This method is marked noexcept, so it guarantees not to throw.
It is also marked [[nodiscard]] to encourage callers to check for nullptr rather than silently ignoring the return value.
Because it performs an atomic load, it is safe to call concurrently from multiple threads (readers).
This method returns the underlying raw pointer of type T* that is stored inside an atomic wrapper within a std::shared_ptr. It performs the following steps:
Tests whether the internal std::shared_ptr<std::atomic<void*>> ptr_ is non-null.
If ptr_ is null, this method immediately returns nullptr.
If ptr_ is non-null, loads the stored void pointer atomically using std::memory_order_acquire to synchronize with any release stores that may have updated the pointer elsewhere. This ensures that all prior writes to the object are visible to the calling thread.
Uses static_cast<T*> to convert the void* to the correct object type and returns the resulting T*
Definition at line 234 of file Link.hpp.
{
      return ptr_ ? static_cast<T*>(ptr_->load(std::memory_order_acquire)) : nullptr;
    }
References ptr_.
Referenced by assign_(), isValid_(), operator!=(), operator*(), operator->(), operator==(), operator==(), operator==(), and operator==().
isValid_()
template<typename T> bool npi::Link< T >::isValid_ () const inline noexcept
Check whether the link currently holds a valid object.
Returns
true if the stored pointer is non-null (link is valid), false otherwise.
Calls get_() to obtain the raw pointer and compares it to nullptr. Returns true if get_() returns a non-null pointer, false otherwise.
Definition at line 293 of file Link.hpp.
{ return get_() != nullptr; }
References get_().
Referenced by operator bool().
operator bool()
template<typename T> npi::Link< T >::operator bool () const inline explicit noexcept
Explicit boolean conversion operator (e.g. if(link){...}).
Returns
true if the link holds a valid object, false if it is empty.
Enables use of Link<T> in boolean contexts (for example, if(link) {...}).
Internally calls isValid_() to determine the truth value.
Definition at line 300 of file Link.hpp.
{ return isValid_(); }
References isValid_().
operator!=() [1/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::Link< T >::operator!= (const Link< U > & other) const inline noexcept
Compare two Link objects for inequality.
Template Parameters
U Must be polymorphically related to T.
Parameters
other Another Link instance.
Returns
true if the links point to different objects.
Definition at line 413 of file Link.hpp.
{
      return !(*this == other);
    }
References Link.
operator!=() [2/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::Link< T >::operator!= (const LinkHost< U > & other) const inline noexcept
Compare this Link to a LinkHost for inequality.
Template Parameters
U Must be polymorphically related to T.
Parameters
other A LinkHost instance.
Returns
true if they point to different objects.
Definition at line 433 of file Link.hpp.
{
      return !(*this == other);
    }
References LinkHost.
operator!=() [3/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::Link< T >::operator!= (const U * raw) const inline noexcept
Inequality comparison with a raw pointer.
Template Parameters
U Must be polymorphically related to T.
Parameters
raw A raw pointer to an object of type U.
Returns
true if the underlying pointer does not equal raw.
Definition at line 371 of file Link.hpp.
{
      return !(*this == raw);
    }
operator!=() [4/4]
template<typename T> bool npi::Link< T >::operator!= (std::nullptr_t) const inline noexcept
Inequality comparison with a null pointer.
Returns
true if the stored pointer is not null, false otherwise.
Definition at line 337 of file Link.hpp.
{
      return get_() != nullptr;
    }
References get_().
operator*()
template<typename T> T & npi::Link< T >::operator* () const inline nodiscard noexcept
Dereference operator to obtain a reference to the managed object.
Returns
A reference to the managed object.
Precondition
get_() must not return nullptr. In release builds, dereferencing a null pointer is undefined behavior.
Postcondition
Returns a reference to the managed T object.
Warning
Check for validity before dereferencing.
Note
This operator is noexcept and [[nodiscard]] to convey that this operation does not throw and its result should be used.
Allows use of the dereference syntax *link to access the underlying object.
Calls get_() to atomically load the stored pointer.
Uses assert() to verify at runtime (in debug builds) that the pointer is not null. If the assertion fails, the program is terminated with an explanatory message.
Dereferences the pointer and returns a reference to T.
Definition at line 282 of file Link.hpp.
{
      auto ptr = get_();
      assert(ptr && "Link::operator* on nullptr");
      return *ptr;
    }
References get_().
operator->()
template<typename T> T * npi::Link< T >::operator-> () const inline nodiscard noexcept
Pointer-like access operator.
Returns
The non-null pointer to the managed T object.
Precondition
get_() must not return nullptr. In release builds, dereferencing a null pointer is undefined behavior.
Postcondition
Returns a valid T* suitable for member-access expressions.
Warning
Check for validity before dereferencing.
Note
Marked noexcept and [[nodiscard]] to convey that this operation does not throw and its result should be used.
Provides direct -> so that users of Link<T> can write link->member instead of link.get_()->member. Internally, this calls get_() and asserts that the result is non-null:
Calls get_() to perform the atomic load and type conversion.
Uses assert() to check at runtime (in debug builds) that the pointer is not null. If the assertion fails, the program is terminated with an explanatory message.
Returns the raw T* allowing access to the object's members.
Definition at line 258 of file Link.hpp.
{
      auto ptr = get_();
      assert(ptr && "Link::operator-> on nullptr");
      return ptr;
    }
References get_().
operator=() [1/3]
template<typename T> Link & npi::Link< T >::operator= (const Link< T > & other) default noexcept
Default copy assignment operator.
References Link.
operator=() [2/3]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> Link & npi::Link< T >::operator= (const Link< U > & other) inline
Polymorphic assignment operator.
Template Parameters
U The type of the object being linked to; must be polymorphically related to T.
Parameters
other The Link object to assign from.
Returns
A reference to this Link object.
Exceptions
std::bad_cast if a safe downcast from U* to T* fails.
Precondition
U must be polymorphically related to T.
This routine does three things:
Equality check:
If the two pointers are already the same, it returns immediately.
Pointer assignment:
If U is T or derived from T, it does a static_cast (upcast).
Otherwise it does a dynamic_cast (downcast), throwing std::bad_cast if that fails.
Null reset:
If other.get_() is null, resets ptr_ to empty instead of assigning.
Definition at line 206 of file Link.hpp.
{
      assign_(other);
      return *this;
    }
References Link, and assign_().
operator=() [3/3]
template<typename T> Link & npi::Link< T >::operator= (Link< T > && other) default noexcept
Default move assignment operator.
References Link.
operator==() [1/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::Link< T >::operator== (const Link< U > & other) const inline noexcept
Compare two Link objects for equality.
Template Parameters
U Must be polymorphically related to T.
Parameters
other Another Link instance.
Returns
true if both links point to the same object.
Definition at line 403 of file Link.hpp.
{
      return get_() == other.get_();
    }
References Link, and get_().
operator==() [2/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::Link< T >::operator== (const LinkHost< U > & other) const inline noexcept
Compare this Link to a LinkHost for equality.
Template Parameters
U Must be polymorphically related to T.
Parameters
other A LinkHost instance.
Returns
true if both point to the same object.
Definition at line 423 of file Link.hpp.
{
      return get_() == other.get_();
    }
References get_(), and LinkHost.
operator==() [3/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::Link< T >::operator== (const U * raw) const inline noexcept
Compare the stored pointer to a raw pointer.
Template Parameters
U Must be polymorphically related to T.
Parameters
raw A raw pointer to an object of type U.
Returns
true if the underlying pointer equals raw, false otherwise.
Definition at line 361 of file Link.hpp.
{
      return get_() == raw;
    }
References get_().
operator==() [4/4]
template<typename T> bool npi::Link< T >::operator== (std::nullptr_t) const inline noexcept
Compare the stored pointer to a null pointer.
Returns
true if the stored pointer is null, false otherwise.
Definition at line 331 of file Link.hpp.
{
      return get_() == nullptr;
    }
References get_().
reset_()
template<typename T> void npi::Link< T >::reset_ () inline noexcept
Reset the link to empty.
Releases ownership by calling reset() on the internal std::shared_ptr, causing the link to no longer refer to any object.
Definition at line 306 of file Link.hpp.
{ ptr_.reset(); }
References ptr_.
swap_()
template<typename T> void npi::Link< T >::swap_ (Link< T > & other) inline noexcept
Member swap function.
Parameters
other The Link to swap with.
Note
Provides a noexcept member swap for generic algorithms.
Swaps this Link with another by invoking the friend swap(Link<T>&, Link<T>&).
Definition at line 324 of file Link.hpp.
{
      using std::swap;
      swap(*this, other);
    }
References Link, and swap.
Friends And Related Symbol Documentation
Link
template<typename T> template<typename U> friend class Link friend
Friend declarations of Link class with type as U. This makes any Link class object a friend of any other Link class object.
Definition at line 441 of file Link.hpp.
References Link.
Referenced by Link(), Link(), Link(), Link, ~Link(), assign_(), operator!=(), operator!=, operator!=, operator=(), operator=(), operator=(), operator==(), operator==, operator==, swap, and swap_().
LinkFromThis
template<typename T> template<typename U> friend class LinkFromThis friend
Friend declarations of LinkFromThis class.
Definition at line 449 of file Link.hpp.
References LinkFromThis.
Referenced by LinkFromThis.
LinkHost
template<typename T> template<typename U> friend class LinkHost friend
Friend declarations of LinkHost class.
Definition at line 445 of file Link.hpp.
References LinkHost.
Referenced by LinkHost, operator!=(), and operator==().
operator!= [1/2]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool operator!= (const U * raw, const Link< T > & link) friend
Inequality comparison between a raw pointer and a Link object.
Template Parameters
U Must be polymorphically related to T.
Parameters
raw A raw pointer to an object of type U.
link A Link object instance.
Returns
true if the Link object is not equal to raw, false otherwise.
Definition at line 393 of file Link.hpp.
{
      return !(link == raw);
    }
References Link.
operator!= [2/2]
template<typename T> bool operator!= (std::nullptr_t , const Link< T > & link) friend
Inequality comparison between a null pointer and the stored pointer.
Parameters
link A Link object instance.
Returns
true if the stored pointer is not null, false otherwise.
Definition at line 351 of file Link.hpp.
{
      return link.get_() != nullptr;
    }
References Link.
operator== [1/2]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool operator== (const U * raw, const Link< T > & link) friend
Compare a raw pointer to a Link object.
Template Parameters
U Must be polymorphically related to T.
Parameters
raw A raw pointer to an object of type U.
link A Link object instance.
Returns
true if the Link object equals raw, false otherwise.
Definition at line 382 of file Link.hpp.
{
      return link.get_() == raw;
    }
References Link.
operator== [2/2]
template<typename T> bool operator== (std::nullptr_t , const Link< T > & link) friend
Compare a null pointer to the stored pointer.
Parameters
link A Link object instance.
Returns
true if the stored pointer is null, false otherwise.
Definition at line 344 of file Link.hpp.
{
      return link.get_() == nullptr;
    }
References Link.
swap
template<typename T> void swap (Link< T > & a, Link< T > & b) friend
Swap the contents of two Link objects.
Parameters
a The first Link to swap.
b The second Link to swap.
Exchanges the internal std::shared_ptr of a and b using ADL-enabled swap. Declared friend so it can access the private ptr_ member directly.
Definition at line 314 of file Link.hpp.
{
      using std::swap;
      swap(a.ptr_, b.ptr_);
    }
References Link, and swap.
Referenced by swap, and swap_().
Member Data Documentation
ptr_
template<typename T> std::shared_ptr<std::atomic<void*> > npi::Link< T >::ptr_ {nullptr} private
Pointer to the object being linked to. static_cast is used to ensure the correct type is provided in the get_() method.
Definition at line 453 of file Link.hpp.
{nullptr};
Referenced by Link(), assign_(), get_(), and reset_().
someValue_
template<typename T> int npi::Link< T >::someValue_ {42}
Test variable.
Definition at line 148 of file Link.hpp.
{42};
The documentation for this class was generated from the following file:
Link.hpp