Main Project: npi::GlobalLocker Class Reference
npi::GlobalLocker Class Reference
RAII wrapper around a Windows named mutex for both inter-process and inter-thread synchronization.
#include <GlobalLocker.hpp>
Public Member Functions
GlobalLocker (const GlobalLocker &other)=delete
Deleted Copy Constructor.
GlobalLocker (const QString &name)
Create or open a session-local named mutex and acquire it.
GlobalLocker (GlobalLocker &&other)=delete
Deleted Move Constructor.
~GlobalLocker ()
Release the mutex (if owned) and close the HANDLE.
bool isLocked_ () const
Query whether this instance currently holds the mutex.
bool lock_ ()
Attempt to acquire the mutex after construction.
operator bool () const
Boolean conversion for convenient checks.
GlobalLocker & operator= (const GlobalLocker &other)=delete
Deleted Copy Assignment.
GlobalLocker & operator= (GlobalLocker &&other)=delete
Deleted Move Assignment.
void unlock_ ()
Release the mutex if currently owned by this instance.
Private Attributes
HANDLE handle_ {nullptr}
HANDLE to the named mutex returned by CreateMutexW; nullptr if creation/open failed.
bool locked_ {false}
Tracks whether this instance currently owns the mutex (true) or not (false).
Detailed Description
RAII wrapper around a Windows named mutex for both inter-process and inter-thread synchronization.
Constructs or opens a named mutex, waits to acquire ownership, and releases it on destruction. The name is qualified with the "Local\\" prefix to scope the mutex to the current session. This class therefore acts as a lock between:
Multiple threads of the same process, and
Multiple processes/applications in the same Windows logon session.
Key points:
Constructor blocks until the mutex is acquired, unless CreateMutexW fails.
Destructor safely releases and closes the handle if owned/opened.
Copy and move are disabled to prevent double-release issues.
WAIT_ABANDONED is treated as successful acquisition as per Win32 semantics.
Definition at line 62 of file GlobalLocker.hpp.
Constructor & Destructor Documentation
GlobalLocker() [1/3]
npi::GlobalLocker::GlobalLocker (const QString & name) inline explicit
Create or open a session-local named mutex and acquire it.
Parameters
name Logical mutex name (without "Local\\"). Example: "npi-SharedFileLock".
Internally, the name is converted to UTF-16 and prefixed with "Local\\". This constructor: 1) Calls CreateMutexW(nullptr, FALSE, L"Local\{name}"). Passing FALSE means the mutex is not acquired at creation time. 2) If the handle is valid, calls WaitForSingleObject(h, INFINITE). On WAIT_OBJECT_0 or WAIT_ABANDONED, the lock is considered acquired. Otherwise, the handle is closed and the locker remains invalid. If another thread/process already owns the mutex, this call blocks until it becomes available.
Definition at line 74 of file GlobalLocker.hpp.
    {
      // Build "Local\{name}" so the mutex is scoped to the current logon session.
      const std::wstring wLockName = (QStringLiteral("Local\\") + name).toStdWString();
      HANDLE h = ::CreateMutexW(nullptr, FALSE, wLockName.c_str());
      if(!h) return;
      DWORD w = ::WaitForSingleObject(h, INFINITE);
      if(w == WAIT_OBJECT_0 || w == WAIT_ABANDONED) {
        handle_ = h;
        locked_ = true;
      }
      else {
        ::CloseHandle(h); // Avoid handle leak on failure.
      }
    }
References handle_, and locked_.
Referenced by GlobalLocker(), GlobalLocker(), operator=(), and operator=().
~GlobalLocker()
npi::GlobalLocker::~GlobalLocker () inline
Release the mutex (if owned) and close the HANDLE.
Calls ReleaseMutex only if this instance previously acquired the lock (locked_ == true). The HANDLE is then closed. This guarantees no handle leak even if acquisition failed.
Definition at line 94 of file GlobalLocker.hpp.
    {
      if(handle_) {
        if(locked_) {
          ::ReleaseMutex(handle_);
          locked_ = false;
        }
        ::CloseHandle(handle_);
      }
    }
References handle_, and locked_.
GlobalLocker() [2/3]
npi::GlobalLocker::GlobalLocker (GlobalLocker && other) delete
Deleted Move Constructor.
References GlobalLocker().
GlobalLocker() [3/3]
npi::GlobalLocker::GlobalLocker (const GlobalLocker & other) delete
Deleted Copy Constructor.
References GlobalLocker().
Member Function Documentation
isLocked_()
bool npi::GlobalLocker::isLocked_ () const inline
Query whether this instance currently holds the mutex.
Returns
true if the mutex is owned by this instance; false otherwise.
Definition at line 112 of file GlobalLocker.hpp.
{ return locked_; }
References locked_.
lock_()
bool npi::GlobalLocker::lock_ () inline
Attempt to acquire the mutex after construction.
Returns
true if the mutex becomes owned by this instance; false otherwise.
If a HANDLE exists but the lock is not currently held, this method blocks with INFINITE timeout until the mutex is available. WAIT_OBJECT_0 and WAIT_ABANDONED are treated as success. If WaitForSingleObject fails (e.g., WAIT_FAILED), the lock is not acquired and this method returns false.
Definition at line 131 of file GlobalLocker.hpp.
    {
      if(handle_ && !locked_) {
        DWORD w = ::WaitForSingleObject(handle_, INFINITE);
        if(w == WAIT_OBJECT_0 || w == WAIT_ABANDONED) {
          locked_ = true;
        }
      }
      return locked_;
    }
References handle_, and locked_.
operator bool()
npi::GlobalLocker::operator bool () const inline explicit
Boolean conversion for convenient checks.
Returns
true if the mutex is owned by this instance; false otherwise.
Enables patterns like:
GlobalLocker lock(...);
if(!lock) return;
Definition at line 122 of file GlobalLocker.hpp.
{ return locked_; }
References locked_.
operator=() [1/2]
GlobalLocker & npi::GlobalLocker::operator= (const GlobalLocker & other) delete
Deleted Copy Assignment.
References GlobalLocker().
operator=() [2/2]
GlobalLocker & npi::GlobalLocker::operator= (GlobalLocker && other) delete
Deleted Move Assignment.
References GlobalLocker().
unlock_()
void npi::GlobalLocker::unlock_ () inline
Release the mutex if currently owned by this instance.
Calls ReleaseMutex(handle_) only when locked_ == true. After a successful release, sets locked_ to false. It does not close the HANDLE; the destructor will close the HANDLE. Note: ReleaseMutex must be called exactly once for each successful acquisition on the same thread. This class ensures that by tracking locked_.
Definition at line 148 of file GlobalLocker.hpp.
    {
      if(handle_ && locked_) {
        // We are releasing ownership, so we MUST set locked_ to false
        // to prevent the destructor from trying again. The ReleaseMutex
        // will only fail if either the handle is invalid (not our case) or
        // the calling thread does not own the mutex (also not our case).
        // In either failure case it means we do not have the lock anymore.
        ::ReleaseMutex(handle_);
        locked_ = false;
      }
    }
References handle_, and locked_.
Member Data Documentation
handle_
HANDLE npi::GlobalLocker::handle_ {nullptr} private
HANDLE to the named mutex returned by CreateMutexW; nullptr if creation/open failed.
Definition at line 162 of file GlobalLocker.hpp.
{nullptr}; ///< HANDLE to the named mutex returned by CreateMutexW; nullptr if creation/open failed.
Referenced by GlobalLocker(), ~GlobalLocker(), lock_(), and unlock_().
locked_
bool npi::GlobalLocker::locked_ {false} private
Tracks whether this instance currently owns the mutex (true) or not (false).
Definition at line 163 of file GlobalLocker.hpp.
{false};     ///< Tracks whether this instance currently owns the mutex (true) or not (false).
Referenced by GlobalLocker(), ~GlobalLocker(), isLocked_(), lock_(), operator bool(), and unlock_().
The documentation for this class was generated from the following file:
GlobalLocker.hpp