Main Project: npi::TextSpec Class Reference
npi::TextSpec Class Reference
Thread-safe font utility with style, sizing, and caching.
#include <TextSpec.hpp>
Classes
struct Group
Cached triplet of QFont and its metrics.
struct Style
Object for styling flags and capitalization mode for fonts.
Public Types
enum class Color : std::uint8_t {
Default , Red , Green , Blue ,
Yellow , Cyan , Magenta
}
Named colors for text with dark-background awareness.
Public Member Functions
TextSpec ()=default
Default constructor.
TextSpec (const int absolutePointSize)
Construct with an absolute point size.
TextSpec (const Style &style)
Construct with a style.
TextSpec (const Style &style, const int absolutePointSize)
Construct with a style and an absolute point size.
QFont appFont_ () const
Get a configured QFont for the application font family.
QFontMetrics appFontMetrics_ () const
Get QFontMetrics for the application font family.
QFontMetricsF appFontMetricsF_ () const
Get QFontMetricsF for the application font family.
QFont fixFont_ () const
Get a configured QFont for the fixed-width font family.
QFontMetrics fixFontMetrics_ () const
Get QFontMetrics for the fixed-width font family.
QFontMetricsF fixFontMetricsF_ () const
Get QFontMetricsF for the fixed-width font family.
int getAbsoluteSize_ () const
Get absolute size override (<= 0 means unset).
int getAppFontEffectiveSize_ () const
Compute effective application font size with overrides.
int getFixFontEffectiveSize_ () const
Compute effective fixed-width font size with overrides.
int getRelativeSize_ () const
Get relative size delta.
Style getStyle_ () const
Get style.
TextSpec & setAbsoluteSize_ (const int absolutePointSize=0)
Set absolute point size (overrides default+relative when > 0).
TextSpec & setRelativeSize_ (const int relativePointSize=0)
Set relative point size delta (applied to the default size).
TextSpec & setStyle_ (const Style &style=Style{})
Set style.
Static Public Member Functions
static QColor Color_ (const Color color, const bool darkBackground)
Map Color to QColor, taking background brightness into account.
static QFont GetCurrentAppFont_ ()
Return the current application base font.
static int GetCurrentAppFontSize_ ()
Return the current application base point size.
static QFont GetCurrentFixFont_ ()
Return the current fixed-width base font.
static int GetCurrentFixFontSize_ ()
Return the current fixed-width base point size.
static void SetAppFont_ (const QFont &font)
Set the global application font (family, size, style).
static void SetFixFont_ (const QFont &font)
Set the global fixed-width font (family, size, style).
Static Private Member Functions
static const Group & GetAppGroup_ (const Style &style, const int absSize, const int relSize)
Get or create the cached Group for the application font family.
static const Group & GetFixGroup_ (const Style &style, const int absSize, const int relSize)
Get or create the cached Group for the fixed-width font family.
static size_t Hash_ (const Style &style, const int size, size_t seed=0)
Compute a hash key from style and size.
Private Attributes
int absSize_ {0}
Absolute point size; if > 0 it overrides default+relative.
int relSize_ {0}
Relative font size adjustment; added to the current base font size if absSize_ is < 1.
Style style_
Style configuration for this TextSpec instance.
Static Private Attributes
static QFont AppFont_
Current application base font.
static QMutex AppFontMutex_
Mutex guarding application font state and cache.
static int AppFontSize_ {AppFont_.pointSize()}
Application base point size; derived from AppFont_.
static QHash< size_t, Group > AppGroupCache_
Cache of application Groups keyed by style+size hash.
static QFont FixFont_
Current fixed-width base font.
static QMutex FixFontMutex_
Mutex guarding fixed-width font state and cache.
static int FixFontSize_ {FixFont_.pointSize()}
Fixed-width base point size; derived from FixFont_.
static QHash< size_t, Group > FixGroupCache_
Cache of fixed-width Groups keyed by style+size hash.
Detailed Description
Thread-safe font utility with style, sizing, and caching.
The TextSpec class exposes:
Global setters for the base application font and the base fixed-width font.
A Style struct to describe per-request font attributes.
Absolute and relative point-size inputs with effective-size calculation.
Cached Groups of (QFont, QFontMetrics, QFontMetricsF) for fast reuse.
Static mutexes to protect shared state and caches.
Typical use:
// Initialize at app startup (GUI thread):
npi::TextSpec::SetAppFont_(qApp->font());
// On demand, configure style and size:
npi::TextSpec::Style st;
st.bold_ = true;
npi::TextSpec f{st};
f.setRelativeSize_(+1);
// Fetch QFont or metrics:
QFont font = f.appFont_();
QFontMetrics fm = f.appFontMetrics_();
Definition at line 74 of file TextSpec.hpp.
Member Enumeration Documentation
Color
enum class npi::TextSpec::Color : std::uint8_t strong
Named colors for text with dark-background awareness.
Enumerator
Default
Default text color (white on dark backgrounds, black on light).
Red
Red font color, RGB: XXX 0 0.
Green
Green font color, RGB: 0 XXX 0.
Blue
Blue font color, RGB: 0 0 XXX.
Yellow
Yellow font color, RGB: XXX XXX 0.
Cyan
Cyan font color, RGB: 0 XXX XXX.
Magenta
Magenta font color, RGB: XXX 0 XXX.
Definition at line 192 of file TextSpec.hpp.
                     : std::uint8_t {
      Default, ///< Default text color (white on dark backgrounds, black on light).
      Red,     ///< Red font color, RGB: XXX 0 0
      Green,   ///< Green font color, RGB: 0 XXX 0
      Blue,    ///< Blue font color, RGB: 0 0 XXX
      Yellow,  ///< Yellow font color, RGB: XXX XXX 0
      Cyan,    ///< Cyan font color, RGB: 0 XXX XXX
      Magenta  ///< Magenta font color, RGB: XXX 0 XXX
    };
Constructor & Destructor Documentation
TextSpec() [1/4]
npi::TextSpec::TextSpec () explicit default
Default constructor.
Referenced by setAbsoluteSize_(), setRelativeSize_(), and setStyle_().
TextSpec() [2/4]
npi::TextSpec::TextSpec (const Style & style) inline explicit
Construct with a style.
Parameters
style Style flags and capitalization.
Definition at line 264 of file TextSpec.hpp.
: style_{style} {}
References style_.
TextSpec() [3/4]
npi::TextSpec::TextSpec (const int absolutePointSize) inline explicit
Construct with an absolute point size.
Parameters
absolutePointSize Absolute point size; if <= 0, considered unset.
Definition at line 268 of file TextSpec.hpp.
: absSize_{absolutePointSize} {}
References absSize_.
TextSpec() [4/4]
npi::TextSpec::TextSpec (const Style & style, const int absolutePointSize) inline explicit
Construct with a style and an absolute point size.
Parameters
style Style flags and capitalization.
absolutePointSize Absolute point size; if <= 0, considered unset.
Definition at line 273 of file TextSpec.hpp.
: style_{style}, absSize_{absolutePointSize} {}
References absSize_, and style_.
Member Function Documentation
appFont_()
QFont npi::TextSpec::appFont_ () const inline nodiscard
Get a configured QFont for the application font family.
Uses a cache keyed by style and effective size.
Returns
Configured QFont for Application font.
Definition at line 349 of file TextSpec.hpp.
    {
      QMutexLocker locker(&AppFontMutex_);
      return GetAppGroup_(style_, absSize_, relSize_).font_;
    }
References absSize_, AppFontMutex_, npi::TextSpec::Group::font_, GetAppGroup_(), relSize_, and style_.
appFontMetrics_()
QFontMetrics npi::TextSpec::appFontMetrics_ () const inline nodiscard
Get QFontMetrics for the application font family.
Uses a cache keyed by style and effective size.
Returns
QFontMetrics for the application font.
Definition at line 358 of file TextSpec.hpp.
    {
      QMutexLocker locker(&AppFontMutex_);
      return GetAppGroup_(style_, absSize_, relSize_).metrics_;
    }
References absSize_, AppFontMutex_, GetAppGroup_(), npi::TextSpec::Group::metrics_, relSize_, and style_.
appFontMetricsF_()
QFontMetricsF npi::TextSpec::appFontMetricsF_ () const inline nodiscard
Get QFontMetricsF for the application font family.
Uses a cache keyed by style and effective size.
Returns
QFontMetricsF for the application font.
Definition at line 367 of file TextSpec.hpp.
    {
      QMutexLocker locker(&AppFontMutex_);
      return GetAppGroup_(style_, absSize_, relSize_).metricsF_;
    }
References absSize_, AppFontMutex_, GetAppGroup_(), npi::TextSpec::Group::metricsF_, relSize_, and style_.
Color_()
QColor npi::TextSpec::Color_ (const Color color, const bool darkBackground) inline static
Map Color to QColor, taking background brightness into account.
The function takes into account whether the background is dark which is provided through darkBackground boolean parameter.
Parameters
color Named color.
darkBackground True if background is dark.
Returns
A QColor suitable for the background choice.
Definition at line 242 of file TextSpec.hpp.
    {
      if(color == Color::Red)
        return darkBackground ? Qt::red : Qt::darkRed;
      if(color == Color::Green)
        return darkBackground ? Qt::green : Qt::darkGreen;
      if(color == Color::Blue)
        return darkBackground ? Qt::blue : Qt::darkBlue;
      if(color == Color::Yellow)
        return darkBackground ? Qt::yellow : Qt::darkYellow;
      if(color == Color::Cyan)
        return darkBackground ? Qt::cyan : Qt::darkCyan;
      if(color == Color::Magenta)
        return darkBackground ? Qt::magenta : Qt::darkMagenta;
      return darkBackground ? Qt::white : Qt::black; // For Default and any unhandled case, return white for dark backgrounds and black for light backgrounds.
    }
References Blue, Cyan, Green, Magenta, Red, and Yellow.
fixFont_()
QFont npi::TextSpec::fixFont_ () const inline nodiscard
Get a configured QFont for the fixed-width font family.
Uses a cache keyed by style and effective size.
Returns
Configured QFont for Fixed-width font.
Definition at line 376 of file TextSpec.hpp.
    {
      QMutexLocker locker(&FixFontMutex_);
      return GetFixGroup_(style_, absSize_, relSize_).font_;
    }
References absSize_, FixFontMutex_, npi::TextSpec::Group::font_, GetFixGroup_(), relSize_, and style_.
fixFontMetrics_()
QFontMetrics npi::TextSpec::fixFontMetrics_ () const inline nodiscard
Get QFontMetrics for the fixed-width font family.
Uses a cache keyed by style and effective size.
Returns
QFontMetrics for the fixed-width font.
Definition at line 385 of file TextSpec.hpp.
    {
      QMutexLocker locker(&FixFontMutex_);
      return GetFixGroup_(style_, absSize_, relSize_).metrics_;
    }
References absSize_, FixFontMutex_, GetFixGroup_(), npi::TextSpec::Group::metrics_, relSize_, and style_.
fixFontMetricsF_()
QFontMetricsF npi::TextSpec::fixFontMetricsF_ () const inline nodiscard
Get QFontMetricsF for the fixed-width font family.
Uses a cache keyed by style and effective size.
Returns
QFontMetricsF for the fixed-width font.
Definition at line 394 of file TextSpec.hpp.
    {
      QMutexLocker locker(&FixFontMutex_);
      return GetFixGroup_(style_, absSize_, relSize_).metricsF_;
    }
References absSize_, FixFontMutex_, GetFixGroup_(), npi::TextSpec::Group::metricsF_, relSize_, and style_.
getAbsoluteSize_()
int npi::TextSpec::getAbsoluteSize_ () const inline nodiscard
Get absolute size override (<= 0 means unset).
Returns
The absolute size override.
Definition at line 310 of file TextSpec.hpp.
{ return absSize_; }
References absSize_.
getAppFontEffectiveSize_()
int npi::TextSpec::getAppFontEffectiveSize_ () const inline nodiscard
Compute effective application font size with overrides.
Effective size:
If absSize_ > 0, use absSize_.
Else if (AppFontSize_ + relSize_) > 0, use (AppFontSize_ + relSize_).
Else use AppFontSize_.
Returns
Effective point size (may be -1 if base font uses pixel size).
Definition at line 325 of file TextSpec.hpp.
    {
      QMutexLocker locker(&AppFontMutex_);
      return absSize_ > 0 ? absSize_ : (AppFontSize_ + relSize_) > 0 ? (AppFontSize_ + relSize_) : AppFontSize_;
    }
References absSize_, AppFontMutex_, AppFontSize_, and relSize_.
GetAppGroup_()
const Group & npi::TextSpec::GetAppGroup_ (const Style & style, const int absSize, const int relSize) inline static private
Get or create the cached Group for the application font family.
Retrieves or creates a cached Group for the application font. The effective font size is computed based on either the absolute size (if > 0) or the current application font size plus the relative size adjustment. A hash key is computed from the style and size, and the cache is checked for an existing entry. If not found, a new QFont is configured, stored in a Group, and inserted into the cache.
Parameters
style Style flags and capitalization.
absSize Absolute point size (> 0 overrides).
relSize Relative point size delta.
Returns
Reference to cached Group (valid for the lifetime of the cache).
Note
Uses AppFont_ as the base family.
Definition at line 503 of file TextSpec.hpp.
    {
      const int size = absSize > 0 ? absSize : (AppFontSize_ + relSize > 0 ? AppFontSize_ + relSize : AppFontSize_); // Compute effective font size.
      const size_t hash = Hash_(style, size);                                                                        // Compute the cache key using the style and effective size.
      auto it = AppGroupCache_.find(hash);                                                                           // Look for the key in the application font cache.
      if(it == AppGroupCache_.end()) {                                                                               // Not found in cache: create a new QFont based on the current AppFont_.
        QFont font{AppFont_};
        font.setPointSize(size);
        font.setBold(style.bold_);
        font.setItalic(style.italic_);
        font.setUnderline(style.underline_);
        font.setOverline(style.overline_);
        font.setStrikeOut(style.strikeout_);
        font.setCapitalization(style.capitalization_);
        AppGroupCache_.insert(hash, Group{font}); // Insert the new Group into the cache.
        it = AppGroupCache_.find(hash);           // Update iterator after insertion and retrieve for newly inserted group.
      }
      return it.value(); // Return the cached Group containing the configured QFont and its metrics.
    }
References AppFont_, AppFontSize_, AppGroupCache_, npi::TextSpec::Style::bold_, npi::TextSpec::Style::capitalization_, Hash_(), npi::TextSpec::Style::italic_, npi::TextSpec::Style::overline_, npi::TextSpec::Style::strikeout_, and npi::TextSpec::Style::underline_.
Referenced by appFont_(), appFontMetrics_(), and appFontMetricsF_().
GetCurrentAppFont_()
QFont npi::TextSpec::GetCurrentAppFont_ () inline static nodiscard
Return the current application base font.
Returns
A copy of the current application font.
Definition at line 204 of file TextSpec.hpp.
    {
      QMutexLocker locker{&AppFontMutex_}; // Lock for thread safety.
      return AppFont_;
    }
References AppFont_, and AppFontMutex_.
GetCurrentAppFontSize_()
int npi::TextSpec::GetCurrentAppFontSize_ () inline static nodiscard
Return the current application base point size.
Returns
The current application font point size.
Note
Can be -1 for pixel-sized fonts if so configured.
Definition at line 213 of file TextSpec.hpp.
    {
      QMutexLocker locker{&AppFontMutex_}; // Lock for thread safety.
      return AppFontSize_;
    }
References AppFontMutex_, and AppFontSize_.
GetCurrentFixFont_()
QFont npi::TextSpec::GetCurrentFixFont_ () inline static nodiscard
Return the current fixed-width base font.
Returns
A copy of the current fixed-width font.
Definition at line 221 of file TextSpec.hpp.
    {
      QMutexLocker locker{&FixFontMutex_}; // Lock for thread safety.
      return FixFont_;
    }
References FixFont_, and FixFontMutex_.
GetCurrentFixFontSize_()
int npi::TextSpec::GetCurrentFixFontSize_ () inline static nodiscard
Return the current fixed-width base point size.
Returns
The current fixed-width font point size.
Note
Can be -1 for pixel-sized fonts if so configured.
Definition at line 230 of file TextSpec.hpp.
    {
      QMutexLocker locker{&FixFontMutex_}; // Lock for thread safety.
      return FixFontSize_;
    }
References FixFontMutex_, and FixFontSize_.
getFixFontEffectiveSize_()
int npi::TextSpec::getFixFontEffectiveSize_ () const inline nodiscard
Compute effective fixed-width font size with overrides.
Effective size:
If absSize_ > 0, use absSize_.
Else if (FixFontSize_ + relSize_) > 0, use (FixFontSize_ + relSize_).
Else use FixFontSize_.
Returns
Effective point size (may be -1 if base font uses pixel size).
Definition at line 340 of file TextSpec.hpp.
    {
      QMutexLocker locker(&FixFontMutex_);
      return absSize_ > 0 ? absSize_ : (FixFontSize_ + relSize_) > 0 ? (FixFontSize_ + relSize_) : FixFontSize_;
    }
References absSize_, FixFontMutex_, FixFontSize_, and relSize_.
GetFixGroup_()
const Group & npi::TextSpec::GetFixGroup_ (const Style & style, const int absSize, const int relSize) inline static private
Get or create the cached Group for the fixed-width font family.
Retrieves or creates a cached Group for the fixed-width font. The effective font size is computed based on either the absolute size (if > 0) or the current fixed-width font size plus the relative size adjustment. A hash key is computed from the style and size, and the cache is checked for an existing entry. If not found, a new QFont is configured, stored in a Group, and inserted into the cache.
Parameters
style Style flags and capitalization.
absSize Absolute point size (> 0 overrides).
relSize Relative point size delta.
Returns
Reference to cached Group (valid for the lifetime of the cache).
Note
Uses FixFont_ as the base family.
Definition at line 538 of file TextSpec.hpp.
    {
      const int size = absSize > 0 ? absSize : (FixFontSize_ + relSize > 0 ? FixFontSize_ + relSize : FixFontSize_); // Compute effective font size.
      const size_t hash = Hash_(style, size);                                                                        // Compute the cache key using the style and effective size.
      auto it = FixGroupCache_.find(hash);                                                                           // Look for the key in the application font cache.
      if(it == FixGroupCache_.end()) {                                                                               // Not found in cache: create a new QFont based on the current FixFont_.
        QFont font{FixFont_};
        font.setPointSize(size);
        font.setBold(style.bold_);
        font.setItalic(style.italic_);
        font.setUnderline(style.underline_);
        font.setOverline(style.overline_);
        font.setStrikeOut(style.strikeout_);
        font.setCapitalization(style.capitalization_);
        FixGroupCache_.insert(hash, Group{font}); // Insert the new Group into the cache.
        it = FixGroupCache_.find(hash);           // Update iterator after insertion and retrieve for newly inserted group.
      }
      return it.value(); // Return the cached Group containing the configured QFont and its metrics.
    }
References npi::TextSpec::Style::bold_, npi::TextSpec::Style::capitalization_, FixFont_, FixFontSize_, FixGroupCache_, Hash_(), npi::TextSpec::Style::italic_, npi::TextSpec::Style::overline_, npi::TextSpec::Style::strikeout_, and npi::TextSpec::Style::underline_.
Referenced by fixFont_(), fixFontMetrics_(), and fixFontMetricsF_().
getRelativeSize_()
int npi::TextSpec::getRelativeSize_ () const inline nodiscard
Get relative size delta.
Returns
The relative size delta.
Definition at line 314 of file TextSpec.hpp.
{ return relSize_; }
References relSize_.
getStyle_()
Style npi::TextSpec::getStyle_ () const inline
Get style.
Returns
The current style.
Definition at line 306 of file TextSpec.hpp.
{ return style_; }
References style_.
Hash_()
size_t npi::TextSpec::Hash_ (const Style & style, const int size, size_t seed = 0) inline static private
Compute a hash key from style and size.
Combines boolean flags, capitalization, and size into a single 32-bit integer. Bit layout before qHash:
bits 0..4 : bold, italic, underline, overline, strikeout
bits 5..12 : capitalization (8 bits)
bits 13..28: point size (16 bits, truncated, assumes size is within [0, 65535])
Parameters
style Style flags and capitalization.
size Point size used for the key (truncated to 16 bits).
seed Optional hash seed.
Returns
size_t hash suitable as a QHash key.
Definition at line 475 of file TextSpec.hpp.
    {
      quint32 combined = 0;
      combined |= (style.bold_ ? 1u : 0u) << 0;
      combined |= (style.italic_ ? 1u : 0u) << 1;
      combined |= (style.underline_ ? 1u : 0u) << 2;
      combined |= (style.overline_ ? 1u : 0u) << 3;
      combined |= (style.strikeout_ ? 1u : 0u) << 4;
      combined |= (static_cast<quint32>(style.capitalization_) & 0xFF) << 5;
      combined |= (static_cast<quint32>(size) & 0xFFFF) << 13;
      return qHash(combined, seed);
    }
References npi::TextSpec::Style::bold_, npi::TextSpec::Style::capitalization_, npi::TextSpec::Style::italic_, npi::TextSpec::Style::overline_, npi::TextSpec::Style::strikeout_, and npi::TextSpec::Style::underline_.
Referenced by GetAppGroup_(), and GetFixGroup_().
setAbsoluteSize_()
TextSpec & npi::TextSpec::setAbsoluteSize_ (const int absolutePointSize = 0) inline
Set absolute point size (overrides default+relative when > 0).
Parameters
absolutePointSize Absolute point size; <= 0 clears the override.
Returns
*this for chaining.
Definition at line 287 of file TextSpec.hpp.
    {
      absSize_ = absolutePointSize;
      return *this;
    }
References TextSpec(), and absSize_.
SetAppFont_()
void npi::TextSpec::SetAppFont_ (const QFont & font) inline static
Set the global application font (family, size, style).
Clears the application font cache so new Groups reflect the new base font.
Calls qApp->setFont(font) after releasing the internal mutex.
Precondition
Must be invoked when QApplication exists. Should be invoked on the GUI thread.
Parameters
font New application base font.
Definition at line 142 of file TextSpec.hpp.
    {
      AppFontMutex_.lock();                                           // Lock for thread safety.
      if(font != AppFont_) {                                          // Only update if the new font differs.
        AppFont_ = font;                                              // Update the global application font.
        AppFontSize_ = (font.pointSize() < 0 ? 9 : font.pointSize()); // Update the font size.
        AppGroupCache_.clear();                                       // Clear the cache to ensure new font groups are created.
        AppFontMutex_.unlock();                                       // Unlock before GUI call.
        qApp->setFont(font);                                          // Apply the new font to the application.
      }
      else {
        AppFontMutex_.unlock(); // Unlock if no change.
      }
    }
References AppFont_, AppFontMutex_, AppFontSize_, and AppGroupCache_.
SetFixFont_()
void npi::TextSpec::SetFixFont_ (const QFont & font) inline static
Set the global fixed-width font (family, size, style).
Clears the fixed-width font cache.
Queues QWidget::update() on widgets marked with npi::GuiProps::FixedWidthFontWidget_. Lifetime is guarded via QPointer in the queued lambda.
Precondition
Should be invoked on the GUI thread.
Parameters
font New fixed-width base font.
Definition at line 166 of file TextSpec.hpp.
    {
      FixFontMutex_.lock();                                           // Lock for thread safety.
      if(font != FixFont_) {                                          // Only update if the new font differs.
        FixFont_ = font;                                              // Update the global fixed-width font.
        FixFontSize_ = (font.pointSize() < 0 ? 9 : font.pointSize()); // Update the font size.
        FixGroupCache_.clear();                                       // Clear the fixed-width font cache.
        FixFontMutex_.unlock();                                       // Unlock before GUI calls.
        // Iterate over all widgets in the application.
        const QList<QWidget*> widgets = qApp->allWidgets();
        for(QWidget* widget : widgets) {
          // If the widget uses the fixed-width font, force an update to apply the new font.
          if(QPointer<QWidget> w{widget}; w && w->property(npi::GuiProps::FixedWidthFontWidget_).toBool()) {
            QMetaObject::invokeMethod(qApp, [w] { if(w) w->update(); }, Qt::QueuedConnection);
          }
        }
      }
      else {
        FixFontMutex_.unlock(); // Unlock if no change.
      }
    }
References npi::GuiProps::FixedWidthFontWidget_, FixFont_, FixFontMutex_, FixFontSize_, and FixGroupCache_.
setRelativeSize_()
TextSpec & npi::TextSpec::setRelativeSize_ (const int relativePointSize = 0) inline
Set relative point size delta (applied to the default size).
Parameters
relativePointSize Positive increases size; negative decreases.
Returns
*this for chaining.
Note
If (default + relative) <= 0, the default size is used.
Definition at line 298 of file TextSpec.hpp.
    {
      relSize_ = relativePointSize;
      return *this;
    }
References TextSpec(), and relSize_.
setStyle_()
TextSpec & npi::TextSpec::setStyle_ (const Style & style = Style{}) inline
Set style.
Parameters
style New style; defaults to Style{} if omitted.
Returns
*this for chaining.
Definition at line 278 of file TextSpec.hpp.
                                                  {})
    {
      style_ = style;
      return *this;
    }
References TextSpec().
Member Data Documentation
absSize_
int npi::TextSpec::absSize_ {0} private
Absolute point size; if > 0 it overrides default+relative.
Definition at line 402 of file TextSpec.hpp.
{0}; ///< Absolute point size; if > 0 it overrides default+relative.
Referenced by TextSpec(), TextSpec(), appFont_(), appFontMetrics_(), appFontMetricsF_(), fixFont_(), fixFontMetrics_(), fixFontMetricsF_(), getAbsoluteSize_(), getAppFontEffectiveSize_(), getFixFontEffectiveSize_(), and setAbsoluteSize_().
AppFont_
QFont npi::TextSpec::AppFont_ inline static private
Initial value:
{[] {
      QFont f;
      if(f.pointSize() < 0) f.setPointSize(9);
      return f;
    }()}
Current application base font.
Note
Starts as default-constructed QFont with fallback size; callers may override via SetAppFont_.
Definition at line 433 of file TextSpec.hpp.
                                {[] {
      QFont f;
      if(f.pointSize() < 0) f.setPointSize(9); // Apply fallback size
      return f;
    }()};
Referenced by GetAppGroup_(), GetCurrentAppFont_(), and SetAppFont_().
AppFontMutex_
QMutex npi::TextSpec::AppFontMutex_ inline static private
Mutex guarding application font state and cache.
Definition at line 429 of file TextSpec.hpp.
Referenced by appFont_(), appFontMetrics_(), appFontMetricsF_(), getAppFontEffectiveSize_(), GetCurrentAppFont_(), GetCurrentAppFontSize_(), and SetAppFont_().
AppFontSize_
int npi::TextSpec::AppFontSize_ {AppFont_.pointSize()} inline static private
Application base point size; derived from AppFont_.
Definition at line 440 of file TextSpec.hpp.
{AppFont_.pointSize()};
Referenced by getAppFontEffectiveSize_(), GetAppGroup_(), GetCurrentAppFontSize_(), and SetAppFont_().
AppGroupCache_
QHash<size_t, Group> npi::TextSpec::AppGroupCache_ inline static private
Cache of application Groups keyed by style+size hash.
Definition at line 443 of file TextSpec.hpp.
Referenced by GetAppGroup_(), and SetAppFont_().
FixFont_
QFont npi::TextSpec::FixFont_ inline static private
Initial value:
{[] {
      QFont f{"Consolas"};
      if(f.pointSize() < 0) f.setPointSize(9);
      return f;
    }()}
Current fixed-width base font.
Note
Uses "Consolas" by default with a point-size fallback to 9 if unset.
Definition at line 450 of file TextSpec.hpp.
                                {[] {
      QFont f{"Consolas"};
      if(f.pointSize() < 0) f.setPointSize(9); // Apply fallback size
      return f;
    }()};
Referenced by GetCurrentFixFont_(), GetFixGroup_(), and SetFixFont_().
FixFontMutex_
QMutex npi::TextSpec::FixFontMutex_ inline static private
Mutex guarding fixed-width font state and cache.
Definition at line 446 of file TextSpec.hpp.
Referenced by fixFont_(), fixFontMetrics_(), fixFontMetricsF_(), GetCurrentFixFont_(), GetCurrentFixFontSize_(), getFixFontEffectiveSize_(), and SetFixFont_().
FixFontSize_
int npi::TextSpec::FixFontSize_ {FixFont_.pointSize()} inline static private
Fixed-width base point size; derived from FixFont_.
Definition at line 457 of file TextSpec.hpp.
{FixFont_.pointSize()};
Referenced by GetCurrentFixFontSize_(), getFixFontEffectiveSize_(), GetFixGroup_(), and SetFixFont_().
FixGroupCache_
QHash<size_t, Group> npi::TextSpec::FixGroupCache_ inline static private
Cache of fixed-width Groups keyed by style+size hash.
Definition at line 460 of file TextSpec.hpp.
Referenced by GetFixGroup_(), and SetFixFont_().
relSize_
int npi::TextSpec::relSize_ {0} private
Relative font size adjustment; added to the current base font size if absSize_ is < 1.
Definition at line 403 of file TextSpec.hpp.
{0}; ///< Relative font size adjustment; added to the current base font size if absSize_ is < 1.
Referenced by appFont_(), appFontMetrics_(), appFontMetricsF_(), fixFont_(), fixFontMetrics_(), fixFontMetricsF_(), getAppFontEffectiveSize_(), getFixFontEffectiveSize_(), getRelativeSize_(), and setRelativeSize_().
style_
Style npi::TextSpec::style_ private
Style configuration for this TextSpec instance.
Definition at line 401 of file TextSpec.hpp.
Referenced by TextSpec(), TextSpec(), appFont_(), appFontMetrics_(), appFontMetricsF_(), fixFont_(), fixFontMetrics_(), fixFontMetricsF_(), and getStyle_().
The documentation for this class was generated from the following file:
TextSpec.hpp