Main Project: npi::RefPtrHost< T >::Obs Struct Reference
npi::RefPtrHost< T >::Obs Struct Reference
Inner observer type holding a type-erased pointer to the object. Used to broadcast the lifetime of the main object to RefPtr objects.
Public Member Functions
Obs (const Obs &other) noexcept=default
Default copy constructor.
Obs (Obs &&other) noexcept=default
Default move constructor.
Obs (void *raw)
Initialize observer with raw pointer.
~Obs () noexcept
Destructor sets the internal pointer to nullptr using std::memory_order_release to ensure thread-safe access.
Obs & operator= (const Obs &other) noexcept=default
Default copy assignment operator.
Obs & operator= (Obs &&other) noexcept=default
Default move assignment operator.
Public Attributes
std::shared_ptr< std::atomic< void * > > ptr_ {nullptr}
Type-erased pointer to the object being observed.
Detailed Description
template<typename T>
struct npi::RefPtrHost< T >::Obs
Inner observer type holding a type-erased pointer to the object. Used to broadcast the lifetime of the main object to RefPtr objects.
Note
Holds a std::shared_ptr<std::atomic<void*>> to ensure thread-safe access to a type-erased pointer.
Type-erased pointer is used instead of actual object pointer to allow for easy casting and polymorphic relations. To obtain the actual pointer, the RefPtr objects have to use static_cast<T*> which is done in RefPtr<T>::get_().
This struct object holds the type-erased pointer to the object. In its destructor the pointer is set to nullptr using std::memory_order_release to ensure thread-safe access. Since the object of this struct is stored as a std::shared_ptr<Obs>, once the last reference to std::shared_ptr<Obs> is destroyed, the destructor will be called and the object in the std::atomic<void*> will be replaced with nullptr. This allows the RefPtr objects to check if the object can still be dereferenced or not.
Definition at line 847 of file RefPtrClasses.hpp.
Constructor & Destructor Documentation
Obs() [1/3]
template<typename T> npi::RefPtrHost< T >::Obs::Obs (void * raw) inline explicit
Initialize observer with raw pointer.
Parameters
raw The raw pointer to the hosted object.
Allocates a new atomic wrapper set to raw.
Definition at line 854 of file RefPtrClasses.hpp.
: ptr_{std::make_shared<std::atomic<void*>>(raw)} {}
References ptr_.
Referenced by Obs(), Obs(), operator=(), and operator=().
Obs() [2/3]
template<typename T> npi::RefPtrHost< T >::Obs::Obs (const Obs & other) default noexcept
Default copy constructor.
References Obs().
Obs() [3/3]
template<typename T> npi::RefPtrHost< T >::Obs::Obs (Obs && other) default noexcept
Default move constructor.
References Obs().
~Obs()
template<typename T> npi::RefPtrHost< T >::Obs::~Obs () inline noexcept
Destructor sets the internal pointer to nullptr using std::memory_order_release to ensure thread-safe access.
Definition at line 870 of file RefPtrClasses.hpp.
{ ptr_->store(nullptr, std::memory_order_release); }
References ptr_.
Member Function Documentation
operator=() [1/2]
template<typename T> Obs & npi::RefPtrHost< T >::Obs::operator= (const Obs & other) default noexcept
Default copy assignment operator.
References Obs().
operator=() [2/2]
template<typename T> Obs & npi::RefPtrHost< T >::Obs::operator= (Obs && other) default noexcept
Default move assignment operator.
References Obs().
Member Data Documentation
ptr_
template<typename T> std::shared_ptr<std::atomic<void*> > npi::RefPtrHost< T >::Obs::ptr_ {nullptr}
Type-erased pointer to the object being observed.
Definition at line 849 of file RefPtrClasses.hpp.
{nullptr};
Referenced by Obs(), and ~Obs().
The documentation for this struct was generated from the following file:
RefPtrClasses.hpp