Main Project: npi::RefPtr< T > Class Template Reference
npi::RefPtr< T > Class Template Reference final
A non-owning, auto-nullifying pointer-like handle to an object of type T.
#include <RefPtrClasses.hpp>
Public Member Functions
RefPtr () noexcept=default
Default constructor.
RefPtr (const RefPtr &other) noexcept=default
Default Copy constructor.
template<typename U>
requires PolymorphicallyRelated<T, U>
RefPtr (const RefPtr< U > &other)
Polymorphic non-explicit converting copy constructor.
RefPtr (RefPtr &&other) noexcept=default
Default Move constructor.
~RefPtr () noexcept=default
Default destructor.
T * get_ () const noexcept
Retrieve a raw pointer to the managed object, if any.
bool isValid_ () const noexcept
Check whether the RefPtr currently holds a valid object.
operator bool () const noexcept
Explicit boolean conversion operator (e.g. if(refPtr){...}).
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const RefPtr< U > &other) const noexcept
Compare two RefPtr objects for inequality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const RefPtrHost< U > &other) const noexcept
Compare this RefPtr to a RefPtrHost for inequality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const U *raw) const noexcept
Inequality comparison with a raw pointer.
bool operator!= (std::nullptr_t) const noexcept
Inequality comparison with a null pointer.
T & operator* () const noexcept
Dereference operator to obtain a reference to the managed object.
T * operator-> () const noexcept
Pointer-like access operator.
RefPtr & operator= (const RefPtr &other) noexcept=default
Default Copy assignment.
template<typename U>
requires PolymorphicallyRelated<T, U>
RefPtr & operator= (const RefPtr< U > &other)
Polymorphic assignment operator.
RefPtr & operator= (RefPtr &&other) noexcept=default
Default Move assignment.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const RefPtr< U > &other) const noexcept
Compare two RefPtr objects for equality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const RefPtrHost< U > &other) const noexcept
Compare this RefPtr to a RefPtrHost for equality.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const U *raw) const noexcept
Compare the stored pointer to a raw pointer.
bool operator== (std::nullptr_t) const noexcept
Compare the stored pointer to a null pointer.
void reset_ () noexcept
Reset the RefPtr to empty.
void swap_ (RefPtr &other) noexcept
Member swap function.
Private Member Functions
RefPtr (std::shared_ptr< std::atomic< void * > > ptr) noexcept
Private constructor that initializes the RefPtr with a shared pointer. It used by other RefPtr-Family of classes to create a RefPtr instance.
template<typename U>
requires PolymorphicallyRelated<T, U>
void assign_ (const RefPtr< U > &other)
Internal helper to assign from another polymorphically related RefPtr object.
Private Attributes
std::shared_ptr< std::atomic< void * > > ptr_ {nullptr}
Pointer to the object being linked to.
Friends
template<typename U>
class RefPtr
Friend declarations of RefPtr class with type as U. This makes any RefPtr class object a friend of any other RefPtr class object.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator!= (const U *raw, const RefPtr< T > &refPtr) noexcept
Inequality comparison between a raw pointer and a RefPtr object.
bool operator!= (std::nullptr_t, const RefPtr< T > &refPtr) noexcept
Inequality comparison between a null pointer and the stored pointer.
template<typename U>
requires PolymorphicallyRelated<T, U>
bool operator== (const U *raw, const RefPtr< T > &refPtr) noexcept
Compare a raw pointer to a RefPtr object.
bool operator== (std::nullptr_t, const RefPtr< T > &refPtr) noexcept
Compare a null pointer to the stored pointer.
template<typename U>
class RefPtrFromThis
Friend declarations of RefPtrFromThis class.
template<typename U>
class RefPtrHost
Friend declarations of RefPtrHost class.
void swap (RefPtr< T > &a, RefPtr< T > &b) noexcept
Swap the contents of two RefPtr objects.
Detailed Description
template<typename T>
class npi::RefPtr< T >
A non-owning, auto-nullifying pointer-like handle to an object of type T.
Does not own the object T.
Object must be wrapped in RefPtrHost.
Provides safe pointer-like access to T.
Supports polymorphic conversion and comparison.
Offers a safe boolean conversion to check if the linked object is still alive.
Holds a shared control block containing an atomic<void*> to the object.
When the observer is torn down, the atomic is set to nullptr (release), so readers detect teardown via acquire loads.
Does not synchronize arbitrary reads or writes to the object T; callers must provide their own synchronization for T's data.
Template Parameters
T The type of the object being linked to.
Definition at line 165 of file RefPtrClasses.hpp.
Constructor & Destructor Documentation
RefPtr() [1/5]
template<typename T> npi::RefPtr< T >::RefPtr () default noexcept
Default constructor.
RefPtr() [2/5]
template<typename T> npi::RefPtr< T >::RefPtr (RefPtr< T > && other) default noexcept
Default Move constructor.
References RefPtr.
RefPtr() [3/5]
template<typename T> npi::RefPtr< T >::RefPtr (const RefPtr< T > & other) default noexcept
Default Copy constructor.
References RefPtr.
~RefPtr()
template<typename T> npi::RefPtr< T >::~RefPtr () default noexcept
Default destructor.
References RefPtr.
RefPtr() [4/5]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> npi::RefPtr< T >::RefPtr (const RefPtr< U > & other) inline
Polymorphic non-explicit converting copy constructor.
Template Parameters
U The type of the object being linked to; must be polymorphically related to T.
Parameters
other The RefPtr object to copy from.
Exceptions
std::bad_cast if a safe downcast from U* to T* fails.
Precondition
U must be polymorphically related to T.
Note
This constructor is not explicit, allowing implicit conversions from RefPtr<U> to RefPtr<T>.
This routine does three things:
Equality check:
If the two pointers are already the same, it returns immediately.
Pointer assignment:
If U is T or derived from T, it does a static_cast (upcast).
Otherwise it does a dynamic_cast (downcast), throwing std::bad_cast if that fails.
Null reset:
If other.get_() is null, resets ptr_ to empty instead of assigning.
Definition at line 191 of file RefPtrClasses.hpp.
    {
      assign_(other);
    }
References RefPtr, and assign_().
RefPtr() [5/5]
template<typename T> npi::RefPtr< T >::RefPtr (std::shared_ptr< std::atomic< void * > > ptr) inline explicit private noexcept
Private constructor that initializes the RefPtr with a shared pointer. It used by other RefPtr-Family of classes to create a RefPtr instance.
Parameters
ptr Shared pointer to the atomic void pointer stored in the RefPtrHost object.
Definition at line 483 of file RefPtrClasses.hpp.
: ptr_{std::move(ptr)} {}
References ptr_.
Member Function Documentation
assign_()
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> void npi::RefPtr< T >::assign_ (const RefPtr< U > & other) inline private
Internal helper to assign from another polymorphically related RefPtr object.
Template Parameters
U The type of object to assign from; must be polymorphically related to T.
Parameters
other The RefPtr object to assign from.
Exceptions
std::bad_cast if a safe downcast from U* to T* fails.
Precondition
U must be polymorphically related to T.
Definition at line 492 of file RefPtrClasses.hpp.
    {
      // Skip assignment if the pointers are the same
      if(ptr_.get() == other.ptr_.get())
        return;
      if(auto raw = other.get_(); raw) {
        if constexpr(std::is_same_v<T, U> || std::is_base_of_v<T, U>) {
          // Upcast: If T and U are the same or T is a base of U.
          // Use static_cast since it is safe to use here.
          ptr_ = other.ptr_;
        }
        else {
          // Downcast: If T is not a base of U, use dynamic_cast to ensure safe downcasting.
          // The use of dynamic_cast requires U to be polymorphic.
          // Throw std::bad_cast if the cast fails.
          static_assert(std::is_polymorphic_v<U>, "U must be polymorphic for dynamic_cast");
          if(auto dynamicRaw = dynamic_cast<T*>(raw))
            ptr_ = other.ptr_;
          else
            throw std::bad_cast();
        }
      }
      else {
        // If the raw pointer is null, reset the shared pointer to null.
        ptr_.reset();
      }
    }
References RefPtr, get_(), and ptr_.
Referenced by RefPtr(), and operator=().
get_()
template<typename T> T * npi::RefPtr< T >::get_ () const inline nodiscard noexcept
Retrieve a raw pointer to the managed object, if any.
Returns
A pointer to the object of type T, or nullptr if no object is set.
Warning
Check for validity before using the pointer to the object.
Note
This method is marked noexcept, so it guarantees not to throw.
It is also marked [[nodiscard]] to encourage callers to check for nullptr rather than silently ignoring the return value.
Because it performs an atomic load, it is safe to call concurrently from multiple threads (readers).
This method returns the underlying raw pointer of type T* that is stored inside an atomic wrapper within a std::shared_ptr. It performs the following steps:
Tests whether the internal std::shared_ptr<std::atomic<void*>> ptr_ is non-null.
If ptr_ is null, this method immediately returns nullptr.
If ptr_ is non-null, loads the stored void pointer atomically using std::memory_order_acquire to synchronize with any release stores that may have updated the pointer elsewhere. This acquire load synchronizes with the release store in the host's observer, guaranteeing that this RefPtr will see nullptr if the host is destroyed. It does not synchronize arbitrary writes to the T object's members.
Uses static_cast<T*> to convert the void* to the correct object type and returns the resulting T*
Definition at line 244 of file RefPtrClasses.hpp.
    {
      return ptr_ ? static_cast<T*>(ptr_->load(std::memory_order_acquire)) : nullptr;
    }
References ptr_.
Referenced by assign_(), isValid_(), operator!=(), operator*(), operator->(), operator==(), operator==(), operator==(), and operator==().
isValid_()
template<typename T> bool npi::RefPtr< T >::isValid_ () const inline noexcept
Check whether the RefPtr currently holds a valid object.
Returns
true if the stored pointer is non-null (RefPtr is valid), false otherwise.
Calls get_() to obtain the raw pointer and compares it to nullptr. Returns true if get_() returns a non-null pointer, false otherwise.
Definition at line 306 of file RefPtrClasses.hpp.
{ return get_() != nullptr; }
References get_().
Referenced by operator bool().
operator bool()
template<typename T> npi::RefPtr< T >::operator bool () const inline explicit noexcept
Explicit boolean conversion operator (e.g. if(refPtr){...}).
Returns
true if the RefPtr holds a valid object, false if it is empty.
Enables use of RefPtr<T> in boolean contexts (for example, if(refPtr) {...}).
Internally calls isValid_() to determine the truth value.
Definition at line 313 of file RefPtrClasses.hpp.
{ return isValid_(); }
References isValid_().
operator!=() [1/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::RefPtr< T >::operator!= (const RefPtr< U > & other) const inline noexcept
Compare two RefPtr objects for inequality.
Template Parameters
U Must be polymorphically related to T.
Parameters
other Another RefPtr instance.
Returns
true if the RefPtr objects point to different objects.
Definition at line 437 of file RefPtrClasses.hpp.
    {
      return !(*this == other);
    }
References RefPtr.
operator!=() [2/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::RefPtr< T >::operator!= (const RefPtrHost< U > & other) const inline noexcept
Compare this RefPtr to a RefPtrHost for inequality.
Template Parameters
U Must be polymorphically related to T.
Parameters
other A RefPtrHost instance.
Returns
true if they point to different objects.
Definition at line 459 of file RefPtrClasses.hpp.
    {
      return !(*this == other);
    }
References RefPtrHost.
operator!=() [3/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::RefPtr< T >::operator!= (const U * raw) const inline noexcept
Inequality comparison with a raw pointer.
Template Parameters
U Must be polymorphically related to T.
Parameters
raw A raw pointer to an object of type U.
Returns
true if the underlying pointer does not equal raw.
Definition at line 391 of file RefPtrClasses.hpp.
    {
      return !(*this == raw);
    }
operator!=() [4/4]
template<typename T> bool npi::RefPtr< T >::operator!= (std::nullptr_t) const inline noexcept
Inequality comparison with a null pointer.
Returns
true if the stored pointer is not null, false otherwise.
Definition at line 353 of file RefPtrClasses.hpp.
    {
      return get_() != nullptr;
    }
References get_().
operator*()
template<typename T> T & npi::RefPtr< T >::operator* () const inline nodiscard noexcept
Dereference operator to obtain a reference to the managed object.
Returns
A reference to the managed object.
Precondition
get_() must not return nullptr. In release builds, dereferencing a null pointer is undefined behavior.
Postcondition
Returns a reference to the managed T object.
Warning
Check for validity before dereferencing.
Note
This operator is noexcept and [[nodiscard]] to convey that this operation does not throw and its result should be used.
Allows use of the dereference syntax *refPtr to access the underlying object.
Calls get_() to atomically load the stored pointer.
Uses assert() to verify at runtime (in debug builds) that the pointer is not null. If the assertion fails, the program is terminated with an explanatory message.
Dereferences the pointer and returns a reference to T.
Definition at line 294 of file RefPtrClasses.hpp.
    {
      auto ptr = get_();
      assert(ptr && "Link::operator* on nullptr");
      return *ptr;
    }
References get_().
operator->()
template<typename T> T * npi::RefPtr< T >::operator-> () const inline nodiscard noexcept
Pointer-like access operator.
Returns
The non-null pointer to the managed T object.
Precondition
get_() must not return nullptr. In release builds, dereferencing a null pointer is undefined behavior.
Postcondition
Returns a valid T* suitable for member-access expressions.
Warning
Check for validity before dereferencing.
Note
Marked noexcept and [[nodiscard]] to convey that this operation does not throw and its result should be used.
Provides direct -> so that users of RefPtr<T> can write refPtr->member instead of refPtr.get_()->member. Internally, this calls get_() and asserts that the result is non-null:
Calls get_() to perform the atomic load and type conversion.
Uses assert() to check at runtime (in debug builds) that the pointer is not null. If the assertion fails, the program is terminated with an explanatory message.
Returns the raw T* allowing access to the object's members.
Definition at line 269 of file RefPtrClasses.hpp.
    {
      auto ptr = get_();
      assert(ptr && "Link::operator-> on nullptr");
      return ptr;
    }
References get_().
operator=() [1/3]
template<typename T> RefPtr & npi::RefPtr< T >::operator= (const RefPtr< T > & other) default noexcept
Default Copy assignment.
References RefPtr.
operator=() [2/3]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> RefPtr & npi::RefPtr< T >::operator= (const RefPtr< U > & other) inline
Polymorphic assignment operator.
Template Parameters
U The type of the object being linked to; must be polymorphically related to T.
Parameters
other The RefPtr object to assign from.
Returns
A reference to this RefPtr object.
Exceptions
std::bad_cast if a safe downcast from U* to T* fails.
Precondition
U must be polymorphically related to T.
This routine does three things:
Equality check:
If the two pointers are already the same, it returns immediately.
Pointer assignment:
If U is T or derived from T, it does a static_cast (upcast).
Otherwise it does a dynamic_cast (downcast), throwing std::bad_cast if that fails.
Null reset:
If other.get_() is null, resets ptr_ to empty instead of assigning.
Definition at line 213 of file RefPtrClasses.hpp.
    {
      assign_(other);
      return *this;
    }
References RefPtr, and assign_().
operator=() [3/3]
template<typename T> RefPtr & npi::RefPtr< T >::operator= (RefPtr< T > && other) default noexcept
Default Move assignment.
References RefPtr.
operator==() [1/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::RefPtr< T >::operator== (const RefPtr< U > & other) const inline noexcept
Compare two RefPtr objects for equality.
Template Parameters
U Must be polymorphically related to T.
Parameters
other Another RefPtr instance.
Returns
true if both RefPtr objects point to the same object.
Definition at line 426 of file RefPtrClasses.hpp.
    {
      return get_() == other.get_();
    }
References RefPtr, and get_().
operator==() [2/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::RefPtr< T >::operator== (const RefPtrHost< U > & other) const inline noexcept
Compare this RefPtr to a RefPtrHost for equality.
Template Parameters
U Must be polymorphically related to T.
Parameters
other A RefPtrHost instance.
Returns
true if both point to the same object.
Definition at line 448 of file RefPtrClasses.hpp.
    {
      return get_() == other.get_();
    }
References get_(), and RefPtrHost.
operator==() [3/4]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool npi::RefPtr< T >::operator== (const U * raw) const inline noexcept
Compare the stored pointer to a raw pointer.
Template Parameters
U Must be polymorphically related to T.
Parameters
raw A raw pointer to an object of type U.
Returns
true if the underlying pointer equals raw, false otherwise.
Definition at line 380 of file RefPtrClasses.hpp.
    {
      return get_() == raw;
    }
References get_().
operator==() [4/4]
template<typename T> bool npi::RefPtr< T >::operator== (std::nullptr_t) const inline noexcept
Compare the stored pointer to a null pointer.
Returns
true if the stored pointer is null, false otherwise.
Definition at line 346 of file RefPtrClasses.hpp.
    {
      return get_() == nullptr;
    }
References get_().
reset_()
template<typename T> void npi::RefPtr< T >::reset_ () inline noexcept
Reset the RefPtr to empty.
Releases ownership by calling reset() on the internal std::shared_ptr, causing the RefPtr to no longer refer to any object.
Definition at line 319 of file RefPtrClasses.hpp.
{ ptr_.reset(); }
References ptr_.
swap_()
template<typename T> void npi::RefPtr< T >::swap_ (RefPtr< T > & other) inline noexcept
Member swap function.
Parameters
other The RefPtr to swap with.
Note
Provides a noexcept member swap for generic algorithms.
Swaps this RefPtr with another by invoking the friend swap(RefPtr<T>&, RefPtr<T>&).
Definition at line 338 of file RefPtrClasses.hpp.
    {
      using std::swap;
      swap(*this, other);
    }
References RefPtr, and swap.
Friends And Related Symbol Documentation
RefPtr
template<typename T> template<typename U> friend class RefPtr friend
Friend declarations of RefPtr class with type as U. This makes any RefPtr class object a friend of any other RefPtr class object.
Definition at line 467 of file RefPtrClasses.hpp.
References RefPtr.
Referenced by RefPtr(), RefPtr(), RefPtr(), RefPtr, ~RefPtr(), assign_(), operator!=(), operator!=, operator!=, operator=(), operator=(), operator=(), operator==(), operator==, operator==, swap, and swap_().
operator!= [1/2]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool operator!= (const U * raw, const RefPtr< T > & refPtr) friend
Inequality comparison between a raw pointer and a RefPtr object.
Template Parameters
U Must be polymorphically related to T.
Parameters
raw A raw pointer to an object of type U.
refPtr A RefPtr object instance.
Returns
true if the RefPtr object is not equal to raw, false otherwise.
Definition at line 415 of file RefPtrClasses.hpp.
    {
      return !(refPtr == raw);
    }
References RefPtr.
operator!= [2/2]
template<typename T> bool operator!= (std::nullptr_t , const RefPtr< T > & refPtr) friend
Inequality comparison between a null pointer and the stored pointer.
Parameters
refPtr A RefPtr object instance.
Returns
true if the stored pointer is not null, false otherwise.
Definition at line 369 of file RefPtrClasses.hpp.
    {
      return refPtr.get_() != nullptr;
    }
References RefPtr.
operator== [1/2]
template<typename T> template<typename U> requires PolymorphicallyRelated<T, U> bool operator== (const U * raw, const RefPtr< T > & refPtr) friend
Compare a raw pointer to a RefPtr object.
Template Parameters
U Must be polymorphically related to T.
Parameters
raw A raw pointer to an object of type U.
refPtr A RefPtr object instance.
Returns
true if the RefPtr object equals raw, false otherwise.
Definition at line 403 of file RefPtrClasses.hpp.
    {
      return refPtr.get_() == raw;
    }
References RefPtr.
operator== [2/2]
template<typename T> bool operator== (std::nullptr_t , const RefPtr< T > & refPtr) friend
Compare a null pointer to the stored pointer.
Parameters
refPtr A RefPtr object instance.
Returns
true if the stored pointer is null, false otherwise.
Definition at line 361 of file RefPtrClasses.hpp.
    {
      return refPtr.get_() == nullptr;
    }
References RefPtr.
RefPtrFromThis
template<typename T> template<typename U> friend class RefPtrFromThis friend
Friend declarations of RefPtrFromThis class.
Definition at line 473 of file RefPtrClasses.hpp.
References RefPtrFromThis.
Referenced by RefPtrFromThis.
RefPtrHost
template<typename T> template<typename U> friend class RefPtrHost friend
Friend declarations of RefPtrHost class.
Definition at line 470 of file RefPtrClasses.hpp.
References RefPtrHost.
Referenced by operator!=(), operator==(), and RefPtrHost.
swap
template<typename T> void swap (RefPtr< T > & a, RefPtr< T > & b) friend
Swap the contents of two RefPtr objects.
Parameters
a The first RefPtr to swap.
b The second RefPtr to swap.
Exchanges the internal std::shared_ptr of a and b using ADL-enabled swap. Declared friend so it can access the private ptr_ member directly.
Definition at line 327 of file RefPtrClasses.hpp.
    {
      using std::swap;
      swap(a.ptr_, b.ptr_);
    }
References RefPtr, and swap.
Referenced by swap, and swap_().
Member Data Documentation
ptr_
template<typename T> std::shared_ptr<std::atomic<void*> > npi::RefPtr< T >::ptr_ {nullptr} private
Pointer to the object being linked to.
static_cast is used to ensure the correct type is provided in the get_() method.
Definition at line 478 of file RefPtrClasses.hpp.
{nullptr};
Referenced by RefPtr(), assign_(), get_(), and reset_().
The documentation for this class was generated from the following file:
RefPtrClasses.hpp