Main Project: npi::AppMetaData Struct Reference
npi::AppMetaData Struct Reference final
Application metadata container.
#include <AppMetaData.hpp>
Public Member Functions
AppMetaData ()=delete
Default constructor deleted.
AppMetaData (AppMetaData &&)=delete
Move constructor deleted.
AppMetaData (const AppMetaData &)=delete
Copy constructor deleted.
~AppMetaData ()=delete
Destructor deleted.
AppMetaData & operator= (AppMetaData &&)=delete
Move assignment deleted.
AppMetaData & operator= (const AppMetaData &)=delete
Copy assignment deleted.
Static Public Attributes
static constexpr QLatin1StringView Name_ {"E106_Log"}
Application display name.
static constexpr QLatin1StringView Version_ {"1.0.0"}
Application version.
Detailed Description
Application metadata container.
This struct holds static constexpr members that define metadata about the application.
Note
This struct is non-instantiable and non-copyable.
Do not add any methods to this struct.
Only add application related metadata as static constexpr members.
Definition at line 25 of file AppMetaData.hpp.
Constructor & Destructor Documentation
AppMetaData() [1/3]
npi::AppMetaData::AppMetaData () delete
Default constructor deleted.
Referenced by AppMetaData(), AppMetaData(), operator=(), and operator=().
AppMetaData() [2/3]
npi::AppMetaData::AppMetaData (AppMetaData &&) delete
Move constructor deleted.
References AppMetaData().
AppMetaData() [3/3]
npi::AppMetaData::AppMetaData (const AppMetaData &) delete
Copy constructor deleted.
References AppMetaData().
~AppMetaData()
npi::AppMetaData::~AppMetaData () delete
Destructor deleted.
Member Function Documentation
operator=() [1/2]
AppMetaData & npi::AppMetaData::operator= (AppMetaData &&) delete
Move assignment deleted.
References AppMetaData().
operator=() [2/2]
AppMetaData & npi::AppMetaData::operator= (const AppMetaData &) delete
Copy assignment deleted.
References AppMetaData().
Member Data Documentation
Name_
QLatin1StringView npi::AppMetaData::Name_ {"E106_Log"} inline static constexpr
Application display name.
Definition at line 33 of file AppMetaData.hpp.
{"E106_Log"}; ///< Application display name
Referenced by npi::app::appProgramDataDir(), npi::app::appPublicDocumentsDir(), anonymous_namespace{Log.cpp}::LogCore::getConsole_(), and npi::app::nativeFatalMessage().
Version_
QLatin1StringView npi::AppMetaData::Version_ {"1.0.0"} inline static constexpr
Application version.
Definition at line 34 of file AppMetaData.hpp.
{"1.0.0"}; ///< Application version
The documentation for this struct was generated from the following file:
AppMetaData.hpp